import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const files=["src/ui/object-selection-context-ui.js","src/ui/editing-ui.js","src/import/dwfx/reference-scene-ui.js","src/ui/assemblies-runtime.js","src/ui/equipment-library-ui.js"];
const normalized=files.map(rel=>fs.readFileSync(path.join(root,rel),"utf8").split(/\r?\n/).map(s=>s.trim()).filter(s=>s.length>=8&&!s.startsWith("//")&&s!=="{"&&s!=="}"&&s!=="};").join("\n"));
const has=(fileIndex,pair)=>assert.ok(normalized[fileIndex].includes(pair));
test("question 47174: preserves adjacent source contract",()=>has(3,"const direct=directAssembliesForRef(ref).filter(item=>String(item.id)!==String(targetAssemblyId??\"\"));\nif(direct.length)throw new Error(\"Компонент уже принадлежит Assembly: \"+String(direct[0].name??direct[0].id));"));
test("question 47175: preserves adjacent source contract",()=>has(3,"if(direct.length)throw new Error(\"Компонент уже принадлежит Assembly: \"+String(direct[0].name??direct[0].id));\nfunction centroidForRefs(refs){"));
test("question 47176: preserves adjacent source contract",()=>has(3,"function centroidForRefs(refs){\nconst points=refs.map(memberPose).map(p=>p?.position_mm).filter(p=>p&&[p.x,p.y,p.z].every(Number.isFinite));"));
test("question 47177: preserves adjacent source contract",()=>has(3,"const points=refs.map(memberPose).map(p=>p?.position_mm).filter(p=>p&&[p.x,p.y,p.z].every(Number.isFinite));\nif(!points.length)return {x:0,y:0,z:0};"));
test("question 47178: preserves adjacent source contract",()=>has(3,"if(!points.length)return {x:0,y:0,z:0};\nreturn points.reduce((a,p)=>({x:a.x+p.x/points.length,y:a.y+p.y/points.length,z:a.z+p.z/points.length}),{x:0,y:0,z:0});"));
test("question 47179: preserves adjacent source contract",()=>has(3,"return points.reduce((a,p)=>({x:a.x+p.x/points.length,y:a.y+p.y/points.length,z:a.z+p.z/points.length}),{x:0,y:0,z:0});\nfunction createFromSelection({name=\"Assembly\",origin_mm=null}={}){"));
test("question 47180: preserves adjacent source contract",()=>has(3,"function createFromSelection({name=\"Assembly\",origin_mm=null}={}){\nlet refs;"));
test("question 47181: preserves adjacent source contract",()=>has(3,"let refs;\ntry{refs=selectionRefs();}catch(error){toast(error.message);return false;}"));
test("question 47182: preserves adjacent source contract",()=>has(3,"try{refs=selectionRefs();}catch(error){toast(error.message);return false;}\nif(!refs.length){toast(\"Выберите компоненты для Assembly\");return false;}"));
test("question 47183: preserves adjacent source contract",()=>has(3,"if(!refs.length){toast(\"Выберите компоненты для Assembly\");return false;}\nfor(const ref of refs){"));
test("question 47184: preserves adjacent source contract",()=>has(3,"for(const ref of refs){\ntry{assertSingleParent(ref);}catch(error){toast(error.message);return false;}"));
test("question 47185: preserves adjacent source contract",()=>has(3,"try{assertSingleParent(ref);}catch(error){toast(error.message);return false;}\nlet created=null;"));
test("question 47186: preserves adjacent source contract",()=>has(3,"let created=null;\nconst origin=origin_mm??centroidForRefs(refs);"));
test("question 47187: preserves adjacent source contract",()=>has(3,"const origin=origin_mm??centroidForRefs(refs);\nconst ok=command(\"Создать Assembly\",()=>{"));
test("question 47188: preserves adjacent source contract",()=>has(3,"const ok=command(\"Создать Assembly\",()=>{\ncreated=assemblies.createAssembly(project(),{"));
test("question 47189: preserves adjacent source contract",()=>has(3,"created=assemblies.createAssembly(project(),{\nframe:{origin_mm:origin,rotation_quaternion:{x:0,y:0,z:0,w:1}},"));
test("question 47190: preserves adjacent source contract",()=>has(3,"frame:{origin_mm:origin,rotation_quaternion:{x:0,y:0,z:0,w:1}},\nmembers:refs.map(ref=>({ref,local:{}}))"));
test("question 47191: preserves adjacent source contract",()=>has(3,"members:refs.map(ref=>({ref,local:{}}))\nsyncAssemblyLocals(created.id);"));
test("question 47192: preserves adjacent source contract",()=>has(3,"syncAssemblyLocals(created.id);\nreturn true;"));
test("question 47193: preserves adjacent source contract",()=>has(3,"return true;\nif(ok&&created)ctx()?.replaceSelectionKeys?.([\"project-assembly:\"+encodeURIComponent(created.id)]);"));
test("question 47194: preserves adjacent source contract",()=>has(3,"if(ok&&created)ctx()?.replaceSelectionKeys?.([\"project-assembly:\"+encodeURIComponent(created.id)]);\nreturn ok?created:false;"));
test("question 47195: preserves adjacent source contract",()=>has(3,"return ok?created:false;\nfunction addSelection(assemblyId){"));
test("question 47196: preserves adjacent source contract",()=>has(3,"function addSelection(assemblyId){\nconst target=assemblyById(assemblyId);if(!target)return false;"));
test("question 47197: preserves adjacent source contract",()=>has(3,"const target=assemblyById(assemblyId);if(!target)return false;\nlet refs;try{refs=selectionRefs();}catch(error){toast(error.message);return false;}"));
test("question 47198: preserves adjacent source contract",()=>has(3,"let refs;try{refs=selectionRefs();}catch(error){toast(error.message);return false;}\nrefs=refs.filter(ref=>!(ref.kind===\"assembly\"&&String(ref.id)===String(assemblyId)));"));
test("question 47199: preserves adjacent source contract",()=>has(3,"refs=refs.filter(ref=>!(ref.kind===\"assembly\"&&String(ref.id)===String(assemblyId)));\nif(!refs.length){toast(\"Нет компонентов для добавления\");return false;}"));
test("question 47200: preserves adjacent source contract",()=>has(3,"if(!refs.length){toast(\"Нет компонентов для добавления\");return false;}\nfor(const ref of refs){"));
test("question 47201: preserves adjacent source contract",()=>has(3,"for(const ref of refs){\ntry{assertSingleParent(ref,assemblyId);}catch(error){toast(error.message);return false;}"));
test("question 47202: preserves adjacent source contract",()=>has(3,"try{assertSingleParent(ref,assemblyId);}catch(error){toast(error.message);return false;}\nreturn command(\"Добавить компоненты в Assembly\",()=>{"));
test("question 47203: preserves adjacent source contract",()=>has(3,"return command(\"Добавить компоненты в Assembly\",()=>{\nassemblies.addAssemblyMembers(project(),assemblyId,refs.map(ref=>({ref,local:{}})));"));
test("question 47204: preserves adjacent source contract",()=>has(3,"assemblies.addAssemblyMembers(project(),assemblyId,refs.map(ref=>({ref,local:{}})));\nsyncAssemblyLocals(assemblyId);return true;"));
test("question 47205: preserves adjacent source contract",()=>has(3,"syncAssemblyLocals(assemblyId);return true;\nfunction removeSelection(assemblyId){"));
test("question 47206: preserves adjacent source contract",()=>has(3,"function removeSelection(assemblyId){\nlet refs;try{refs=selectionRefs();}catch(error){toast(error.message);return false;}"));
test("question 47207: preserves adjacent source contract",()=>has(3,"let refs;try{refs=selectionRefs();}catch(error){toast(error.message);return false;}\nif(!refs.length){toast(\"Нет компонентов для удаления\");return false;}"));
test("question 47208: preserves adjacent source contract",()=>has(3,"if(!refs.length){toast(\"Нет компонентов для удаления\");return false;}\nreturn command(\"Удалить компоненты из Assembly\",()=>{"));
test("question 47209: preserves adjacent source contract",()=>has(3,"return command(\"Удалить компоненты из Assembly\",()=>{\nassemblies.removeAssemblyMembers(project(),assemblyId,refs);"));
test("question 47210: preserves adjacent source contract",()=>has(3,"assemblies.removeAssemblyMembers(project(),assemblyId,refs);\nfor(const ref of refs)if(ref.kind===\"tube\")syncTubePortConstraints(ref.id);"));
test("question 47211: preserves adjacent source contract",()=>has(3,"for(const ref of refs)if(ref.kind===\"tube\")syncTubePortConstraints(ref.id);\nreturn true;"));
test("question 47212: preserves adjacent source contract",()=>has(3,"return true;\nfunction rename(assemblyId,name){"));
test("question 47213: preserves adjacent source contract",()=>has(3,"function rename(assemblyId,name){\nreturn command(\"Переименовать Assembly\",()=>{assemblies.renameAssembly(project(),assemblyId,name);return true;});"));
test("question 47214: preserves adjacent source contract",()=>has(3,"return command(\"Переименовать Assembly\",()=>{assemblies.renameAssembly(project(),assemblyId,name);return true;});\nfunction setFixed(assemblyId,fixed){"));
test("question 47215: preserves adjacent source contract",()=>has(3,"function setFixed(assemblyId,fixed){\nreturn command(fixed?\"Зафиксировать Assembly\":\"Освободить Assembly\",()=>{assemblies.setAssemblyFixed(project(),assemblyId,fixed);return true;});"));
test("question 47216: preserves adjacent source contract",()=>has(3,"return command(fixed?\"Зафиксировать Assembly\":\"Освободить Assembly\",()=>{assemblies.setAssemblyFixed(project(),assemblyId,fixed);return true;});\nfunction setVisible(assemblyId,visible){"));
test("question 47217: preserves adjacent source contract",()=>has(3,"function setVisible(assemblyId,visible){\nreturn command(visible?\"Показать Assembly\":\"Скрыть Assembly\",()=>{assemblies.setAssemblyVisibility(project(),assemblyId,visible);return true;});"));
test("question 47218: preserves adjacent source contract",()=>has(3,"return command(visible?\"Показать Assembly\":\"Скрыть Assembly\",()=>{assemblies.setAssemblyVisibility(project(),assemblyId,visible);return true;});\nfunction setLock(assemblyId,mode){"));
test("question 47219: preserves adjacent source contract",()=>has(3,"function setLock(assemblyId,mode){\nreturn command(mode===\"Unlocked\"?\"Разблокировать Assembly\":mode===\"Object\"?\"Lock Object Assembly\":\"Lock Position Assembly\",()=>{assemblies.setAssemblyLock(project(),assemblyId,mode);return true;});"));
test("question 47220: preserves adjacent source contract",()=>has(3,"return command(mode===\"Unlocked\"?\"Разблокировать Assembly\":mode===\"Object\"?\"Lock Object Assembly\":\"Lock Position Assembly\",()=>{assemblies.setAssemblyLock(project(),assemblyId,mode);return true;});\nfunction directLeafPermission(ref,action){"));
test("question 47221: preserves adjacent source contract",()=>has(3,"function directLeafPermission(ref,action){\nconst entry=entryFromRef(ref);"));
test("question 47222: preserves adjacent source contract",()=>has(3,"const entry=entryFromRef(ref);\nconst layerPermission=entry?layerApi()?.permissionForEntry?.(entry,action):null;"));
test("question 47223: preserves adjacent source contract",()=>has(3,"const layerPermission=entry?layerApi()?.permissionForEntry?.(entry,action):null;\nif(layerPermission&&layerPermission.allowed===false)return layerPermission;"));
test("question 47224: preserves adjacent source contract",()=>has(3,"if(layerPermission&&layerPermission.allowed===false)return layerPermission;\nconst object=objectForRef(ref),policy=lockPolicy();"));
test("question 47225: preserves adjacent source contract",()=>has(3,"const object=objectForRef(ref),policy=lockPolicy();\nif(object&&policy){"));
test("question 47226: preserves adjacent source contract",()=>has(3,"if(object&&policy){\nconst permission=policy.lockPermission(object,action);"));
test("question 47227: preserves adjacent source contract",()=>has(3,"const permission=policy.lockPermission(object,action);\nif(!permission.allowed)return permission;"));
test("question 47228: preserves adjacent source contract",()=>has(3,"if(!permission.allowed)return permission;\nreturn {allowed:true,code:\"ASSEMBLY_MEMBER_ALLOWED\",reason:null};"));
test("question 47229: preserves adjacent source contract",()=>has(3,"return {allowed:true,code:\"ASSEMBLY_MEMBER_ALLOWED\",reason:null};\nfunction permissionForEntry(entry,action){"));
test("question 47230: preserves adjacent source contract",()=>has(3,"function permissionForEntry(entry,action){\nconst positionAction=[\"move\",\"rotate\",\"position\",\"orientation\",\"transform\",\"transform-stack\"].includes(String(action));"));
test("question 47231: preserves adjacent source contract",()=>has(3,"const positionAction=[\"move\",\"rotate\",\"position\",\"orientation\",\"transform\",\"transform-stack\"].includes(String(action));\nlet list=[];"));
test("question 47232: preserves adjacent source contract",()=>has(3,"let list=[];\nif(entry?.kind===\"project-assembly\"){"));
test("question 47233: preserves adjacent source contract",()=>has(3,"if(entry?.kind===\"project-assembly\"){\nconst root=assemblyById(entry.assemblyId);"));
test("question 47234: preserves adjacent source contract",()=>has(3,"const root=assemblyById(entry.assemblyId);\nlist=[root,...(assemblies.assemblyDescendantIds(project(),entry.assemblyId).map(assemblyById))].filter(Boolean);"));
test("question 47235: preserves adjacent source contract",()=>has(3,"list=[root,...(assemblies.assemblyDescendantIds(project(),entry.assemblyId).map(assemblyById))].filter(Boolean);\nlist=containingAssembliesForEntry(entry);"));
test("question 47236: preserves adjacent source contract",()=>has(3,"list=containingAssembliesForEntry(entry);\nconst policy=lockPolicy();"));
test("question 47237: preserves adjacent source contract",()=>has(3,"const policy=lockPolicy();\nfor(const assembly of list){"));
test("question 47238: preserves adjacent source contract",()=>has(3,"for(const assembly of list){\nif(positionAction&&assembly.fixed===true)return {allowed:false,code:\"ASSEMBLY_FIXED\",reason:\"Assembly зафиксирован\",assembly_id:String(assembly.id)};"));
test("question 47239: preserves adjacent source contract",()=>has(3,"if(positionAction&&assembly.fixed===true)return {allowed:false,code:\"ASSEMBLY_FIXED\",reason:\"Assembly зафиксирован\",assembly_id:String(assembly.id)};\nif(policy){"));
test("question 47240: preserves adjacent source contract",()=>has(3,"if(policy){\nconst permission=policy.lockPermission(assembly,action);"));
test("question 47241: preserves adjacent source contract",()=>has(3,"const permission=policy.lockPermission(assembly,action);\nif(!permission.allowed)return {...permission,assembly_id:String(assembly.id)};"));
test("question 47242: preserves adjacent source contract",()=>has(3,"if(!permission.allowed)return {...permission,assembly_id:String(assembly.id)};\nif(entry?.kind===\"project-assembly\"){"));
test("question 47243: preserves adjacent source contract",()=>has(3,"if(entry?.kind===\"project-assembly\"){\nfor(const member of assemblies.leafAssemblyMembers(project(),entry.assemblyId)){"));
test("question 47244: preserves adjacent source contract",()=>has(3,"for(const member of assemblies.leafAssemblyMembers(project(),entry.assemblyId)){\nconst permission=directLeafPermission(member.ref,action);"));
test("question 47245: preserves adjacent source contract",()=>has(3,"const permission=directLeafPermission(member.ref,action);\nif(!permission.allowed)return permission;"));
test("question 47246: preserves adjacent source contract",()=>has(3,"if(!permission.allowed)return permission;\nreturn {allowed:true,code:\"ASSEMBLY_ALLOWED\",reason:null};"));
test("question 47247: preserves adjacent source contract",()=>has(3,"return {allowed:true,code:\"ASSEMBLY_ALLOWED\",reason:null};\nfunction canSelection(action,{notify=true}={}){"));
test("question 47248: preserves adjacent source contract",()=>has(3,"function canSelection(action,{notify=true}={}){\nfor(const entry of entries()){"));
test("question 47249: preserves adjacent source contract",()=>has(3,"for(const entry of entries()){\nconst permission=permissionForEntry(entry,action);"));
test("question 47250: preserves adjacent source contract",()=>has(3,"const permission=permissionForEntry(entry,action);\nif(!permission.allowed){if(notify)toast(permission.reason);return false;}"));
test("question 47251: preserves adjacent source contract",()=>has(3,"if(!permission.allowed){if(notify)toast(permission.reason);return false;}\nreturn true;"));
test("question 47252: preserves adjacent source contract",()=>has(3,"return true;\nfunction applyTubeResult(tube,result){"));
test("question 47253: preserves adjacent source contract",()=>has(3,"function applyTubeResult(tube,result){\nif(result?.status!==\"exact\"||!result.tube)throw new Error(result?.reason??\"Assembly rigid transform failed\");"));
test("question 47254: preserves adjacent source contract",()=>has(3,"if(result?.status!==\"exact\"||!result.tube)throw new Error(result?.reason??\"Assembly rigid transform failed\");\nfor(const key of Object.keys(tube))delete tube[key];"));
test("question 47255: preserves adjacent source contract",()=>has(3,"for(const key of Object.keys(tube))delete tube[key];\nObject.assign(tube,clone(result.tube));"));
test("question 47256: preserves adjacent source contract",()=>has(3,"Object.assign(tube,clone(result.tube));\nfunction transformPoint(oldFrame,newFrame,p){"));
test("question 47257: preserves adjacent source contract",()=>has(3,"function transformPoint(oldFrame,newFrame,p){\nreturn assemblies.localToWorldPoint(newFrame,assemblies.worldToLocalPoint(oldFrame,p));"));
test("question 47258: preserves adjacent source contract",()=>has(3,"return assemblies.localToWorldPoint(newFrame,assemblies.worldToLocalPoint(oldFrame,p));\nfunction transformQuaternion(oldFrame,newFrame,q){"));
test("question 47259: preserves adjacent source contract",()=>has(3,"function transformQuaternion(oldFrame,newFrame,q){\nconst local=assemblies.worldToLocalQuaternion(oldFrame,q);"));
test("question 47260: preserves adjacent source contract",()=>has(3,"const local=assemblies.worldToLocalQuaternion(oldFrame,q);\nreturn assemblies.localToWorldQuaternion(newFrame,local);"));
test("question 47261: preserves adjacent source contract",()=>has(3,"return assemblies.localToWorldQuaternion(newFrame,local);\nfunction transformTube(ref,oldFrame,newFrame,axisAngle){"));
test("question 47262: preserves adjacent source contract",()=>has(3,"function transformTube(ref,oldFrame,newFrame,axisAngle){\nconst tube=tubeById(ref.id);if(!tube)return;"));
test("question 47263: preserves adjacent source contract",()=>has(3,"const tube=tubeById(ref.id);if(!tube)return;\nlet next={status:\"exact\",tube:clone(tube)};"));
test("question 47264: preserves adjacent source contract",()=>has(3,"let next={status:\"exact\",tube:clone(tube)};\nif(Math.abs(axisAngle.angle_deg)>1e-10){"));
test("question 47265: preserves adjacent source contract",()=>has(3,"if(Math.abs(axisAngle.angle_deg)>1e-10){\nnext=rigid.rotateLegacyTubeRigid(tube,{axis:axisAngle.axis,center:oldFrame.origin_mm,angle_deg:axisAngle.angle_deg});"));
test("question 47266: preserves adjacent source contract",()=>has(3,"next=rigid.rotateLegacyTubeRigid(tube,{axis:axisAngle.axis,center:oldFrame.origin_mm,angle_deg:axisAngle.angle_deg});\nif(next.status!==\"exact\")throw new Error(next.reason??\"Assembly tube rotation failed\");"));
test("question 47267: preserves adjacent source contract",()=>has(3,"if(next.status!==\"exact\")throw new Error(next.reason??\"Assembly tube rotation failed\");\nconst delta={"));
test("question 47268: preserves adjacent source contract",()=>has(3,"const delta={\nx:newFrame.origin_mm.x-oldFrame.origin_mm.x,"));
test("question 47269: preserves adjacent source contract",()=>has(3,"x:newFrame.origin_mm.x-oldFrame.origin_mm.x,\ny:newFrame.origin_mm.y-oldFrame.origin_mm.y,"));
test("question 47270: preserves adjacent source contract",()=>has(3,"y:newFrame.origin_mm.y-oldFrame.origin_mm.y,\nz:newFrame.origin_mm.z-oldFrame.origin_mm.z"));
test("question 47271: preserves adjacent source contract",()=>has(3,"z:newFrame.origin_mm.z-oldFrame.origin_mm.z\nnext=rigid.translateLegacyTubeRigid(next.tube,delta);"));
test("question 47272: preserves adjacent source contract",()=>has(3,"next=rigid.translateLegacyTubeRigid(next.tube,delta);\napplyTubeResult(tube,next);"));
test("question 47273: preserves adjacent source contract",()=>has(3,"applyTubeResult(tube,next);\nfunction transformMesh(ref,oldFrame,newFrame,axisAngle){"));
test("question 47274: preserves adjacent source contract",()=>has(3,"function transformMesh(ref,oldFrame,newFrame,axisAngle){\nconst mesh=meshById(ref.id);if(!mesh)return;"));
test("question 47275: preserves adjacent source contract",()=>has(3,"const mesh=meshById(ref.id);if(!mesh)return;\nconst p=mesh.transform?.position_mm??{x:0,y:0,z:0},target=transformPoint(oldFrame,newFrame,p);"));
test("question 47276: preserves adjacent source contract",()=>has(3,"const p=mesh.transform?.position_mm??{x:0,y:0,z:0},target=transformPoint(oldFrame,newFrame,p);\nrefApi()?.moveEditableMeshInstance?.(project(),ref.id,{x:target.x-p.x,y:target.y-p.y,z:target.z-p.z});"));
test("question 47277: preserves adjacent source contract",()=>has(3,"refApi()?.moveEditableMeshInstance?.(project(),ref.id,{x:target.x-p.x,y:target.y-p.y,z:target.z-p.z});\nif(Math.abs(axisAngle.angle_deg)>1e-10)refApi()?.rotateEditableMeshInstanceAxis?.(project(),ref.id,{axis:axisAngle.axis,angle_deg:axisAngle.angle_deg});"));
test("question 47278: preserves adjacent source contract",()=>has(3,"if(Math.abs(axisAngle.angle_deg)>1e-10)refApi()?.rotateEditableMeshInstanceAxis?.(project(),ref.id,{axis:axisAngle.axis,angle_deg:axisAngle.angle_deg});\nfunction transformConstruction(ref,oldFrame,newFrame,axisAngle){"));
test("question 47279: preserves adjacent source contract",()=>has(3,"function transformConstruction(ref,oldFrame,newFrame,axisAngle){\nconst item=objectForRef(ref);if(!item)return;"));
test("question 47280: preserves adjacent source contract",()=>has(3,"const item=objectForRef(ref);if(!item)return;\nconst key=item.position_mm?\"position_mm\":item.origin?\"origin\":null;"));
test("question 47281: preserves adjacent source contract",()=>has(3,"const key=item.position_mm?\"position_mm\":item.origin?\"origin\":null;\nif(key)item[key]={...transformPoint(oldFrame,newFrame,item[key])};"));
test("question 47282: preserves adjacent source contract",()=>has(3,"if(key)item[key]={...transformPoint(oldFrame,newFrame,item[key])};\nif(item.direction)item.direction={...assemblies.rotateVectorByQuaternion(item.direction,assemblies.axisAngleQuaternion(axisAngle.axis,axisAngle.angle_deg))};"));
test("question 47283: preserves adjacent source contract",()=>has(3,"if(item.direction)item.direction={...assemblies.rotateVectorByQuaternion(item.direction,assemblies.axisAngleQuaternion(axisAngle.axis,axisAngle.angle_deg))};\nif(item.rotation_quaternion)item.rotation_quaternion={...transformQuaternion(oldFrame,newFrame,item.rotation_quaternion)};"));
test("question 47284: preserves adjacent source contract",()=>has(3,"if(item.rotation_quaternion)item.rotation_quaternion={...transformQuaternion(oldFrame,newFrame,item.rotation_quaternion)};\nfunction transformDimension(ref,oldFrame,newFrame,axisAngle){"));
test("question 47285: preserves adjacent source contract",()=>has(3,"function transformDimension(ref,oldFrame,newFrame,axisAngle){\nconst dim=objectForRef(ref);if(!dim)return;"));
test("question 47286: preserves adjacent source contract",()=>has(3,"const dim=objectForRef(ref);if(!dim)return;\nif(dim.text_position&&[dim.text_position.x,dim.text_position.y,dim.text_position.z].every(Number.isFinite)){"));
test("question 47287: preserves adjacent source contract",()=>has(3,"if(dim.text_position&&[dim.text_position.x,dim.text_position.y,dim.text_position.z].every(Number.isFinite)){\ndim.text_position={...transformPoint(oldFrame,newFrame,dim.text_position)};"));
test("question 47288: preserves adjacent source contract",()=>has(3,"dim.text_position={...transformPoint(oldFrame,newFrame,dim.text_position)};\nif(dim.leader?.start&&[dim.leader.start.x,dim.leader.start.y,dim.leader.start.z].every(Number.isFinite)){"));
test("question 47289: preserves adjacent source contract",()=>has(3,"if(dim.leader?.start&&[dim.leader.start.x,dim.leader.start.y,dim.leader.start.z].every(Number.isFinite)){\ndim.leader={...dim.leader,start:{...transformPoint(oldFrame,newFrame,dim.leader.start)}};"));
test("question 47290: preserves adjacent source contract",()=>has(3,"dim.leader={...dim.leader,start:{...transformPoint(oldFrame,newFrame,dim.leader.start)}};\nif(dim.leader?.end&&[dim.leader.end.x,dim.leader.end.y,dim.leader.end.z].every(Number.isFinite)){"));
test("question 47291: preserves adjacent source contract",()=>has(3,"if(dim.leader?.end&&[dim.leader.end.x,dim.leader.end.y,dim.leader.end.z].every(Number.isFinite)){\ndim.leader={...dim.leader,end:{...transformPoint(oldFrame,newFrame,dim.leader.end)}};"));
test("question 47292: preserves adjacent source contract",()=>has(3,"dim.leader={...dim.leader,end:{...transformPoint(oldFrame,newFrame,dim.leader.end)}};\nif(dim.local_plane?.origin&&[dim.local_plane.origin.x,dim.local_plane.origin.y,dim.local_plane.origin.z].every(Number.isFinite)){"));
test("question 47293: preserves adjacent source contract",()=>has(3,"if(dim.local_plane?.origin&&[dim.local_plane.origin.x,dim.local_plane.origin.y,dim.local_plane.origin.z].every(Number.isFinite)){\nconst q=assemblies.axisAngleQuaternion(axisAngle.axis,axisAngle.angle_deg);"));
test("question 47294: preserves adjacent source contract",()=>has(3,"const q=assemblies.axisAngleQuaternion(axisAngle.axis,axisAngle.angle_deg);\ndim.local_plane={"));
test("question 47295: preserves adjacent source contract",()=>has(3,"dim.local_plane={\n...dim.local_plane,"));
test("question 47296: preserves adjacent source contract",()=>has(3,"...dim.local_plane,\norigin:{...transformPoint(oldFrame,newFrame,dim.local_plane.origin)},"));
test("question 47297: preserves adjacent source contract",()=>has(3,"origin:{...transformPoint(oldFrame,newFrame,dim.local_plane.origin)},\nx_axis:dim.local_plane.x_axis?{...assemblies.rotateVectorByQuaternion(dim.local_plane.x_axis,q)}:dim.local_plane.x_axis,"));
test("question 47298: preserves adjacent source contract",()=>has(3,"x_axis:dim.local_plane.x_axis?{...assemblies.rotateVectorByQuaternion(dim.local_plane.x_axis,q)}:dim.local_plane.x_axis,\ny_axis:dim.local_plane.y_axis?{...assemblies.rotateVectorByQuaternion(dim.local_plane.y_axis,q)}:dim.local_plane.y_axis,"));
test("question 47299: preserves adjacent source contract",()=>has(3,"y_axis:dim.local_plane.y_axis?{...assemblies.rotateVectorByQuaternion(dim.local_plane.y_axis,q)}:dim.local_plane.y_axis,\nnormal:dim.local_plane.normal?{...assemblies.rotateVectorByQuaternion(dim.local_plane.normal,q)}:dim.local_plane.normal"));
test("question 47300: preserves adjacent source contract",()=>has(3,"normal:dim.local_plane.normal?{...assemblies.rotateVectorByQuaternion(dim.local_plane.normal,q)}:dim.local_plane.normal\nfunction transformLeaf(ref,oldFrame,newFrame,axisAngle){"));
test("question 47301: preserves adjacent source contract",()=>has(3,"function transformLeaf(ref,oldFrame,newFrame,axisAngle){\nif(ref.kind===\"tube\")transformTube(ref,oldFrame,newFrame,axisAngle);"));
test("question 47302: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"tube\")transformTube(ref,oldFrame,newFrame,axisAngle);\nelse if(ref.kind===\"mesh-instance\")transformMesh(ref,oldFrame,newFrame,axisAngle);"));
test("question 47303: preserves adjacent source contract",()=>has(3,"else if(ref.kind===\"mesh-instance\")transformMesh(ref,oldFrame,newFrame,axisAngle);\nelse if(ref.kind===\"construction\")transformConstruction(ref,oldFrame,newFrame,axisAngle);"));
test("question 47304: preserves adjacent source contract",()=>has(3,"else if(ref.kind===\"construction\")transformConstruction(ref,oldFrame,newFrame,axisAngle);\nelse if(ref.kind===\"dimension\")transformDimension(ref,oldFrame,newFrame,axisAngle);"));
test("question 47305: preserves adjacent source contract",()=>has(3,"else if(ref.kind===\"dimension\")transformDimension(ref,oldFrame,newFrame,axisAngle);\nfunction translateLeafDirect(ref,delta){"));
test("question 47306: preserves adjacent source contract",()=>has(3,"function translateLeafDirect(ref,delta){\nif(ref.kind===\"tube\"){"));
test("question 47307: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"tube\"){\nconst tube=tubeById(ref.id);if(!tube)return;"));
test("question 47308: preserves adjacent source contract",()=>has(3,"const tube=tubeById(ref.id);if(!tube)return;\napplyTubeResult(tube,rigid.translateLegacyTubeRigid(tube,delta));"));
test("question 47309: preserves adjacent source contract",()=>has(3,"applyTubeResult(tube,rigid.translateLegacyTubeRigid(tube,delta));\n}else if(ref.kind===\"mesh-instance\"){"));
test("question 47310: preserves adjacent source contract",()=>has(3,"}else if(ref.kind===\"mesh-instance\"){\nrefApi()?.moveEditableMeshInstance?.(project(),ref.id,delta);"));
test("question 47311: preserves adjacent source contract",()=>has(3,"refApi()?.moveEditableMeshInstance?.(project(),ref.id,delta);\n}else if(ref.kind===\"construction\"){"));
test("question 47312: preserves adjacent source contract",()=>has(3,"}else if(ref.kind===\"construction\"){\nconst item=objectForRef(ref);if(!item)return;"));
test("question 47313: preserves adjacent source contract",()=>has(3,"const key=item.position_mm?\"position_mm\":item.origin?\"origin\":null;\nif(key){"));
test("question 47314: preserves adjacent source contract",()=>has(3,"if(key){\nconst p=item[key];item[key]={x:Number(p.x||0)+delta.x,y:Number(p.y||0)+delta.y,z:Number(p.z||0)+delta.z};"));
test("question 47315: preserves adjacent source contract",()=>has(3,"const p=item[key];item[key]={x:Number(p.x||0)+delta.x,y:Number(p.y||0)+delta.y,z:Number(p.z||0)+delta.z};\n}else if(ref.kind===\"dimension\"){"));
test("question 47316: preserves adjacent source contract",()=>has(3,"}else if(ref.kind===\"dimension\"){\nconst dim=objectForRef(ref);if(!dim)return;"));
test("question 47317: preserves adjacent source contract",()=>has(3,"const dim=objectForRef(ref);if(!dim)return;\nif(dim.text_position)dim.text_position={x:Number(dim.text_position.x||0)+delta.x,y:Number(dim.text_position.y||0)+delta.y,z:Number(dim.text_position.z||0)+delta.z};"));
test("question 47318: preserves adjacent source contract",()=>has(3,"if(dim.text_position)dim.text_position={x:Number(dim.text_position.x||0)+delta.x,y:Number(dim.text_position.y||0)+delta.y,z:Number(dim.text_position.z||0)+delta.z};\nfunction rotatePointAround(point,pivot,q){"));
test("question 47319: preserves adjacent source contract",()=>has(3,"function rotatePointAround(point,pivot,q){\nconst rel={x:point.x-pivot.x,y:point.y-pivot.y,z:point.z-pivot.z};"));
test("question 47320: preserves adjacent source contract",()=>has(3,"const rel={x:point.x-pivot.x,y:point.y-pivot.y,z:point.z-pivot.z};\nconst rotated=assemblies.rotateVectorByQuaternion(rel,q);"));
test("question 47321: preserves adjacent source contract",()=>has(3,"const rotated=assemblies.rotateVectorByQuaternion(rel,q);\nreturn {x:pivot.x+rotated.x,y:pivot.y+rotated.y,z:pivot.z+rotated.z};"));
test("question 47322: preserves adjacent source contract",()=>has(3,"return {x:pivot.x+rotated.x,y:pivot.y+rotated.y,z:pivot.z+rotated.z};\nfunction rotateLeafDirect(ref,axis,pivot,angle){"));
test("question 47323: preserves adjacent source contract",()=>has(3,"function rotateLeafDirect(ref,axis,pivot,angle){\nconst q=assemblies.axisAngleQuaternion(axis,angle);"));
test("question 47324: preserves adjacent source contract",()=>has(3,"const q=assemblies.axisAngleQuaternion(axis,angle);\nif(ref.kind===\"tube\"){"));
test("question 47325: preserves adjacent source contract",()=>has(3,"const tube=tubeById(ref.id);if(!tube)return;\napplyTubeResult(tube,rigid.rotateLegacyTubeRigid(tube,{axis,center:pivot,angle_deg:angle}));"));
test("question 47326: preserves adjacent source contract",()=>has(3,"applyTubeResult(tube,rigid.rotateLegacyTubeRigid(tube,{axis,center:pivot,angle_deg:angle}));\n}else if(ref.kind===\"mesh-instance\"){"));
test("question 47327: preserves adjacent source contract",()=>has(3,"}else if(ref.kind===\"mesh-instance\"){\nconst mesh=meshById(ref.id);if(!mesh)return;"));
test("question 47328: preserves adjacent source contract",()=>has(3,"const mesh=meshById(ref.id);if(!mesh)return;\nconst p=mesh.transform?.position_mm??{x:0,y:0,z:0},target=rotatePointAround(p,pivot,q);"));
test("question 47329: preserves adjacent source contract",()=>has(3,"const p=mesh.transform?.position_mm??{x:0,y:0,z:0},target=rotatePointAround(p,pivot,q);\nrefApi()?.moveEditableMeshInstance?.(project(),ref.id,{x:target.x-p.x,y:target.y-p.y,z:target.z-p.z});"));
test("question 47330: preserves adjacent source contract",()=>has(3,"refApi()?.moveEditableMeshInstance?.(project(),ref.id,{x:target.x-p.x,y:target.y-p.y,z:target.z-p.z});\nrefApi()?.rotateEditableMeshInstanceAxis?.(project(),ref.id,{axis,angle_deg:angle});"));
test("question 47331: preserves adjacent source contract",()=>has(3,"refApi()?.rotateEditableMeshInstanceAxis?.(project(),ref.id,{axis,angle_deg:angle});\n}else if(ref.kind===\"construction\"){"));
test("question 47332: preserves adjacent source contract",()=>has(3,"const key=item.position_mm?\"position_mm\":item.origin?\"origin\":null;\nif(key)item[key]=rotatePointAround(item[key],pivot,q);"));
test("question 47333: preserves adjacent source contract",()=>has(3,"if(key)item[key]=rotatePointAround(item[key],pivot,q);\nif(item.direction)item.direction={...assemblies.rotateVectorByQuaternion(item.direction,q)};"));
test("question 47334: preserves adjacent source contract",()=>has(3,"if(item.direction)item.direction={...assemblies.rotateVectorByQuaternion(item.direction,q)};\n}else if(ref.kind===\"dimension\"){"));
test("question 47335: preserves adjacent source contract",()=>has(3,"const dim=objectForRef(ref);if(!dim)return;\nif(dim.text_position)dim.text_position=rotatePointAround(dim.text_position,pivot,q);"));
test("question 47336: preserves adjacent source contract",()=>has(3,"if(dim.text_position)dim.text_position=rotatePointAround(dim.text_position,pivot,q);\nfunction editRefsForEntries(list){"));
test("question 47337: preserves adjacent source contract",()=>has(3,"function editRefsForEntries(list){\nconst active=activeEditAssembly();if(!active)return null;"));
test("question 47338: preserves adjacent source contract",()=>has(3,"const active=activeEditAssembly();if(!active)return null;\nconst refs=new Map();"));
test("question 47339: preserves adjacent source contract",()=>has(3,"const refs=new Map();\nfor(const entry of list??[]){"));
test("question 47340: preserves adjacent source contract",()=>has(3,"for(const entry of list??[]){\nconst direct=directMemberEntry(active,entry);"));
test("question 47341: preserves adjacent source contract",()=>has(3,"const direct=directMemberEntry(active,entry);\nif(!direct)return null;"));
test("question 47342: preserves adjacent source contract",()=>has(3,"if(!direct)return null;\nconst ref=refFromEntry(direct);if(!ref||ref.kind===\"source-ref\")return null;"));
test("question 47343: preserves adjacent source contract",()=>has(3,"const ref=refFromEntry(direct);if(!ref||ref.kind===\"source-ref\")return null;\nrefs.set(assemblies.assemblyMemberKey(ref),ref);"));
test("question 47344: preserves adjacent source contract",()=>has(3,"return [...refs.values()];\nfunction canHandleEditEntries(list=entries()){return editing()&&Array.isArray(editRefsForEntries(list));}"));
test("question 47345: preserves adjacent source contract",()=>has(3,"function canHandleEditEntries(list=entries()){return editing()&&Array.isArray(editRefsForEntries(list));}\nfunction moveEditEntries(list,delta){"));
test("question 47346: preserves adjacent source contract",()=>has(3,"function moveEditEntries(list,delta){\nconst active=activeEditAssembly(),refs=editRefsForEntries(list);"));
test("question 47347: preserves adjacent source contract",()=>has(3,"const active=activeEditAssembly(),refs=editRefsForEntries(list);\nif(!active||!refs?.length)return false;"));
test("question 47348: preserves adjacent source contract",()=>has(3,"if(!active||!refs?.length)return false;\nconst d={x:Number(delta?.x)||0,y:Number(delta?.y)||0,z:Number(delta?.z)||0};"));
test("question 47349: preserves adjacent source contract",()=>has(3,"const d={x:Number(delta?.x)||0,y:Number(delta?.y)||0,z:Number(delta?.z)||0};\nreturn command(\"Edit Assembly Move\",()=>{"));
test("question 47350: preserves adjacent source contract",()=>has(3,"return command(\"Edit Assembly Move\",()=>{\nfor(const ref of refs){"));
test("question 47351: preserves adjacent source contract",()=>has(3,"for(const ref of refs){\nif(ref.kind===\"assembly\"){"));
test("question 47352: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"assembly\"){\nconst child=assemblyById(ref.id),f=child.frame;"));
test("question 47353: preserves adjacent source contract",()=>has(3,"const child=assemblyById(ref.id),f=child.frame;\napplyAssemblyFrame(child.id,{origin_mm:{x:f.origin_mm.x+d.x,y:f.origin_mm.y+d.y,z:f.origin_mm.z+d.z},rotation_quaternion:f.rotation_quaternion});"));
test("question 47354: preserves adjacent source contract",()=>has(3,"applyAssemblyFrame(child.id,{origin_mm:{x:f.origin_mm.x+d.x,y:f.origin_mm.y+d.y,z:f.origin_mm.z+d.z},rotation_quaternion:f.rotation_quaternion});\n}else translateLeafDirect(ref,d);"));
test("question 47355: preserves adjacent source contract",()=>has(3,"}else translateLeafDirect(ref,d);\nsyncAssemblyLocals(active.id);return true;"));
test("question 47356: preserves adjacent source contract",()=>has(3,"syncAssemblyLocals(active.id);return true;\n},{wholeObject:true});"));
test("question 47357: preserves adjacent source contract",()=>has(3,"},{wholeObject:true});\nfunction rotateEditEntries(list,{axis,pivot,angle_deg}={}){"));
test("question 47358: preserves adjacent source contract",()=>has(3,"function rotateEditEntries(list,{axis,pivot,angle_deg}={}){\nconst active=activeEditAssembly(),refs=editRefsForEntries(list);"));
test("question 47359: preserves adjacent source contract",()=>has(3,"if(!active||!refs?.length)return false;\nconst angle=Number(angle_deg),center={x:Number(pivot?.x)||0,y:Number(pivot?.y)||0,z:Number(pivot?.z)||0};"));
test("question 47360: preserves adjacent source contract",()=>has(3,"const angle=Number(angle_deg),center={x:Number(pivot?.x)||0,y:Number(pivot?.y)||0,z:Number(pivot?.z)||0};\nif(!Number.isFinite(angle))return false;"));
test("question 47361: preserves adjacent source contract",()=>has(3,"if(!Number.isFinite(angle))return false;\nreturn command(\"Edit Assembly Rotate\",()=>{"));
test("question 47362: preserves adjacent source contract",()=>has(3,"return command(\"Edit Assembly Rotate\",()=>{\nconst q=assemblies.axisAngleQuaternion(axis,angle);"));
test("question 47363: preserves adjacent source contract",()=>has(3,"const q=assemblies.axisAngleQuaternion(axis,angle);\nfor(const ref of refs){"));
test("question 47364: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"assembly\"){\nconst child=assemblyById(ref.id),newOrigin=rotatePointAround(child.frame.origin_mm,center,q);"));
test("question 47365: preserves adjacent source contract",()=>has(3,"const child=assemblyById(ref.id),newOrigin=rotatePointAround(child.frame.origin_mm,center,q);\napplyAssemblyFrame(child.id,{origin_mm:newOrigin,rotation_quaternion:assemblies.multiplyQuaternions(q,child.frame.rotation_quaternion)});"));
test("question 47366: preserves adjacent source contract",()=>has(3,"applyAssemblyFrame(child.id,{origin_mm:newOrigin,rotation_quaternion:assemblies.multiplyQuaternions(q,child.frame.rotation_quaternion)});\n}else rotateLeafDirect(ref,axis,center,angle);"));
test("question 47367: preserves adjacent source contract",()=>has(3,"}else rotateLeafDirect(ref,axis,center,angle);\nsyncAssemblyLocals(active.id);return true;"));
test("question 47368: preserves adjacent source contract",()=>has(3,"},{wholeObject:true});\nfunction transformDescendantFrames(rootId,oldFrame,newFrame){"));
test("question 47369: preserves adjacent source contract",()=>has(3,"function transformDescendantFrames(rootId,oldFrame,newFrame){\nfor(const id of assemblies.assemblyDescendantIds(project(),rootId)){"));
test("question 47370: preserves adjacent source contract",()=>has(3,"for(const id of assemblies.assemblyDescendantIds(project(),rootId)){\nconst child=assemblyById(id);if(!child)continue;"));
test("question 47371: preserves adjacent source contract",()=>has(3,"const child=assemblyById(id);if(!child)continue;\nchild.frame={"));
test("question 47372: preserves adjacent source contract",()=>has(3,"child.frame={\norigin_mm:{...transformPoint(oldFrame,newFrame,child.frame.origin_mm)},"));
test("question 47373: preserves adjacent source contract",()=>has(3,"origin_mm:{...transformPoint(oldFrame,newFrame,child.frame.origin_mm)},\nrotation_quaternion:{...transformQuaternion(oldFrame,newFrame,child.frame.rotation_quaternion)}"));
test("question 47374: preserves adjacent source contract",()=>has(3,"rotation_quaternion:{...transformQuaternion(oldFrame,newFrame,child.frame.rotation_quaternion)}\nfunction applyAssemblyFrame(assemblyId,newFrame){"));
test("question 47375: preserves adjacent source contract",()=>has(3,"function applyAssemblyFrame(assemblyId,newFrame){\nconst assembly=assemblyById(assemblyId);if(!assembly)throw new Error(\"Assembly not found\");"));
test("question 47376: preserves adjacent source contract",()=>has(3,"const assembly=assemblyById(assemblyId);if(!assembly)throw new Error(\"Assembly not found\");\nsyncAssemblyLocals(assemblyId);"));
test("question 47377: preserves adjacent source contract",()=>has(3,"syncAssemblyLocals(assemblyId);\nconst oldFrame=clone(assembly.frame),normalized=assemblies.normalizeAssemblyFrame(newFrame);"));
test("question 47378: preserves adjacent source contract",()=>has(3,"const oldFrame=clone(assembly.frame),normalized=assemblies.normalizeAssemblyFrame(newFrame);\nconst qDelta=assemblies.multiplyQuaternions(normalized.rotation_quaternion,assemblies.conjugateQuaternion(oldFrame.rotation_quaternion));"));
test("question 47379: preserves adjacent source contract",()=>has(3,"const qDelta=assemblies.multiplyQuaternions(normalized.rotation_quaternion,assemblies.conjugateQuaternion(oldFrame.rotation_quaternion));\nconst axisAngle=assemblies.quaternionAxisAngle(qDelta);"));
test("question 47380: preserves adjacent source contract",()=>has(3,"const axisAngle=assemblies.quaternionAxisAngle(qDelta);\nconst leaves=assemblies.leafAssemblyMembers(project(),assemblyId);"));
test("question 47381: preserves adjacent source contract",()=>has(3,"const leaves=assemblies.leafAssemblyMembers(project(),assemblyId);\nfor(const member of leaves)transformLeaf(member.ref,oldFrame,normalized,axisAngle);"));
test("question 47382: preserves adjacent source contract",()=>has(3,"for(const member of leaves)transformLeaf(member.ref,oldFrame,normalized,axisAngle);\ntransformDescendantFrames(assemblyId,oldFrame,normalized);"));
test("question 47383: preserves adjacent source contract",()=>has(3,"transformDescendantFrames(assemblyId,oldFrame,normalized);\nassemblies.setAssemblyFrame(project(),assemblyId,normalized);"));
test("question 47384: preserves adjacent source contract",()=>has(3,"assemblies.setAssemblyFrame(project(),assemblyId,normalized);\nreturn assembly;"));
test("question 47385: preserves adjacent source contract",()=>has(3,"return assembly;\nfunction rootSelectionIds(ids){"));
test("question 47386: preserves adjacent source contract",()=>has(3,"function rootSelectionIds(ids){\nconst selected=new Set((ids??[]).map(String));"));
test("question 47387: preserves adjacent source contract",()=>has(3,"const selected=new Set((ids??[]).map(String));\nreturn [...selected].filter(id=>{"));
test("question 47388: preserves adjacent source contract",()=>has(3,"return [...selected].filter(id=>{\nconst parents=assemblies.assembliesContainingMember(project(),{kind:\"assembly\",id},{includeAncestors:true});"));
test("question 47389: preserves adjacent source contract",()=>has(3,"const parents=assemblies.assembliesContainingMember(project(),{kind:\"assembly\",id},{includeAncestors:true});\nreturn !parents.some(parent=>selected.has(String(parent.id)));"));
test("question 47390: preserves adjacent source contract",()=>has(3,"return !parents.some(parent=>selected.has(String(parent.id)));\nfunction moveAssemblies(ids,delta){"));
test("question 47391: preserves adjacent source contract",()=>has(3,"function moveAssemblies(ids,delta){\nconst roots=rootSelectionIds(ids);"));
test("question 47392: preserves adjacent source contract",()=>has(3,"const roots=rootSelectionIds(ids);\nif(!roots.length)return false;"));
test("question 47393: preserves adjacent source contract",()=>has(3,"if(!roots.length)return false;\nfor(const id of roots){"));
test("question 47394: preserves adjacent source contract",()=>has(3,"for(const id of roots){\nconst permission=permissionForEntry({kind:\"project-assembly\",assemblyId:id},\"move\");"));
test("question 47395: preserves adjacent source contract",()=>has(3,"const permission=permissionForEntry({kind:\"project-assembly\",assemblyId:id},\"move\");\nif(!permission.allowed){toast(permission.reason);return false;}"));
test("question 47396: preserves adjacent source contract",()=>has(3,"if(!permission.allowed){toast(permission.reason);return false;}\nconst d={x:Number(delta?.x)||0,y:Number(delta?.y)||0,z:Number(delta?.z)||0};"));
test("question 47397: preserves adjacent source contract",()=>has(3,"const d={x:Number(delta?.x)||0,y:Number(delta?.y)||0,z:Number(delta?.z)||0};\nreturn q78GuardedAssemblyTransform(roots.length>1?\"Move Assemblies\":\"Move Assembly\",roots,()=>{"));
test("question 47398: preserves adjacent source contract",()=>has(3,"return q78GuardedAssemblyTransform(roots.length>1?\"Move Assemblies\":\"Move Assembly\",roots,()=>{\nfor(const id of roots){"));
test("question 47399: preserves adjacent source contract",()=>has(3,"for(const id of roots){\nconst a=assemblyById(id),f=a.frame;"));
test("question 47400: preserves adjacent source contract",()=>has(3,"const a=assemblyById(id),f=a.frame;\napplyAssemblyFrame(id,{origin_mm:{x:f.origin_mm.x+d.x,y:f.origin_mm.y+d.y,z:f.origin_mm.z+d.z},rotation_quaternion:f.rotation_quaternion});"));
test("question 47401: preserves adjacent source contract",()=>has(3,"applyAssemblyFrame(id,{origin_mm:{x:f.origin_mm.x+d.x,y:f.origin_mm.y+d.y,z:f.origin_mm.z+d.z},rotation_quaternion:f.rotation_quaternion});\nreturn true;"));
test("question 47402: preserves adjacent source contract",()=>has(3,"return true;\nfunction moveAssembly(id,delta){return moveAssemblies([id],delta);}"));
test("question 47403: preserves adjacent source contract",()=>has(3,"function moveAssembly(id,delta){return moveAssemblies([id],delta);}\nfunction rotateAssembly(id,{axis={x:0,y:0,z:1},angle_deg=0}={}){"));
test("question 47404: preserves adjacent source contract",()=>has(3,"function rotateAssembly(id,{axis={x:0,y:0,z:1},angle_deg=0}={}){\nconst permission=permissionForEntry({kind:\"project-assembly\",assemblyId:id},\"rotate\");"));
test("question 47405: preserves adjacent source contract",()=>has(3,"const permission=permissionForEntry({kind:\"project-assembly\",assemblyId:id},\"rotate\");\nif(!permission.allowed){toast(permission.reason);return false;}"));
test("question 47406: preserves adjacent source contract",()=>has(3,"if(!permission.allowed){toast(permission.reason);return false;}\nconst angle=Number(angle_deg);if(!Number.isFinite(angle)){toast(\"Угол Rotate должен быть числом\");return false;}"));
test("question 47407: preserves adjacent source contract",()=>has(3,"const angle=Number(angle_deg);if(!Number.isFinite(angle)){toast(\"Угол Rotate должен быть числом\");return false;}\nreturn q78GuardedAssemblyTransform(\"Rotate Assembly\",[id],()=>{"));
test("question 47408: preserves adjacent source contract",()=>has(3,"return q78GuardedAssemblyTransform(\"Rotate Assembly\",[id],()=>{\nconst a=assemblyById(id),q=assemblies.axisAngleQuaternion(axis,angle);"));
test("question 47409: preserves adjacent source contract",()=>has(3,"const a=assemblyById(id),q=assemblies.axisAngleQuaternion(axis,angle);\napplyAssemblyFrame(id,{origin_mm:a.frame.origin_mm,rotation_quaternion:assemblies.multiplyQuaternions(q,a.frame.rotation_quaternion)});"));
test("question 47410: preserves adjacent source contract",()=>has(3,"applyAssemblyFrame(id,{origin_mm:a.frame.origin_mm,rotation_quaternion:assemblies.multiplyQuaternions(q,a.frame.rotation_quaternion)});\nreturn true;"));
test("question 47411: preserves adjacent source contract",()=>has(3,"return true;\nfunction setOrigin(id,origin){"));
test("question 47412: preserves adjacent source contract",()=>has(3,"function setOrigin(id,origin){\nconst p={x:Number(origin?.x),y:Number(origin?.y),z:Number(origin?.z)};"));
test("question 47413: preserves adjacent source contract",()=>has(3,"const p={x:Number(origin?.x),y:Number(origin?.y),z:Number(origin?.z)};\nif(![p.x,p.y,p.z].every(Number.isFinite)){toast(\"Origin XYZ должен быть числовым\");return false;}"));
test("question 47414: preserves adjacent source contract",()=>has(3,"if(![p.x,p.y,p.z].every(Number.isFinite)){toast(\"Origin XYZ должен быть числовым\");return false;}\nreturn command(\"Set Assembly Origin\",()=>{"));
test("question 47415: preserves adjacent source contract",()=>has(3,"return command(\"Set Assembly Origin\",()=>{\nconst a=assemblyById(id);syncAssemblyLocals(id);"));
test("question 47416: preserves adjacent source contract",()=>has(3,"const a=assemblyById(id);syncAssemblyLocals(id);\nassemblies.setAssemblyFrame(project(),id,{origin_mm:p,rotation_quaternion:a.frame.rotation_quaternion});"));
test("question 47417: preserves adjacent source contract",()=>has(3,"assemblies.setAssemblyFrame(project(),id,{origin_mm:p,rotation_quaternion:a.frame.rotation_quaternion});\nsyncAssemblyLocals(id);"));
test("question 47418: preserves adjacent source contract",()=>has(3,"syncAssemblyLocals(id);\nreturn true;"));
test("question 47419: preserves adjacent source contract",()=>has(3,"return true;\nfunction dissolve(id){"));
test("question 47420: preserves adjacent source contract",()=>has(3,"function dissolve(id){\nreturn command(\"Dissolve Assembly\",()=>{"));
test("question 47421: preserves adjacent source contract",()=>has(3,"return command(\"Dissolve Assembly\",()=>{\nconst leaves=assemblies.leafAssemblyMembers(project(),id).map(member=>clone(member.ref));"));
test("question 47422: preserves adjacent source contract",()=>has(3,"const leaves=assemblies.leafAssemblyMembers(project(),id).map(member=>clone(member.ref));\nconst result=assemblies.dissolveAssembly(project(),id);"));
test("question 47423: preserves adjacent source contract",()=>has(3,"const result=assemblies.dissolveAssembly(project(),id);\nif(result===false)return false;"));
test("question 47424: preserves adjacent source contract",()=>has(3,"if(result===false)return false;\nfor(const ref of leaves)if(ref.kind===\"tube\")syncTubePortConstraints(ref.id);"));
test("question 47425: preserves adjacent source contract",()=>has(3,"for(const ref of leaves)if(ref.kind===\"tube\")syncTubePortConstraints(ref.id);\nreturn true;"));
test("question 47426: preserves adjacent source contract",()=>has(3,"return true;\nfunction hiddenLeafKeys(){"));
test("question 47427: preserves adjacent source contract",()=>has(3,"function hiddenLeafKeys(){\nconst hidden=new Set();"));
test("question 47428: preserves adjacent source contract",()=>has(3,"const hidden=new Set();\nfor(const assembly of assemblies.ensureAssemblyState(project())){"));
test("question 47429: preserves adjacent source contract",()=>has(3,"for(const assembly of assemblies.ensureAssemblyState(project())){\nif(assembly.visible!==false)continue;"));
test("question 47430: preserves adjacent source contract",()=>has(3,"if(assembly.visible!==false)continue;\nfor(const member of assemblies.leafAssemblyMembers(project(),assembly.id))hidden.add(assemblies.assemblyMemberKey(member.ref));"));
test("question 47431: preserves adjacent source contract",()=>has(3,"for(const member of assemblies.leafAssemblyMembers(project(),assembly.id))hidden.add(assemblies.assemblyMemberKey(member.ref));\nreturn hidden;"));
test("question 47432: preserves adjacent source contract",()=>has(3,"return hidden;\nfunction objectMemberKey(object){"));
test("question 47433: preserves adjacent source contract",()=>has(3,"function objectMemberKey(object){\nlet item=object,active=String(eng()?.activeTube?.()?.id??\"\");"));
test("question 47434: preserves adjacent source contract",()=>has(3,"let item=object,active=String(eng()?.activeTube?.()?.id??\"\");\nwhile(item){"));
test("question 47435: preserves adjacent source contract",()=>has(3,"while(item){\nconst data=item.userData??{};"));
test("question 47436: preserves adjacent source contract",()=>has(3,"const data=item.userData??{};\nif(data.referenceEditableInstanceId)return \"mesh-instance:\"+String(data.referenceEditableInstanceId);"));
test("question 47437: preserves adjacent source contract",()=>has(3,"if(data.referenceEditableInstanceId)return \"mesh-instance:\"+String(data.referenceEditableInstanceId);\nif(data.tubeId)return \"tube:\"+String(data.tubeId);"));
test("question 47438: preserves adjacent source contract",()=>has(3,"if(data.tubeId)return \"tube:\"+String(data.tubeId);\nif(active&&(data.pipe===true||data.originPoint===true||data.tubeEnd===true||Number.isInteger(Number(data.rowIndex))))return \"tube:\"+active;"));
test("question 47439: preserves adjacent source contract",()=>has(3,"if(active&&(data.pipe===true||data.originPoint===true||data.tubeEnd===true||Number.isInteger(Number(data.rowIndex))))return \"tube:\"+active;\nitem=item.parent;"));
test("question 47440: preserves adjacent source contract",()=>has(3,"item=item.parent;\nreturn null;"));
test("question 47441: preserves adjacent source contract",()=>has(3,"return null;\nfunction memberKeyForObject(object){"));
test("question 47442: preserves adjacent source contract",()=>has(3,"function memberKeyForObject(object){\nlet item=object,activeTube=String(eng()?.activeTube?.()?.id??\"\");"));
test("question 47443: preserves adjacent source contract",()=>has(3,"let item=object,activeTube=String(eng()?.activeTube?.()?.id??\"\");\nwhile(item){"));
test("question 47444: preserves adjacent source contract",()=>has(3,"if(data.tubeId)return \"tube:\"+String(data.tubeId);\nif(activeTube&&(data.pipe===true||data.originPoint===true||data.tubeEnd===true||Number.isInteger(Number(data.rowIndex))))return \"tube:\"+activeTube;"));
test("question 47445: preserves adjacent source contract",()=>has(3,"if(activeTube&&(data.pipe===true||data.originPoint===true||data.tubeEnd===true||Number.isInteger(Number(data.rowIndex))))return \"tube:\"+activeTube;\nitem=item.parent;"));
test("question 47446: preserves adjacent source contract",()=>has(3,"return null;\nfunction restoreEditMaterial(object){"));
test("question 47447: preserves adjacent source contract",()=>has(3,"function restoreEditMaterial(object){\nconst saved=object?.userData?.tbAssemblyEditMaterial;"));
test("question 47448: preserves adjacent source contract",()=>has(3,"const saved=object?.userData?.tbAssemblyEditMaterial;\nif(!saved||!object?.material)return;"));
test("question 47449: preserves adjacent source contract",()=>has(3,"if(!saved||!object?.material)return;\nconst mats=Array.isArray(object.material)?object.material:[object.material];"));
test("question 47450: preserves adjacent source contract",()=>has(3,"const mats=Array.isArray(object.material)?object.material:[object.material];\nmats.forEach((m,index)=>{"));
test("question 47451: preserves adjacent source contract",()=>has(3,"mats.forEach((m,index)=>{\nconst state=saved[index]??saved[0];if(!m||!state)return;"));
test("question 47452: preserves adjacent source contract",()=>has(3,"const state=saved[index]??saved[0];if(!m||!state)return;\nm.opacity=state.opacity;m.transparent=state.transparent;m.depthWrite=state.depthWrite;m.needsUpdate=true;"));
test("question 47453: preserves adjacent source contract",()=>has(3,"m.opacity=state.opacity;m.transparent=state.transparent;m.depthWrite=state.depthWrite;m.needsUpdate=true;\ndelete object.userData.tbAssemblyEditMaterial;"));
test("question 47454: preserves adjacent source contract",()=>has(3,"delete object.userData.tbAssemblyEditMaterial;\nfunction muteEditMaterial(object){"));
test("question 47455: preserves adjacent source contract",()=>has(3,"function muteEditMaterial(object){\nif(!object?.material)return;"));
test("question 47456: preserves adjacent source contract",()=>has(3,"if(!object?.material)return;\nconst mats=Array.isArray(object.material)?object.material:[object.material];"));
test("question 47457: preserves adjacent source contract",()=>has(3,"const mats=Array.isArray(object.material)?object.material:[object.material];\nif(!object.userData.tbAssemblyEditMaterial){"));
test("question 47458: preserves adjacent source contract",()=>has(3,"if(!object.userData.tbAssemblyEditMaterial){\nobject.userData.tbAssemblyEditMaterial=mats.map(m=>({opacity:Number(m?.opacity??1),transparent:m?.transparent===true,depthWrite:m?.depthWrite!==false}));"));
test("question 47459: preserves adjacent source contract",()=>has(3,"object.userData.tbAssemblyEditMaterial=mats.map(m=>({opacity:Number(m?.opacity??1),transparent:m?.transparent===true,depthWrite:m?.depthWrite!==false}));\nmats.forEach(m=>{if(!m)return;m.opacity=Math.min(Number(m.opacity??1),.22);m.transparent=true;m.depthWrite=false;m.needsUpdate=true;});"));
test("question 47460: preserves adjacent source contract",()=>has(3,"mats.forEach(m=>{if(!m)return;m.opacity=Math.min(Number(m.opacity??1),.22);m.transparent=true;m.depthWrite=false;m.needsUpdate=true;});\nfunction applyEditContext(){"));
test("question 47461: preserves adjacent source contract",()=>has(3,"function applyEditContext(){\nif(typeof pipeGroup===\"undefined\"||!pipeGroup)return;"));
test("question 47462: preserves adjacent source contract",()=>has(3,"if(typeof pipeGroup===\"undefined\"||!pipeGroup)return;\nconst active=activeEditAssembly();"));
test("question 47463: preserves adjacent source contract",()=>has(3,"const active=activeEditAssembly();\nconst inside=active?new Set(assemblies.leafAssemblyMembers(project(),active.id).map(member=>assemblies.assemblyMemberKey(member.ref))):new Set();"));
test("question 47464: preserves adjacent source contract",()=>has(3,"const inside=active?new Set(assemblies.leafAssemblyMembers(project(),active.id).map(member=>assemblies.assemblyMemberKey(member.ref))):new Set();\npipeGroup.traverse(object=>{"));
test("question 47465: preserves adjacent source contract",()=>has(3,"pipeGroup.traverse(object=>{\nif(object===pipeGroup||object.userData?.helper)return;"));
test("question 47466: preserves adjacent source contract",()=>has(3,"if(object===pipeGroup||object.userData?.helper)return;\nconst key=memberKeyForObject(object);"));
test("question 47467: preserves adjacent source contract",()=>has(3,"const key=memberKeyForObject(object);\nif(!active||!key||inside.has(key))restoreEditMaterial(object);"));
test("question 47468: preserves adjacent source contract",()=>has(3,"if(!active||!key||inside.has(key))restoreEditMaterial(object);\nelse muteEditMaterial(object);"));
test("question 47469: preserves adjacent source contract",()=>has(3,"else muteEditMaterial(object);\ntry{if(typeof markViewerDirty===\"function\")markViewerDirty();}catch{}"));
test("question 47470: preserves adjacent source contract",()=>has(3,"try{if(typeof markViewerDirty===\"function\")markViewerDirty();}catch{}\nfunction applyVisibility(){"));
test("question 47471: preserves adjacent source contract",()=>has(3,"function applyVisibility(){\nif(typeof pipeGroup===\"undefined\"||!pipeGroup||!assemblies)return;"));
test("question 47472: preserves adjacent source contract",()=>has(3,"if(typeof pipeGroup===\"undefined\"||!pipeGroup||!assemblies)return;\nconst hidden=hiddenLeafKeys();"));
test("question 47473: preserves adjacent source contract",()=>has(3,"const hidden=hiddenLeafKeys();\npipeGroup.traverse(object=>{"));
test("question 47474: preserves adjacent source contract",()=>has(3,"if(object===pipeGroup||object.userData?.helper)return;\nconst key=objectMemberKey(object);if(!key)return;"));
test("question 47475: preserves adjacent source contract",()=>has(3,"const key=objectMemberKey(object);if(!key)return;\nobject.userData={...(object.userData??{}),tbAssemblyHidden:hidden.has(key)};"));
test("question 47476: preserves adjacent source contract",()=>has(3,"object.userData={...(object.userData??{}),tbAssemblyHidden:hidden.has(key)};\nif(hidden.has(key))object.visible=false;"));
test("question 47477: preserves adjacent source contract",()=>has(3,"if(hidden.has(key))object.visible=false;\ntry{if(typeof markViewerDirty===\"function\")markViewerDirty();}catch{}"));
test("question 47478: preserves adjacent source contract",()=>has(3,"try{if(typeof markViewerDirty===\"function\")markViewerDirty();}catch{}\nfunction memberLabel(member){"));
test("question 47479: preserves adjacent source contract",()=>has(3,"function memberLabel(member){\nconst ref=member.ref;"));
test("question 47480: preserves adjacent source contract",()=>has(3,"const ref=member.ref;\nif(ref.kind===\"tube\")return tubeById(ref.id)?.name??ref.id;"));
test("question 47481: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"tube\")return tubeById(ref.id)?.name??ref.id;\nif(ref.kind===\"mesh-instance\")return meshById(ref.id)?.name??ref.id;"));
test("question 47482: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"mesh-instance\")return meshById(ref.id)?.name??ref.id;\nif(ref.kind===\"assembly\")return assemblyById(ref.id)?.name??ref.id;"));
test("question 47483: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"assembly\")return assemblyById(ref.id)?.name??ref.id;\nreturn ref.kind+\" · \"+ref.id;"));
test("question 47484: preserves adjacent source contract",()=>has(3,"return ref.kind+\" · \"+ref.id;\nfunction assemblyTreeHtml(id,depth=0,seen=new Set()){"));
test("question 47485: preserves adjacent source contract",()=>has(3,"function assemblyTreeHtml(id,depth=0,seen=new Set()){\nconst a=assemblyById(id);if(!a||seen.has(String(id)))return \"\";"));
test("question 47486: preserves adjacent source contract",()=>has(3,"const a=assemblyById(id);if(!a||seen.has(String(id)))return \"\";\nseen.add(String(id));"));
test("question 47487: preserves adjacent source contract",()=>has(3,"seen.add(String(id));\nconst pad=30+depth*18,lock=String(a.lock_state?.mode??\"Unlocked\");"));
test("question 47488: preserves adjacent source contract",()=>has(3,"const pad=30+depth*18,lock=String(a.lock_state?.mode??\"Unlocked\");\nlet html='<div class=\"tb-tree-node clickable tb-project-assembly\" style=\"padding-left:'+pad+'px\" data-project-assembly=\"'+esc(a.id)+'\"><span class=\"tb-tree-icon\">◫</span><span class=\"tb-tree-label\">'+esc(a.name)+' <small>· '+(a.members?.length??0)+(a.fixed?' · fixed':'')+(a.visible===false?' · hidden':'')+(lock!==\"Unlocked\"?' · '+esc(lock):'')+'</small></span></div>';"));
test("question 47489: preserves adjacent source contract",()=>has(3,"let html='<div class=\"tb-tree-node clickable tb-project-assembly\" style=\"padding-left:'+pad+'px\" data-project-assembly=\"'+esc(a.id)+'\"><span class=\"tb-tree-icon\">◫</span><span class=\"tb-tree-label\">'+esc(a.name)+' <small>· '+(a.members?.length??0)+(a.fixed?' · fixed':'')+(a.visible===false?' · hidden':'')+(lock!==\"Unlocked\"?' · '+esc(lock):'')+'</small></span></div>';\nfor(const member of a.members??[]){"));
test("question 47490: preserves adjacent source contract",()=>has(3,"for(const member of a.members??[]){\nif(member.ref.kind===\"assembly\"){html+=assemblyTreeHtml(member.ref.id,depth+1,seen);continue;}"));
test("question 47491: preserves adjacent source contract",()=>has(3,"if(member.ref.kind===\"assembly\"){html+=assemblyTreeHtml(member.ref.id,depth+1,seen);continue;}\nconst key=selectionKeyForRef(member.ref);"));
test("question 47492: preserves adjacent source contract",()=>has(3,"const key=selectionKeyForRef(member.ref);\nhtml+='<div class=\"tb-tree-node clickable tb-assembly-member\" style=\"padding-left:'+(pad+18)+'px\" data-assembly-member-key=\"'+esc(key)+'\" data-assembly-owner=\"'+esc(a.id)+'\"><span class=\"tb-tree-icon\">·</span><span class=\"tb-tree-label\">'+esc(memberLabel(member))+'</span></div>';"));
test("question 47493: preserves adjacent source contract",()=>has(3,"html+='<div class=\"tb-tree-node clickable tb-assembly-member\" style=\"padding-left:'+(pad+18)+'px\" data-assembly-member-key=\"'+esc(key)+'\" data-assembly-owner=\"'+esc(a.id)+'\"><span class=\"tb-tree-icon\">·</span><span class=\"tb-tree-label\">'+esc(memberLabel(member))+'</span></div>';\nseen.delete(String(id));return html;"));
test("question 47494: preserves adjacent source contract",()=>has(3,"seen.delete(String(id));return html;\nfunction renderTree(){"));
test("question 47495: preserves adjacent source contract",()=>has(3,"function renderTree(){\nconst host=document.getElementById(\"tbProjectTree\");if(!host||!assemblies)return;"));
test("question 47496: preserves adjacent source contract",()=>has(3,"const host=document.getElementById(\"tbProjectTree\");if(!host||!assemblies)return;\nconst all=assemblies.ensureAssemblyState(project());"));
test("question 47497: preserves adjacent source contract",()=>has(3,"const all=assemblies.ensureAssemblyState(project());\nconst signature=JSON.stringify(all.map(a=>({id:a.id,name:a.name,frame:a.frame,members:a.members,fixed:a.fixed,visible:a.visible,lock_state:a.lock_state})));"));
test("question 47498: preserves adjacent source contract",()=>has(3,"const signature=JSON.stringify(all.map(a=>({id:a.id,name:a.name,frame:a.frame,members:a.members,fixed:a.fixed,visible:a.visible,lock_state:a.lock_state})));\nlet section=host.querySelector(\"[data-assemblies-tree-root]\");"));
