import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const files=["src/ui/object-selection-context-ui.js","src/ui/editing-ui.js","src/import/dwfx/reference-scene-ui.js","src/ui/assemblies-runtime.js","src/ui/equipment-library-ui.js"];
const normalized=files.map(rel=>fs.readFileSync(path.join(root,rel),"utf8").split(/\r?\n/).map(s=>s.trim()).filter(s=>s.length>=8&&!s.startsWith("//")&&s!=="{"&&s!=="}"&&s!=="};").join("\n"));
// DWFx adjacent pairs were intentionally rebased after indexed scene rendering (PERF-001).
const has=(fileIndex,pair)=>assert.ok(normalized[fileIndex].includes(pair));
test("question 45599: preserves adjacent source contract",()=>has(2,"x:Number((Number(r.x||0)+Number(deltaDeg?.x||0)).toFixed(6)),\ny:Number((Number(r.y||0)+Number(deltaDeg?.y||0)).toFixed(6)),"));
test("question 45600: preserves adjacent source contract",()=>has(2,"y:Number((Number(r.y||0)+Number(deltaDeg?.y||0)).toFixed(6)),\nz:Number((Number(r.z||0)+Number(deltaDeg?.z||0)).toFixed(6))"));
test("question 45601: preserves adjacent source contract",()=>has(2,"z:Number((Number(r.z||0)+Number(deltaDeg?.z||0)).toFixed(6))\nreturn instance;"));
test("question 45602: preserves adjacent source contract",()=>has(2,"return instance;\nfunction copyEditableMeshInstance(project,instanceId,{offset_mm={x:0,y:0,z:0},name=null}={}){"));
test("question 45603: preserves adjacent source contract",()=>has(2,"function copyEditableMeshInstance(project,instanceId,{offset_mm={x:0,y:0,z:0},name=null}={}){\nbumpRevision(\"geometry\");"));
test("question 45604: preserves adjacent source contract",()=>has(2,"const source=meshInstanceById(project,instanceId);\nif(!source)throw new Error(\"Editable mesh instance not found\");"));
test("question 45605: preserves adjacent source contract",()=>has(2,"if(!source)throw new Error(\"Editable mesh instance not found\");\nconst p=source.transform?.position_mm??{x:0,y:0,z:0};"));
test("question 45606: preserves adjacent source contract",()=>has(2,"const p=source.transform?.position_mm??{x:0,y:0,z:0};\nconst copy=clonePlain(source);"));
test("question 45607: preserves adjacent source contract",()=>has(2,"const copy=clonePlain(source);\ncopy.id=meshInstanceId();"));
test("question 45608: preserves adjacent source contract",()=>has(2,"copy.id=meshInstanceId();\ncopy.name=String(name??String(source.name??\"Editable mesh\")+\" copy\");"));
test("question 45609: preserves adjacent source contract",()=>has(2,"copy.name=String(name??String(source.name??\"Editable mesh\")+\" copy\");\ncopy.source_seed=false;"));
test("question 45610: preserves adjacent source contract",()=>has(2,"copy.source_seed=false;\ncopy.array_member=null;"));
test("question 45611: preserves adjacent source contract",()=>has(2,"copy.array_member=null;\ncopy.transform={"));
test("question 45612: preserves adjacent source contract",()=>has(2,"copy.transform={\n...(copy.transform??{}),"));
test("question 45613: preserves adjacent source contract",()=>has(2,"...(copy.transform??{}),\nposition_mm:{"));
test("question 45614: preserves adjacent source contract",()=>has(2,"position_mm:{\nx:Number(p.x||0)+Number(offset_mm?.x||0),"));
test("question 45615: preserves adjacent source contract",()=>has(2,"x:Number(p.x||0)+Number(offset_mm?.x||0),\ny:Number(p.y||0)+Number(offset_mm?.y||0),"));
test("question 45616: preserves adjacent source contract",()=>has(2,"y:Number(p.y||0)+Number(offset_mm?.y||0),\nz:Number(p.z||0)+Number(offset_mm?.z||0)"));
test("question 45617: preserves adjacent source contract",()=>has(2,"z:Number(p.z||0)+Number(offset_mm?.z||0)\neditableMeshInstanceList(project).push(copy);"));
test("question 45618: preserves adjacent source contract",()=>has(2,"editableMeshInstanceList(project).push(copy);\nreturn copy;"));
test("question 45619: preserves adjacent source contract",()=>has(2,"return copy;\nfunction arrayEditableMeshInstance(project,instanceId,{count=2,step_mm={x:0,y:0,z:0}}={}){"));
test("question 45620: preserves adjacent source contract",()=>has(2,"function arrayEditableMeshInstance(project,instanceId,{count=2,step_mm={x:0,y:0,z:0}}={}){\nbumpRevision(\"geometry\");"));
test("question 45621: preserves adjacent source contract",()=>has(2,"const n=Math.trunc(Number(count));\nif(!(n>=2))throw new RangeError(\"Array count must be >= 2\");"));
test("question 45622: preserves adjacent source contract",()=>has(2,"if(!(n>=2))throw new RangeError(\"Array count must be >= 2\");\nconst created=[];"));
test("question 45623: preserves adjacent source contract",()=>has(2,"const created=[];\nfor(let index=1;index<n;index++){"));
test("question 45624: preserves adjacent source contract",()=>has(2,"for(let index=1;index<n;index++){\nconst copy=copyEditableMeshInstance(project,instanceId,{"));
test("question 45625: preserves adjacent source contract",()=>has(2,"const copy=copyEditableMeshInstance(project,instanceId,{\noffset_mm:{"));
test("question 45626: preserves adjacent source contract",()=>has(2,"offset_mm:{\nx:Number(step_mm?.x||0)*index,"));
test("question 45627: preserves adjacent source contract",()=>has(2,"x:Number(step_mm?.x||0)*index,\ny:Number(step_mm?.y||0)*index,"));
test("question 45628: preserves adjacent source contract",()=>has(2,"y:Number(step_mm?.y||0)*index,\nz:Number(step_mm?.z||0)*index"));
test("question 45629: preserves adjacent source contract",()=>has(2,"z:Number(step_mm?.z||0)*index\ncopy.array_member={source_instance_id:String(instanceId),member_index:index,derived:false};"));
test("question 45630: preserves adjacent source contract",()=>has(2,"copy.array_member={source_instance_id:String(instanceId),member_index:index,derived:false};\ncreated.push(copy);"));
test("question 45631: preserves adjacent source contract",()=>has(2,"created.push(copy);\nreturn created;"));
test("question 45632: preserves adjacent source contract",()=>has(2,"return created;\nfunction collectDetachedAssets(runtime,node){"));
test("question 45633: preserves adjacent source contract",()=>has(2,"function collectDetachedAssets(runtime,node){\nconst ids=new Set();"));
test("question 45634: preserves adjacent source contract",()=>has(2,"const ids=new Set();\nconst visitAsset=(assetId)=>{"));
test("question 45635: preserves adjacent source contract",()=>has(2,"const visitAsset=(assetId)=>{\nconst key=String(assetId??\"\");"));
test("question 45636: preserves adjacent source contract",()=>has(2,"const key=String(assetId??\"\");\nif(!key||ids.has(key))return;"));
test("question 45637: preserves adjacent source contract",()=>has(2,"if(!key||ids.has(key))return;\nconst asset=runtime?.assetsById?.get(key);"));
test("question 45638: preserves adjacent source contract",()=>has(2,"const asset=runtime?.assetsById?.get(key);\nif(!asset)return;"));
test("question 45639: preserves adjacent source contract",()=>has(2,"if(!asset)return;\nids.add(key);"));
test("question 45640: preserves adjacent source contract",()=>has(2,"ids.add(key);\nfor(const nested of asset.nested_instances??[])visitAsset(nested?.asset_id);"));
test("question 45641: preserves adjacent source contract",()=>has(2,"for(const nested of asset.nested_instances??[])visitAsset(nested?.asset_id);\nconst visitNode=(item)=>{"));
test("question 45642: preserves adjacent source contract",()=>has(2,"const visitNode=(item)=>{\nfor(const gi of item?.geometry_instances??[])visitAsset(gi?.asset_id);"));
test("question 45643: preserves adjacent source contract",()=>has(2,"for(const gi of item?.geometry_instances??[])visitAsset(gi?.asset_id);\nfor(const child of item?.children??[])visitNode(child);"));
test("question 45644: preserves adjacent source contract",()=>has(2,"for(const child of item?.children??[])visitNode(child);\nvisitNode(node);"));
test("question 45645: preserves adjacent source contract",()=>has(2,"visitNode(node);\nreturn [...ids].map((key)=>clonePlain(runtime.assetsById.get(key))).filter(Boolean);"));
test("question 45646: preserves adjacent source contract",()=>has(2,"return [...ids].map((key)=>clonePlain(runtime.assetsById.get(key))).filter(Boolean);\nfunction snapshotMeshInstanceSource(project,instance){"));
test("question 45647: preserves adjacent source contract",()=>has(2,"function snapshotMeshInstanceSource(project,instance){\nconst linked=meshInstanceSource(project,instance);"));
test("question 45648: preserves adjacent source contract",()=>has(2,"const linked=meshInstanceSource(project,instance);\nif(!linked)throw new Error(\"Source mesh is unavailable\");"));
test("question 45649: preserves adjacent source contract",()=>has(2,"if(!linked)throw new Error(\"Source mesh is unavailable\");\nconst runtime=runtimeForScene(linked.scene);"));
test("question 45650: preserves adjacent source contract",()=>has(2,"const runtime=runtimeForScene(linked.scene);\nif(!runtime)throw new Error(\"Source mesh runtime is unavailable\");"));
test("question 45651: preserves adjacent source contract",()=>has(2,"if(!runtime)throw new Error(\"Source mesh runtime is unavailable\");\nreturn {"));
test("question 45652: preserves adjacent source contract",()=>has(2,"return {\nschema:\"detached_mesh_instance_v1\","));
test("question 45653: preserves adjacent source contract",()=>has(2,"schema:\"detached_mesh_instance_v1\",\nsource_scene_id:String(linked.scene.id),"));
test("question 45654: preserves adjacent source contract",()=>has(2,"source_scene_id:String(linked.scene.id),\nsource_node_id:String(linked.node.id),"));
test("question 45655: preserves adjacent source contract",()=>has(2,"source_node_id:String(linked.node.id),\nscale_mm_per_source_unit:Number(linked.scene.scale_mm_per_source_unit)||Number(runtime.scale_mm_per_source_unit)||1,"));
test("question 45656: preserves adjacent source contract",()=>has(2,"scale_mm_per_source_unit:Number(linked.scene.scale_mm_per_source_unit)||Number(runtime.scale_mm_per_source_unit)||1,\nnode:clonePlain(linked.node),"));
test("question 45657: preserves adjacent source contract",()=>has(2,"node:clonePlain(linked.node),\nassets:collectDetachedAssets(runtime,linked.node)"));
test("question 45658: preserves adjacent source contract",()=>has(2,"assets:collectDetachedAssets(runtime,linked.node)\nfunction breakEditableMeshInstanceLink(project,instanceId){"));
test("question 45659: preserves adjacent source contract",()=>has(2,"function breakEditableMeshInstanceLink(project,instanceId){\nbumpRevision(\"geometry\");"));
test("question 45660: preserves adjacent source contract",()=>has(2,"if(!instance)throw new Error(\"Editable mesh instance not found\");\nif(instance.link_status===\"detached\")return instance;"));
test("question 45661: preserves adjacent source contract",()=>has(2,"if(instance.link_status===\"detached\")return instance;\ninstance.detached_payload=snapshotMeshInstanceSource(project,instance);"));
test("question 45662: preserves adjacent source contract",()=>has(2,"instance.detached_payload=snapshotMeshInstanceSource(project,instance);\ninstance.link_status=\"detached\";"));
test("question 45663: preserves adjacent source contract",()=>has(2,"instance.link_status=\"detached\";\ninstance.source_seed=false;"));
test("question 45664: preserves adjacent source contract",()=>has(2,"instance.source_seed=false;\ninstance.compare_source=false;"));
test("question 45665: preserves adjacent source contract",()=>has(2,"instance.compare_source=false;\ninstance.source_visible=false;"));
test("question 45666: preserves adjacent source contract",()=>has(2,"instance.source_visible=false;\nreturn instance;"));
test("question 45667: preserves adjacent source contract",()=>has(2,"return instance;\nfunction nodeTranslationMm(node){"));
test("question 45668: preserves adjacent source contract",()=>has(2,"function nodeTranslationMm(node){\nconst value=node?.translation_mm;"));
test("question 45669: preserves adjacent source contract",()=>has(2,"const value=node?.translation_mm;\nconst source=Array.isArray(value)"));
test("question 45670: preserves adjacent source contract",()=>has(2,"const source=Array.isArray(value)\n? {x:value[0],y:value[1],z:value[2]}"));
test("question 45671: preserves adjacent source contract",()=>has(2,"? {x:value[0],y:value[1],z:value[2]}\n: value&&typeof value===\"object\""));
test("question 45672: preserves adjacent source contract",()=>has(2,": value&&typeof value===\"object\"\nconst out={"));
test("question 45673: preserves adjacent source contract",()=>has(2,"const out={\nx:Number(source.x)||0,"));
test("question 45674: preserves adjacent source contract",()=>has(2,"x:Number(source.x)||0,\ny:Number(source.y)||0,"));
test("question 45675: preserves adjacent source contract",()=>has(2,"y:Number(source.y)||0,\nz:Number(source.z)||0"));
test("question 45676: preserves adjacent source contract",()=>has(2,"z:Number(source.z)||0\nreturn out;"));
test("question 45677: preserves adjacent source contract",()=>has(2,"return out;\nfunction addTranslationMm(a,b){"));
test("question 45678: preserves adjacent source contract",()=>has(2,"function addTranslationMm(a,b){\nreturn {"));
test("question 45679: preserves adjacent source contract",()=>has(2,"return {\nx:(Number(a?.x)||0)+(Number(b?.x)||0),"));
test("question 45680: preserves adjacent source contract",()=>has(2,"x:(Number(a?.x)||0)+(Number(b?.x)||0),\ny:(Number(a?.y)||0)+(Number(b?.y)||0),"));
test("question 45681: preserves adjacent source contract",()=>has(2,"y:(Number(a?.y)||0)+(Number(b?.y)||0),\nz:(Number(a?.z)||0)+(Number(b?.z)||0)"));
test("question 45682: preserves adjacent source contract",()=>has(2,"z:(Number(a?.z)||0)+(Number(b?.z)||0)\nfunction selectedKeySet(){"));
test("question 45683: preserves adjacent source contract",()=>has(2,"function selectedKeySet(){\nreturn new Set(bulkSelected);"));
test("question 45684: preserves adjacent source contract",()=>has(2,"return new Set(bulkSelected);\nconst FRAME_IDENTITY=Object.freeze(["));
test("question 45685: preserves adjacent source contract",()=>has(2,"const FRAME_IDENTITY=Object.freeze([\n1,0,0,0,"));
test("question 45686: preserves adjacent source contract",()=>has(2,"1,0,0,0,\n0,1,0,0,"));
test("question 45687: preserves adjacent source contract",()=>has(2,"0,1,0,0,\n0,0,1,0,"));
test("question 45688: preserves adjacent source contract",()=>has(2,"0,0,1,0,\nfunction frameMatrix16(value){"));
test("question 45689: preserves adjacent source contract",()=>has(2,"function frameMatrix16(value){\nif(!Array.isArray(value)||value.length!==16)return FRAME_IDENTITY;"));
test("question 45690: preserves adjacent source contract",()=>has(2,"if(!Array.isArray(value)||value.length!==16)return FRAME_IDENTITY;\nconst out=value.map(Number);"));
test("question 45691: preserves adjacent source contract",()=>has(2,"const out=value.map(Number);\nreturn out.every(Number.isFinite)?out:FRAME_IDENTITY;"));
test("question 45692: preserves adjacent source contract",()=>has(2,"return out.every(Number.isFinite)?out:FRAME_IDENTITY;\nfunction frameMultiply4(a,b){"));
test("question 45693: preserves adjacent source contract",()=>has(2,"function frameMultiply4(a,b){\nconst left=frameMatrix16(a),right=frameMatrix16(b);"));
test("question 45694: preserves adjacent source contract",()=>has(2,"const left=frameMatrix16(a),right=frameMatrix16(b);\nconst out=new Array(16).fill(0);"));
test("question 45695: preserves adjacent source contract",()=>has(2,"const out=new Array(16).fill(0);\nfor(let col=0;col<4;col+=1){"));
test("question 45696: preserves adjacent source contract",()=>has(2,"for(let col=0;col<4;col+=1){\nfor(let row=0;row<4;row+=1){"));
test("question 45697: preserves adjacent source contract",()=>has(2,"for(let row=0;row<4;row+=1){\nlet sum=0;"));
test("question 45698: preserves adjacent source contract",()=>has(2,"let sum=0;\nfor(let k=0;k<4;k+=1){"));
test("question 45699: preserves adjacent source contract",()=>has(2,"for(let k=0;k<4;k+=1){\nsum+=left[k*4+row]*right[col*4+k];"));
test("question 45700: preserves adjacent source contract",()=>has(2,"sum+=left[k*4+row]*right[col*4+k];\nout[col*4+row]=sum;"));
test("question 45701: preserves adjacent source contract",()=>has(2,"out[col*4+row]=sum;\nreturn out;"));
test("question 45702: preserves adjacent source contract",()=>has(2,"return out;\nfunction frameTransformPoint(point,matrix){"));
test("question 45703: preserves adjacent source contract",()=>has(2,"function frameTransformPoint(point,matrix){\nif(!Array.isArray(point)||point.length<3)return null;"));
test("question 45704: preserves adjacent source contract",()=>has(2,"if(!Array.isArray(point)||point.length<3)return null;\nconst x=Number(point[0]),y=Number(point[1]),z=Number(point[2]);"));
test("question 45705: preserves adjacent source contract",()=>has(2,"const x=Number(point[0]),y=Number(point[1]),z=Number(point[2]);\nif(![x,y,z].every(Number.isFinite))return null;"));
test("question 45706: preserves adjacent source contract",()=>has(2,"if(![x,y,z].every(Number.isFinite))return null;\nconst m=frameMatrix16(matrix);"));
test("question 45707: preserves adjacent source contract",()=>has(2,"const m=frameMatrix16(matrix);\nconst w=m[3]*x+m[7]*y+m[11]*z+m[15];"));
test("question 45708: preserves adjacent source contract",()=>has(2,"const w=m[3]*x+m[7]*y+m[11]*z+m[15];\nconst denom=Number.isFinite(w)&&Math.abs(w)>1e-12?w:1;"));
test("question 45709: preserves adjacent source contract",()=>has(2,"const denom=Number.isFinite(w)&&Math.abs(w)>1e-12?w:1;\nreturn ["));
test("question 45710: preserves adjacent source contract",()=>has(2,"return [\n(m[0]*x+m[4]*y+m[8]*z+m[12])/denom,"));
test("question 45711: preserves adjacent source contract",()=>has(2,"(m[0]*x+m[4]*y+m[8]*z+m[12])/denom,\n(m[1]*x+m[5]*y+m[9]*z+m[13])/denom,"));
test("question 45712: preserves adjacent source contract",()=>has(2,"(m[1]*x+m[5]*y+m[9]*z+m[13])/denom,\n(m[2]*x+m[6]*y+m[10]*z+m[14])/denom"));
test("question 45713: preserves adjacent source contract",()=>has(2,"(m[2]*x+m[6]*y+m[10]*z+m[14])/denom\nfunction runtimeForScene(scene){"));
test("question 45714: preserves adjacent source contract",()=>has(2,"function runtimeForScene(scene){\nlet runtime=runtimes.get(runtimeKey(scene));"));
test("question 45715: preserves adjacent source contract",()=>has(2,"let runtime=runtimes.get(runtimeKey(scene));\nif(!runtime&&scene?.display_runtime){"));
test("question 45716: preserves adjacent source contract",()=>has(2,"if(!runtime&&scene?.display_runtime){\nregisterRuntime(scene.display_runtime);"));
test("question 45717: preserves adjacent source contract",()=>has(2,"registerRuntime(scene.display_runtime);\nruntime=runtimes.get(runtimeKey(scene));"));
test("question 45718: preserves adjacent source contract",()=>has(2,"runtime=runtimes.get(runtimeKey(scene));\nreturn runtime??null;"));
test("question 45719: preserves adjacent source contract",()=>has(2,"return runtime??null;\nfunction emptyFrameBounds(){"));
test("question 45720: preserves adjacent source contract",()=>has(2,"function emptyFrameBounds(){\nreturn {"));
test("question 45721: preserves adjacent source contract",()=>has(2,"return {\nmin:[Infinity,Infinity,Infinity],"));
test("question 45722: preserves adjacent source contract",()=>has(2,"min:[Infinity,Infinity,Infinity],\nmax:[-Infinity,-Infinity,-Infinity],"));
test("question 45723: preserves adjacent source contract",()=>has(2,"max:[-Infinity,-Infinity,-Infinity],\npoint_count:0"));
test("question 45724: preserves adjacent source contract",()=>has(2,"point_count:0\nfunction expandFrameBounds(bounds,pointMm){"));
test("question 45725: preserves adjacent source contract",()=>has(2,"function expandFrameBounds(bounds,pointMm){\nif(!Array.isArray(pointMm)||pointMm.length<3)return;"));
test("question 45726: preserves adjacent source contract",()=>has(2,"if(!Array.isArray(pointMm)||pointMm.length<3)return;\nconst point=pointMm.slice(0,3).map(Number);"));
test("question 45727: preserves adjacent source contract",()=>has(2,"const point=pointMm.slice(0,3).map(Number);\nif(!point.every(Number.isFinite))return;"));
test("question 45728: preserves adjacent source contract",()=>has(2,"if(!point.every(Number.isFinite))return;\nfor(let axis=0;axis<3;axis+=1){"));
test("question 45729: preserves adjacent source contract",()=>has(2,"for(let axis=0;axis<3;axis+=1){\nbounds.min[axis]=Math.min(bounds.min[axis],point[axis]);"));
test("question 45730: preserves adjacent source contract",()=>has(2,"bounds.min[axis]=Math.min(bounds.min[axis],point[axis]);\nbounds.max[axis]=Math.max(bounds.max[axis],point[axis]);"));
test("question 45731: preserves adjacent source contract",()=>has(2,"bounds.max[axis]=Math.max(bounds.max[axis],point[axis]);\nbounds.point_count+=1;"));
test("question 45732: preserves adjacent source contract",()=>has(2,"bounds.point_count+=1;\nfunction appendAssetBounds({"));
test("question 45733: preserves adjacent source contract",()=>has(2,"function appendAssetBounds({\nruntime,"));
test("question 45734: preserves adjacent source contract",()=>has(2,"runtime,\nassetId,"));
test("question 45735: preserves adjacent source contract",()=>has(2,"assetId,\ntranslationMm,"));
test("question 45736: preserves adjacent source contract",()=>has(2,"translationMm,\nscaleMm,"));
test("question 45737: preserves adjacent source contract",()=>has(2,"scaleMm,\nstack=new Set()"));
test("question 45738: preserves adjacent source contract",()=>has(2,"stack=new Set()\nconst key=String(assetId??\"\");"));
test("question 45739: preserves adjacent source contract",()=>has(2,"const key=String(assetId??\"\");\nif(!key||stack.has(key))return;"));
test("question 45740: preserves adjacent source contract",()=>has(2,"if(!key||stack.has(key))return;\nconst asset=runtime?.assetsById?.get(key);"));
test("question 45741: preserves adjacent source contract",()=>has(2,"const asset=runtime?.assetsById?.get(key);\nif(!asset||asset.status!==\"exact\")return;"));
test("question 45742: preserves adjacent source contract",()=>has(2,"if(!asset||asset.status!==\"exact\")return;\nconst nextStack=new Set(stack);"));
test("question 45743: preserves adjacent source contract",()=>has(2,"const nextStack=new Set(stack);\nnextStack.add(key);"));
test("question 45744: preserves adjacent source contract",()=>has(2,"nextStack.add(key);\nconst appendPoint=(point,transform)=>{"));
test("question 45745: preserves adjacent source contract",()=>has(2,"const appendPoint=(point,transform)=>{\nconst source=frameTransformPoint(point,transform);"));
test("question 45746: preserves adjacent source contract",()=>has(2,"const source=frameTransformPoint(point,transform);\nif(!source)return;"));
test("question 45747: preserves adjacent source contract",()=>has(2,"if(!source)return;\nexpandFrameBounds(bounds,["));
test("question 45748: preserves adjacent source contract",()=>has(2,"expandFrameBounds(bounds,[\nsource[0]*scaleMm+translationMm.x,"));
test("question 45749: preserves adjacent source contract",()=>has(2,"source[0]*scaleMm+translationMm.x,\nsource[1]*scaleMm+translationMm.y,"));
test("question 45750: preserves adjacent source contract",()=>has(2,"source[1]*scaleMm+translationMm.y,\nsource[2]*scaleMm+translationMm.z"));
test("question 45751: preserves adjacent source contract",()=>has(2,"source[2]*scaleMm+translationMm.z\nfor(const mesh of asset.meshes??[]){"));
test("question 45752: preserves adjacent source contract",()=>has(2,"for(const mesh of asset.meshes??[]){\nconst meshMatrix=frameMultiply4(matrix,mesh?.matrix);"));
test("question 45753: preserves adjacent source contract",()=>has(2,"const meshMatrix=frameMultiply4(matrix,mesh?.matrix);\nfor(const vertex of mesh?.vertices??[])appendPoint(vertex,meshMatrix);"));
test("question 45754: preserves adjacent source contract",()=>has(2,"for(const vertex of mesh?.vertices??[])appendPoint(vertex,meshMatrix);\nconst positions=asset.line_segments?.positions??[];"));
test("question 45755: preserves adjacent source contract",()=>has(2,"const positions=asset.line_segments?.positions??[];\nfor(let index=0;index+2<positions.length;index+=3){"));
test("question 45756: preserves adjacent source contract",()=>has(2,"for(let index=0;index+2<positions.length;index+=3){\nappendPoint("));
test("question 45757: preserves adjacent source contract",()=>has(2,"appendPoint(\n[positions[index],positions[index+1],positions[index+2]],"));
test("question 45758: preserves adjacent source contract",()=>has(2,"[positions[index],positions[index+1],positions[index+2]],\nfor(const nested of asset.nested_instances??[]){"));
test("question 45759: preserves adjacent source contract",()=>has(2,"for(const nested of asset.nested_instances??[]){\nif(nested?.status!==\"exact\")continue;"));
test("question 45760: preserves adjacent source contract",()=>has(2,"if(nested?.status!==\"exact\")continue;\nappendAssetBounds({"));
test("question 45761: preserves adjacent source contract",()=>has(2,"appendAssetBounds({\nruntime,"));
test("question 45762: preserves adjacent source contract",()=>has(2,"runtime,\nassetId:nested.asset_id,"));
test("question 45763: preserves adjacent source contract",()=>has(2,"assetId:nested.asset_id,\nmatrix:frameMultiply4(matrix,nested.placement_matrix),"));
test("question 45764: preserves adjacent source contract",()=>has(2,"matrix:frameMultiply4(matrix,nested.placement_matrix),\ntranslationMm,"));
test("question 45765: preserves adjacent source contract",()=>has(2,"scaleMm,\nstack:nextStack"));
test("question 45766: preserves adjacent source contract",()=>has(2,"stack:nextStack\nfunction currentReferenceProjectBounds(project){"));
test("question 45767: preserves adjacent source contract",()=>has(2,"function currentReferenceProjectBounds(project){\nconst bounds=emptyFrameBounds();"));
test("question 45768: preserves adjacent source contract",()=>has(2,"const bounds=emptyFrameBounds();\nfor(const scene of project?.referenceScenes??[]){"));
test("question 45769: preserves adjacent source contract",()=>has(2,"for(const scene of project?.referenceScenes??[]){\nconst runtime=runtimeForScene(scene);"));
test("question 45770: preserves adjacent source contract",()=>has(2,"const runtime=runtimeForScene(scene);\nif(!runtime){"));
test("question 45771: preserves adjacent source contract",()=>has(2,"if(!runtime){\nreturn Object.freeze({"));
test("question 45772: preserves adjacent source contract",()=>has(2,"return Object.freeze({\nstatus:\"unresolved\","));
test("question 45773: preserves adjacent source contract",()=>has(2,"status:\"unresolved\",\nreason:\"Reference-scene runtime is unavailable.\","));
test("question 45774: preserves adjacent source contract",()=>has(2,"reason:\"Reference-scene runtime is unavailable.\",\npoint_count:bounds.point_count"));
test("question 45775: preserves adjacent source contract",()=>has(2,"point_count:bounds.point_count\nconst scaleMm=Number(scene?.scale_mm_per_source_unit)||"));
test("question 45776: preserves adjacent source contract",()=>has(2,"const scaleMm=Number(scene?.scale_mm_per_source_unit)||\nNumber(runtime?.scale_mm_per_source_unit)||1;"));
test("question 45777: preserves adjacent source contract",()=>has(2,"Number(runtime?.scale_mm_per_source_unit)||1;\nif(!Number.isFinite(scaleMm)||scaleMm<=0){"));
test("question 45778: preserves adjacent source contract",()=>has(2,"if(!Number.isFinite(scaleMm)||scaleMm<=0){\nreturn Object.freeze({"));
test("question 45779: preserves adjacent source contract",()=>has(2,"status:\"unresolved\",\nreason:\"Reference-scene scale is invalid.\","));
test("question 45780: preserves adjacent source contract",()=>has(2,"reason:\"Reference-scene scale is invalid.\",\npoint_count:bounds.point_count"));
test("question 45781: preserves adjacent source contract",()=>has(2,"point_count:bounds.point_count\nconst visit=(node,parentTranslation={x:0,y:0,z:0})=>{"));
test("question 45782: preserves adjacent source contract",()=>has(2,"const visit=(node,parentTranslation={x:0,y:0,z:0})=>{\nconst translation=addTranslationMm(parentTranslation,nodeTranslationMm(node));"));
test("question 45783: preserves adjacent source contract",()=>has(2,"const translation=addTranslationMm(parentTranslation,nodeTranslationMm(node));\nfor(const instance of node?.geometry_instances??[]){"));
test("question 45784: preserves adjacent source contract",()=>has(2,"for(const instance of node?.geometry_instances??[]){\nif(instance?.status!==\"exact\")continue;"));
test("question 45785: preserves adjacent source contract",()=>has(2,"if(instance?.status!==\"exact\")continue;\nappendAssetBounds({"));
test("question 45786: preserves adjacent source contract",()=>has(2,"runtime,\nassetId:instance.asset_id,"));
test("question 45787: preserves adjacent source contract",()=>has(2,"assetId:instance.asset_id,\nmatrix:frameMatrix16(instance.placement_matrix),"));
test("question 45788: preserves adjacent source contract",()=>has(2,"matrix:frameMatrix16(instance.placement_matrix),\ntranslationMm:translation,"));
test("question 45789: preserves adjacent source contract",()=>has(2,"translationMm:translation,\nscaleMm,"));
test("question 45790: preserves adjacent source contract",()=>has(2,"scaleMm,\nfor(const child of node?.children??[])visit(child,translation);"));
test("question 45791: preserves adjacent source contract",()=>has(2,"for(const child of node?.children??[])visit(child,translation);\nfor(const root of scene?.tree??[])visit(root);"));
test("question 45792: preserves adjacent source contract",()=>has(2,"for(const root of scene?.tree??[])visit(root);\nif(bounds.point_count===0){"));
test("question 45793: preserves adjacent source contract",()=>has(2,"if(bounds.point_count===0){\nreturn Object.freeze({"));
test("question 45794: preserves adjacent source contract",()=>has(2,"return Object.freeze({\nstatus:\"empty\","));
test("question 45795: preserves adjacent source contract",()=>has(2,"status:\"empty\",\npoint_count:0,"));
test("question 45796: preserves adjacent source contract",()=>has(2,"point_count:0,\nmin:null,"));
test("question 45797: preserves adjacent source contract",()=>has(2,"min:null,\nmax:null,"));
test("question 45798: preserves adjacent source contract",()=>has(2,"max:null,\nsize:null"));
test("question 45799: preserves adjacent source contract",()=>has(2,"size:null\nconst size=bounds.max.map((value,index)=>value-bounds.min[index]);"));
test("question 45800: preserves adjacent source contract",()=>has(2,"const size=bounds.max.map((value,index)=>value-bounds.min[index]);\nreturn Object.freeze({"));
test("question 45801: preserves adjacent source contract",()=>has(2,"return Object.freeze({\nstatus:\"exact\","));
test("question 45802: preserves adjacent source contract",()=>has(2,"status:\"exact\",\npoint_count:bounds.point_count,"));
test("question 45803: preserves adjacent source contract",()=>has(2,"point_count:bounds.point_count,\nmin:Object.freeze([...bounds.min]),"));
test("question 45804: preserves adjacent source contract",()=>has(2,"min:Object.freeze([...bounds.min]),\nmax:Object.freeze([...bounds.max]),"));
test("question 45805: preserves adjacent source contract",()=>has(2,"max:Object.freeze([...bounds.max]),\nsize:Object.freeze(size)"));
test("question 45806: preserves adjacent source contract",()=>has(2,"size:Object.freeze(size)\nfunction automaticFrameFromCurrentBounds(bounds){"));
test("question 45807: preserves adjacent source contract",()=>has(2,"function automaticFrameFromCurrentBounds(bounds){\nif(bounds?.status!==\"exact\")return Object.freeze({"));
test("question 45808: preserves adjacent source contract",()=>has(2,"if(bounds?.status!==\"exact\")return Object.freeze({\nstatus:bounds?.status??\"unresolved\","));
test("question 45809: preserves adjacent source contract",()=>has(2,"status:bounds?.status??\"unresolved\",\nreason:bounds?.reason??\"Reference bounds are unavailable.\""));
test("question 45810: preserves adjacent source contract",()=>has(2,"reason:bounds?.reason??\"Reference bounds are unavailable.\"\nconst min=bounds.min.map(Math.floor);"));
test("question 45811: preserves adjacent source contract",()=>has(2,"const min=bounds.min.map(Math.floor);\nconst max=bounds.max.map(Math.ceil);"));
test("question 45812: preserves adjacent source contract",()=>has(2,"const max=bounds.max.map(Math.ceil);\nconst size=max.map((value,index)=>value-min[index]);"));
test("question 45813: preserves adjacent source contract",()=>has(2,"const size=max.map((value,index)=>value-min[index]);\nif(!size.every((value)=>Number.isFinite(value)&&value>0)){"));
test("question 45814: preserves adjacent source contract",()=>has(2,"if(!size.every((value)=>Number.isFinite(value)&&value>0)){\nreturn Object.freeze({"));
test("question 45815: preserves adjacent source contract",()=>has(2,"status:\"unresolved\",\nreason:\"Remaining imported geometry does not define a positive 3D frame.\""));
test("question 45816: preserves adjacent source contract",()=>has(2,"reason:\"Remaining imported geometry does not define a positive 3D frame.\"\nreturn Object.freeze({"));
test("question 45817: preserves adjacent source contract",()=>has(2,"status:\"exact\",\nbbox:Object.freeze({x:size[0],y:size[1],z:size[2]}),"));
test("question 45818: preserves adjacent source contract",()=>has(2,"bbox:Object.freeze({x:size[0],y:size[1],z:size[2]}),\nbboxAnchor:Object.freeze({x:0,y:0,z:0}),"));
test("question 45819: preserves adjacent source contract",()=>has(2,"bboxAnchor:Object.freeze({x:0,y:0,z:0}),\ncoordinateOffset:Object.freeze({x:min[0],y:min[1],z:min[2]}),"));
test("question 45820: preserves adjacent source contract",()=>has(2,"coordinateOffset:Object.freeze({x:min[0],y:min[1],z:min[2]}),\nexactBoundsMm:Object.freeze({"));
test("question 45821: preserves adjacent source contract",()=>has(2,"exactBoundsMm:Object.freeze({\nmin:Object.freeze([...bounds.min]),"));
test("question 45822: preserves adjacent source contract",()=>has(2,"max:Object.freeze([...bounds.max]),\nsize:Object.freeze([...bounds.size])"));
test("question 45823: preserves adjacent source contract",()=>has(2,"size:Object.freeze([...bounds.size])\nframeBoundsMm:Object.freeze({"));
test("question 45824: preserves adjacent source contract",()=>has(2,"frameBoundsMm:Object.freeze({\nmin:Object.freeze([...min]),"));
test("question 45825: preserves adjacent source contract",()=>has(2,"min:Object.freeze([...min]),\nmax:Object.freeze([...max]),"));
test("question 45826: preserves adjacent source contract",()=>has(2,"max:Object.freeze([...max]),\nsize:Object.freeze([...size])"));
test("question 45827: preserves adjacent source contract",()=>has(2,"size:Object.freeze([...size])\nroundingRule:\"floor_min_ceil_max_mm\""));
test("question 45828: preserves adjacent source contract",()=>has(2,"roundingRule:\"floor_min_ceil_max_mm\"\nfunction renderSceneTree({"));
test("question 45829: preserves adjacent source contract",()=>has(2,"function renderSceneTree({\nsceneMeta,"));
test("question 45830: preserves adjacent source contract",()=>has(2,"sceneMeta,\nruntime,"));
test("question 45831: preserves adjacent source contract",()=>has(2,"runtime,\nproject,"));
test("question 45832: preserves adjacent source contract",()=>has(2,"project,\ngeomScale"));
test("question 45833: preserves adjacent source contract",()=>has(2,"sourceLookup=null\nif(sceneMeta?.visible===false)return;"));
test("question 45834: preserves adjacent source contract",()=>has(2,"if(sceneMeta?.visible===false)return;\nconst sceneGroup=new THREE.Group();"));
test("question 45835: preserves adjacent source contract",()=>has(2,"const sceneGroup=new THREE.Group();\nsceneGroup.name=\"DWFx reference: \"+String(sceneMeta?.source_file??sceneMeta?.name??\"\");"));
test("question 45836: preserves adjacent source contract",()=>has(2,"sceneGroup.name=\"DWFx reference: \"+String(sceneMeta?.source_file??sceneMeta?.name??\"\");\nsceneGroup.userData.referenceGeometry=true;"));
test("question 45837: preserves adjacent source contract",()=>has(2,"sceneGroup.userData.referenceGeometry=true;\nsceneGroup.userData.referenceSceneId=sceneMeta.id;"));
test("question 45838: preserves adjacent source contract",()=>has(2,"sceneGroup.userData.referenceSceneId=sceneMeta.id;\nconst scaleMm=Number(sceneMeta?.scale_mm_per_source_unit)||"));
test("question 45839: preserves adjacent source contract",()=>has(2,"const scaleMm=Number(sceneMeta?.scale_mm_per_source_unit)||\nNumber(runtime.scale_mm_per_source_unit)||1;"));
test("question 45840: preserves adjacent source contract",()=>has(2,"Number(runtime.scale_mm_per_source_unit)||1;\nsceneGroup.scale.setScalar(scaleMm*Number(geomScale||1));"));
test("question 45841: preserves adjacent source contract",()=>has(2,"sceneGroup.scale.setScalar(scaleMm*Number(geomScale||1));\nconst hidden=hiddenSet(sceneMeta);"));
test("question 45842: preserves adjacent source contract",()=>has(2,"const hidden=hiddenSet(sceneMeta);\nconst transparent=transparentSet(sceneMeta);"));
test("question 45843: preserves adjacent source contract",()=>has(2,"const transparent=transparentSet(sceneMeta);\nconst renderLookup=sourceLookup??buildSourceRenderIndex(project,sceneMeta.id);"));
test("question 45844: preserves adjacent source contract",()=>has(2,"const renderLookup=sourceLookup??buildSourceRenderIndex(project,sceneMeta.id);\nconst editable=renderLookup.editableParts;"));
test("question 45845: preserves adjacent source contract",()=>has(2,"const selectedKeys=renderLookup.selectedKeys;\nconst selectedGroups=[];"));
test("question 45846: preserves adjacent source contract",()=>has(2,"const selectedGroups=[];\nconst visit=("));
test("question 45847: preserves adjacent source contract",()=>has(2,"const visit=(\nparentHidden=false,"));
test("question 45848: preserves adjacent source contract",()=>has(2,"parentHidden=false,\nparentTransparent=false,"));
test("question 45849: preserves adjacent source contract",()=>has(2,"parentTransparent=false,\nparentTranslation={x:0,y:0,z:0}"));
test("question 45850: preserves adjacent source contract",()=>has(2,"parentTranslation={x:0,y:0,z:0}\nconst nodeHidden=parentHidden||hidden.has(String(node.id))||node.visible===false;"));
test("question 45851: preserves adjacent source contract",()=>has(2,"const nodeHidden=parentHidden||hidden.has(String(node.id))||node.visible===false;\nif(nodeHidden)return;"));
test("question 45852: preserves adjacent source contract",()=>has(2,"if(nodeHidden)return;\nconst nodeTransparent=parentTransparent||transparent.has(String(node.id));"));
test("question 45853: preserves adjacent source contract",()=>has(2,"const nodeTransparent=parentTransparent||transparent.has(String(node.id));\nconst translation=addTranslationMm(parentTranslation,nodeTranslationMm(node));"));
test("question 45854: preserves adjacent source contract",()=>has(2,"const translation=addTranslationMm(parentTranslation,nodeTranslationMm(node));\nconst recognizedPart=String(node.editable_part_number??\"\");"));
test("question 45855: preserves adjacent source contract",()=>has(2,"const recognizedPart=String(node.editable_part_number??\"\");\nconst linkedState=sourceDisplayState(project,sceneMeta,node,renderLookup);"));
test("question 45856: preserves adjacent source contract",()=>has(2,"const linkedState=sourceDisplayState(project,sceneMeta,node,renderLookup);\nconst meshState=meshSourceDisplayState(project,sceneMeta,node,renderLookup);"));
test("question 45857: preserves adjacent source contract",()=>has(2,"const meshState=meshSourceDisplayState(project,sceneMeta,node,renderLookup);\nconst sourceTube=renderLookup.firstAny.get(String(node.id))??null;"));
test("question 45858: preserves adjacent source contract",()=>has(2,"const sourceTube=renderLookup.firstAny.get(String(node.id))??null;\nconst detachedSource=sourceLink(sourceTube)?.detached===true;"));
test("question 45859: preserves adjacent source contract",()=>has(2,"const detachedSource=sourceLink(sourceTube)?.detached===true;\nconst suppressEditable=meshState"));
test("question 45860: preserves adjacent source contract",()=>has(2,"const suppressEditable=meshState\n? !meshState.visible"));
test("question 45861: preserves adjacent source contract",()=>has(2,"? !meshState.visible\n: linkedState"));
test("question 45862: preserves adjacent source contract",()=>has(2,": linkedState\n? !linkedState.visible"));
test("question 45863: preserves adjacent source contract",()=>has(2,"? !linkedState.visible\n: detachedSource"));
test("question 45864: preserves adjacent source contract",()=>has(2,": detachedSource\n: !!(recognizedPart&&editable.has(recognizedPart));"));
test("question 45865: preserves adjacent source contract",()=>has(2,": !!(recognizedPart&&editable.has(recognizedPart));\nif(!suppressEditable){"));
test("question 45866: preserves adjacent source contract",()=>has(2,"if(!suppressEditable){\nconst nodeGroup=new THREE.Group();"));
test("question 45867: preserves adjacent source contract",()=>has(2,"const nodeGroup=new THREE.Group();\nnodeGroup.userData.referenceShared=true;"));
test("question 45868: preserves adjacent source contract",()=>has(2,"nodeGroup.userData.referenceShared=true;\nnodeGroup.userData.referenceGeometry=true;"));
test("question 45869: preserves adjacent source contract",()=>has(2,"nodeGroup.userData.referenceGeometry=true;\nnodeGroup.userData.referenceNodeId=String(node.id);"));
test("question 45870: preserves adjacent source contract",()=>has(2,"nodeGroup.userData.referenceNodeId=String(node.id);\nnodeGroup.userData.referenceSceneId=String(sceneMeta.id);"));
test("question 45871: preserves adjacent source contract",()=>has(2,"nodeGroup.userData.referenceSceneId=String(sceneMeta.id);\nif(linkedState?.tube?.id){"));
test("question 45872: preserves adjacent source contract",()=>has(2,"if(linkedState?.tube?.id){\nnodeGroup.userData.sourceLinkedEditableTubeId=String(linkedState.tube.id);"));
test("question 45873: preserves adjacent source contract",()=>has(2,"nodeGroup.userData.sourceLinkedEditableTubeId=String(linkedState.tube.id);\nnodeGroup.userData.sourceEditableHighlight=linkedState.selectedEditable===true;"));
test("question 45874: preserves adjacent source contract",()=>has(2,"nodeGroup.userData.sourceEditableHighlight=linkedState.selectedEditable===true;\nnodeGroup.userData.sourceCompare=linkedState.compare===true;"));
test("question 45875: preserves adjacent source contract",()=>has(2,"nodeGroup.userData.sourceCompare=linkedState.compare===true;\nnodeGroup.position.set("));
test("question 45876: preserves adjacent source contract",()=>has(2,"nodeGroup.position.set(\ntranslation.x/scaleMm,"));
test("question 45877: preserves adjacent source contract",()=>has(2,"translation.x/scaleMm,\ntranslation.y/scaleMm,"));
test("question 45878: preserves adjacent source contract",()=>has(2,"translation.y/scaleMm,\ntranslation.z/scaleMm"));
test("question 45879: preserves adjacent source contract",()=>has(2,"translation.z/scaleMm\nlet instanceCount=0;"));
test("question 45880: preserves adjacent source contract",()=>has(2,"let instanceCount=0;\nfor(const instance of node.geometry_instances??[]){"));
test("question 45881: preserves adjacent source contract",()=>has(2,"for(const instance of node.geometry_instances??[]){\nif(instance?.status!==\"exact\")continue;"));
test("question 45882: preserves adjacent source contract",()=>has(2,"if(instance?.status!==\"exact\")continue;\nconst asset=runtime.assetsById.get(String(instance.asset_id));"));
test("question 45883: preserves adjacent source contract",()=>has(2,"const asset=runtime.assetsById.get(String(instance.asset_id));\nif(!asset||asset.status!==\"exact\")continue;"));
test("question 45884: preserves adjacent source contract",()=>has(2,"if(!asset||asset.status!==\"exact\")continue;\nconst template=buildAssetTemplate("));
test("question 45885: preserves adjacent source contract",()=>has(2,"const template=buildAssetTemplate(\nruntime,"));
test("question 45886: preserves adjacent source contract",()=>has(2,"runtime,\n(nodeTransparent||linkedState?.transparent||meshState?.transparent)?\"transparent\":\"normal\""));
test("question 45887: preserves adjacent source contract",()=>has(2,"(nodeTransparent||linkedState?.transparent||meshState?.transparent)?\"transparent\":\"normal\"\nconst placed=template.clone(true);"));
test("question 45888: preserves adjacent source contract",()=>has(2,"const placed=template.clone(true);\nplaced.userData.referenceShared=true;"));
test("question 45889: preserves adjacent source contract",()=>has(2,"placed.userData.referenceGeometry=true;\nplaced.userData.referenceNodeId=String(node.id);"));
test("question 45890: preserves adjacent source contract",()=>has(2,"placed.userData.referenceNodeId=String(node.id);\nplaced.userData.referenceSceneId=String(sceneMeta.id);"));
test("question 45891: preserves adjacent source contract",()=>has(2,"placed.userData.referenceSceneId=String(sceneMeta.id);\nif(linkedState?.tube?.id){"));
test("question 45892: preserves adjacent source contract",()=>has(2,"if(linkedState?.tube?.id){\nplaced.userData.sourceLinkedEditableTubeId=String(linkedState.tube.id);"));
test("question 45893: preserves adjacent source contract",()=>has(2,"placed.userData.sourceLinkedEditableTubeId=String(linkedState.tube.id);\nplaced.userData.sourceEditableHighlight=linkedState.selectedEditable===true;"));
test("question 45894: preserves adjacent source contract",()=>has(2,"placed.userData.sourceEditableHighlight=linkedState.selectedEditable===true;\nplaced.userData.sourceCompare=linkedState.compare===true;"));
test("question 45895: preserves adjacent source contract",()=>has(2,"placed.userData.sourceCompare=linkedState.compare===true;\nif(Array.isArray(instance.placement_matrix)&&instance.placement_matrix.length===16){"));
test("question 45896: preserves adjacent source contract",()=>has(2,"placed.matrixAutoUpdate=false;\nnodeGroup.add(placed);"));
test("question 45897: preserves adjacent source contract",()=>has(2,"nodeGroup.add(placed);\ninstanceCount+=1;"));
test("question 45898: preserves adjacent source contract",()=>has(2,"instanceCount+=1;\nif(instanceCount){"));
test("question 45899: preserves adjacent source contract",()=>has(2,"if(instanceCount){\nsceneGroup.add(nodeGroup);"));
test("question 45900: preserves adjacent source contract",()=>has(2,"sceneGroup.add(nodeGroup);\nif(selectedKeys.has(selectionKey(sceneMeta.id,node.id))){"));
test("question 45901: preserves adjacent source contract",()=>has(2,"if(selectedKeys.has(selectionKey(sceneMeta.id,node.id))){\nselectedGroups.push(nodeGroup);"));
test("question 45902: preserves adjacent source contract",()=>has(2,"selectedGroups.push(nodeGroup);\nfor(const child of node.children??[]){"));
test("question 45903: preserves adjacent source contract",()=>has(2,"for(const child of node.children??[]){\nvisit(child,nodeHidden,nodeTransparent,translation);"));
test("question 45904: preserves adjacent source contract",()=>has(2,"visit(child,nodeHidden,nodeTransparent,translation);\nfor(const root of sceneMeta?.tree??[]){"));
test("question 45905: preserves adjacent source contract",()=>has(2,"for(const root of sceneMeta?.tree??[]){\nvisit(root,false,false,{x:0,y:0,z:0});"));
test("question 45906: preserves adjacent source contract",()=>has(2,"visit(root,false,false,{x:0,y:0,z:0});\nparent.add(sceneGroup);"));
test("question 45907: preserves adjacent source contract",()=>has(2,"parent.add(sceneGroup);\nif(selectedGroups.length){"));
test("question 45908: preserves adjacent source contract",()=>has(2,"if(selectedGroups.length){\nsceneGroup.updateMatrixWorld(true);"));
test("question 45909: preserves adjacent source contract",()=>has(2,"sceneGroup.updateMatrixWorld(true);\nfor(const group of selectedGroups){"));
test("question 45910: preserves adjacent source contract",()=>has(2,"for(const group of selectedGroups){\nconst box=new THREE.Box3().setFromObject(group);"));
test("question 45911: preserves adjacent source contract",()=>has(2,"const box=new THREE.Box3().setFromObject(group);\nif(box.isEmpty())continue;"));
test("question 45912: preserves adjacent source contract",()=>has(2,"if(box.isEmpty())continue;\nconst helper=new THREE.Box3Helper(box,0x4da3ff);"));
test("question 45913: preserves adjacent source contract",()=>has(2,"const helper=new THREE.Box3Helper(box,0x4da3ff);\nhelper.userData.helper=true;"));
test("question 45914: preserves adjacent source contract",()=>has(2,"helper.userData.helper=true;\nhelper.userData.referenceSelectionHelper=true;"));
test("question 45915: preserves adjacent source contract",()=>has(2,"helper.userData.referenceSelectionHelper=true;\nparent.add(helper);"));
test("question 45916: preserves adjacent source contract",()=>has(2,"parent.add(helper);\nfunction detachedRuntime(payload){"));
test("question 45917: preserves adjacent source contract",()=>has(2,"function detachedRuntime(payload){\nif(!payload?.assets)return null;"));
test("question 45918: preserves adjacent source contract",()=>has(2,"if(!payload?.assets)return null;\nreturn {"));
test("question 45919: preserves adjacent source contract",()=>has(2,"return {\nscale_mm_per_source_unit:Number(payload.scale_mm_per_source_unit)||1,"));
test("question 45920: preserves adjacent source contract",()=>has(2,"scale_mm_per_source_unit:Number(payload.scale_mm_per_source_unit)||1,\nassetsById:new Map((payload.assets??[]).map((asset)=>[String(asset.id),asset]))"));
test("question 45921: preserves adjacent source contract",()=>has(2,"assetsById:new Map((payload.assets??[]).map((asset)=>[String(asset.id),asset]))\nfunction renderMeshInstanceNode({"));
test("question 45922: preserves adjacent source contract",()=>has(2,"function renderMeshInstanceNode({\nparent,node,runtime,THREE,instanceId,sceneId,sourceNodeId,transparent=false"));
test("question 45923: preserves adjacent source contract",()=>has(2,"parent,node,runtime,THREE,instanceId,sceneId,sourceNodeId,transparent=false\nconst nodeGroup=new THREE.Group();"));
test("question 45924: preserves adjacent source contract",()=>has(2,"const nodeGroup=new THREE.Group();\nconst t=nodeTranslationMm(node);"));
test("question 45925: preserves adjacent source contract",()=>has(2,"const t=nodeTranslationMm(node);\nconst scaleMm=Number(runtime?.scale_mm_per_source_unit)||1;"));
test("question 45926: preserves adjacent source contract",()=>has(2,"const scaleMm=Number(runtime?.scale_mm_per_source_unit)||1;\nnodeGroup.position.set(t.x/scaleMm,t.y/scaleMm,t.z/scaleMm);"));
test("question 45927: preserves adjacent source contract",()=>has(2,"nodeGroup.position.set(t.x/scaleMm,t.y/scaleMm,t.z/scaleMm);\nnodeGroup.userData={"));
test("question 45928: preserves adjacent source contract",()=>has(2,"nodeGroup.userData={\nhelper:false,"));
test("question 45929: preserves adjacent source contract",()=>has(2,"helper:false,\nreferenceEditableInstanceId:String(instanceId),"));
test("question 45930: preserves adjacent source contract",()=>has(2,"referenceEditableInstanceId:String(instanceId),\nsourceReferenceSceneId:String(sceneId??\"\"),"));
test("question 45931: preserves adjacent source contract",()=>has(2,"sourceReferenceSceneId:String(sceneId??\"\"),\nsourceReferenceNodeId:String(sourceNodeId??\"\"),"));
test("question 45932: preserves adjacent source contract",()=>has(2,"sourceReferenceNodeId:String(sourceNodeId??\"\"),\neditableMeshInstance:true"));
test("question 45933: preserves adjacent source contract",()=>has(2,"editableMeshInstance:true\nlet count=0;"));
test("question 45934: preserves adjacent source contract",()=>has(2,"let count=0;\nfor(const geometryInstance of node?.geometry_instances??[]){"));
test("question 45935: preserves adjacent source contract",()=>has(2,"for(const geometryInstance of node?.geometry_instances??[]){\nif(geometryInstance?.status!==\"exact\")continue;"));
test("question 45936: preserves adjacent source contract",()=>has(2,"if(geometryInstance?.status!==\"exact\")continue;\nconst asset=runtime?.assetsById?.get(String(geometryInstance.asset_id));"));
test("question 45937: preserves adjacent source contract",()=>has(2,"const asset=runtime?.assetsById?.get(String(geometryInstance.asset_id));\nif(!asset||asset.status!==\"exact\")continue;"));
test("question 45938: preserves adjacent source contract",()=>has(2,"if(!asset||asset.status!==\"exact\")continue;\nconst placed=buildAssetTemplate(runtime,asset,THREE,transparent?\"transparent\":\"normal\").clone(true);"));
test("question 45939: preserves adjacent source contract",()=>has(2,"const placed=buildAssetTemplate(runtime,asset,THREE,transparent?\"transparent\":\"normal\").clone(true);\nplaced.userData={"));
test("question 45940: preserves adjacent source contract",()=>has(2,"placed.userData={\n...(placed.userData??{}),"));
test("question 45941: preserves adjacent source contract",()=>has(2,"...(placed.userData??{}),\nreferenceEditableInstanceId:String(instanceId),"));
test("question 45942: preserves adjacent source contract",()=>has(2,"editableMeshInstance:true\nif(Array.isArray(geometryInstance.placement_matrix)&&geometryInstance.placement_matrix.length===16){"));
test("question 45943: preserves adjacent source contract",()=>has(2,"if(Array.isArray(geometryInstance.placement_matrix)&&geometryInstance.placement_matrix.length===16){\nplaced.matrix.fromArray(geometryInstance.placement_matrix);"));
test("question 45944: preserves adjacent source contract",()=>has(2,"placed.matrix.fromArray(geometryInstance.placement_matrix);\nplaced.matrixAutoUpdate=false;"));
test("question 45945: preserves adjacent source contract",()=>has(2,"placed.matrixAutoUpdate=false;\nnodeGroup.add(placed);count+=1;"));
test("question 45946: preserves adjacent source contract",()=>has(2,"nodeGroup.add(placed);count+=1;\nfor(const child of node?.children??[]){"));
test("question 45947: preserves adjacent source contract",()=>has(2,"for(const child of node?.children??[]){\ncount+=renderMeshInstanceNode({"));
test("question 45948: preserves adjacent source contract",()=>has(2,"count+=renderMeshInstanceNode({\nparent:nodeGroup,node:child,runtime,THREE,instanceId,sceneId,sourceNodeId,transparent"));
test("question 45949: preserves adjacent source contract",()=>has(2,"parent:nodeGroup,node:child,runtime,THREE,instanceId,sceneId,sourceNodeId,transparent\nif(count)parent.add(nodeGroup);"));
test("question 45950: preserves adjacent source contract",()=>has(2,"if(count)parent.add(nodeGroup);\nreturn count;"));
test("question 45951: preserves adjacent source contract",()=>has(2,"return count;\nfunction renderEditableMeshInstances({parent,project,THREE,geomScale}){"));
test("question 45952: preserves adjacent source contract",()=>has(2,"function renderEditableMeshInstances({parent,project,THREE,geomScale}){\nlet rendered=0;"));
test("question 45953: preserves adjacent source contract",()=>has(2,"let rendered=0;\nfor(const instance of editableMeshInstanceList(project,{create:false})){"));
test("question 45954: preserves adjacent source contract",()=>has(2,"for(const instance of editableMeshInstanceList(project,{create:false})){\nif(instance?.visible===false)continue;"));
test("question 45955: preserves adjacent source contract",()=>has(2,"if(instance?.visible===false)continue;\nlet sourceScene=null,sourceNode=null,runtime=null,scaleMm=1;"));
test("question 45956: preserves adjacent source contract",()=>has(2,"let sourceScene=null,sourceNode=null,runtime=null,scaleMm=1;\nif(instance.link_status===\"detached\"&&instance.detached_payload){"));
test("question 45957: preserves adjacent source contract",()=>has(2,"if(instance.link_status===\"detached\"&&instance.detached_payload){\nsourceNode=instance.detached_payload.node;"));
test("question 45958: preserves adjacent source contract",()=>has(2,"sourceNode=instance.detached_payload.node;\nruntime=detachedRuntime(instance.detached_payload);"));
test("question 45959: preserves adjacent source contract",()=>has(2,"runtime=detachedRuntime(instance.detached_payload);\nscaleMm=Number(instance.detached_payload.scale_mm_per_source_unit)||1;"));
test("question 45960: preserves adjacent source contract",()=>has(2,"scaleMm=Number(instance.detached_payload.scale_mm_per_source_unit)||1;\nconst linked=meshInstanceSource(project,instance);"));
test("question 45961: preserves adjacent source contract",()=>has(2,"const linked=meshInstanceSource(project,instance);\nif(!linked)continue;"));
test("question 45962: preserves adjacent source contract",()=>has(2,"if(!linked)continue;\nsourceScene=linked.scene;sourceNode=linked.node;"));
test("question 45963: preserves adjacent source contract",()=>has(2,"sourceScene=linked.scene;sourceNode=linked.node;\nruntime=runtimeForScene(sourceScene);"));
test("question 45964: preserves adjacent source contract",()=>has(2,"runtime=runtimeForScene(sourceScene);\nscaleMm=Number(sourceScene?.scale_mm_per_source_unit)||Number(runtime?.scale_mm_per_source_unit)||1;"));
test("question 45965: preserves adjacent source contract",()=>has(2,"scaleMm=Number(sourceScene?.scale_mm_per_source_unit)||Number(runtime?.scale_mm_per_source_unit)||1;\nif(!sourceNode||!runtime)continue;"));
test("question 45966: preserves adjacent source contract",()=>has(2,"if(!sourceNode||!runtime)continue;\nconst sceneGroup=new THREE.Group();"));
test("question 45967: preserves adjacent source contract",()=>has(2,"const sceneGroup=new THREE.Group();\nsceneGroup.name=\"Editable mesh instance: \"+String(instance.name??instance.id);"));
test("question 45968: preserves adjacent source contract",()=>has(2,"sceneGroup.name=\"Editable mesh instance: \"+String(instance.name??instance.id);\nsceneGroup.scale.setScalar(scaleMm*Number(geomScale||1));"));
test("question 45969: preserves adjacent source contract",()=>has(2,"sceneGroup.scale.setScalar(scaleMm*Number(geomScale||1));\nsceneGroup.userData={"));
test("question 45970: preserves adjacent source contract",()=>has(2,"sceneGroup.userData={\nreferenceEditableInstanceId:String(instance.id),"));
test("question 45971: preserves adjacent source contract",()=>has(2,"referenceEditableInstanceId:String(instance.id),\neditableMeshInstance:true,"));
test("question 45972: preserves adjacent source contract",()=>has(2,"editableMeshInstance:true,\nsourceReferenceSceneId:String(instance.source?.scene_id??\"\"),"));
test("question 45973: preserves adjacent source contract",()=>has(2,"sourceReferenceSceneId:String(instance.source?.scene_id??\"\"),\nsourceReferenceNodeId:String(instance.source?.node_id??\"\")"));
test("question 45974: preserves adjacent source contract",()=>has(2,"sourceReferenceNodeId:String(instance.source?.node_id??\"\")\nconst transform=instance.transform??{};"));
test("question 45975: preserves adjacent source contract",()=>has(2,"const transform=instance.transform??{};\nconst p=transform.position_mm??{};"));
test("question 45976: preserves adjacent source contract",()=>has(2,"const p=transform.position_mm??{};\nsceneGroup.position.set("));
test("question 45977: preserves adjacent source contract",()=>has(2,"sceneGroup.position.set(\n(Number(p.x)||0)*Number(geomScale||1),"));
test("question 45978: preserves adjacent source contract",()=>has(2,"(Number(p.x)||0)*Number(geomScale||1),\n(Number(p.y)||0)*Number(geomScale||1),"));
test("question 45979: preserves adjacent source contract",()=>has(2,"(Number(p.y)||0)*Number(geomScale||1),\n(Number(p.z)||0)*Number(geomScale||1)"));
test("question 45980: preserves adjacent source contract",()=>has(2,"(Number(p.z)||0)*Number(geomScale||1)\nconst q=transform.rotation_quaternion;"));
test("question 45981: preserves adjacent source contract",()=>has(2,"const q=transform.rotation_quaternion;\nif(q&&[q.x,q.y,q.z,q.w].every((value)=>Number.isFinite(Number(value)))){"));
test("question 45982: preserves adjacent source contract",()=>has(2,"if(q&&[q.x,q.y,q.z,q.w].every((value)=>Number.isFinite(Number(value)))){\nsceneGroup.quaternion.set(Number(q.x),Number(q.y),Number(q.z),Number(q.w)).normalize();"));
test("question 45983: preserves adjacent source contract",()=>has(2,"sceneGroup.quaternion.set(Number(q.x),Number(q.y),Number(q.z),Number(q.w)).normalize();\nconst r=transform.rotation_deg??{};"));
test("question 45984: preserves adjacent source contract",()=>has(2,"const r=transform.rotation_deg??{};\nsceneGroup.rotation.set("));
test("question 45985: preserves adjacent source contract",()=>has(2,"sceneGroup.rotation.set(\nTHREE.MathUtils.degToRad(Number(r.x)||0),"));
test("question 45986: preserves adjacent source contract",()=>has(2,"THREE.MathUtils.degToRad(Number(r.x)||0),\nTHREE.MathUtils.degToRad(Number(r.y)||0),"));
test("question 45987: preserves adjacent source contract",()=>has(2,"THREE.MathUtils.degToRad(Number(r.y)||0),\nTHREE.MathUtils.degToRad(Number(r.z)||0),"));
test("question 45988: preserves adjacent source contract",()=>has(2,"THREE.MathUtils.degToRad(Number(r.z)||0),\nconst count=renderMeshInstanceNode({"));
test("question 45989: preserves adjacent source contract",()=>has(2,"const count=renderMeshInstanceNode({\nparent:sceneGroup,node:sourceNode,runtime:{...runtime,scale_mm_per_source_unit:scaleMm},"));
test("question 45990: preserves adjacent source contract",()=>has(2,"parent:sceneGroup,node:sourceNode,runtime:{...runtime,scale_mm_per_source_unit:scaleMm},\nTHREE,instanceId:instance.id,"));
test("question 45991: preserves adjacent source contract",()=>has(2,"THREE,instanceId:instance.id,\nsceneId:instance.source?.scene_id,nodeId:instance.source?.node_id,"));
test("question 45992: preserves adjacent source contract",()=>has(2,"sceneId:instance.source?.scene_id,nodeId:instance.source?.node_id,\nsourceNodeId:instance.source?.node_id,"));
test("question 45993: preserves adjacent source contract",()=>has(2,"sourceNodeId:instance.source?.node_id,\ntransparent:false"));
test("question 45994: preserves adjacent source contract",()=>has(2,"transparent:false\nif(count){"));
test("question 45995: preserves adjacent source contract",()=>has(2,"if(count){\nparent.add(sceneGroup);rendered+=1;"));
test("question 45996: preserves adjacent source contract",()=>has(2,"parent.add(sceneGroup);rendered+=1;\nreturn rendered;"));
test("question 45997: preserves adjacent source contract",()=>has(2,"return rendered;\nfunction render3D({parent,project,THREE,geomScale}){"));
test("question 45998: preserves adjacent source contract",()=>has(2,"function render3D({parent,project,THREE,geomScale}){\nif(!parent||!project||!THREE)return 0;"));
test("question 45999: preserves adjacent source contract",()=>has(2,"if(!parent||!project||!THREE)return 0;\nlet count=0;"));
test("question 46000: preserves adjacent source contract",()=>has(2,"let count=0;\nfor(const geometryInstance of node?.geometry_instances??[]){"));
test("question 46001: preserves adjacent source contract",()=>has(2,"for(const sceneMeta of project.referenceScenes??[]){\nlet runtime=runtimes.get(runtimeKey(sceneMeta));"));
test("question 46002: preserves adjacent source contract",()=>has(2,"let runtime=runtimes.get(runtimeKey(sceneMeta));\nif(!runtime&&sceneMeta?.display_runtime){"));
test("question 46003: preserves adjacent source contract",()=>has(2,"if(!runtime&&sceneMeta?.display_runtime){\nregisterRuntime(sceneMeta.display_runtime);"));
test("question 46004: preserves adjacent source contract",()=>has(2,"registerRuntime(sceneMeta.display_runtime);\nruntime=runtimes.get(runtimeKey(sceneMeta));"));
test("question 46005: preserves adjacent source contract",()=>has(2,"runtime=runtimes.get(runtimeKey(sceneMeta));\nif(!runtime)continue;"));
test("question 46006: preserves adjacent source contract",()=>has(2,"if(!runtime)continue;\nif(!sourceIndex)sourceIndex=buildProjectSourceRenderIndex(project);"));
test("question 46007: preserves adjacent source contract",()=>has(2,"sourceLookup:sourceIndex.forScene(sceneMeta.id)\ncount+=1;"));
test("question 46008: preserves adjacent source contract",()=>has(2,"count+=1;\ncount+=renderEditableMeshInstances({parent,project,THREE,geomScale});"));
test("question 46009: preserves adjacent source contract",()=>has(2,"count+=renderEditableMeshInstances({parent,project,THREE,geomScale});\nreturn count;"));
test("question 46010: preserves adjacent source contract",()=>has(2,"return count;\nfunction renderEditableMeshInstances({parent,project,THREE,geomScale}){"));
test("question 46011: preserves adjacent source contract",()=>has(2,"function matchNode(node,query){\nif(!query)return true;"));
test("question 46012: preserves adjacent source contract",()=>has(2,"if(!query)return true;\nif(String(node?.label??\"\").toLowerCase().includes(query))return true;"));
test("question 46013: preserves adjacent source contract",()=>has(2,"if(String(node?.label??\"\").toLowerCase().includes(query))return true;\nreturn (node?.children??[]).some((child)=>matchNode(child,query));"));
test("question 46014: preserves adjacent source contract",()=>has(2,"return (node?.children??[]).some((child)=>matchNode(child,query));\nfunction selectionKey(sceneId,nodeId){"));
test("question 46015: preserves adjacent source contract",()=>has(2,"function selectionKey(sceneId,nodeId){\nreturn String(sceneId)+\"|\"+String(nodeId);"));
test("question 46016: preserves adjacent source contract",()=>has(2,"return String(sceneId)+\"|\"+String(nodeId);\nfunction selectableNode(node){"));
test("question 46017: preserves adjacent source contract",()=>has(2,"function selectableNode(node){\nreturn !!node && !node.editable_part_number;"));
test("question 46018: preserves adjacent source contract",()=>has(2,"return !!node && !node.editable_part_number;\nfunction collectSelectableNodes(nodes,out=[]){"));
test("question 46019: preserves adjacent source contract",()=>has(2,"function collectSelectableNodes(nodes,out=[]){\nfor(const node of nodes??[]){"));
test("question 46020: preserves adjacent source contract",()=>has(2,"for(const node of nodes??[]){\nif(selectableNode(node))out.push(node);"));
test("question 46021: preserves adjacent source contract",()=>has(2,"if(selectableNode(node))out.push(node);\ncollectSelectableNodes(node?.children,out);"));
test("question 46022: preserves adjacent source contract",()=>has(2,"collectSelectableNodes(node?.children,out);\nreturn out;"));
test("question 46023: preserves adjacent source contract",()=>has(2,"return out;\nfunction collectSelectableSubtree(node,out=[]){"));
test("question 46024: preserves adjacent source contract",()=>has(2,"function collectSelectableSubtree(node,out=[]){\nif(!node)return out;"));
test("question 46025: preserves adjacent source contract",()=>has(2,"if(!node)return out;\nif(selectableNode(node))out.push(node);"));
test("question 46026: preserves adjacent source contract",()=>has(2,"if(selectableNode(node))out.push(node);\nfor(const child of node.children??[])collectSelectableSubtree(child,out);"));
test("question 46027: preserves adjacent source contract",()=>has(2,"for(const child of node.children??[])collectSelectableSubtree(child,out);\nreturn out;"));
test("question 46028: preserves adjacent source contract",()=>has(2,"return out;\nfunction selectedEntries(project){"));
test("question 46029: preserves adjacent source contract",()=>has(2,"function selectedEntries(project){\nconst entries=[];"));
test("question 46030: preserves adjacent source contract",()=>has(2,"const entries=[];\nfor(const scene of project?.referenceScenes??[]){"));
test("question 46031: preserves adjacent source contract",()=>has(2,"for(const scene of project?.referenceScenes??[]){\nconst byId=new Map();"));
test("question 46032: preserves adjacent source contract",()=>has(2,"const byId=new Map();\nconst stack=[...(scene?.tree??[])];"));
test("question 46033: preserves adjacent source contract",()=>has(2,"const stack=[...(scene?.tree??[])];\nwhile(stack.length){"));
test("question 46034: preserves adjacent source contract",()=>has(2,"while(stack.length){\nconst node=stack.shift();"));
test("question 46035: preserves adjacent source contract",()=>has(2,"const node=stack.shift();\nbyId.set(String(node.id),node);"));
test("question 46036: preserves adjacent source contract",()=>has(2,"byId.set(String(node.id),node);\nstack.unshift(...(node.children??[]));"));
test("question 46037: preserves adjacent source contract",()=>has(2,"stack.unshift(...(node.children??[]));\nfor(const key of bulkSelected){"));
test("question 46038: preserves adjacent source contract",()=>has(2,"for(const key of bulkSelected){\nconst prefix=String(scene.id)+\"|\";"));
test("question 46039: preserves adjacent source contract",()=>has(2,"const prefix=String(scene.id)+\"|\";\nif(!key.startsWith(prefix))continue;"));
test("question 46040: preserves adjacent source contract",()=>has(2,"if(!key.startsWith(prefix))continue;\nconst node=byId.get(key.slice(prefix.length));"));
test("question 46041: preserves adjacent source contract",()=>has(2,"const node=byId.get(key.slice(prefix.length));\nif(node&&selectableNode(node))entries.push({scene,node});"));
test("question 46042: preserves adjacent source contract",()=>has(2,"if(node&&selectableNode(node))entries.push({scene,node});\nreturn entries;"));
test("question 46043: preserves adjacent source contract",()=>has(2,"return entries;\nfunction pruneBulkSelection(project){"));
test("question 46044: preserves adjacent source contract",()=>has(2,"function pruneBulkSelection(project){\nconst valid=new Set("));
test("question 46045: preserves adjacent source contract",()=>has(2,"const valid=new Set(\nselectedEntries(project).map(({scene,node})=>selectionKey(scene.id,node.id))"));
test("question 46046: preserves adjacent source contract",()=>has(2,"selectedEntries(project).map(({scene,node})=>selectionKey(scene.id,node.id))\nfor(const key of [...bulkSelected]){"));
test("question 46047: preserves adjacent source contract",()=>has(2,"for(const key of [...bulkSelected]){\nif(!valid.has(key))bulkSelected.delete(key);"));
test("question 46048: preserves adjacent source contract",()=>has(2,"if(!valid.has(key))bulkSelected.delete(key);\nfunction selectedCount(project){"));
test("question 46049: preserves adjacent source contract",()=>has(2,"function selectedCount(project){\npruneBulkSelection(project);"));
test("question 46050: preserves adjacent source contract",()=>has(2,"pruneBulkSelection(project);\nreturn bulkSelected.size;"));
test("question 46051: preserves adjacent source contract",()=>has(2,"return bulkSelected.size;\nfunction treeItems({project,query=\"\",escape=escHtml}){"));
test("question 46052: preserves adjacent source contract",()=>has(2,"function treeItems({project,query=\"\",escape=escHtml}){\nconst rows=[];"));
test("question 46053: preserves adjacent source contract",()=>has(2,"const rows=[];\nconst q=String(query??\"\").trim().toLowerCase();"));
test("question 46054: preserves adjacent source contract",()=>has(2,"const q=String(query??\"\").trim().toLowerCase();\nconst scenes=(project?.referenceScenes??[]).filter(Boolean);"));
test("question 46055: preserves adjacent source contract",()=>has(2,"const scenes=(project?.referenceScenes??[]).filter(Boolean);\nconst editableTubes=linkedEditableTubes(project);"));
test("question 46056: preserves adjacent source contract",()=>has(2,"const editableTubes=linkedEditableTubes(project);\nconst editableMeshes=editableMeshInstanceList(project,{create:false});"));
test("question 46057: preserves adjacent source contract",()=>has(2,"const editableMeshes=editableMeshInstanceList(project,{create:false});\nif(!scenes.length&&!editableTubes.length&&!editableMeshes.length)return rows;"));
test("question 46058: preserves adjacent source contract",()=>has(2,"if(!scenes.length&&!editableTubes.length&&!editableMeshes.length)return rows;\npruneBulkSelection(project);"));
test("question 46059: preserves adjacent source contract",()=>has(2,"pruneBulkSelection(project);\nconst bulkCount=bulkSelected.size;"));
test("question 46060: preserves adjacent source contract",()=>has(2,"const bulkCount=bulkSelected.size;\nconst rootCollapsed=q?false:project?.referenceGeometryTreeCollapsed===true;"));
test("question 46061: preserves adjacent source contract",()=>has(2,"const rootCollapsed=q?false:project?.referenceGeometryTreeCollapsed===true;\nconst sourceCollapsed=q?false:project?.referenceSourceTreeCollapsed===true;"));
test("question 46062: preserves adjacent source contract",()=>has(2,"const sourceCollapsed=q?false:project?.referenceSourceTreeCollapsed===true;\nconst editableCollapsed=q?false:project?.referenceEditableTreeCollapsed===true;"));
test("question 46063: preserves adjacent source contract",()=>has(2,"const editableCollapsed=q?false:project?.referenceEditableTreeCollapsed===true;\nconst allSelectable=scenes.flatMap((scene)=>collectSelectableNodes(scene.tree??[]));"));
test("question 46064: preserves adjacent source contract",()=>has(2,"const allSelectable=scenes.flatMap((scene)=>collectSelectableNodes(scene.tree??[]));\nconst allSelectedCount=scenes.reduce((sum,scene)=>"));
test("question 46065: preserves adjacent source contract",()=>has(2,"const allSelectedCount=scenes.reduce((sum,scene)=>\nsum+collectSelectableNodes(scene.tree??[]).filter((node)=>"));
test("question 46066: preserves adjacent source contract",()=>has(2,"sum+collectSelectableNodes(scene.tree??[]).filter((node)=>\nbulkSelected.has(selectionKey(scene.id,node.id))"));
test("question 46067: preserves adjacent source contract",()=>has(2,"bulkSelected.has(selectionKey(scene.id,node.id))\n).length"));
test("question 46068: preserves adjacent source contract",()=>has(2,").length\nconst rootChecked=allSelectable.length>0&&allSelectedCount===allSelectable.length;"));
test("question 46069: preserves adjacent source contract",()=>has(2,"const rootChecked=allSelectable.length>0&&allSelectedCount===allSelectable.length;\nconst rootIndeterminate=allSelectedCount>0&&!rootChecked;"));
test("question 46070: preserves adjacent source contract",()=>has(2,"const rootIndeterminate=allSelectedCount>0&&!rootChecked;\nrows.push("));
test("question 46071: preserves adjacent source contract",()=>has(2,"rows.push(\n'<div class=\"tb-tree-node level1 tb-ref-root\" data-ref-root-row=\"1\">'+"));
test("question 46072: preserves adjacent source contract",()=>has(2,"'<div class=\"tb-tree-node level1 tb-ref-root\" data-ref-root-row=\"1\">'+\n'<input type=\"checkbox\" data-ref-root-select=\"1\" '+"));
test("question 46073: preserves adjacent source contract",()=>has(2,"'<input type=\"checkbox\" data-ref-root-select=\"1\" '+\n(rootChecked?'checked ':'')+"));
test("question 46074: preserves adjacent source contract",()=>has(2,"(rootChecked?'checked ':'')+\n(allSelectable.length?'':'disabled ')+"));
test("question 46075: preserves adjacent source contract",()=>has(2,"(allSelectable.length?'':'disabled ')+\n'data-ref-indeterminate=\"'+(rootIndeterminate?'1':'0')+'\" title=\"Выбрать Source / Reference геометрию\">'+"));
test("question 46076: preserves adjacent source contract",()=>has(2,"'data-ref-indeterminate=\"'+(rootIndeterminate?'1':'0')+'\" title=\"Выбрать Source / Reference геометрию\">'+\n'<button class=\"tb-tree-icon\" data-ref-root-toggle=\"1\" title=\"Свернуть/развернуть импортированную геометрию\">'+"));
test("question 46077: preserves adjacent source contract",()=>has(2,"'<button class=\"tb-tree-icon\" data-ref-root-toggle=\"1\" title=\"Свернуть/развернуть импортированную геометрию\">'+\n(rootCollapsed?'▸':'▾')+"));
test("question 46078: preserves adjacent source contract",()=>has(2,"(rootCollapsed?'▸':'▾')+\n'</button>'+"));
test("question 46079: preserves adjacent source contract",()=>has(2,"'</button>'+\n'<span class=\"tb-tree-label\">🌐 Импортированная геометрия <small>· Source: '+scenes.length+' · Editable: '+(editableTubes.length+editableMeshes.length)+'</small></span>'+"));
test("question 46080: preserves adjacent source contract",()=>has(2,"'<span class=\"tb-tree-label\">🌐 Импортированная геометрия <small>· Source: '+scenes.length+' · Editable: '+(editableTubes.length+editableMeshes.length)+'</small></span>'+\n'</div>'"));
test("question 46081: preserves adjacent source contract",()=>has(2,"'</div>'\nif(rootCollapsed)return rows;"));
test("question 46082: preserves adjacent source contract",()=>has(2,"if(rootCollapsed)return rows;\nrows.push("));
test("question 46083: preserves adjacent source contract",()=>has(2,"rows.push(\n'<div class=\"tb-tree-node level2 tb-ref-source-root\" style=\"padding-left:30px\" data-ref-source-root=\"1\">'+"));
test("question 46084: preserves adjacent source contract",()=>has(2,"'<div class=\"tb-tree-node level2 tb-ref-source-root\" style=\"padding-left:30px\" data-ref-source-root=\"1\">'+\n'<button class=\"tb-tree-icon\" data-ref-source-toggle=\"1\" title=\"Свернуть/развернуть Source / Reference\">'+"));
test("question 46085: preserves adjacent source contract",()=>has(2,"'<button class=\"tb-tree-icon\" data-ref-source-toggle=\"1\" title=\"Свернуть/развернуть Source / Reference\">'+\n(sourceCollapsed?'▸':'▾')+"));
test("question 46086: preserves adjacent source contract",()=>has(2,"(sourceCollapsed?'▸':'▾')+\n'</button>'+"));
test("question 46087: preserves adjacent source contract",()=>has(2,"'</button>'+\n'<span class=\"tb-tree-label\">🔒 Source / Reference <small>· неизменяемый исходник</small></span>'+"));
test("question 46088: preserves adjacent source contract",()=>has(2,"'<span class=\"tb-tree-label\">🔒 Source / Reference <small>· неизменяемый исходник</small></span>'+\n'</div>'"));
test("question 46089: preserves adjacent source contract",()=>has(2,"'</div>'\nif(!sourceCollapsed){"));
test("question 46090: preserves adjacent source contract",()=>has(2,"if(!sourceCollapsed){\nrows.push("));
test("question 46091: preserves adjacent source contract",()=>has(2,"rows.push(\n'<div class=\"tb-tree-node tb-ref-bulk-toolbar\" data-ref-bulk-toolbar=\"1\" '+"));
test("question 46092: preserves adjacent source contract",()=>has(2,"'<div class=\"tb-tree-node tb-ref-bulk-toolbar\" data-ref-bulk-toolbar=\"1\" '+\n'style=\"gap:6px;align-items:center;flex-wrap:wrap;padding:6px 8px 6px 48px\">'+"));
test("question 46093: preserves adjacent source contract",()=>has(2,"'style=\"gap:6px;align-items:center;flex-wrap:wrap;padding:6px 8px 6px 48px\">'+\n'<span class=\"tb-tree-label\" style=\"min-width:86px\">Выбрано: '+bulkCount+'</span>'+"));
test("question 46094: preserves adjacent source contract",()=>has(2,"'<span class=\"tb-tree-label\" style=\"min-width:86px\">Выбрано: '+bulkCount+'</span>'+\n'<small title=\"Групповой выбор: Ctrl+клик; диапазон: Shift+клик\">Ctrl+клик · Shift+клик</small>'+"));
test("question 46095: preserves adjacent source contract",()=>has(2,"'<small title=\"Групповой выбор: Ctrl+клик; диапазон: Shift+клик\">Ctrl+клик · Shift+клик</small>'+\n'<button data-ref-bulk-action=\"show\" '+(bulkCount?'':'disabled')+' title=\"Показать выбранные Source-компоненты\">Показать</button>'+"));
test("question 46096: preserves adjacent source contract",()=>has(2,"'<button data-ref-bulk-action=\"show\" '+(bulkCount?'':'disabled')+' title=\"Показать выбранные Source-компоненты\">Показать</button>'+\n'<button data-ref-bulk-action=\"hide\" '+(bulkCount?'':'disabled')+' title=\"Скрыть выбранные Source-компоненты\">Скрыть</button>'+"));
test("question 46097: preserves adjacent source contract",()=>has(2,"'<button data-ref-bulk-action=\"hide\" '+(bulkCount?'':'disabled')+' title=\"Скрыть выбранные Source-компоненты\">Скрыть</button>'+\n'<button data-ref-bulk-action=\"transparent\" '+(bulkCount?'':'disabled')+' title=\"Переключить прозрачность Source\">Прозрачность</button>'+"));
test("question 46098: preserves adjacent source contract",()=>has(2,"'<button data-ref-bulk-action=\"transparent\" '+(bulkCount?'':'disabled')+' title=\"Переключить прозрачность Source\">Прозрачность</button>'+\n'<button data-ref-bulk-action=\"clear\" '+(bulkCount?'':'disabled')+' title=\"Снять выбор\">Снять выбор</button>'+"));
test("question 46099: preserves adjacent source contract",()=>has(2,"'<button data-ref-bulk-action=\"clear\" '+(bulkCount?'':'disabled')+' title=\"Снять выбор\">Снять выбор</button>'+\n'</div>'"));
test("question 46100: preserves adjacent source contract",()=>has(2,"'</div>'\nfor(const scene of scenes){"));
test("question 46101: preserves adjacent source contract",()=>has(2,"for(const scene of scenes){\nconst collapsedScenes=new Set("));
test("question 46102: preserves adjacent source contract",()=>has(2,"const collapsedScenes=new Set(\nArray.isArray(scene.collapsedNodeIds)"));
test("question 46103: preserves adjacent source contract",()=>has(2,"Array.isArray(scene.collapsedNodeIds)\n? scene.collapsedNodeIds.map(String)"));
test("question 46104: preserves adjacent source contract",()=>has(2,"? scene.collapsedNodeIds.map(String)\nconst hidden=hiddenSet(scene);"));
test("question 46105: preserves adjacent source contract",()=>has(2,"const hidden=hiddenSet(scene);\nconst transparent=transparentSet(scene);"));
test("question 46106: preserves adjacent source contract",()=>has(2,"const transparent=transparentSet(scene);\nconst sceneSelectable=collectSelectableNodes(scene.tree??[]);"));
test("question 46107: preserves adjacent source contract",()=>has(2,"const sceneSelectable=collectSelectableNodes(scene.tree??[]);\nconst sceneSelectedCount=sceneSelectable.filter((node)=>"));
test("question 46108: preserves adjacent source contract",()=>has(2,"const sceneSelectedCount=sceneSelectable.filter((node)=>\nbulkSelected.has(selectionKey(scene.id,node.id))"));
test("question 46109: preserves adjacent source contract",()=>has(2,"bulkSelected.has(selectionKey(scene.id,node.id))\n).length;"));
test("question 46110: preserves adjacent source contract",()=>has(2,").length;\nconst sceneChecked=sceneSelectable.length>0&&sceneSelectedCount===sceneSelectable.length;"));
test("question 46111: preserves adjacent source contract",()=>has(2,"const sceneChecked=sceneSelectable.length>0&&sceneSelectedCount===sceneSelectable.length;\nconst sceneIndeterminate=sceneSelectedCount>0&&!sceneChecked;"));
test("question 46112: preserves adjacent source contract",()=>has(2,"const sceneIndeterminate=sceneSelectedCount>0&&!sceneChecked;\nconst sceneLabel=String(scene.name??scene.source_file??\"DWFx\");"));
test("question 46113: preserves adjacent source contract",()=>has(2,"const sceneLabel=String(scene.name??scene.source_file??\"DWFx\");\nconst sceneMatches="));
test("question 46114: preserves adjacent source contract",()=>has(2,"const sceneMatches=\nsceneLabel.toLowerCase().includes(q)||"));
test("question 46115: preserves adjacent source contract",()=>has(2,"sceneLabel.toLowerCase().includes(q)||\n(scene.tree??[]).some((node)=>matchNode(node,q));"));
test("question 46116: preserves adjacent source contract",()=>has(2,"(scene.tree??[]).some((node)=>matchNode(node,q));\nif(!sceneMatches)continue;"));
test("question 46117: preserves adjacent source contract",()=>has(2,"if(!sceneMatches)continue;\nconst sceneCollapsed=q?false:scene.treeCollapsed===true;"));
test("question 46118: preserves adjacent source contract",()=>has(2,"const sceneCollapsed=q?false:scene.treeCollapsed===true;\nrows.push("));
test("question 46119: preserves adjacent source contract",()=>has(2,"rows.push(\n'<div class=\"tb-tree-node tb-ref-scene\" style=\"padding-left:48px\" data-ref-scene-row=\"'+escape(scene.id)+'\">'+"));
test("question 46120: preserves adjacent source contract",()=>has(2,"'<div class=\"tb-tree-node tb-ref-scene\" style=\"padding-left:48px\" data-ref-scene-row=\"'+escape(scene.id)+'\">'+\n'<input type=\"checkbox\" data-ref-scene-select=\"'+escape(scene.id)+'\" '+"));
test("question 46121: preserves adjacent source contract",()=>has(2,"'<input type=\"checkbox\" data-ref-scene-select=\"'+escape(scene.id)+'\" '+\n(sceneChecked?'checked ':'')+"));
test("question 46122: preserves adjacent source contract",()=>has(2,"(sceneChecked?'checked ':'')+\n'data-ref-indeterminate=\"'+(sceneIndeterminate?'1':'0')+'\" title=\"Выбрать readonly-компоненты файла\">'+"));
test("question 46123: preserves adjacent source contract",()=>has(2,"'data-ref-indeterminate=\"'+(sceneIndeterminate?'1':'0')+'\" title=\"Выбрать readonly-компоненты файла\">'+\n'<button class=\"tb-tree-icon\" data-ref-scene-toggle=\"'+escape(scene.id)+'\" title=\"Свернуть/развернуть файл\">'+"));
