import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const files=["src/ui/object-selection-context-ui.js","src/ui/editing-ui.js","src/import/dwfx/reference-scene-ui.js","src/ui/assemblies-runtime.js","src/ui/equipment-library-ui.js"];
const normalized=files.map(rel=>fs.readFileSync(path.join(root,rel),"utf8").split(/\r?\n/).map(s=>s.trim()).filter(s=>s.length>=8&&!s.startsWith("//")&&s!=="{"&&s!=="}"&&s!=="};").join("\n"));
const has=(fileIndex,pair)=>assert.ok(normalized[fileIndex].includes(pair),"missing adjacent source contract: "+files[fileIndex]+"::"+pair);
test("question 43499: preserves adjacent source contract",()=>has(0,"return true;\nconst ok=typeof tbModelCommand===\"function\"?tbModelCommand(\"Сравнить Mesh Instance с Source\",mutate):mutate();"));
test("question 43500: preserves adjacent source contract",()=>has(0,"const ok=typeof tbModelCommand===\"function\"?tbModelCommand(\"Сравнить Mesh Instance с Source\",mutate):mutate();\nif(ok===false)return false;"));
test("question 43501: preserves adjacent source contract",()=>has(0,"if(ok===false)return false;\ntry{if(typeof save===\"function\")save();if(typeof renderAll===\"function\")renderAll();if(typeof refreshProjectTree===\"function\")refreshProjectTree();}catch{}"));
test("question 43502: preserves adjacent source contract",()=>has(0,"try{if(typeof save===\"function\")save();if(typeof renderAll===\"function\")renderAll();if(typeof refreshProjectTree===\"function\")refreshProjectTree();}catch{}\nrefreshVisualSelection();return true;"));
test("question 43503: preserves adjacent source contract",()=>has(0,"refreshVisualSelection();return true;\nfunction breakSelectedMeshLinks(){"));
test("question 43504: preserves adjacent source contract",()=>has(0,"function breakSelectedMeshLinks(){\nconst p=project(),meshEntries=selectionEntries().filter((entry)=>entry.kind===\"mesh-instance\");"));
test("question 43505: preserves adjacent source contract",()=>has(0,"if(!p||!meshEntries.length)return false;\nif(!lockAllowed(\"break-link\"))return false;"));
test("question 43506: preserves adjacent source contract",()=>has(0,"if(!lockAllowed(\"break-link\"))return false;\nconst mutate=()=>{"));
test("question 43507: preserves adjacent source contract",()=>has(0,"for(const entry of meshEntries){\nrefApi()?.breakEditableMeshInstanceLink?.(p,entry.instanceId);"));
test("question 43508: preserves adjacent source contract",()=>has(0,"refApi()?.breakEditableMeshInstanceLink?.(p,entry.instanceId);\nreturn true;"));
test("question 43509: preserves adjacent source contract",()=>has(0,"return true;\nconst ok=typeof tbModelCommand===\"function\"?tbModelCommand(\"Разорвать Source Link mesh instance\",mutate):mutate();"));
test("question 43510: preserves adjacent source contract",()=>has(0,"const ok=typeof tbModelCommand===\"function\"?tbModelCommand(\"Разорвать Source Link mesh instance\",mutate):mutate();\nif(ok===false)return false;"));
test("question 43511: preserves adjacent source contract",()=>has(0,"refreshVisualSelection();return true;\nfunction selectedReferenceEntries(entries){"));
test("question 43512: preserves adjacent source contract",()=>has(0,"function selectedReferenceEntries(entries){\nreturn entries.filter((entry)=>entry.kind===\"ref\");"));
test("question 43513: preserves adjacent source contract",()=>has(0,"return entries.filter((entry)=>entry.kind===\"ref\");\nfunction selectedMeshEntries(entries){"));
test("question 43514: preserves adjacent source contract",()=>has(0,"function selectedMeshEntries(entries){\nreturn entries.filter((entry)=>entry.kind===\"mesh-instance\");"));
test("question 43515: preserves adjacent source contract",()=>has(0,"return entries.filter((entry)=>entry.kind===\"mesh-instance\");\nfunction prepareReferenceSelection(entries){"));
test("question 43516: preserves adjacent source contract",()=>has(0,"function prepareReferenceSelection(entries){\nconst api=refApi();"));
test("question 43517: preserves adjacent source contract",()=>has(0,"const api=refApi();\nconst p=project();"));
test("question 43518: preserves adjacent source contract",()=>has(0,"const p=project();\nif(!api||!p)return;"));
test("question 43519: preserves adjacent source contract",()=>has(0,"if(!api||!p)return;\nconst raw=selectedReferenceEntries(entries).map(rawReferenceKey);"));
test("question 43520: preserves adjacent source contract",()=>has(0,"const raw=selectedReferenceEntries(entries).map(rawReferenceKey);\napi.replaceSelection?.(p,raw);"));
test("question 43521: preserves adjacent source contract",()=>has(0,"api.replaceSelection?.(p,raw);\nfunction applyMove(delta){"));
test("question 43522: preserves adjacent source contract",()=>has(0,"function applyMove(delta){\nconst entries=selectionEntries();"));
test("question 43523: preserves adjacent source contract",()=>has(0,"const entries=selectionEntries();\nif(!entries.length||!canMoveSelection())return false;"));
test("question 43524: preserves adjacent source contract",()=>has(0,"if(!entries.length||!canMoveSelection())return false;\nif(!lockAllowed(\"move\"))return false;"));
test("question 43525: preserves adjacent source contract",()=>has(0,"if(!lockAllowed(\"move\"))return false;\nif(assembliesApi()?.editing?.()&&assembliesApi()?.canHandleEditEntries?.(entries)){"));
test("question 43526: preserves adjacent source contract",()=>has(0,"if(assembliesApi()?.editing?.()&&assembliesApi()?.canHandleEditEntries?.(entries)){\nreturn assembliesApi()?.moveEditEntries?.(entries,delta)??false;"));
test("question 43527: preserves adjacent source contract",()=>has(0,"return assembliesApi()?.moveEditEntries?.(entries,delta)??false;\nif(entries.every(entry=>entry.kind===\"group\")){"));
test("question 43528: preserves adjacent source contract",()=>has(0,"if(entries.every(entry=>entry.kind===\"group\")){\nreturn groupsApi()?.moveGroups?.(entries.map(entry=>entry.groupId),delta)??false;"));
test("question 43529: preserves adjacent source contract",()=>has(0,"return groupsApi()?.moveGroups?.(entries.map(entry=>entry.groupId),delta)??false;\nif(entries.every(entry=>entry.kind===\"project-assembly\")){"));
test("question 43530: preserves adjacent source contract",()=>has(0,"if(entries.every(entry=>entry.kind===\"project-assembly\")){\nreturn assembliesApi()?.moveAssemblies?.(entries.map(entry=>entry.assemblyId),delta)??false;"));
test("question 43531: preserves adjacent source contract",()=>has(0,"return assembliesApi()?.moveAssemblies?.(entries.map(entry=>entry.assemblyId),delta)??false;\nconst p=project();"));
test("question 43532: preserves adjacent source contract",()=>has(0,"const p=project();\nif(!p)return false;"));
test("question 43533: preserves adjacent source contract",()=>has(0,"if(!p)return false;\nlet createdInstanceIds=[];"));
test("question 43534: preserves adjacent source contract",()=>has(0,"let createdInstanceIds=[];\nconst mutate=()=>{"));
test("question 43535: preserves adjacent source contract",()=>has(0,"const mutate=()=>{\nif(typeof syncActiveTubeFromState===\"function\")syncActiveTubeFromState();"));
test("question 43536: preserves adjacent source contract",()=>has(0,"if(typeof syncActiveTubeFromState===\"function\")syncActiveTubeFromState();\nconst refEntries=selectedReferenceEntries(entries);"));
test("question 43537: preserves adjacent source contract",()=>has(0,"const refEntries=selectedReferenceEntries(entries);\nif(refEntries.length){"));
test("question 43538: preserves adjacent source contract",()=>has(0,"if(refEntries.length){\nprepareReferenceSelection(entries);"));
test("question 43539: preserves adjacent source contract",()=>has(0,"prepareReferenceSelection(entries);\nconst result=refApi()?.moveSelection?.(p,delta);"));
test("question 43540: preserves adjacent source contract",()=>has(0,"const result=refApi()?.moveSelection?.(p,delta);\ncreatedInstanceIds=Array.isArray(result?.instance_ids)?result.instance_ids.map(String):[];"));
test("question 43541: preserves adjacent source contract",()=>has(0,"createdInstanceIds=Array.isArray(result?.instance_ids)?result.instance_ids.map(String):[];\nfor(const entry of selectedMeshEntries(entries)){"));
test("question 43542: preserves adjacent source contract",()=>has(0,"for(const entry of selectedMeshEntries(entries)){\nrefApi()?.moveEditableMeshInstance?.(p,entry.instanceId,delta);"));
test("question 43543: preserves adjacent source contract",()=>has(0,"refApi()?.moveEditableMeshInstance?.(p,entry.instanceId,delta);\nconst originals=[];"));
test("question 43544: preserves adjacent source contract",()=>has(0,"const originals=[];\nfor(const entry of entries){"));
test("question 43545: preserves adjacent source contract",()=>has(0,"for(const entry of entries){\nif(entry.kind!==\"tube\")continue;"));
test("question 43546: preserves adjacent source contract",()=>has(0,"if(entry.kind!==\"tube\")continue;\nconst tube=tubeById(entry.tubeId);"));
test("question 43547: preserves adjacent source contract",()=>has(0,"const tube=tubeById(entry.tubeId);\nif(!tube)continue;"));
test("question 43548: preserves adjacent source contract",()=>has(0,"if(!tube)continue;\nconst origin=tube.origin??{x:0,y:0,z:0};"));
test("question 43549: preserves adjacent source contract",()=>has(0,"const origin=tube.origin??{x:0,y:0,z:0};\noriginals.push({tube,origin:{x:Number(origin.x)||0,y:Number(origin.y)||0,z:Number(origin.z)||0}});"));
test("question 43550: preserves adjacent source contract",()=>has(0,"originals.push({tube,origin:{x:Number(origin.x)||0,y:Number(origin.y)||0,z:Number(origin.z)||0}});\ntube.origin={"));
test("question 43551: preserves adjacent source contract",()=>has(0,"tube.origin={\nx:Number(((Number(origin.x)||0)+delta.x).toFixed(6)),"));
test("question 43552: preserves adjacent source contract",()=>has(0,"x:Number(((Number(origin.x)||0)+delta.x).toFixed(6)),\ny:Number(((Number(origin.y)||0)+delta.y).toFixed(6)),"));
test("question 43553: preserves adjacent source contract",()=>has(0,"y:Number(((Number(origin.y)||0)+delta.y).toFixed(6)),\nz:Number(((Number(origin.z)||0)+delta.z).toFixed(6))"));
test("question 43554: preserves adjacent source contract",()=>has(0,"z:Number(((Number(origin.z)||0)+delta.z).toFixed(6))\ntry{if(typeof markImportedOriginOverride===\"function\")markImportedOriginOverride(tube);}catch{}"));
test("question 43555: preserves adjacent source contract",()=>has(0,"try{if(typeof markImportedOriginOverride===\"function\")markImportedOriginOverride(tube);}catch{}\nlet invalid=false;"));
test("question 43556: preserves adjacent source contract",()=>has(0,"let invalid=false;\nfor(const {tube} of originals){"));
test("question 43557: preserves adjacent source contract",()=>has(0,"for(const {tube} of originals){\nif(typeof analyzeTubeBounds===\"function\"&&!analyzeTubeBounds(tube)?.valid){"));
test("question 43558: preserves adjacent source contract",()=>has(0,"if(typeof analyzeTubeBounds===\"function\"&&!analyzeTubeBounds(tube)?.valid){\ninvalid=true;"));
test("question 43559: preserves adjacent source contract",()=>has(0,"invalid=true;\n}catch{}"));
test("question 43560: preserves adjacent source contract",()=>has(0,"}catch{}\nif(invalid){"));
test("question 43561: preserves adjacent source contract",()=>has(0,"if(invalid){\nfor(const item of originals)item.tube.origin=item.origin;"));
test("question 43562: preserves adjacent source contract",()=>has(0,"for(const item of originals)item.tube.origin=item.origin;\nif(typeof ptToast===\"function\")ptToast(\"Перемещение отменено: труба выходит за габаритную рамку\");"));
test("question 43563: preserves adjacent source contract",()=>has(0,"if(typeof ptToast===\"function\")ptToast(\"Перемещение отменено: труба выходит за габаритную рамку\");\nreturn false;"));
test("question 43564: preserves adjacent source contract",()=>has(0,"return false;\nconst active=tubeById(activeTubeId());"));
test("question 43565: preserves adjacent source contract",()=>has(0,"const active=tubeById(activeTubeId());\nif(active&&entries.some((entry)=>entry.kind===\"tube\"&&entry.tubeId===active.id)){"));
test("question 43566: preserves adjacent source contract",()=>has(0,"if(active&&entries.some((entry)=>entry.kind===\"tube\"&&entry.tubeId===active.id)){\nstate.origin={...active.origin};"));
test("question 43567: preserves adjacent source contract",()=>has(0,"state.origin={...active.origin};\nreturn true;"));
test("question 43568: preserves adjacent source contract",()=>has(0,"return true;\nconst wholeObjectCommand=window.TubeBenderEngineering?.wholeObjectCommand;"));
test("question 43569: preserves adjacent source contract",()=>has(0,"const wholeObjectCommand=window.TubeBenderEngineering?.wholeObjectCommand;\nconst ok=typeof wholeObjectCommand===\"function\""));
test("question 43570: preserves adjacent source contract",()=>has(0,"const ok=typeof wholeObjectCommand===\"function\"\n? wholeObjectCommand(\"Переместить выбранные объекты\",mutate)"));
test("question 43571: preserves adjacent source contract",()=>has(0,"? wholeObjectCommand(\"Переместить выбранные объекты\",mutate)\n: typeof tbModelCommand===\"function\""));
test("question 43572: preserves adjacent source contract",()=>has(0,": typeof tbModelCommand===\"function\"\n? tbModelCommand(\"Переместить выбранные объекты\",mutate)"));
test("question 43573: preserves adjacent source contract",()=>has(0,"? tbModelCommand(\"Переместить выбранные объекты\",mutate)\n: mutate();"));
test("question 43574: preserves adjacent source contract",()=>has(0,": mutate();\nif(ok===false)return false;"));
test("question 43575: preserves adjacent source contract",()=>has(0,"if(ok===false)return false;\ntry{repeatApi()?.record?.(\"edit.move\",\"Move\",{editDx:Number(delta.x)||0,editDy:Number(delta.y)||0,editDz:Number(delta.z)||0},\"context\");}catch{}"));
test("question 43576: preserves adjacent source contract",()=>has(0,"try{repeatApi()?.record?.(\"edit.move\",\"Move\",{editDx:Number(delta.x)||0,editDy:Number(delta.y)||0,editDz:Number(delta.z)||0},\"context\");}catch{}\nif(createdInstanceIds.length){"));
test("question 43577: preserves adjacent source contract",()=>has(0,"if(createdInstanceIds.length){\nselected.clear();"));
test("question 43578: preserves adjacent source contract",()=>has(0,"refApi()?.clearSelection?.();\nfor(const id of createdInstanceIds)selected.add(meshKey(id));"));
test("question 43579: preserves adjacent source contract",()=>has(0,"for(const id of createdInstanceIds)selected.add(meshKey(id));\ntry{if(typeof save===\"function\")save();}catch{}"));
test("question 43580: preserves adjacent source contract",()=>has(0,"refreshVisualSelection();\nupdateTreeSelectionStyles();"));
test("question 43581: preserves adjacent source contract",()=>has(0,"updateTreeSelectionStyles();\nreturn true;"));
test("question 43582: preserves adjacent source contract",()=>has(0,"return true;\nfunction setDisplayState(entry,action){"));
test("question 43583: preserves adjacent source contract",()=>has(0,"function setDisplayState(entry,action){\nif(entry.kind===\"mesh-instance\"){"));
test("question 43584: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"mesh-instance\"){\nconst instance=refApi()?.meshInstanceById?.(project(),entry.instanceId);"));
test("question 43585: preserves adjacent source contract",()=>has(0,"const instance=refApi()?.meshInstanceById?.(project(),entry.instanceId);\nif(instance)instance.visible=action===\"show\";"));
test("question 43586: preserves adjacent source contract",()=>has(0,"if(instance)instance.visible=action===\"show\";\nif(entry.kind===\"group\"){"));
test("question 43587: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"group\"){\nconst group=groupsApi()?.groupById?.(entry.groupId);"));
test("question 43588: preserves adjacent source contract",()=>has(0,"const group=groupsApi()?.groupById?.(entry.groupId);\nif(group)group.visible=action===\"show\";"));
test("question 43589: preserves adjacent source contract",()=>has(0,"if(group)group.visible=action===\"show\";\nif(entry.kind===\"project-assembly\"){"));
test("question 43590: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"project-assembly\"){\nconst assembly=assembliesApi()?.assemblyById?.(entry.assemblyId);"));
test("question 43591: preserves adjacent source contract",()=>has(0,"const assembly=assembliesApi()?.assemblyById?.(entry.assemblyId);\nif(assembly)assembly.visible=action===\"show\";"));
test("question 43592: preserves adjacent source contract",()=>has(0,"if(assembly)assembly.visible=action===\"show\";\nif(entry.kind===\"tube\"){"));
test("question 43593: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"tube\"){\nconst tube=tubeById(entry.tubeId);"));
test("question 43594: preserves adjacent source contract",()=>has(0,"const tube=tubeById(entry.tubeId);\nif(!tube)return;"));
test("question 43595: preserves adjacent source contract",()=>has(0,"if(!tube)return;\nif(action===\"hide\")tube.uiHiddenIn3D=true;"));
test("question 43596: preserves adjacent source contract",()=>has(0,"if(action===\"hide\")tube.uiHiddenIn3D=true;\nif(action===\"show\"){"));
test("question 43597: preserves adjacent source contract",()=>has(0,"if(action===\"show\"){\ntube.uiHiddenIn3D=false;"));
test("question 43598: preserves adjacent source contract",()=>has(0,"tube.uiHiddenIn3D=false;\ntube.visible=true;"));
test("question 43599: preserves adjacent source contract",()=>has(0,"tube.visible=true;\nif(entry.kind===\"row\"){"));
test("question 43600: preserves adjacent source contract",()=>has(0,"const row=rowFor(entry);\nif(!row)return;"));
test("question 43601: preserves adjacent source contract",()=>has(0,"if(!row)return;\nrow.uiHiddenIn3D=action===\"hide\";"));
test("question 43602: preserves adjacent source contract",()=>has(0,"row.uiHiddenIn3D=action===\"hide\";\nif(entry.kind===\"assembly\"){"));
test("question 43603: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"assembly\"){\nconst tube=tubeById(entry.tubeId);"));
test("question 43604: preserves adjacent source contract",()=>has(0,"const tube=tubeById(entry.tubeId);\nfor(const row of tube?.rows??[]){"));
test("question 43605: preserves adjacent source contract",()=>has(0,"for(const row of tube?.rows??[]){\nif(String(row?.assemblyId??\"\")===String(entry.assemblyId)){"));
test("question 43606: preserves adjacent source contract",()=>has(0,"if(String(row?.assemblyId??\"\")===String(entry.assemblyId)){\nrow.uiHiddenIn3D=action===\"hide\";"));
test("question 43607: preserves adjacent source contract",()=>has(0,"row.uiHiddenIn3D=action===\"hide\";\nfunction isolateEditableSelection(entries,projectValue){"));
test("question 43608: preserves adjacent source contract",()=>has(0,"function isolateEditableSelection(entries,projectValue){\nconst wholeTubes=new Set("));
test("question 43609: preserves adjacent source contract",()=>has(0,"const wholeTubes=new Set(\n.filter((entry)=>entry.kind===\"tube\")"));
test("question 43610: preserves adjacent source contract",()=>has(0,".filter((entry)=>entry.kind===\"tube\")\n.map((entry)=>String(entry.tubeId))"));
test("question 43611: preserves adjacent source contract",()=>has(0,".map((entry)=>String(entry.tubeId))\nconst rowsByTube=new Map();"));
test("question 43612: preserves adjacent source contract",()=>has(0,"const rowsByTube=new Map();\nconst assembliesByTube=new Map();"));
test("question 43613: preserves adjacent source contract",()=>has(0,"const assembliesByTube=new Map();\nfor(const entry of entries){"));
test("question 43614: preserves adjacent source contract",()=>has(0,"for(const entry of entries){\nconst tubeId=String(entry.tubeId??\"\");"));
test("question 43615: preserves adjacent source contract",()=>has(0,"const tubeId=String(entry.tubeId??\"\");\nif(!tubeId)continue;"));
test("question 43616: preserves adjacent source contract",()=>has(0,"if(!tubeId)continue;\nif(entry.kind===\"row\"){"));
test("question 43617: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"row\"){\nconst set=rowsByTube.get(tubeId)??new Set();"));
test("question 43618: preserves adjacent source contract",()=>has(0,"const set=rowsByTube.get(tubeId)??new Set();\nset.add(Number(entry.rowIndex));"));
test("question 43619: preserves adjacent source contract",()=>has(0,"set.add(Number(entry.rowIndex));\nrowsByTube.set(tubeId,set);"));
test("question 43620: preserves adjacent source contract",()=>has(0,"rowsByTube.set(tubeId,set);\n}else if(entry.kind===\"assembly\"){"));
test("question 43621: preserves adjacent source contract",()=>has(0,"}else if(entry.kind===\"assembly\"){\nconst set=assembliesByTube.get(tubeId)??new Set();"));
test("question 43622: preserves adjacent source contract",()=>has(0,"const set=assembliesByTube.get(tubeId)??new Set();\nset.add(String(entry.assemblyId));"));
test("question 43623: preserves adjacent source contract",()=>has(0,"set.add(String(entry.assemblyId));\nassembliesByTube.set(tubeId,set);"));
test("question 43624: preserves adjacent source contract",()=>has(0,"assembliesByTube.set(tubeId,set);\nfor(const tube of projectValue?.tubes??[]){"));
test("question 43625: preserves adjacent source contract",()=>has(0,"for(const tube of projectValue?.tubes??[]){\nconst tubeId=String(tube?.id??\"\");"));
test("question 43626: preserves adjacent source contract",()=>has(0,"const tubeId=String(tube?.id??\"\");\nconst keepWhole=wholeTubes.has(tubeId);"));
test("question 43627: preserves adjacent source contract",()=>has(0,"const keepWhole=wholeTubes.has(tubeId);\nconst rowSet=rowsByTube.get(tubeId)??new Set();"));
test("question 43628: preserves adjacent source contract",()=>has(0,"const rowSet=rowsByTube.get(tubeId)??new Set();\nconst assemblySet=assembliesByTube.get(tubeId)??new Set();"));
test("question 43629: preserves adjacent source contract",()=>has(0,"const assemblySet=assembliesByTube.get(tubeId)??new Set();\nconst partial=rowSet.size>0||assemblySet.size>0;"));
test("question 43630: preserves adjacent source contract",()=>has(0,"const partial=rowSet.size>0||assemblySet.size>0;\nif(keepWhole){"));
test("question 43631: preserves adjacent source contract",()=>has(0,"if(keepWhole){\ntube.uiHiddenIn3D=false;"));
test("question 43632: preserves adjacent source contract",()=>has(0,"tube.visible=true;\nfor(const row of tube.rows??[])row.uiHiddenIn3D=false;"));
test("question 43633: preserves adjacent source contract",()=>has(0,"for(const row of tube.rows??[])row.uiHiddenIn3D=false;\ncontinue;"));
test("question 43634: preserves adjacent source contract",()=>has(0,"continue;\nif(partial){"));
test("question 43635: preserves adjacent source contract",()=>has(0,"if(partial){\ntube.uiHiddenIn3D=false;"));
test("question 43636: preserves adjacent source contract",()=>has(0,"tube.visible=true;\n(tube.rows??[]).forEach((row,index)=>{"));
test("question 43637: preserves adjacent source contract",()=>has(0,"(tube.rows??[]).forEach((row,index)=>{\nconst keep="));
test("question 43638: preserves adjacent source contract",()=>has(0,"const keep=\nrowSet.has(index)||"));
test("question 43639: preserves adjacent source contract",()=>has(0,"rowSet.has(index)||\n(row?.assemblyId&&assemblySet.has(String(row.assemblyId)));"));
test("question 43640: preserves adjacent source contract",()=>has(0,"(row?.assemblyId&&assemblySet.has(String(row.assemblyId)));\nrow.uiHiddenIn3D=!keep;"));
test("question 43641: preserves adjacent source contract",()=>has(0,"row.uiHiddenIn3D=!keep;\ncontinue;"));
test("question 43642: preserves adjacent source contract",()=>has(0,"continue;\ntube.uiHiddenIn3D=true;"));
test("question 43643: preserves adjacent source contract",()=>has(0,"tube.uiHiddenIn3D=true;\nconst active=tubeById(activeTubeId());"));
test("question 43644: preserves adjacent source contract",()=>has(0,"const active=tubeById(activeTubeId());\nif(active&&Array.isArray(state?.rows)&&Array.isArray(active.rows)){"));
test("question 43645: preserves adjacent source contract",()=>has(0,"if(active&&Array.isArray(state?.rows)&&Array.isArray(active.rows)){\nstate.rows.forEach((row,index)=>{"));
test("question 43646: preserves adjacent source contract",()=>has(0,"state.rows.forEach((row,index)=>{\nif(active.rows[index])row.uiHiddenIn3D=active.rows[index].uiHiddenIn3D===true;"));
test("question 43647: preserves adjacent source contract",()=>has(0,"if(active.rows[index])row.uiHiddenIn3D=active.rows[index].uiHiddenIn3D===true;\nfunction toggleTransparency(entries){"));
test("question 43648: preserves adjacent source contract",()=>has(0,"function toggleTransparency(entries){\nconst editable=entries.filter((entry)=>{"));
test("question 43649: preserves adjacent source contract",()=>has(0,"const editable=entries.filter((entry)=>{\nif(entry.kind===\"ref\")return false;"));
test("question 43650: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"ref\")return false;\nconst tube=tubeById(entry.tubeId);"));
test("question 43651: preserves adjacent source contract",()=>has(0,"const tube=tubeById(entry.tubeId);\nreturn !isRecognizedTube(tube);"));
test("question 43652: preserves adjacent source contract",()=>has(0,"return !isRecognizedTube(tube);\nconst allTransparent=editable.length>0&&editable.every((entry)=>{"));
test("question 43653: preserves adjacent source contract",()=>has(0,"const allTransparent=editable.length>0&&editable.every((entry)=>{\nif(entry.kind===\"tube\")return tubeById(entry.tubeId)?.uiTransparentIn3D===true;"));
test("question 43654: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"tube\")return tubeById(entry.tubeId)?.uiTransparentIn3D===true;\nif(entry.kind===\"row\")return rowFor(entry)?.uiTransparentIn3D===true;"));
test("question 43655: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"row\")return rowFor(entry)?.uiTransparentIn3D===true;\nif(entry.kind===\"assembly\"){"));
test("question 43656: preserves adjacent source contract",()=>has(0,"const tube=tubeById(entry.tubeId);\nconst rows=(tube?.rows??[]).filter((row)=>String(row?.assemblyId??\"\")===String(entry.assemblyId));"));
test("question 43657: preserves adjacent source contract",()=>has(0,"const rows=(tube?.rows??[]).filter((row)=>String(row?.assemblyId??\"\")===String(entry.assemblyId));\nreturn rows.length>0&&rows.every((row)=>row.uiTransparentIn3D===true);"));
test("question 43658: preserves adjacent source contract",()=>has(0,"return rows.length>0&&rows.every((row)=>row.uiTransparentIn3D===true);\nreturn false;"));
test("question 43659: preserves adjacent source contract",()=>has(0,"return false;\nconst next=!allTransparent;"));
test("question 43660: preserves adjacent source contract",()=>has(0,"const next=!allTransparent;\nfor(const entry of entries){"));
test("question 43661: preserves adjacent source contract",()=>has(0,"for(const entry of entries){\nif(entry.kind===\"ref\")continue;"));
test("question 43662: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"ref\")continue;\nconst tube=tubeById(entry.tubeId);"));
test("question 43663: preserves adjacent source contract",()=>has(0,"const tube=tubeById(entry.tubeId);\nif(!isRecognizedTube(tube))continue;"));
test("question 43664: preserves adjacent source contract",()=>has(0,"if(!isRecognizedTube(tube))continue;\ntube.uiTransparentIn3D=false;"));
test("question 43665: preserves adjacent source contract",()=>has(0,"tube.uiTransparentIn3D=false;\nif(entry.kind===\"row\"){"));
test("question 43666: preserves adjacent source contract",()=>has(0,"const row=rowFor(entry);\nif(row)row.uiTransparentIn3D=false;"));
test("question 43667: preserves adjacent source contract",()=>has(0,"if(row)row.uiTransparentIn3D=false;\n}else if(entry.kind===\"assembly\"){"));
test("question 43668: preserves adjacent source contract",()=>has(0,"}else if(entry.kind===\"assembly\"){\nfor(const row of tube?.rows??[]){"));
test("question 43669: preserves adjacent source contract",()=>has(0,"if(String(row?.assemblyId??\"\")===String(entry.assemblyId)){\nrow.uiTransparentIn3D=false;"));
test("question 43670: preserves adjacent source contract",()=>has(0,"row.uiTransparentIn3D=false;\nfor(const entry of editable){"));
test("question 43671: preserves adjacent source contract",()=>has(0,"for(const entry of editable){\nif(entry.kind===\"tube\"){"));
test("question 43672: preserves adjacent source contract",()=>has(0,"const tube=tubeById(entry.tubeId);\nif(tube)tube.uiTransparentIn3D=next;"));
test("question 43673: preserves adjacent source contract",()=>has(0,"if(tube)tube.uiTransparentIn3D=next;\n}else if(entry.kind===\"row\"){"));
test("question 43674: preserves adjacent source contract",()=>has(0,"}else if(entry.kind===\"row\"){\nconst row=rowFor(entry);"));
test("question 43675: preserves adjacent source contract",()=>has(0,"const row=rowFor(entry);\nif(row)row.uiTransparentIn3D=next;"));
test("question 43676: preserves adjacent source contract",()=>has(0,"if(row)row.uiTransparentIn3D=next;\n}else if(entry.kind===\"assembly\"){"));
test("question 43677: preserves adjacent source contract",()=>has(0,"}else if(entry.kind===\"assembly\"){\nconst tube=tubeById(entry.tubeId);"));
test("question 43678: preserves adjacent source contract",()=>has(0,"if(String(row?.assemblyId??\"\")===String(entry.assemblyId)){\nrow.uiTransparentIn3D=next;"));
test("question 43679: preserves adjacent source contract",()=>has(0,"row.uiTransparentIn3D=next;\nfunction deleteRows(entries){"));
test("question 43680: preserves adjacent source contract",()=>has(0,"function deleteRows(entries){\nconst activeId=activeTubeId();"));
test("question 43681: preserves adjacent source contract",()=>has(0,"const activeId=activeTubeId();\nconst activeRows=entries"));
test("question 43682: preserves adjacent source contract",()=>has(0,"const activeRows=entries\n.filter((entry)=>entry.kind===\"row\"&&entry.tubeId===activeId)"));
test("question 43683: preserves adjacent source contract",()=>has(0,".filter((entry)=>entry.kind===\"row\"&&entry.tubeId===activeId)\n.map((entry)=>Number(entry.rowIndex))"));
test("question 43684: preserves adjacent source contract",()=>has(0,".map((entry)=>Number(entry.rowIndex))\n.filter((index)=>Number.isInteger(index)&&index>=0)"));
test("question 43685: preserves adjacent source contract",()=>has(0,".filter((index)=>Number.isInteger(index)&&index>=0)\n.sort((a,b)=>b-a);"));
test("question 43686: preserves adjacent source contract",()=>has(0,".sort((a,b)=>b-a);\nconst assemblies=new Set("));
test("question 43687: preserves adjacent source contract",()=>has(0,"const assemblies=new Set(\n.filter((entry)=>entry.kind===\"assembly\"&&entry.tubeId===activeId)"));
test("question 43688: preserves adjacent source contract",()=>has(0,".filter((entry)=>entry.kind===\"assembly\"&&entry.tubeId===activeId)\n.map((entry)=>String(entry.assemblyId))"));
test("question 43689: preserves adjacent source contract",()=>has(0,".map((entry)=>String(entry.assemblyId))\nfor(const index of activeRows){"));
test("question 43690: preserves adjacent source contract",()=>has(0,"for(const index of activeRows){\nconst row=state?.rows?.[index];"));
test("question 43691: preserves adjacent source contract",()=>has(0,"const row=state?.rows?.[index];\nif(row?.assemblyId)assemblies.add(String(row.assemblyId));"));
test("question 43692: preserves adjacent source contract",()=>has(0,"if(row?.assemblyId)assemblies.add(String(row.assemblyId));\nfor(const assemblyId of assemblies){"));
test("question 43693: preserves adjacent source contract",()=>has(0,"for(const assemblyId of assemblies){\nstate.rows=normalizeTubeRowStart("));
test("question 43694: preserves adjacent source contract",()=>has(0,"state.rows=normalizeTubeRowStart(\n(state.rows??[]).filter((row)=>String(row?.assemblyId??\"\")!==assemblyId),"));
test("question 43695: preserves adjacent source contract",()=>has(0,"(state.rows??[]).filter((row)=>String(row?.assemblyId??\"\")!==assemblyId),\nstate.diameterIndex"));
test("question 43696: preserves adjacent source contract",()=>has(0,"state.diameterIndex\nfor(const index of activeRows){"));
test("question 43697: preserves adjacent source contract",()=>has(0,"const row=state?.rows?.[index];\nif(!row||row.assemblyId)continue;"));
test("question 43698: preserves adjacent source contract",()=>has(0,"if(!row||row.assemblyId)continue;\nif(row.type!==\"BEND\"){"));
test("question 43699: preserves adjacent source contract",()=>has(0,"if(row.type!==\"BEND\"){\nif(typeof ptToast===\"function\")ptToast(\"Прямой участок удаляется только вместе с предыдущим гибом\");"));
test("question 43700: preserves adjacent source contract",()=>has(0,"if(typeof ptToast===\"function\")ptToast(\"Прямой участок удаляется только вместе с предыдущим гибом\");\ncontinue;"));
test("question 43701: preserves adjacent source contract",()=>has(0,"continue;\nconst count=state.rows[index+1]?.type===\"LINE\"&&!state.rows[index+1]?.assemblyId?2:1;"));
test("question 43702: preserves adjacent source contract",()=>has(0,"const count=state.rows[index+1]?.type===\"LINE\"&&!state.rows[index+1]?.assemblyId?2:1;\nstate.rows.splice(index,count);"));
test("question 43703: preserves adjacent source contract",()=>has(0,"state.rows.splice(index,count);\nstate.rows=normalizeTubeRowStart(state.rows,state.diameterIndex);"));
test("question 43704: preserves adjacent source contract",()=>has(0,"state.rows=normalizeTubeRowStart(state.rows,state.diameterIndex);\nfunction deleteTubes(entries){"));
test("question 43705: preserves adjacent source contract",()=>has(0,"function deleteTubes(entries){\nconst p=project();"));
test("question 43706: preserves adjacent source contract",()=>has(0,"const p=project();\nif(!p)return;"));
test("question 43707: preserves adjacent source contract",()=>has(0,"if(!p)return;\nconst requested=entries.filter((entry)=>entry.kind===\"tube\");"));
test("question 43708: preserves adjacent source contract",()=>has(0,"const requested=entries.filter((entry)=>entry.kind===\"tube\");\nconst derived=requested.filter((entry)=>{const tube=tubeById(entry.tubeId);return tube?.array_member?.derived_readonly===true||tube?.mirror_member?.derived_readonly===true||tube?.transform_stack_member?.derived_readonly===true;});"));
test("question 43709: preserves adjacent source contract",()=>has(0,"const derived=requested.filter((entry)=>{const tube=tubeById(entry.tubeId);return tube?.array_member?.derived_readonly===true||tube?.mirror_member?.derived_readonly===true||tube?.transform_stack_member?.derived_readonly===true;});\nif(derived.length){"));
test("question 43710: preserves adjacent source contract",()=>has(0,"if(derived.length){\nif(typeof ptToast===\"function\")ptToast(\"Элемент ассоциативного массива нельзя удалить напрямую; Mirror / Transform Stack также управляются через свою операцию — используйте Suppress / Detach / Break Array либо Bake / Break\");"));
test("question 43711: preserves adjacent source contract",()=>has(0,"if(typeof ptToast===\"function\")ptToast(\"Элемент ассоциативного массива нельзя удалить напрямую; Mirror / Transform Stack также управляются через свою операцию — используйте Suppress / Detach / Break Array либо Bake / Break\");\nconst ids=new Set(requested.filter((entry)=>{const tube=tubeById(entry.tubeId);return tube?.array_member?.derived_readonly!==true&&tube?.mirror_member?.derived_readonly!==true&&tube?.transform_stack_member?.derived_readonly!==true;}).map((entry)=>String(entry.tubeId)));"));
test("question 43712: preserves adjacent source contract",()=>has(0,"const ids=new Set(requested.filter((entry)=>{const tube=tubeById(entry.tubeId);return tube?.array_member?.derived_readonly!==true&&tube?.mirror_member?.derived_readonly!==true&&tube?.transform_stack_member?.derived_readonly!==true;}).map((entry)=>String(entry.tubeId)));\nif(!ids.size)return;"));
test("question 43713: preserves adjacent source contract",()=>has(0,"if(!ids.size)return;\np.tubes=(p.tubes??[]).filter((tube)=>!ids.has(String(tube.id)));"));
test("question 43714: preserves adjacent source contract",()=>has(0,"p.tubes=(p.tubes??[]).filter((tube)=>!ids.has(String(tube.id)));\nif(!p.tubes.length&&typeof newTubeData===\"function\"){"));
test("question 43715: preserves adjacent source contract",()=>has(0,"if(!p.tubes.length&&typeof newTubeData===\"function\"){\np.tubes.push(newTubeData(\"Pipe 1\"));"));
test("question 43716: preserves adjacent source contract",()=>has(0,"p.tubes.push(newTubeData(\"Pipe 1\"));\nif(ids.has(activeTubeId())){"));
test("question 43717: preserves adjacent source contract",()=>has(0,"if(ids.has(activeTubeId())){\nstate.activeTubeId=p.tubes?.[0]?.id??null;"));
test("question 43718: preserves adjacent source contract",()=>has(0,"state.activeTubeId=p.tubes?.[0]?.id??null;\ntry{if(typeof syncProjectToLegacy===\"function\")syncProjectToLegacy();}catch{}"));
test("question 43719: preserves adjacent source contract",()=>has(0,"try{if(typeof syncProjectToLegacy===\"function\")syncProjectToLegacy();}catch{}\ntry{if(typeof loadActiveTubeToState===\"function\")loadActiveTubeToState();}catch{}"));
test("question 43720: preserves adjacent source contract",()=>has(0,"try{if(typeof loadActiveTubeToState===\"function\")loadActiveTubeToState();}catch{}\nfunction deleteMeshInstances(entries){"));
test("question 43721: preserves adjacent source contract",()=>has(0,"function deleteMeshInstances(entries){\nconst p=project();if(!p)return;"));
test("question 43722: preserves adjacent source contract",()=>has(0,"const p=project();if(!p)return;\nconst ids=new Set(entries.filter(entry=>entry.kind===\"mesh-instance\").map(entry=>String(entry.instanceId)));"));
test("question 43723: preserves adjacent source contract",()=>has(0,"const ids=new Set(entries.filter(entry=>entry.kind===\"mesh-instance\").map(entry=>String(entry.instanceId)));\nif(!ids.size)return;"));
test("question 43724: preserves adjacent source contract",()=>has(0,"if(!ids.size)return;\np.editable_mesh_instances=(p.editable_mesh_instances??[]).filter(item=>!ids.has(String(item?.id)));"));
test("question 43725: preserves adjacent source contract",()=>has(0,"p.editable_mesh_instances=(p.editable_mesh_instances??[]).filter(item=>!ids.has(String(item?.id)));\nfunction finitePoint3(value,fallback={x:0,y:0,z:0}){"));
test("question 43726: preserves adjacent source contract",()=>has(0,"function finitePoint3(value,fallback={x:0,y:0,z:0}){\nconst source=value&&typeof value===\"object\"?value:{};"));
test("question 43727: preserves adjacent source contract",()=>has(0,"const source=value&&typeof value===\"object\"?value:{};\nconst out={};"));
test("question 43728: preserves adjacent source contract",()=>has(0,"const out={};\nfor(const axis of [\"x\",\"y\",\"z\"]){"));
test("question 43729: preserves adjacent source contract",()=>has(0,"for(const axis of [\"x\",\"y\",\"z\"]){\nconst n=Number(source[axis]);"));
test("question 43730: preserves adjacent source contract",()=>has(0,"const n=Number(source[axis]);\nout[axis]=Number.isFinite(n)?n:Number(fallback?.[axis])||0;"));
test("question 43731: preserves adjacent source contract",()=>has(0,"out[axis]=Number.isFinite(n)?n:Number(fallback?.[axis])||0;\nreturn out;"));
test("question 43732: preserves adjacent source contract",()=>has(0,"return out;\nfunction frameDimensions(projectValue){"));
test("question 43733: preserves adjacent source contract",()=>has(0,"function frameDimensions(projectValue){\nconst source=projectValue?.bbox??state?.bbox??{};"));
test("question 43734: preserves adjacent source contract",()=>has(0,"const source=projectValue?.bbox??state?.bbox??{};\nreturn finitePoint3(source,{x:0,y:0,z:0});"));
test("question 43735: preserves adjacent source contract",()=>has(0,"return finitePoint3(source,{x:0,y:0,z:0});\nfunction frameOffset(projectValue){"));
test("question 43736: preserves adjacent source contract",()=>has(0,"function frameOffset(projectValue){\nconst source=projectValue?.coordinateOffset??state?.coordinateOffset??{};"));
test("question 43737: preserves adjacent source contract",()=>has(0,"const source=projectValue?.coordinateOffset??state?.coordinateOffset??{};\nreturn finitePoint3(source,{x:0,y:0,z:0});"));
test("question 43738: preserves adjacent source contract",()=>has(0,"return finitePoint3(source,{x:0,y:0,z:0});\nfunction frameChanged(a,b,tolerance=.001){"));
test("question 43739: preserves adjacent source contract",()=>has(0,"function frameChanged(a,b,tolerance=.001){\nreturn [\"x\",\"y\",\"z\"].some("));
test("question 43740: preserves adjacent source contract",()=>has(0,"return [\"x\",\"y\",\"z\"].some(\n(axis)=>Math.abs((Number(a?.[axis])||0)-(Number(b?.[axis])||0))>tolerance"));
test("question 43741: preserves adjacent source contract",()=>has(0,"(axis)=>Math.abs((Number(a?.[axis])||0)-(Number(b?.[axis])||0))>tolerance\nfunction frameText(value){"));
test("question 43742: preserves adjacent source contract",()=>has(0,"function frameText(value){\nreturn [\"x\",\"y\",\"z\"]"));
test("question 43743: preserves adjacent source contract",()=>has(0,"return [\"x\",\"y\",\"z\"]\n.map((axis)=>{"));
test("question 43744: preserves adjacent source contract",()=>has(0,".map((axis)=>{\nconst n=Number(value?.[axis])||0;"));
test("question 43745: preserves adjacent source contract",()=>has(0,"const n=Number(value?.[axis])||0;\nreturn Math.abs(n-Math.round(n))<1e-9"));
test("question 43746: preserves adjacent source contract",()=>has(0,"return Math.abs(n-Math.round(n))<1e-9\n? String(Math.round(n))"));
test("question 43747: preserves adjacent source contract",()=>has(0,"? String(Math.round(n))\n: n.toFixed(2);"));
test("question 43748: preserves adjacent source contract",()=>has(0,": n.toFixed(2);\n.join(\" × \");"));
test("question 43749: preserves adjacent source contract",()=>has(0,".join(\" × \");\nfunction shouldApplyReferenceFrame(projectValue,preview){"));
test("question 43750: preserves adjacent source contract",()=>has(0,"function shouldApplyReferenceFrame(projectValue,preview){\nconst frame=preview?.frame;"));
test("question 43751: preserves adjacent source contract",()=>has(0,"const frame=preview?.frame;\nif(preview?.status!==\"exact\"||!frame)return false;"));
test("question 43752: preserves adjacent source contract",()=>has(0,"if(preview?.status!==\"exact\"||!frame)return false;\nconst current=frameDimensions(projectValue);"));
test("question 43753: preserves adjacent source contract",()=>has(0,"const current=frameDimensions(projectValue);\nconst next=frameDimensions({bbox:frame.bbox});"));
test("question 43754: preserves adjacent source contract",()=>has(0,"const next=frameDimensions({bbox:frame.bbox});\nconst dimensionsChanged=frameChanged(current,next);"));
test("question 43755: preserves adjacent source contract",()=>has(0,"const dimensionsChanged=frameChanged(current,next);\nif(!dimensionsChanged)return true;"));
test("question 43756: preserves adjacent source contract",()=>has(0,"if(!dimensionsChanged)return true;\nconst message="));
test("question 43757: preserves adjacent source contract",()=>has(0,"const message=\n\"После удаления импортированного компонента габаритная рамка изменится.\\n\\n\"+"));
test("question 43758: preserves adjacent source contract",()=>has(0,"\"После удаления импортированного компонента габаритная рамка изменится.\\n\\n\"+\n\"Текущая: \"+frameText(current)+\" мм\\n\"+"));
test("question 43759: preserves adjacent source contract",()=>has(0,"\"Текущая: \"+frameText(current)+\" мм\\n\"+\n\"Новая: \"+frameText(next)+\" мм\\n\\n\"+"));
test("question 43760: preserves adjacent source contract",()=>has(0,"\"Новая: \"+frameText(next)+\" мм\\n\\n\"+\n\"Обновить габаритную рамку?\";"));
test("question 43761: preserves adjacent source contract",()=>has(0,"\"Обновить габаритную рамку?\";\ntry{return window.confirm(message);}"));
test("question 43762: preserves adjacent source contract",()=>has(0,"try{return window.confirm(message);}\ncatch{return false;}"));
test("question 43763: preserves adjacent source contract",()=>has(0,"catch{return false;}\nfunction updateImportOriginEvidence(tube,oldOrigin,newOrigin,oldOffset,newOffset){"));
test("question 43764: preserves adjacent source contract",()=>has(0,"function updateImportOriginEvidence(tube,oldOrigin,newOrigin,oldOffset,newOffset){\nconst spatial=tube?.importEvidence?.spatialPlacement;"));
test("question 43765: preserves adjacent source contract",()=>has(0,"const spatial=tube?.importEvidence?.spatialPlacement;\nif(!spatial||typeof spatial!==\"object\")return;"));
test("question 43766: preserves adjacent source contract",()=>has(0,"if(!spatial||typeof spatial!==\"object\")return;\nspatial.editable_origin_mm=[newOrigin.x,newOrigin.y,newOrigin.z];"));
test("question 43767: preserves adjacent source contract",()=>has(0,"spatial.editable_origin_mm=[newOrigin.x,newOrigin.y,newOrigin.z];\nspatial.reference_frame_rebase_after_delete={"));
test("question 43768: preserves adjacent source contract",()=>has(0,"spatial.reference_frame_rebase_after_delete={\nstatus:\"applied\","));
test("question 43769: preserves adjacent source contract",()=>has(0,"status:\"applied\",\nsource_editable_origin_mm:[oldOrigin.x,oldOrigin.y,oldOrigin.z],"));
test("question 43770: preserves adjacent source contract",()=>has(0,"source_editable_origin_mm:[oldOrigin.x,oldOrigin.y,oldOrigin.z],\nprevious_coordinate_offset_mm:[oldOffset.x,oldOffset.y,oldOffset.z],"));
test("question 43771: preserves adjacent source contract",()=>has(0,"previous_coordinate_offset_mm:[oldOffset.x,oldOffset.y,oldOffset.z],\nnext_coordinate_offset_mm:[newOffset.x,newOffset.y,newOffset.z],"));
test("question 43772: preserves adjacent source contract",()=>has(0,"next_coordinate_offset_mm:[newOffset.x,newOffset.y,newOffset.z],\nrebased_editable_origin_mm:[newOrigin.x,newOrigin.y,newOrigin.z],"));
test("question 43773: preserves adjacent source contract",()=>has(0,"rebased_editable_origin_mm:[newOrigin.x,newOrigin.y,newOrigin.z],\nphysical_world_position_preserved:true,"));
test("question 43774: preserves adjacent source contract",()=>has(0,"physical_world_position_preserved:true,\nsource_geometry_preserved:true"));
test("question 43775: preserves adjacent source contract",()=>has(0,"source_geometry_preserved:true\nconst linear=tube?.importEvidence?.linearDimensionNormalization;"));
test("question 43776: preserves adjacent source contract",()=>has(0,"const linear=tube?.importEvidence?.linearDimensionNormalization;\nif(linear&&typeof linear===\"object\"){"));
test("question 43777: preserves adjacent source contract",()=>has(0,"if(linear&&typeof linear===\"object\"){\nlinear.project_frame_rebased_origin_mm=[newOrigin.x,newOrigin.y,newOrigin.z];"));
test("question 43778: preserves adjacent source contract",()=>has(0,"linear.project_frame_rebased_origin_mm=[newOrigin.x,newOrigin.y,newOrigin.z];\nfunction applyReferenceFrame(projectValue,frame){"));
test("question 43779: preserves adjacent source contract",()=>has(0,"function applyReferenceFrame(projectValue,frame){\nif(!projectValue||frame?.status!==\"exact\")return false;"));
test("question 43780: preserves adjacent source contract",()=>has(0,"if(!projectValue||frame?.status!==\"exact\")return false;\nconst oldOffset=frameOffset(projectValue);"));
test("question 43781: preserves adjacent source contract",()=>has(0,"const oldOffset=frameOffset(projectValue);\nconst nextOffset=finitePoint3(frame.coordinateOffset,oldOffset);"));
test("question 43782: preserves adjacent source contract",()=>has(0,"const nextOffset=finitePoint3(frame.coordinateOffset,oldOffset);\nconst delta={"));
test("question 43783: preserves adjacent source contract",()=>has(0,"const delta={\nx:oldOffset.x-nextOffset.x,"));
test("question 43784: preserves adjacent source contract",()=>has(0,"x:oldOffset.x-nextOffset.x,\ny:oldOffset.y-nextOffset.y,"));
test("question 43785: preserves adjacent source contract",()=>has(0,"y:oldOffset.y-nextOffset.y,\nz:oldOffset.z-nextOffset.z"));
test("question 43786: preserves adjacent source contract",()=>has(0,"z:oldOffset.z-nextOffset.z\nfor(const tube of projectValue.tubes??[]){"));
test("question 43787: preserves adjacent source contract",()=>has(0,"for(const tube of projectValue.tubes??[]){\nconst oldOrigin=finitePoint3(tube?.origin,{x:0,y:0,z:0});"));
test("question 43788: preserves adjacent source contract",()=>has(0,"const oldOrigin=finitePoint3(tube?.origin,{x:0,y:0,z:0});\nconst newOrigin={"));
test("question 43789: preserves adjacent source contract",()=>has(0,"const newOrigin={\nx:Number((oldOrigin.x+delta.x).toFixed(6)),"));
test("question 43790: preserves adjacent source contract",()=>has(0,"x:Number((oldOrigin.x+delta.x).toFixed(6)),\ny:Number((oldOrigin.y+delta.y).toFixed(6)),"));
test("question 43791: preserves adjacent source contract",()=>has(0,"y:Number((oldOrigin.y+delta.y).toFixed(6)),\nz:Number((oldOrigin.z+delta.z).toFixed(6))"));
test("question 43792: preserves adjacent source contract",()=>has(0,"z:Number((oldOrigin.z+delta.z).toFixed(6))\ntube.origin=newOrigin;"));
test("question 43793: preserves adjacent source contract",()=>has(0,"tube.origin=newOrigin;\nupdateImportOriginEvidence(tube,oldOrigin,newOrigin,oldOffset,nextOffset);"));
test("question 43794: preserves adjacent source contract",()=>has(0,"updateImportOriginEvidence(tube,oldOrigin,newOrigin,oldOffset,nextOffset);\nprojectValue.bbox={...frame.bbox};"));
test("question 43795: preserves adjacent source contract",()=>has(0,"projectValue.bbox={...frame.bbox};\nprojectValue.bboxAnchor={...frame.bboxAnchor};"));
test("question 43796: preserves adjacent source contract",()=>has(0,"projectValue.bboxAnchor={...frame.bboxAnchor};\nprojectValue.coordinateOffset={...nextOffset};"));
test("question 43797: preserves adjacent source contract",()=>has(0,"projectValue.coordinateOffset={...nextOffset};\nif(typeof state===\"object\"&&state){"));
test("question 43798: preserves adjacent source contract",()=>has(0,"if(typeof state===\"object\"&&state){\nstate.bbox={...frame.bbox};"));
test("question 43799: preserves adjacent source contract",()=>has(0,"state.bbox={...frame.bbox};\nstate.bboxAnchor={...frame.bboxAnchor};"));
test("question 43800: preserves adjacent source contract",()=>has(0,"state.bboxAnchor={...frame.bboxAnchor};\nstate.coordinateOffset={...nextOffset};"));
test("question 43801: preserves adjacent source contract",()=>has(0,"state.coordinateOffset={...nextOffset};\nconst active=(projectValue.tubes??[]).find("));
test("question 43802: preserves adjacent source contract",()=>has(0,"const active=(projectValue.tubes??[]).find(\n(tube)=>String(tube?.id)===activeTubeId()"));
test("question 43803: preserves adjacent source contract",()=>has(0,"(tube)=>String(tube?.id)===activeTubeId()\nif(active?.origin)state.origin={...active.origin};"));
test("question 43804: preserves adjacent source contract",()=>has(0,"if(active?.origin)state.origin={...active.origin};\nreturn true;"));
test("question 43805: preserves adjacent source contract",()=>has(0,"return true;\nfunction showAllObjects(projectValue){"));
test("question 43806: preserves adjacent source contract",()=>has(0,"function showAllObjects(projectValue){\nfor(const tube of projectValue?.tubes??[]){"));
test("question 43807: preserves adjacent source contract",()=>has(0,"for(const tube of projectValue?.tubes??[]){\ntube.uiHiddenIn3D=false;"));
test("question 43808: preserves adjacent source contract",()=>has(0,"for(const row of tube.rows??[])row.uiHiddenIn3D=false;\nif(Array.isArray(state?.rows)){"));
test("question 43809: preserves adjacent source contract",()=>has(0,"if(Array.isArray(state?.rows)){\nfor(const row of state.rows)row.uiHiddenIn3D=false;"));
test("question 43810: preserves adjacent source contract",()=>has(0,"for(const row of state.rows)row.uiHiddenIn3D=false;\nrefApi()?.showAll?.(projectValue);"));
test("question 43811: preserves adjacent source contract",()=>has(0,"refApi()?.showAll?.(projectValue);\nfunction applyAction(action,{dependencyResolved=false,dependencyResolution=null}={}){"));
test("question 43812: preserves adjacent source contract",()=>has(0,"function applyAction(action,{dependencyResolved=false,dependencyResolution=null}={}){\nconst entries=selectionEntries();"));
test("question 43813: preserves adjacent source contract",()=>has(0,"const entries=selectionEntries();\nconst p=project();"));
test("question 43814: preserves adjacent source contract",()=>has(0,"if(!p)return;\nif(action!==\"show-all\"&&!entries.length)return;"));
test("question 43815: preserves adjacent source contract",()=>has(0,"if(action!==\"show-all\"&&!entries.length)return;\nif(action===\"delete\"&&!lockAllowed(\"delete\"))return;"));
test("question 43816: preserves adjacent source contract",()=>has(0,"if(action===\"delete\"&&!lockAllowed(\"delete\"))return;\nif(action===\"delete\"&&!dependencyResolved){"));
test("question 43817: preserves adjacent source contract",()=>has(0,"if(action===\"delete\"&&!dependencyResolved){\nconst api=deleteDependencyApi();"));
test("question 43818: preserves adjacent source contract",()=>has(0,"const api=deleteDependencyApi();\nif(typeof api?.request!==\"function\"){"));
test("question 43819: preserves adjacent source contract",()=>has(0,"if(typeof api?.request!==\"function\"){\nif(typeof ptToast===\"function\")ptToast(\"Удаление заблокировано: анализ зависимостей недоступен\");"));
test("question 43820: preserves adjacent source contract",()=>has(0,"if(typeof ptToast===\"function\")ptToast(\"Удаление заблокировано: анализ зависимостей недоступен\");\nreturn false;"));
test("question 43821: preserves adjacent source contract",()=>has(0,"return false;\napi.request(entries,(resolution)=>{"));
test("question 43822: preserves adjacent source contract",()=>has(0,"api.request(entries,(resolution)=>{\nif(resolution?.cancelled||resolution?.strategy===\"Cancel\")return;"));
test("question 43823: preserves adjacent source contract",()=>has(0,"if(resolution?.cancelled||resolution?.strategy===\"Cancel\")return;\napplyAction(\"delete\",{dependencyResolved:true,dependencyResolution:resolution});"));
test("question 43824: preserves adjacent source contract",()=>has(0,"applyAction(\"delete\",{dependencyResolved:true,dependencyResolution:resolution});\nreturn true;"));
test("question 43825: preserves adjacent source contract",()=>has(0,"return true;\nconst mutate=()=>{"));
test("question 43826: preserves adjacent source contract",()=>has(0,"if(typeof syncActiveTubeFromState===\"function\")syncActiveTubeFromState();\nif(action===\"show-all\"){"));
test("question 43827: preserves adjacent source contract",()=>has(0,"if(action===\"show-all\"){\nshowAllObjects(p);"));
test("question 43828: preserves adjacent source contract",()=>has(0,"showAllObjects(p);\nprepareReferenceSelection(entries);"));
test("question 43829: preserves adjacent source contract",()=>has(0,"prepareReferenceSelection(entries);\nif(action===\"hide\"||action===\"show\"){"));
test("question 43830: preserves adjacent source contract",()=>has(0,"if(action===\"hide\"||action===\"show\"){\nconst refs=selectedReferenceEntries(entries);"));
test("question 43831: preserves adjacent source contract",()=>has(0,"const refs=selectedReferenceEntries(entries);\nif(refs.length)refApi()?.applyBulkAction?.(p,action);"));
test("question 43832: preserves adjacent source contract",()=>has(0,"if(refs.length)refApi()?.applyBulkAction?.(p,action);\nfor(const entry of entries)if(entry.kind!==\"ref\")setDisplayState(entry,action);"));
test("question 43833: preserves adjacent source contract",()=>has(0,"for(const entry of entries)if(entry.kind!==\"ref\")setDisplayState(entry,action);\n}else if(action===\"isolate\"){"));
test("question 43834: preserves adjacent source contract",()=>has(0,"}else if(action===\"isolate\"){\nisolateEditableSelection(entries,p);"));
test("question 43835: preserves adjacent source contract",()=>has(0,"isolateEditableSelection(entries,p);\nrefApi()?.isolateSelection?.(p);"));
test("question 43836: preserves adjacent source contract",()=>has(0,"refApi()?.isolateSelection?.(p);\n}else if(action===\"transparent\"){"));
test("question 43837: preserves adjacent source contract",()=>has(0,"}else if(action===\"transparent\"){\nconst refs=selectedReferenceEntries(entries);"));
test("question 43838: preserves adjacent source contract",()=>has(0,"const refs=selectedReferenceEntries(entries);\nif(refs.length)refApi()?.applyBulkAction?.(p,\"transparent\");"));
test("question 43839: preserves adjacent source contract",()=>has(0,"if(refs.length)refApi()?.applyBulkAction?.(p,\"transparent\");\ntoggleTransparency(entries);"));
test("question 43840: preserves adjacent source contract",()=>has(0,"toggleTransparency(entries);\n}else if(action===\"delete\"){"));
test("question 43841: preserves adjacent source contract",()=>has(0,"}else if(action===\"delete\"){\nif(dependencyResolution?.analysis){"));
test("question 43842: preserves adjacent source contract",()=>has(0,"if(dependencyResolution?.analysis){\nconst resolved=deleteDependencyApi()?.applyStrategy?.(p,dependencyResolution);"));
test("question 43843: preserves adjacent source contract",()=>has(0,"const resolved=deleteDependencyApi()?.applyStrategy?.(p,dependencyResolution);\nif(resolved?.ok===false)return false;"));
test("question 43844: preserves adjacent source contract",()=>has(0,"if(resolved?.ok===false)return false;\nconst refs=selectedReferenceEntries(entries);"));
test("question 43845: preserves adjacent source contract",()=>has(0,"const refs=selectedReferenceEntries(entries);\nlet framePreview=null;"));
test("question 43846: preserves adjacent source contract",()=>has(0,"let framePreview=null;\nlet applyFrame=false;"));
test("question 43847: preserves adjacent source contract",()=>has(0,"let applyFrame=false;\nif(refs.length){"));
test("question 43848: preserves adjacent source contract",()=>has(0,"if(refs.length){\nframePreview=refApi()?.previewDeleteFrame?.(p)??null;"));
test("question 43849: preserves adjacent source contract",()=>has(0,"framePreview=refApi()?.previewDeleteFrame?.(p)??null;\nif(framePreview?.status===\"exact\"){"));
test("question 43850: preserves adjacent source contract",()=>has(0,"if(framePreview?.status===\"exact\"){\napplyFrame=shouldApplyReferenceFrame(p,framePreview);"));
test("question 43851: preserves adjacent source contract",()=>has(0,"applyFrame=shouldApplyReferenceFrame(p,framePreview);\nrefApi()?.applyBulkAction?.(p,\"delete\");"));
test("question 43852: preserves adjacent source contract",()=>has(0,"refApi()?.applyBulkAction?.(p,\"delete\");\ndeleteRows(entries);"));
test("question 43853: preserves adjacent source contract",()=>has(0,"deleteRows(entries);\ndeleteTubes(entries);"));
test("question 43854: preserves adjacent source contract",()=>has(0,"deleteTubes(entries);\ndeleteMeshInstances(entries);"));
test("question 43855: preserves adjacent source contract",()=>has(0,"deleteMeshInstances(entries);\ntry{window.TubeBenderSelectionSets?.pruneMissing?.();}catch{}"));
test("question 43856: preserves adjacent source contract",()=>has(0,"try{window.TubeBenderSelectionSets?.pruneMissing?.();}catch{}\nif(refs.length&&applyFrame&&framePreview?.frame){"));
test("question 43857: preserves adjacent source contract",()=>has(0,"if(refs.length&&applyFrame&&framePreview?.frame){\napplyReferenceFrame(p,framePreview.frame);"));
test("question 43858: preserves adjacent source contract",()=>has(0,"applyReferenceFrame(p,framePreview.frame);\n}else if(refs.length&&framePreview&&framePreview.status!==\"exact\"){"));
test("question 43859: preserves adjacent source contract",()=>has(0,"}else if(refs.length&&framePreview&&framePreview.status!==\"exact\"){\nif(typeof ptToast===\"function\"){"));
test("question 43860: preserves adjacent source contract",()=>has(0,"if(typeof ptToast===\"function\"){\nptToast(\"Компонент удалён; габаритная рамка не пересчитана: \"+String(framePreview.reason??\"нет точных габаритов\"));"));
test("question 43861: preserves adjacent source contract",()=>has(0,"ptToast(\"Компонент удалён; габаритная рамка не пересчитана: \"+String(framePreview.reason??\"нет точных габаритов\"));\n}catch{}"));
test("question 43862: preserves adjacent source contract",()=>has(0,"}catch{}\nselected.clear();"));
test("question 43863: preserves adjacent source contract",()=>has(0,"refApi()?.clearSelection?.();\nreturn true;"));
test("question 43864: preserves adjacent source contract",()=>has(0,"return true;\nconst label={"));
test("question 43865: preserves adjacent source contract",()=>has(0,"const label={\nhide:\"Скрыть выбранные объекты\","));
test("question 43866: preserves adjacent source contract",()=>has(0,"hide:\"Скрыть выбранные объекты\",\nisolate:\"Скрыть другие объекты\","));
test("question 43867: preserves adjacent source contract",()=>has(0,"isolate:\"Скрыть другие объекты\",\nshow:\"Показать выбранные объекты\","));
test("question 43868: preserves adjacent source contract",()=>has(0,"show:\"Показать выбранные объекты\",\n\"show-all\":\"Показать все объекты\","));
test("question 43869: preserves adjacent source contract",()=>has(0,"\"show-all\":\"Показать все объекты\",\ntransparent:\"Изменить прозрачность выбранных объектов\","));
test("question 43870: preserves adjacent source contract",()=>has(0,"transparent:\"Изменить прозрачность выбранных объектов\",\ndelete:\"Удалить выбранные объекты\""));
test("question 43871: preserves adjacent source contract",()=>has(0,"delete:\"Удалить выбранные объекты\"\n}[action]||\"Изменить выбранные объекты\";"));
test("question 43872: preserves adjacent source contract",()=>has(0,"}[action]||\"Изменить выбранные объекты\";\nconst ok=typeof tbModelCommand===\"function\"?tbModelCommand(label,mutate):mutate();"));
test("question 43873: preserves adjacent source contract",()=>has(0,"const ok=typeof tbModelCommand===\"function\"?tbModelCommand(label,mutate):mutate();\nif(ok===false)return;"));
test("question 43874: preserves adjacent source contract",()=>has(0,"if(ok===false)return;\nif(action===\"hide\"||action===\"show\"||action===\"isolate\"){"));
test("question 43875: preserves adjacent source contract",()=>has(0,"if(action===\"hide\"||action===\"show\"||action===\"isolate\"){\nconst repeatLabel=action===\"hide\"?\"Скрыть\":action===\"show\"?\"Показать\":\"Скрыть другие\";"));
test("question 43876: preserves adjacent source contract",()=>has(0,"const repeatLabel=action===\"hide\"?\"Скрыть\":action===\"show\"?\"Показать\":\"Скрыть другие\";\ntry{repeatApi()?.record?.(\"context.\"+action,repeatLabel,{},\"context\");}catch{}"));
test("question 43877: preserves adjacent source contract",()=>has(0,"try{repeatApi()?.record?.(\"context.\"+action,repeatLabel,{},\"context\");}catch{}\ntry{if(typeof save===\"function\")save();}catch{}"));
test("question 43878: preserves adjacent source contract",()=>has(0,"try{if(typeof renderAll===\"function\")renderAll();}catch{}\ntry{groupsApi()?.applyVisibility?.();assembliesApi()?.applyVisibility?.();}catch{}"));
test("question 43879: preserves adjacent source contract",()=>has(0,"try{groupsApi()?.applyVisibility?.();assembliesApi()?.applyVisibility?.();}catch{}\nrefreshVisualSelection();"));
test("question 43880: preserves adjacent source contract",()=>has(0,"refreshVisualSelection();\nlet areaSelection=null;"));
test("question 43881: preserves adjacent source contract",()=>has(0,"let areaSelection=null;\nfunction ensureAreaOverlay(){"));
test("question 43882: preserves adjacent source contract",()=>has(0,"function ensureAreaOverlay(){\nlet el=document.getElementById(\"tbAreaSelectionOverlay\");"));
test("question 43883: preserves adjacent source contract",()=>has(0,"let el=document.getElementById(\"tbAreaSelectionOverlay\");\nif(el)return el;"));
test("question 43884: preserves adjacent source contract",()=>has(0,"if(el)return el;\nel=document.createElement(\"div\");el.id=\"tbAreaSelectionOverlay\";"));
test("question 43885: preserves adjacent source contract",()=>has(0,"el=document.createElement(\"div\");el.id=\"tbAreaSelectionOverlay\";\nel.style.cssText=\"position:fixed;z-index:119990;pointer-events:none;border:1px solid #ffd54a;background:rgba(255,213,74,.10);display:none\";"));
test("question 43886: preserves adjacent source contract",()=>has(0,"el.style.cssText=\"position:fixed;z-index:119990;pointer-events:none;border:1px solid #ffd54a;background:rgba(255,213,74,.10);display:none\";\ndocument.body.appendChild(el);"));
test("question 43887: preserves adjacent source contract",()=>has(0,"document.body.appendChild(el);\nreturn el;"));
test("question 43888: preserves adjacent source contract",()=>has(0,"return el;\nfunction pointInPolygon(point,polygon){"));
test("question 43889: preserves adjacent source contract",()=>has(0,"function pointInPolygon(point,polygon){\nlet inside=false;"));
test("question 43890: preserves adjacent source contract",()=>has(0,"let inside=false;\nfor(let i=0,j=polygon.length-1;i<polygon.length;j=i++){"));
test("question 43891: preserves adjacent source contract",()=>has(0,"for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){\nconst a=polygon[i],b=polygon[j];"));
test("question 43892: preserves adjacent source contract",()=>has(0,"const a=polygon[i],b=polygon[j];\nif(((a.y>point.y)!==(b.y>point.y))&&(point.x<(b.x-a.x)*(point.y-a.y)/(b.y-a.y||1e-12)+a.x))inside=!inside;"));
test("question 43893: preserves adjacent source contract",()=>has(0,"if(((a.y>point.y)!==(b.y>point.y))&&(point.x<(b.x-a.x)*(point.y-a.y)/(b.y-a.y||1e-12)+a.x))inside=!inside;\nreturn inside;"));
test("question 43894: preserves adjacent source contract",()=>has(0,"return inside;\nfunction projectedSelectionCandidates(){"));
test("question 43895: preserves adjacent source contract",()=>has(0,"function projectedSelectionCandidates(){\nif(typeof THREE===\"undefined\"||typeof camera===\"undefined\"||typeof pipeGroup===\"undefined\")return [];"));
test("question 43896: preserves adjacent source contract",()=>has(0,"if(typeof THREE===\"undefined\"||typeof camera===\"undefined\"||typeof pipeGroup===\"undefined\")return [];\nconst canvas=document.getElementById(\"threeCanvas\");if(!canvas)return [];"));
test("question 43897: preserves adjacent source contract",()=>has(0,"const canvas=document.getElementById(\"threeCanvas\");if(!canvas)return [];\nconst rect=canvas.getBoundingClientRect(),map=new Map();"));
test("question 43898: preserves adjacent source contract",()=>has(0,"const rect=canvas.getBoundingClientRect(),map=new Map();\npipeGroup.traverse((object)=>{"));
test("question 43899: preserves adjacent source contract",()=>has(0,"pipeGroup.traverse((object)=>{\nif(!object||object.visible===false||skip3DHit(object))return;"));
test("question 43900: preserves adjacent source contract",()=>has(0,"if(!object||object.visible===false||skip3DHit(object))return;\nconst hit=entryFrom3DObject(object);if(!hit||map.has(hit.key))return;"));
test("question 43901: preserves adjacent source contract",()=>has(0,"const hit=entryFrom3DObject(object);if(!hit||map.has(hit.key))return;\nlet box;try{box=new THREE.Box3().setFromObject(object);}catch{return;}"));
test("question 43902: preserves adjacent source contract",()=>has(0,"let box;try{box=new THREE.Box3().setFromObject(object);}catch{return;}\nif(!box||box.isEmpty())return;"));
test("question 43903: preserves adjacent source contract",()=>has(0,"if(!box||box.isEmpty())return;\nconst center=box.getCenter(new THREE.Vector3()).project(camera);"));
test("question 43904: preserves adjacent source contract",()=>has(0,"const center=box.getCenter(new THREE.Vector3()).project(camera);\nif(center.z<-1||center.z>1)return;"));
test("question 43905: preserves adjacent source contract",()=>has(0,"if(center.z<-1||center.z>1)return;\nmap.set(hit.key,{key:hit.key,x:rect.left+(center.x+1)*.5*rect.width,y:rect.top+(1-center.y)*.5*rect.height});"));
test("question 43906: preserves adjacent source contract",()=>has(0,"map.set(hit.key,{key:hit.key,x:rect.left+(center.x+1)*.5*rect.width,y:rect.top+(1-center.y)*.5*rect.height});\nreturn [...map.values()];"));
test("question 43907: preserves adjacent source contract",()=>has(0,"return [...map.values()];\nfunction beginAreaSelection(event){"));
test("question 43908: preserves adjacent source contract",()=>has(0,"function beginAreaSelection(event){\nif(event.button!==0||!(event.shiftKey||event.altKey))return false;"));
test("question 43909: preserves adjacent source contract",()=>has(0,"if(event.button!==0||!(event.shiftKey||event.altKey))return false;\nareaSelection={mode:event.altKey?\"lasso\":\"box\",start:{x:event.clientX,y:event.clientY},points:[{x:event.clientX,y:event.clientY}],additive:!!(event.ctrlKey||event.metaKey),moved:false};"));
test("question 43910: preserves adjacent source contract",()=>has(0,"areaSelection={mode:event.altKey?\"lasso\":\"box\",start:{x:event.clientX,y:event.clientY},points:[{x:event.clientX,y:event.clientY}],additive:!!(event.ctrlKey||event.metaKey),moved:false};\nconst overlay=ensureAreaOverlay();overlay.style.display=\"block\";"));
test("question 43911: preserves adjacent source contract",()=>has(0,"const overlay=ensureAreaOverlay();overlay.style.display=\"block\";\nif(areaSelection.mode===\"lasso\"){overlay.style.borderStyle=\"dashed\";overlay.style.background=\"rgba(255,213,74,.06)\";}else overlay.style.borderStyle=\"solid\";"));
test("question 43912: preserves adjacent source contract",()=>has(0,"if(areaSelection.mode===\"lasso\"){overlay.style.borderStyle=\"dashed\";overlay.style.background=\"rgba(255,213,74,.06)\";}else overlay.style.borderStyle=\"solid\";\nevent.preventDefault();event.stopPropagation();"));
test("question 43913: preserves adjacent source contract",()=>has(0,"event.preventDefault();event.stopPropagation();\ntry{event.target.setPointerCapture?.(event.pointerId);}catch{}"));
test("question 43914: preserves adjacent source contract",()=>has(0,"try{event.target.setPointerCapture?.(event.pointerId);}catch{}\nreturn true;"));
test("question 43915: preserves adjacent source contract",()=>has(0,"return true;\nfunction updateAreaSelection(event){"));
test("question 43916: preserves adjacent source contract",()=>has(0,"function updateAreaSelection(event){\nif(!areaSelection)return;"));
test("question 43917: preserves adjacent source contract",()=>has(0,"if(!areaSelection)return;\nconst dx=event.clientX-areaSelection.start.x,dy=event.clientY-areaSelection.start.y;"));
test("question 43918: preserves adjacent source contract",()=>has(0,"const dx=event.clientX-areaSelection.start.x,dy=event.clientY-areaSelection.start.y;\nif(Math.hypot(dx,dy)>4)areaSelection.moved=true;"));
test("question 43919: preserves adjacent source contract",()=>has(0,"if(Math.hypot(dx,dy)>4)areaSelection.moved=true;\nareaSelection.points.push({x:event.clientX,y:event.clientY});"));
test("question 43920: preserves adjacent source contract",()=>has(0,"areaSelection.points.push({x:event.clientX,y:event.clientY});\nconst overlay=ensureAreaOverlay();"));
test("question 43921: preserves adjacent source contract",()=>has(0,"const overlay=ensureAreaOverlay();\nconst xs=areaSelection.points.map((p)=>p.x),ys=areaSelection.points.map((p)=>p.y);"));
test("question 43922: preserves adjacent source contract",()=>has(0,"const xs=areaSelection.points.map((p)=>p.x),ys=areaSelection.points.map((p)=>p.y);\noverlay.style.left=Math.min(...xs)+\"px\";overlay.style.top=Math.min(...ys)+\"px\";"));
test("question 43923: preserves adjacent source contract",()=>has(0,"overlay.style.left=Math.min(...xs)+\"px\";overlay.style.top=Math.min(...ys)+\"px\";\noverlay.style.width=Math.max(1,Math.max(...xs)-Math.min(...xs))+\"px\";overlay.style.height=Math.max(1,Math.max(...ys)-Math.min(...ys))+\"px\";"));
test("question 43924: preserves adjacent source contract",()=>has(0,"overlay.style.width=Math.max(1,Math.max(...xs)-Math.min(...xs))+\"px\";overlay.style.height=Math.max(1,Math.max(...ys)-Math.min(...ys))+\"px\";\nevent.preventDefault();event.stopPropagation();"));
test("question 43925: preserves adjacent source contract",()=>has(0,"event.preventDefault();event.stopPropagation();\nfunction finishAreaSelection(event){"));
test("question 43926: preserves adjacent source contract",()=>has(0,"function finishAreaSelection(event){\nif(!areaSelection)return false;"));
test("question 43927: preserves adjacent source contract",()=>has(0,"if(!areaSelection)return false;\nconst gesture=areaSelection;areaSelection=null;"));
test("question 43928: preserves adjacent source contract",()=>has(0,"const gesture=areaSelection;areaSelection=null;\nconst overlay=ensureAreaOverlay();overlay.style.display=\"none\";"));
test("question 43929: preserves adjacent source contract",()=>has(0,"const overlay=ensureAreaOverlay();overlay.style.display=\"none\";\nif(!gesture.moved)return false;"));
test("question 43930: preserves adjacent source contract",()=>has(0,"if(!gesture.moved)return false;\nconst candidates=projectedSelectionCandidates(),start=gesture.start,end={x:event.clientX,y:event.clientY};"));
test("question 43931: preserves adjacent source contract",()=>has(0,"const candidates=projectedSelectionCandidates(),start=gesture.start,end={x:event.clientX,y:event.clientY};\nconst minX=Math.min(start.x,end.x),maxX=Math.max(start.x,end.x),minY=Math.min(start.y,end.y),maxY=Math.max(start.y,end.y);"));
test("question 43932: preserves adjacent source contract",()=>has(0,"const minX=Math.min(start.x,end.x),maxX=Math.max(start.x,end.x),minY=Math.min(start.y,end.y),maxY=Math.max(start.y,end.y);\nconst rawKeys=candidates.filter((p)=>gesture.mode===\"lasso\""));
test("question 43933: preserves adjacent source contract",()=>has(0,"const rawKeys=candidates.filter((p)=>gesture.mode===\"lasso\"\n?pointInPolygon(p,gesture.points)"));
test("question 43934: preserves adjacent source contract",()=>has(0,"?pointInPolygon(p,gesture.points)\n:(p.x>=minX&&p.x<=maxX&&p.y>=minY&&p.y<=maxY)).map((p)=>p.key);"));
test("question 43935: preserves adjacent source contract",()=>has(0,":(p.x>=minX&&p.x<=maxX&&p.y>=minY&&p.y<=maxY)).map((p)=>p.key);\nconst keys=[];"));
test("question 43936: preserves adjacent source contract",()=>has(0,"const keys=[];\nfor(const rawKey of rawKeys){"));
test("question 43937: preserves adjacent source contract",()=>has(0,"for(const rawKey of rawKeys){\nconst entry=parseKey(rawKey),resolved=entry?assembliesApi()?.resolveInteraction?.(entry,rawKey):null;"));
test("question 43938: preserves adjacent source contract",()=>has(0,"const entry=parseKey(rawKey),resolved=entry?assembliesApi()?.resolveInteraction?.(entry,rawKey):null;\nif(resolved?.blocked)continue;"));
test("question 43939: preserves adjacent source contract",()=>has(0,"if(resolved?.blocked)continue;\nlet key=resolved?.handled?resolved.key:rawKey;"));
test("question 43940: preserves adjacent source contract",()=>has(0,"let key=resolved?.handled?resolved.key:rawKey;\nif(!resolved?.handled){"));
test("question 43941: preserves adjacent source contract",()=>has(0,"if(!resolved?.handled){\nconst group=entry?groupsApi()?.primaryGroupForEntry?.(entry):null;"));
test("question 43942: preserves adjacent source contract",()=>has(0,"const group=entry?groupsApi()?.primaryGroupForEntry?.(entry):null;\nif(group)key=groupKey(group.id);"));
test("question 43943: preserves adjacent source contract",()=>has(0,"if(group)key=groupKey(group.id);\nif(key&&!keys.includes(key))keys.push(key);"));
test("question 43944: preserves adjacent source contract",()=>has(0,"if(key&&!keys.includes(key))keys.push(key);\nif(!gesture.additive){selected.clear();refApi()?.clearSelection?.();}"));
test("question 43945: preserves adjacent source contract",()=>has(0,"if(!gesture.additive){selected.clear();refApi()?.clearSelection?.();}\nfor(const key of keys)selected.add(key);"));
test("question 43946: preserves adjacent source contract",()=>has(0,"for(const key of keys)selected.add(key);\nsyncSelectionIntoReference();refreshVisualSelection();"));
test("question 43947: preserves adjacent source contract",()=>has(0,"syncSelectionIntoReference();refreshVisualSelection();\nwindow.dispatchEvent(new CustomEvent(\"tubebender-selection-change\"));"));
test("question 43948: preserves adjacent source contract",()=>has(0,"window.dispatchEvent(new CustomEvent(\"tubebender-selection-change\"));\nevent.preventDefault();event.stopPropagation();"));
test("question 43949: preserves adjacent source contract",()=>has(0,"event.preventDefault();event.stopPropagation();\nreturn true;"));
test("question 43950: preserves adjacent source contract",()=>has(0,"return true;\nfunction resolvePickedAssembly(picked){"));
test("question 43951: preserves adjacent source contract",()=>has(0,"function resolvePickedAssembly(picked){\nif(!picked)return null;"));
test("question 43952: preserves adjacent source contract",()=>has(0,"if(!picked)return null;\nreturn assembliesApi()?.resolveInteraction?.(picked.entry,picked.key);"));
test("question 43953: preserves adjacent source contract",()=>has(0,"return assembliesApi()?.resolveInteraction?.(picked.entry,picked.key);\nfunction resolveSelectionCandidate(candidate,{direct=false}={}){"));
test("question 43954: preserves adjacent source contract",()=>has(0,"function resolveSelectionCandidate(candidate,{direct=false}={}){\nif(!candidate)return null;"));
test("question 43955: preserves adjacent source contract",()=>has(0,"if(!candidate)return null;\nconst picked=candidate;"));
test("question 43956: preserves adjacent source contract",()=>has(0,"const picked=candidate;\nconst assemblyResolved=resolvePickedAssembly(picked);"));
test("question 43957: preserves adjacent source contract",()=>has(0,"const assemblyResolved=resolvePickedAssembly(picked);\nif(assemblyResolved?.blocked)return null;"));
test("question 43958: preserves adjacent source contract",()=>has(0,"if(assemblyResolved?.blocked)return null;\nlet key=assemblyResolved?.handled?assemblyResolved.key:candidate.key;"));
test("question 43959: preserves adjacent source contract",()=>has(0,"let key=assemblyResolved?.handled?assemblyResolved.key:candidate.key;\nlet entry=assemblyResolved?.handled?parseKey(key):candidate.entry;"));
test("question 43960: preserves adjacent source contract",()=>has(0,"let entry=assemblyResolved?.handled?parseKey(key):candidate.entry;\nif(!assemblyResolved?.handled&&!direct){"));
test("question 43961: preserves adjacent source contract",()=>has(0,"if(!assemblyResolved?.handled&&!direct){\nconst group=groupsApi()?.primaryGroupForEntry?.(candidate.entry);"));
test("question 43962: preserves adjacent source contract",()=>has(0,"const group=groupsApi()?.primaryGroupForEntry?.(candidate.entry);\nif(group){key=groupKey(group.id);entry=parseKey(key);}"));
test("question 43963: preserves adjacent source contract",()=>has(0,"if(group){key=groupKey(group.id);entry=parseKey(key);}\nreturn key?{key,entry:entry??parseKey(key),distance:candidate.distance??0}:null;"));
test("question 43964: preserves adjacent source contract",()=>has(0,"return key?{key,entry:entry??parseKey(key),distance:candidate.distance??0}:null;\nfunction selectionCandidatesAtEvent(event,{direct=false}={}){"));
test("question 43965: preserves adjacent source contract",()=>has(0,"function selectionCandidatesAtEvent(event,{direct=false}={}){\nconst map=new Map();"));
test("question 43966: preserves adjacent source contract",()=>has(0,"const map=new Map();\nconst dimensionCandidate=dimensionGripsApi()?.selectionCandidateAtEvent?.(event)??null;"));
test("question 43967: preserves adjacent source contract",()=>has(0,"const dimensionCandidate=dimensionGripsApi()?.selectionCandidateAtEvent?.(event)??null;\nif(dimensionCandidate?.dimensionId){"));
test("question 43968: preserves adjacent source contract",()=>has(0,"if(dimensionCandidate?.dimensionId){\nconst key=dimensionKey(dimensionCandidate.dimensionId);"));
test("question 43969: preserves adjacent source contract",()=>has(0,"const key=dimensionKey(dimensionCandidate.dimensionId);\nmap.set(key,{"));
test("question 43970: preserves adjacent source contract",()=>has(0,"map.set(key,{\nentry:{kind:\"dimension\",dimensionId:String(dimensionCandidate.dimensionId)},"));
test("question 43971: preserves adjacent source contract",()=>has(0,"entry:{kind:\"dimension\",dimensionId:String(dimensionCandidate.dimensionId)},\ndistance:Number(dimensionCandidate.distance)||0,"));
test("question 43972: preserves adjacent source contract",()=>has(0,"distance:Number(dimensionCandidate.distance)||0,\ndimensionPart:dimensionCandidate.part??null,"));
test("question 43973: preserves adjacent source contract",()=>has(0,"dimensionPart:dimensionCandidate.part??null,\ndimensionStatus:dimensionCandidate.status??null,"));
test("question 43974: preserves adjacent source contract",()=>has(0,"dimensionStatus:dimensionCandidate.status??null,\ndimensionMode:dimensionCandidate.mode??null,"));
test("question 43975: preserves adjacent source contract",()=>has(0,"dimensionMode:dimensionCandidate.mode??null,\ndimensionGeometryClass:dimensionCandidate.geometryClass??null,"));
test("question 43976: preserves adjacent source contract",()=>has(0,"dimensionGeometryClass:dimensionCandidate.geometryClass??null,\ndimensionNeedsReview:dimensionCandidate.needsReview===true"));
test("question 43977: preserves adjacent source contract",()=>has(0,"dimensionNeedsReview:dimensionCandidate.needsReview===true\nconst sectionCandidates=window.TubeBenderSectionView?.selectionCandidatesAtEvent?.(event)??[];"));
test("question 43978: preserves adjacent source contract",()=>has(0,"const sectionCandidates=window.TubeBenderSectionView?.selectionCandidatesAtEvent?.(event)??[];\nfor(const record of sectionCandidates){"));
test("question 43979: preserves adjacent source contract",()=>has(0,"for(const record of sectionCandidates){\nconst key=sectionDerivedKey(record.id);"));
test("question 43980: preserves adjacent source contract",()=>has(0,"const key=sectionDerivedKey(record.id);\nif(!map.has(key))map.set(key,{key,entry:{kind:\"section-derived\",derivedId:String(record.id)},distance:Number(record.screen_distance_px)||0,screenDistance:true});"));
test("question 43981: preserves adjacent source contract",()=>has(0,"if(!map.has(key))map.set(key,{key,entry:{kind:\"section-derived\",derivedId:String(record.id)},distance:Number(record.screen_distance_px)||0,screenDistance:true});\nfor(const raw of pick3DCandidates(event)){"));
test("question 43982: preserves adjacent source contract",()=>has(0,"for(const raw of pick3DCandidates(event)){\nconst candidate=resolveSelectionCandidate(raw,{direct});"));
test("question 43983: preserves adjacent source contract",()=>has(0,"const candidate=resolveSelectionCandidate(raw,{direct});\nif(candidate&&!map.has(candidate.key))map.set(candidate.key,candidate);"));
test("question 43984: preserves adjacent source contract",()=>has(0,"if(candidate&&!map.has(candidate.key))map.set(candidate.key,candidate);\nreturn Object.freeze([...map.values()]);"));
test("question 43985: preserves adjacent source contract",()=>has(0,"return Object.freeze([...map.values()]);\nfunction setSelectionCycle(candidates,event,index=0){"));
test("question 43986: preserves adjacent source contract",()=>has(0,"function setSelectionCycle(candidates,event,index=0){\nselectionCycle={"));
test("question 43987: preserves adjacent source contract",()=>has(0,"selectionCycle={\nactive:Array.isArray(candidates)&&candidates.length>1,"));
test("question 43988: preserves adjacent source contract",()=>has(0,"active:Array.isArray(candidates)&&candidates.length>1,\ncandidates:Array.isArray(candidates)?candidates.map(item=>({...item})):[],"));
test("question 43989: preserves adjacent source contract",()=>has(0,"candidates:Array.isArray(candidates)?candidates.map(item=>({...item})):[],\nindex:Math.max(0,Math.min(Number(index)||0,Math.max(0,(candidates?.length??1)-1))),"));
test("question 43990: preserves adjacent source contract",()=>has(0,"index:Math.max(0,Math.min(Number(index)||0,Math.max(0,(candidates?.length??1)-1))),\nclientX:Number(event?.clientX)||0,"));
test("question 43991: preserves adjacent source contract",()=>has(0,"clientX:Number(event?.clientX)||0,\nclientY:Number(event?.clientY)||0"));
test("question 43992: preserves adjacent source contract",()=>has(0,"clientY:Number(event?.clientY)||0\nreturn selectionCycle;"));
test("question 43993: preserves adjacent source contract",()=>has(0,"return selectionCycle;\nfunction resetSelectionCycle(){"));
test("question 43994: preserves adjacent source contract",()=>has(0,"function resetSelectionCycle(){\nselectionCycle={active:false,candidates:[],index:0,clientX:0,clientY:0};"));
test("question 43995: preserves adjacent source contract",()=>has(0,"selectionCycle={active:false,candidates:[],index:0,clientX:0,clientY:0};\nhideObjectChooser();"));
test("question 43996: preserves adjacent source contract",()=>has(0,"hideObjectChooser();\nfunction applySelectionCycleIndex(index,{reveal=true}={}){"));
test("question 43997: preserves adjacent source contract",()=>has(0,"function applySelectionCycleIndex(index,{reveal=true}={}){\nif(!selectionCycle.candidates.length)return null;"));
test("question 43998: preserves adjacent source contract",()=>has(0,"if(!selectionCycle.candidates.length)return null;\nconst n=selectionCycle.candidates.length;"));
test("question 43999: preserves adjacent source contract",()=>has(0,"const n=selectionCycle.candidates.length;\nselectionCycle.index=((Math.trunc(index)%n)+n)%n;"));
test("question 44000: preserves adjacent source contract",()=>has(0,"selectionCycle.index=((Math.trunc(index)%n)+n)%n;\nconst candidate=selectionCycle.candidates[selectionCycle.index];"));
test("question 44001: preserves adjacent source contract",()=>has(0,"const candidate=selectionCycle.candidates[selectionCycle.index];\nsetSelectedKey(candidate.key,{additive:false,toggle:false});"));
test("question 44002: preserves adjacent source contract",()=>has(0,"setSelectedKey(candidate.key,{additive:false,toggle:false});\nif(reveal)revealTreeKey(candidate.key);"));
test("question 44003: preserves adjacent source contract",()=>has(0,"if(reveal)revealTreeKey(candidate.key);\nrenderObjectChooserActive();"));
test("question 44004: preserves adjacent source contract",()=>has(0,"renderObjectChooserActive();\nreturn candidate;"));
test("question 44005: preserves adjacent source contract",()=>has(0,"return candidate;\nfunction cycleSelection(direction=1){"));
test("question 44006: preserves adjacent source contract",()=>has(0,"function cycleSelection(direction=1){\nif(!selectionCycle.active||selectionCycle.candidates.length<2)return null;"));
test("question 44007: preserves adjacent source contract",()=>has(0,"if(!selectionCycle.active||selectionCycle.candidates.length<2)return null;\nreturn applySelectionCycleIndex(selectionCycle.index+(direction<0?-1:1));"));
test("question 44008: preserves adjacent source contract",()=>has(0,"return applySelectionCycleIndex(selectionCycle.index+(direction<0?-1:1));\nfunction selectionCandidateLabel(candidate){"));
test("question 44009: preserves adjacent source contract",()=>has(0,"function selectionCandidateLabel(candidate){\nconst entry=candidate?.entry??parseKey(candidate?.key);"));
test("question 44010: preserves adjacent source contract",()=>has(0,"const entry=candidate?.entry??parseKey(candidate?.key);\nif(!entry)return String(candidate?.key??\"Object\");"));
test("question 44011: preserves adjacent source contract",()=>has(0,"if(!entry)return String(candidate?.key??\"Object\");\nif(entry.kind===\"tube\"){"));
test("question 44012: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"tube\"){\nconst tube=tubeById(entry.tubeId);return \"Tube · \"+String(tube?.name??entry.tubeId);"));
test("question 44013: preserves adjacent source contract",()=>has(0,"const tube=tubeById(entry.tubeId);return \"Tube · \"+String(tube?.name??entry.tubeId);\nif(entry.kind===\"mesh-instance\"){"));
test("question 44014: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"mesh-instance\"){\nconst item=refApi()?.meshInstanceById?.(project(),entry.instanceId);return \"Mesh · \"+String(item?.name??entry.instanceId);"));
test("question 44015: preserves adjacent source contract",()=>has(0,"const item=refApi()?.meshInstanceById?.(project(),entry.instanceId);return \"Mesh · \"+String(item?.name??entry.instanceId);\nif(entry.kind===\"ref\")return \"Source / Reference · \"+String(entry.nodeId);"));
test("question 44016: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"ref\")return \"Source / Reference · \"+String(entry.nodeId);\nif(entry.kind===\"group\")return \"Group · \"+String(groupsApi()?.groupById?.(entry.groupId)?.name??entry.groupId);"));
test("question 44017: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"group\")return \"Group · \"+String(groupsApi()?.groupById?.(entry.groupId)?.name??entry.groupId);\nif(entry.kind===\"project-assembly\")return \"Assembly · \"+String(assembliesApi()?.assemblyById?.(entry.assemblyId)?.name??entry.assemblyId);"));
test("question 44018: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"project-assembly\")return \"Assembly · \"+String(assembliesApi()?.assemblyById?.(entry.assemblyId)?.name??entry.assemblyId);\nif(entry.kind===\"row\")return \"Tube element · #\"+(Number(entry.rowIndex)+1);"));
test("question 44019: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"row\")return \"Tube element · #\"+(Number(entry.rowIndex)+1);\nif(entry.kind===\"dimension\"){"));
test("question 44020: preserves adjacent source contract",()=>has(0,"if(entry.kind===\"dimension\"){\nconst dimension=(project()?.engineering_dimensions??[]).find(item=>String(item?.id)===String(entry.dimensionId));"));
test("question 44021: preserves adjacent source contract",()=>has(0,"const dimension=(project()?.engineering_dimensions??[]).find(item=>String(item?.id)===String(entry.dimensionId));\nconst part=String(candidate?.dimensionPart??\"dimension\");"));
test("question 44022: preserves adjacent source contract",()=>has(0,"const part=String(candidate?.dimensionPart??\"dimension\");\nconst partLabel=part===\"text\"?\"Text\":part===\"line\"?\"Line\":part===\"reference\"?\"Reference\":part;"));
test("question 44023: preserves adjacent source contract",()=>has(0,"const partLabel=part===\"text\"?\"Text\":part===\"line\"?\"Line\":part===\"reference\"?\"Reference\":part;\nconst geometryClass=String(candidate?.dimensionGeometryClass??window.TubeBenderMeasurements?.dimensionAuditGeometryClass?.(dimension)??\"Unknown\");"));
