import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const files=["src/ui/object-selection-context-ui.js","src/ui/editing-ui.js","src/import/dwfx/reference-scene-ui.js","src/ui/assemblies-runtime.js","src/ui/equipment-library-ui.js"];
const normalized=files.map(rel=>fs.readFileSync(path.join(root,rel),"utf8").split(/\r?\n/).map(s=>s.trim()).filter(s=>s.length>=8&&!s.startsWith("//")&&s!=="{"&&s!=="}"&&s!=="};").join("\n"));
const has=(fileIndex,pair)=>assert.ok(normalized[fileIndex].includes(pair));
test("question 46649: preserves adjacent source contract",()=>has(2,"event.stopPropagation();\nconst scene=findScene(project,button.dataset.refSceneEye);"));
test("question 46650: preserves adjacent source contract",()=>has(2,"const scene=findScene(project,button.dataset.refSceneEye);\nif(!scene)return;"));
test("question 46651: preserves adjacent source contract",()=>has(2,"if(!scene)return;\nscene.visible=scene.visible===false;"));
test("question 46652: preserves adjacent source contract",()=>has(2,"scene.visible=scene.visible===false;\nsave?.();"));
test("question 46653: preserves adjacent source contract",()=>has(2,"renderAll?.();\nhost.querySelectorAll(\"[data-ref-toggle]\").forEach((button)=>{"));
test("question 46654: preserves adjacent source contract",()=>has(2,"host.querySelectorAll(\"[data-ref-toggle]\").forEach((button)=>{\nbutton.addEventListener(\"click\",(event)=>{"));
test("question 46655: preserves adjacent source contract",()=>has(2,"event.stopPropagation();\nconst row=button.closest(\"[data-ref-scene]\");"));
test("question 46656: preserves adjacent source contract",()=>has(2,"const row=button.closest(\"[data-ref-scene]\");\nconst scene=findScene(project,row?.dataset.refScene);"));
test("question 46657: preserves adjacent source contract",()=>has(2,"const scene=findScene(project,row?.dataset.refScene);\nif(!scene)return;"));
test("question 46658: preserves adjacent source contract",()=>has(2,"if(!scene)return;\nconst id=String(button.dataset.refToggle);"));
test("question 46659: preserves adjacent source contract",()=>has(2,"const id=String(button.dataset.refToggle);\nconst set=new Set(Array.isArray(scene.collapsedNodeIds)?scene.collapsedNodeIds.map(String):[]);"));
test("question 46660: preserves adjacent source contract",()=>has(2,"const set=new Set(Array.isArray(scene.collapsedNodeIds)?scene.collapsedNodeIds.map(String):[]);\nif(set.has(id))set.delete(id);else set.add(id);"));
test("question 46661: preserves adjacent source contract",()=>has(2,"if(set.has(id))set.delete(id);else set.add(id);\nscene.collapsedNodeIds=[...set];"));
test("question 46662: preserves adjacent source contract",()=>has(2,"scene.collapsedNodeIds=[...set];\nsave?.();"));
test("question 46663: preserves adjacent source contract",()=>has(2,"refreshProjectTree?.();\nhost.querySelectorAll(\"[data-ref-eye]\").forEach((button)=>{"));
test("question 46664: preserves adjacent source contract",()=>has(2,"host.querySelectorAll(\"[data-ref-eye]\").forEach((button)=>{\nbutton.addEventListener(\"click\",(event)=>{"));
test("question 46665: preserves adjacent source contract",()=>has(2,"if(!scene)return;\nconst id=String(button.dataset.refEye);"));
test("question 46666: preserves adjacent source contract",()=>has(2,"const id=String(button.dataset.refEye);\nconst set=new Set(Array.isArray(scene.hiddenNodeIds)?scene.hiddenNodeIds.map(String):[]);"));
test("question 46667: preserves adjacent source contract",()=>has(2,"const set=new Set(Array.isArray(scene.hiddenNodeIds)?scene.hiddenNodeIds.map(String):[]);\nif(set.has(id))set.delete(id);else set.add(id);"));
test("question 46668: preserves adjacent source contract",()=>has(2,"if(set.has(id))set.delete(id);else set.add(id);\nscene.hiddenNodeIds=[...set];"));
test("question 46669: preserves adjacent source contract",()=>has(2,"scene.hiddenNodeIds=[...set];\nsave?.();"));
test("question 46670: preserves adjacent source contract",()=>has(2,"renderAll?.();\nhost.querySelectorAll(\"[data-import-editable-tube]\").forEach((row)=>{"));
test("question 46671: preserves adjacent source contract",()=>has(2,"host.querySelectorAll(\"[data-import-editable-tube]\").forEach((row)=>{\nconst tube=importedEditableTubeById(project,row.dataset.importEditableTube);"));
test("question 46672: preserves adjacent source contract",()=>has(2,"const tube=importedEditableTubeById(project,row.dataset.importEditableTube);\nif(!tube)return;"));
test("question 46673: preserves adjacent source contract",()=>has(2,"if(!tube)return;\nrow.addEventListener(\"click\",(event)=>{"));
test("question 46674: preserves adjacent source contract",()=>has(2,"row.addEventListener(\"click\",(event)=>{\nif(event.button!==0)return;"));
test("question 46675: preserves adjacent source contract",()=>has(2,"if(event.button!==0)return;\nif(typeof switchTube===\"function\")switchTube(tube.id);"));
test("question 46676: preserves adjacent source contract",()=>has(2,"if(typeof switchTube===\"function\")switchTube(tube.id);\nrow.addEventListener(\"contextmenu\",(event)=>{"));
test("question 46677: preserves adjacent source contract",()=>has(2,"row.addEventListener(\"contextmenu\",(event)=>{\nshowSourceLinkMenu(event,project,tube,{"));
test("question 46678: preserves adjacent source contract",()=>has(2,"showSourceLinkMenu(event,project,tube,{\nmodelCommand,save,renderAll,refreshProjectTree,reloadActiveTube"));
test("question 46679: preserves adjacent source contract",()=>has(2,"modelCommand,save,renderAll,refreshProjectTree,reloadActiveTube\nhost.querySelectorAll(\"[data-ref-node]\").forEach((row)=>{"));
test("question 46680: preserves adjacent source contract",()=>has(2,"host.querySelectorAll(\"[data-ref-node]\").forEach((row)=>{\nrow.addEventListener(\"click\",(event)=>{"));
test("question 46681: preserves adjacent source contract",()=>has(2,"row.addEventListener(\"click\",(event)=>{\nif(event.target.closest(\"button,input\"))return;"));
test("question 46682: preserves adjacent source contract",()=>has(2,"if(event.target.closest(\"button,input\"))return;\nconst scene=findScene(project,row.dataset.refScene);"));
test("question 46683: preserves adjacent source contract",()=>has(2,"const scene=findScene(project,row.dataset.refScene);\nconst node=findNode(scene?.tree,row.dataset.refNode);"));
test("question 46684: preserves adjacent source contract",()=>has(2,"const node=findNode(scene?.tree,row.dataset.refNode);\nif(!scene||!node)return;"));
test("question 46685: preserves adjacent source contract",()=>has(2,"if(!scene||!node)return;\nconst key=selectionKey(scene.id,node.id);"));
test("question 46686: preserves adjacent source contract",()=>has(2,"const key=selectionKey(scene.id,node.id);\nif(!node.editable_part_number&&(event.ctrlKey||event.metaKey||event.shiftKey)){"));
test("question 46687: preserves adjacent source contract",()=>has(2,"if(!node.editable_part_number&&(event.ctrlKey||event.metaKey||event.shiftKey)){\nevent.preventDefault();"));
test("question 46688: preserves adjacent source contract",()=>has(2,"event.preventDefault();\napplyModifierSelection("));
test("question 46689: preserves adjacent source contract",()=>has(2,"applyModifierSelection(\nproject,"));
test("question 46690: preserves adjacent source contract",()=>has(2,"project,\nvisibleSelectionKeys(host),"));
test("question 46691: preserves adjacent source contract",()=>has(2,"visibleSelectionKeys(host),\nctrlKey:event.ctrlKey,"));
test("question 46692: preserves adjacent source contract",()=>has(2,"ctrlKey:event.ctrlKey,\nmetaKey:event.metaKey,"));
test("question 46693: preserves adjacent source contract",()=>has(2,"metaKey:event.metaKey,\nshiftKey:event.shiftKey"));
test("question 46694: preserves adjacent source contract",()=>has(2,"shiftKey:event.shiftKey\nselected={sceneId:String(scene.id),nodeId:String(node.id)};"));
test("question 46695: preserves adjacent source contract",()=>has(2,"selected={sceneId:String(scene.id),nodeId:String(node.id)};\nrefreshProjectTree?.();"));
test("question 46696: preserves adjacent source contract",()=>has(2,"notifyExternalSelection(\"tree\");\nconst part=String(node.editable_part_number??\"\");"));
test("question 46697: preserves adjacent source contract",()=>has(2,"const part=String(node.editable_part_number??\"\");\nif(part&&typeof switchTube===\"function\"){"));
test("question 46698: preserves adjacent source contract",()=>has(2,"if(part&&typeof switchTube===\"function\"){\nconst tube=(project.tubes??[]).find((item)=>"));
test("question 46699: preserves adjacent source contract",()=>has(2,"const tube=(project.tubes??[]).find((item)=>\nitem?.partNumber,"));
test("question 46700: preserves adjacent source contract",()=>has(2,"item?.partNumber,\nitem?.part_number,"));
test("question 46701: preserves adjacent source contract",()=>has(2,"item?.part_number,\nitem?.importEvidence?.part_number,"));
test("question 46702: preserves adjacent source contract",()=>has(2,"item?.importEvidence?.part_number,\nitem?.currentProjectImport?.part_number"));
test("question 46703: preserves adjacent source contract",()=>has(2,"item?.currentProjectImport?.part_number\n].filter(Boolean).map(String).includes(part)"));
test("question 46704: preserves adjacent source contract",()=>has(2,"].filter(Boolean).map(String).includes(part)\nif(tube){"));
test("question 46705: preserves adjacent source contract",()=>has(2,"if(tube){\nswitchTube(tube.id);"));
test("question 46706: preserves adjacent source contract",()=>has(2,"switchTube(tube.id);\nselected={sceneId:String(scene.id),nodeId:String(node.id)};"));
test("question 46707: preserves adjacent source contract",()=>has(2,"selected={sceneId:String(scene.id),nodeId:String(node.id)};\nif(!node.editable_part_number){"));
test("question 46708: preserves adjacent source contract",()=>has(2,"if(!node.editable_part_number){\nbulkSelected.clear();"));
test("question 46709: preserves adjacent source contract",()=>has(2,"bulkSelected.clear();\nbulkSelected.add(key);"));
test("question 46710: preserves adjacent source contract",()=>has(2,"bulkSelected.add(key);\nrangeAnchorKey=key;"));
test("question 46711: preserves adjacent source contract",()=>has(2,"rangeAnchorKey=key;\nrefreshProjectTree?.();"));
test("question 46712: preserves adjacent source contract",()=>has(2,"notifyExternalSelection(\"tree\");\nfunction restorePersistedRuntimes(project){"));
test("question 46713: preserves adjacent source contract",()=>has(2,"function restorePersistedRuntimes(project){\nlet count=0;"));
test("question 46714: preserves adjacent source contract",()=>has(2,"let count=0;\nfor(const scene of project?.referenceScenes??[]){"));
test("question 46715: preserves adjacent source contract",()=>has(2,"for(const scene of project?.referenceScenes??[]){\nif(scene?.display_runtime&&registerRuntime(scene.display_runtime))count+=1;"));
test("question 46716: preserves adjacent source contract",()=>has(2,"if(scene?.display_runtime&&registerRuntime(scene.display_runtime))count+=1;\nreturn count;"));
test("question 46717: preserves adjacent source contract",()=>has(2,"return count;\nfunction runtimeSummary(){"));
test("question 46718: preserves adjacent source contract",()=>has(2,"function runtimeSummary(){\nreturn [...runtimes.values()].map((runtime)=>({"));
test("question 46719: preserves adjacent source contract",()=>has(2,"return [...runtimes.values()].map((runtime)=>({\nscene_id:runtime.scene_id,"));
test("question 46720: preserves adjacent source contract",()=>has(2,"scene_id:runtime.scene_id,\nasset_count:runtime.assetsById.size"));
test("question 46721: preserves adjacent source contract",()=>has(2,"asset_count:runtime.assetsById.size\nwindow.TubeBenderReferenceSceneUi=Object.freeze({"));
test("question 46722: preserves adjacent source contract",()=>has(2,"window.TubeBenderReferenceSceneUi=Object.freeze({\nregisterRuntime,"));
test("question 46723: preserves adjacent source contract",()=>has(2,"registerRuntime,\nrender3D,"));
test("question 46724: preserves adjacent source contract",()=>has(2,"render3D,\ntreeItems,"));
test("question 46725: preserves adjacent source contract",()=>has(2,"treeItems,\nbindTree,"));
test("question 46726: preserves adjacent source contract",()=>has(2,"bindTree,\nselectScene,"));
test("question 46727: preserves adjacent source contract",()=>has(2,"selectScene,\nselectNode,"));
test("question 46728: preserves adjacent source contract",()=>has(2,"selectNode,\nselectOnlyNode,"));
test("question 46729: preserves adjacent source contract",()=>has(2,"selectOnlyNode,\nselectedKeys,"));
test("question 46730: preserves adjacent source contract",()=>has(2,"selectedKeys,\nreplaceSelection,"));
test("question 46731: preserves adjacent source contract",()=>has(2,"replaceSelection,\nrevealNode,"));
test("question 46732: preserves adjacent source contract",()=>has(2,"revealNode,\nmoveSelection,"));
test("question 46733: preserves adjacent source contract",()=>has(2,"moveSelection,\neditableMeshInstances:(project)=>editableMeshInstanceList(project,{create:false}),"));
test("question 46734: preserves adjacent source contract",()=>has(2,"editableMeshInstances:(project)=>editableMeshInstanceList(project,{create:false}),\nmeshInstanceById,"));
test("question 46735: preserves adjacent source contract",()=>has(2,"meshInstanceById,\ncreateEditableMeshInstance,"));
test("question 46736: preserves adjacent source contract",()=>has(2,"createEditableMeshInstance,\ncreateEditableMeshInstanceByRef,"));
test("question 46737: preserves adjacent source contract",()=>has(2,"createEditableMeshInstanceByRef,\nensureEditableMeshInstance,"));
test("question 46738: preserves adjacent source contract",()=>has(2,"ensureEditableMeshInstance,\nensureEditableMeshInstanceByRef,"));
test("question 46739: preserves adjacent source contract",()=>has(2,"ensureEditableMeshInstanceByRef,\nmoveEditableMeshInstance,"));
test("question 46740: preserves adjacent source contract",()=>has(2,"moveEditableMeshInstance,\nrotateEditableMeshInstance,"));
test("question 46741: preserves adjacent source contract",()=>has(2,"rotateEditableMeshInstance,\nrotateEditableMeshInstanceAxis,"));
test("question 46742: preserves adjacent source contract",()=>has(2,"rotateEditableMeshInstanceAxis,\ncopyEditableMeshInstance,"));
test("question 46743: preserves adjacent source contract",()=>has(2,"copyEditableMeshInstance,\narrayEditableMeshInstance,"));
test("question 46744: preserves adjacent source contract",()=>has(2,"arrayEditableMeshInstance,\nbreakEditableMeshInstanceLink,"));
test("question 46745: preserves adjacent source contract",()=>has(2,"breakEditableMeshInstanceLink,\nclearSelection,"));
test("question 46746: preserves adjacent source contract",()=>has(2,"clearSelection,\nisolateSelection,"));
test("question 46747: preserves adjacent source contract",()=>has(2,"isolateSelection,\nshowAll,"));
test("question 46748: preserves adjacent source contract",()=>has(2,"showAll,\ncurrentReferenceProjectBounds,"));
test("question 46749: preserves adjacent source contract",()=>has(2,"currentReferenceProjectBounds,\npreviewDeleteFrame,"));
test("question 46750: preserves adjacent source contract",()=>has(2,"previewDeleteFrame,\napplyBulkAction,"));
test("question 46751: preserves adjacent source contract",()=>has(2,"applyBulkAction,\napplyModifierSelection,"));
test("question 46752: preserves adjacent source contract",()=>has(2,"applyModifierSelection,\nselectedCount,"));
test("question 46753: preserves adjacent source contract",()=>has(2,"selectedCount,\nrestorePersistedRuntimes,"));
test("question 46754: preserves adjacent source contract",()=>has(2,"restorePersistedRuntimes,\nruntimeSummary"));
test("question 46755: preserves adjacent source contract",()=>has(3,"const ASSEMBLIES_URL=\"__TB_ASSEMBLIES_MODULE_URL__\";\nconst RIGID_URL=\"__TB_ASSEMBLY_RIGID_MODULE_URL__\";"));
test("question 46756: preserves adjacent source contract",()=>has(3,"const RIGID_URL=\"__TB_ASSEMBLY_RIGID_MODULE_URL__\";\nlet installed=false,assemblies=null,rigid=null,panel=null,toggle=null,observer=null,treeScheduled=false,breadcrumbBar=null;"));
test("question 46757: preserves adjacent source contract",()=>has(3,"let installed=false,assemblies=null,rigid=null,panel=null,toggle=null,observer=null,treeScheduled=false,breadcrumbBar=null;\nconst editPath=[];"));
test("question 46758: preserves adjacent source contract",()=>has(3,"const editPath=[];\nconst ctx=()=>window.TubeBenderObjectContext??null;"));
test("question 46759: preserves adjacent source contract",()=>has(3,"const ctx=()=>window.TubeBenderObjectContext??null;\nconst eng=()=>window.TubeBenderEngineering??null;"));
test("question 46760: preserves adjacent source contract",()=>has(3,"const eng=()=>window.TubeBenderEngineering??null;\nconst refApi=()=>window.TubeBenderReferenceSceneUi??null;"));
test("question 46761: preserves adjacent source contract",()=>has(3,"const refApi=()=>window.TubeBenderReferenceSceneUi??null;\nconst layerApi=()=>window.TubeBenderLayers??null;"));
test("question 46762: preserves adjacent source contract",()=>has(3,"const layerApi=()=>window.TubeBenderLayers??null;\nconst lockPolicy=()=>window.TubeBenderObjectLocks?.policy??null;"));
test("question 46763: preserves adjacent source contract",()=>has(3,"const lockPolicy=()=>window.TubeBenderObjectLocks?.policy??null;\nconst project=()=>{try{return eng()?.activeProject?.()??null;}catch{return null;}};"));
test("question 46764: preserves adjacent source contract",()=>has(3,"const project=()=>{try{return eng()?.activeProject?.()??null;}catch{return null;}};\nconst entries=()=>ctx()?.selectionEntries?.()??[];"));
test("question 46765: preserves adjacent source contract",()=>has(3,"const entries=()=>ctx()?.selectionEntries?.()??[];\nconst clone=(v)=>v==null?v:structuredClone(v);"));
test("question 46766: preserves adjacent source contract",()=>has(3,"const clone=(v)=>v==null?v:structuredClone(v);\nconst esc=(v)=>String(v??\"\").replace(/[&<>\"']/g,ch=>({\"&\":\"&amp;\",\"<\":\"&lt;\",\">\":\"&gt;\",'\"':\"&quot;\",\"'\":\"&#39;\"}[ch]));"));
test("question 46767: preserves adjacent source contract",()=>has(3,"const esc=(v)=>String(v??\"\").replace(/[&<>\"']/g,ch=>({\"&\":\"&amp;\",\"<\":\"&lt;\",\">\":\"&gt;\",'\"':\"&quot;\",\"'\":\"&#39;\"}[ch]));\nconst toast=(m)=>{try{eng()?.toast?.(String(m??\"\"));}catch{}};"));
test("question 46768: preserves adjacent source contract",()=>has(3,"const toast=(m)=>{try{eng()?.toast?.(String(m??\"\"));}catch{}};\nconst tubeById=(id)=>(project()?.tubes??[]).find(t=>String(t?.id)===String(id))??null;"));
test("question 46769: preserves adjacent source contract",()=>has(3,"const tubeById=(id)=>(project()?.tubes??[]).find(t=>String(t?.id)===String(id))??null;\nconst meshById=(id)=>refApi()?.meshInstanceById?.(project(),id)??null;"));
test("question 46770: preserves adjacent source contract",()=>has(3,"const meshById=(id)=>refApi()?.meshInstanceById?.(project(),id)??null;\nconst assemblyById=(id)=>assemblies?.assemblyById?.(project(),id)??null;"));
test("question 46771: preserves adjacent source contract",()=>has(3,"const assemblyById=(id)=>assemblies?.assemblyById?.(project(),id)??null;\nfunction command(label,mutate,{wholeObject=false}={}){"));
test("question 46772: preserves adjacent source contract",()=>has(3,"function command(label,mutate,{wholeObject=false}={}){\nconst fn=wholeObject?(eng()?.wholeObjectCommand??eng()?.modelCommand):eng()?.modelCommand;let ok;"));
test("question 46773: preserves adjacent source contract",()=>has(3,"const fn=wholeObject?(eng()?.wholeObjectCommand??eng()?.modelCommand):eng()?.modelCommand;let ok;\ntry{ok=typeof fn===\"function\"?fn(label,mutate):mutate();}"));
test("question 46774: preserves adjacent source contract",()=>has(3,"try{ok=typeof fn===\"function\"?fn(label,mutate):mutate();}\ncatch(error){toast(error?.message??error);return false;}"));
test("question 46775: preserves adjacent source contract",()=>has(3,"catch(error){toast(error?.message??error);return false;}\nif(ok===false)return false;"));
test("question 46776: preserves adjacent source contract",()=>has(3,"if(ok===false)return false;\ntry{eng()?.save?.();eng()?.renderAll?.();}catch{}"));
test("question 46777: preserves adjacent source contract",()=>has(3,"try{eng()?.save?.();eng()?.renderAll?.();}catch{}\ntry{window.refreshProjectTree?.();}catch{}"));
test("question 46778: preserves adjacent source contract",()=>has(3,"try{window.refreshProjectTree?.();}catch{}\nrenderTree();applyVisibility();applyEditContext();renderPanel();renderBreadcrumb();"));
test("question 46779: preserves adjacent source contract",()=>has(3,"renderTree();applyVisibility();applyEditContext();renderPanel();renderBreadcrumb();\ntry{window.dispatchEvent(new CustomEvent(\"tubebender-assembly-change\",{detail:{project_id:String(project()?.id??\"\")}}));}catch{}"));
test("question 46780: preserves adjacent source contract",()=>has(3,"try{window.dispatchEvent(new CustomEvent(\"tubebender-assembly-change\",{detail:{project_id:String(project()?.id??\"\")}}));}catch{}\nreturn true;"));
test("question 46781: preserves adjacent source contract",()=>has(3,"return true;\nfunction refFromEntry(entry){"));
test("question 46782: preserves adjacent source contract",()=>has(3,"function refFromEntry(entry){\nif(!entry)return null;"));
test("question 46783: preserves adjacent source contract",()=>has(3,"if(!entry)return null;\nif([\"tube\",\"row\",\"origin\",\"end\"].includes(entry.kind))return {kind:\"tube\",id:String(entry.tubeId)};"));
test("question 46784: preserves adjacent source contract",()=>has(3,"if([\"tube\",\"row\",\"origin\",\"end\"].includes(entry.kind))return {kind:\"tube\",id:String(entry.tubeId)};\nif(entry.kind===\"mesh-instance\")return {kind:\"mesh-instance\",id:String(entry.instanceId)};"));
test("question 46785: preserves adjacent source contract",()=>has(3,"if(entry.kind===\"mesh-instance\")return {kind:\"mesh-instance\",id:String(entry.instanceId)};\nif(entry.kind===\"construction\")return {kind:\"construction\",id:String(entry.constructionId??entry.id)};"));
test("question 46786: preserves adjacent source contract",()=>has(3,"if(entry.kind===\"construction\")return {kind:\"construction\",id:String(entry.constructionId??entry.id)};\nif(entry.kind===\"dimension\")return {kind:\"dimension\",id:String(entry.dimensionId??entry.id)};"));
test("question 46787: preserves adjacent source contract",()=>has(3,"if(entry.kind===\"dimension\")return {kind:\"dimension\",id:String(entry.dimensionId??entry.id)};\nif(entry.kind===\"project-assembly\")return {kind:\"assembly\",id:String(entry.assemblyId)};"));
test("question 46788: preserves adjacent source contract",()=>has(3,"if(entry.kind===\"project-assembly\")return {kind:\"assembly\",id:String(entry.assemblyId)};\nif(entry.kind===\"ref\")return {kind:\"source-ref\",scene_id:String(entry.sceneId),node_id:String(entry.nodeId)};"));
test("question 46789: preserves adjacent source contract",()=>has(3,"if(entry.kind===\"ref\")return {kind:\"source-ref\",scene_id:String(entry.sceneId),node_id:String(entry.nodeId)};\nreturn null;"));
test("question 46790: preserves adjacent source contract",()=>has(3,"return null;\nfunction entryFromRef(ref){"));
test("question 46791: preserves adjacent source contract",()=>has(3,"function entryFromRef(ref){\nif(ref.kind===\"tube\")return {kind:\"tube\",tubeId:String(ref.id)};"));
test("question 46792: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"tube\")return {kind:\"tube\",tubeId:String(ref.id)};\nif(ref.kind===\"mesh-instance\")return {kind:\"mesh-instance\",instanceId:String(ref.id)};"));
test("question 46793: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"mesh-instance\")return {kind:\"mesh-instance\",instanceId:String(ref.id)};\nif(ref.kind===\"construction\")return {kind:\"construction\",constructionId:String(ref.id)};"));
test("question 46794: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"construction\")return {kind:\"construction\",constructionId:String(ref.id)};\nif(ref.kind===\"dimension\")return {kind:\"dimension\",dimensionId:String(ref.id)};"));
test("question 46795: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"dimension\")return {kind:\"dimension\",dimensionId:String(ref.id)};\nif(ref.kind===\"assembly\")return {kind:\"project-assembly\",assemblyId:String(ref.id)};"));
test("question 46796: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"assembly\")return {kind:\"project-assembly\",assemblyId:String(ref.id)};\nreturn null;"));
test("question 46797: preserves adjacent source contract",()=>has(3,"return null;\nfunction selectionKeyForRef(ref){"));
test("question 46798: preserves adjacent source contract",()=>has(3,"function selectionKeyForRef(ref){\nif(ref.kind===\"tube\")return \"tube:\"+encodeURIComponent(ref.id);"));
test("question 46799: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"tube\")return \"tube:\"+encodeURIComponent(ref.id);\nif(ref.kind===\"mesh-instance\")return \"mesh:\"+encodeURIComponent(ref.id);"));
test("question 46800: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"mesh-instance\")return \"mesh:\"+encodeURIComponent(ref.id);\nif(ref.kind===\"assembly\")return \"project-assembly:\"+encodeURIComponent(ref.id);"));
test("question 46801: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"assembly\")return \"project-assembly:\"+encodeURIComponent(ref.id);\nreturn \"\";"));
test("question 46802: preserves adjacent source contract",()=>has(3,"return \"\";\nfunction directAssembliesForRef(ref){"));
test("question 46803: preserves adjacent source contract",()=>has(3,"function directAssembliesForRef(ref){\nif(!ref||ref.kind===\"source-ref\")return [];"));
test("question 46804: preserves adjacent source contract",()=>has(3,"if(!ref||ref.kind===\"source-ref\")return [];\nreturn assemblies.assembliesContainingMember(project(),ref,{includeAncestors:false});"));
test("question 46805: preserves adjacent source contract",()=>has(3,"return assemblies.assembliesContainingMember(project(),ref,{includeAncestors:false});\nfunction directTubeAssembly(tubeOrId){"));
test("question 46806: preserves adjacent source contract",()=>has(3,"function directTubeAssembly(tubeOrId){\nconst id=String(typeof tubeOrId===\"object\"?tubeOrId?.id:tubeOrId??\"\");"));
test("question 46807: preserves adjacent source contract",()=>has(3,"const id=String(typeof tubeOrId===\"object\"?tubeOrId?.id:tubeOrId??\"\");\nif(!id)return null;"));
test("question 46808: preserves adjacent source contract",()=>has(3,"if(!id)return null;\nreturn directAssembliesForRef({kind:\"tube\",id})[0]??null;"));
test("question 46809: preserves adjacent source contract",()=>has(3,"return directAssembliesForRef({kind:\"tube\",id})[0]??null;\nfunction portWorldPosition(tube,portName){"));
test("question 46810: preserves adjacent source contract",()=>has(3,"function portWorldPosition(tube,portName){\nconst port=tube?.engineering?.ports?.[portName];"));
test("question 46811: preserves adjacent source contract",()=>has(3,"const port=tube?.engineering?.ports?.[portName];\nif(port?.position&&[port.position.x,port.position.y,port.position.z].every(Number.isFinite))return clone(port.position);"));
test("question 46812: preserves adjacent source contract",()=>has(3,"if(port?.position&&[port.position.x,port.position.y,port.position.z].every(Number.isFinite))return clone(port.position);\nif(portName===\"P1\"&&tube?.origin)return clone(tube.origin);"));
test("question 46813: preserves adjacent source contract",()=>has(3,"if(portName===\"P1\"&&tube?.origin)return clone(tube.origin);\nreturn null;"));
test("question 46814: preserves adjacent source contract",()=>has(3,"return null;\nfunction setPortAssemblyConstraint(tube,portName,parent,worldPosition){"));
test("question 46815: preserves adjacent source contract",()=>has(3,"function setPortAssemblyConstraint(tube,portName,parent,worldPosition){\nconst port=tube?.engineering?.ports?.[portName];if(!port)return null;"));
test("question 46816: preserves adjacent source contract",()=>has(3,"const port=tube?.engineering?.ports?.[portName];if(!port)return null;\nif(!parent||!worldPosition){delete port.assembly_constraint;return null;}"));
test("question 46817: preserves adjacent source contract",()=>has(3,"if(!parent||!worldPosition){delete port.assembly_constraint;return null;}\nconst constraint={"));
test("question 46818: preserves adjacent source contract",()=>has(3,"const constraint={\nschema:\"assembly_port_constraint_v1\","));
test("question 46819: preserves adjacent source contract",()=>has(3,"schema:\"assembly_port_constraint_v1\",\nassembly_id:String(parent.id),"));
test("question 46820: preserves adjacent source contract",()=>has(3,"assembly_id:String(parent.id),\nlocal_position_mm:{...assemblies.worldToLocalPoint(parent.frame,worldPosition)}"));
test("question 46821: preserves adjacent source contract",()=>has(3,"local_position_mm:{...assemblies.worldToLocalPoint(parent.frame,worldPosition)}\nport.assembly_constraint=constraint;"));
test("question 46822: preserves adjacent source contract",()=>has(3,"port.assembly_constraint=constraint;\nreturn constraint;"));
test("question 46823: preserves adjacent source contract",()=>has(3,"return constraint;\nfunction syncTubePortConstraints(tubeOrId){"));
test("question 46824: preserves adjacent source contract",()=>has(3,"function syncTubePortConstraints(tubeOrId){\nconst tube=typeof tubeOrId===\"object\"?tubeOrId:tubeById(tubeOrId);"));
test("question 46825: preserves adjacent source contract",()=>has(3,"const tube=typeof tubeOrId===\"object\"?tubeOrId:tubeById(tubeOrId);\nif(!tube?.engineering?.ports)return null;"));
test("question 46826: preserves adjacent source contract",()=>has(3,"if(!tube?.engineering?.ports)return null;\nconst parent=directTubeAssembly(tube);"));
test("question 46827: preserves adjacent source contract",()=>has(3,"const parent=directTubeAssembly(tube);\nconst p1=tube.engineering.ports.P1,p2=tube.engineering.ports.P2;"));
test("question 46828: preserves adjacent source contract",()=>has(3,"const p1=tube.engineering.ports.P1,p2=tube.engineering.ports.P2;\np1.locked=true;"));
test("question 46829: preserves adjacent source contract",()=>has(3,"p1.locked=true;\nconst world=portWorldPosition(tube,\"P1\")??clone(tube.origin??{x:0,y:0,z:0});"));
test("question 46830: preserves adjacent source contract",()=>has(3,"const world=portWorldPosition(tube,\"P1\")??clone(tube.origin??{x:0,y:0,z:0});\np1.position=clone(world);"));
test("question 46831: preserves adjacent source contract",()=>has(3,"p1.position=clone(world);\nsetPortAssemblyConstraint(tube,\"P1\",parent,world);"));
test("question 46832: preserves adjacent source contract",()=>has(3,"setPortAssemblyConstraint(tube,\"P1\",parent,world);\nif(p2.locked===true)setPortAssemblyConstraint(tube,\"P2\",parent,portWorldPosition(tube,\"P2\"));"));
test("question 46833: preserves adjacent source contract",()=>has(3,"if(p2.locked===true)setPortAssemblyConstraint(tube,\"P2\",parent,portWorldPosition(tube,\"P2\"));\nelse delete p2.assembly_constraint;"));
test("question 46834: preserves adjacent source contract",()=>has(3,"else delete p2.assembly_constraint;\nreturn {assembly_id:parent?String(parent.id):null,p1:clone(p1?.assembly_constraint??null),p2:clone(p2?.assembly_constraint??null)};"));
test("question 46835: preserves adjacent source contract",()=>has(3,"return {assembly_id:parent?String(parent.id):null,p1:clone(p1?.assembly_constraint??null),p2:clone(p2?.assembly_constraint??null)};\nfunction captureTubeEndConstraint(tubeOrId){"));
test("question 46836: preserves adjacent source contract",()=>has(3,"function captureTubeEndConstraint(tubeOrId){\nconst tube=typeof tubeOrId===\"object\"?tubeOrId:tubeById(tubeOrId);"));
test("question 46837: preserves adjacent source contract",()=>has(3,"const tube=typeof tubeOrId===\"object\"?tubeOrId:tubeById(tubeOrId);\nconst p2=tube?.engineering?.ports?.P2;"));
test("question 46838: preserves adjacent source contract",()=>has(3,"const p2=tube?.engineering?.ports?.P2;\nif(!tube||p2?.locked!==true||!p2?.position)return null;"));
test("question 46839: preserves adjacent source contract",()=>has(3,"if(!tube||p2?.locked!==true||!p2?.position)return null;\nconst parent=directTubeAssembly(tube);if(!parent)return null;"));
test("question 46840: preserves adjacent source contract",()=>has(3,"const parent=directTubeAssembly(tube);if(!parent)return null;\nconst stored=p2.assembly_constraint;"));
test("question 46841: preserves adjacent source contract",()=>has(3,"const stored=p2.assembly_constraint;\nreturn clone(stored&&String(stored.assembly_id)===String(parent.id)&&stored.local_position_mm"));
test("question 46842: preserves adjacent source contract",()=>has(3,"return clone(stored&&String(stored.assembly_id)===String(parent.id)&&stored.local_position_mm\n:{schema:\"assembly_port_constraint_v1\",assembly_id:String(parent.id),local_position_mm:{...assemblies.worldToLocalPoint(parent.frame,p2.position)}});"));
test("question 46843: preserves adjacent source contract",()=>has(3,":{schema:\"assembly_port_constraint_v1\",assembly_id:String(parent.id),local_position_mm:{...assemblies.worldToLocalPoint(parent.frame,p2.position)}});\nfunction resolveTubeEndConstraintTarget(constraint,tubeOrId=null){"));
test("question 46844: preserves adjacent source contract",()=>has(3,"function resolveTubeEndConstraintTarget(constraint,tubeOrId=null){\nif(!constraint?.assembly_id||!constraint?.local_position_mm)return null;"));
test("question 46845: preserves adjacent source contract",()=>has(3,"if(!constraint?.assembly_id||!constraint?.local_position_mm)return null;\nconst parent=assemblyById(constraint.assembly_id);if(!parent)return null;"));
test("question 46846: preserves adjacent source contract",()=>has(3,"const parent=assemblyById(constraint.assembly_id);if(!parent)return null;\nconst tube=tubeOrId?(typeof tubeOrId===\"object\"?tubeOrId:tubeById(tubeOrId)):null;"));
test("question 46847: preserves adjacent source contract",()=>has(3,"const tube=tubeOrId?(typeof tubeOrId===\"object\"?tubeOrId:tubeById(tubeOrId)):null;\nif(tube){"));
test("question 46848: preserves adjacent source contract",()=>has(3,"if(tube){\nconst directParent=directTubeAssembly(tube);"));
test("question 46849: preserves adjacent source contract",()=>has(3,"const directParent=directTubeAssembly(tube);\nif(!directParent||String(directParent.id)!==String(parent.id))return null;"));
test("question 46850: preserves adjacent source contract",()=>has(3,"if(!directParent||String(directParent.id)!==String(parent.id))return null;\nreturn {"));
test("question 46851: preserves adjacent source contract",()=>has(3,"return {\nspace:\"assembly-local\","));
test("question 46852: preserves adjacent source contract",()=>has(3,"space:\"assembly-local\",\nassembly_id:String(parent.id),"));
test("question 46853: preserves adjacent source contract",()=>has(3,"assembly_id:String(parent.id),\nlocal_position_mm:clone(constraint.local_position_mm),"));
test("question 46854: preserves adjacent source contract",()=>has(3,"local_position_mm:clone(constraint.local_position_mm),\nposition:{...assemblies.localToWorldPoint(parent.frame,constraint.local_position_mm)}"));
test("question 46855: preserves adjacent source contract",()=>has(3,"position:{...assemblies.localToWorldPoint(parent.frame,constraint.local_position_mm)}\nfunction clearTubePortConstraint(tubeOrId,portName=\"P2\"){"));
test("question 46856: preserves adjacent source contract",()=>has(3,"function clearTubePortConstraint(tubeOrId,portName=\"P2\"){\nconst tube=typeof tubeOrId===\"object\"?tubeOrId:tubeById(tubeOrId),port=tube?.engineering?.ports?.[portName];"));
test("question 46857: preserves adjacent source contract",()=>has(3,"const tube=typeof tubeOrId===\"object\"?tubeOrId:tubeById(tubeOrId),port=tube?.engineering?.ports?.[portName];\nif(port)delete port.assembly_constraint;"));
test("question 46858: preserves adjacent source contract",()=>has(3,"if(port)delete port.assembly_constraint;\nreturn !!port;"));
test("question 46859: preserves adjacent source contract",()=>has(3,"return !!port;\nfunction containingAssembliesForEntry(entry){"));
test("question 46860: preserves adjacent source contract",()=>has(3,"function containingAssembliesForEntry(entry){\nconst ref=refFromEntry(entry);if(!ref||ref.kind===\"source-ref\")return [];"));
test("question 46861: preserves adjacent source contract",()=>has(3,"const ref=refFromEntry(entry);if(!ref||ref.kind===\"source-ref\")return [];\nreturn assemblies.assembliesContainingMember(project(),ref,{includeAncestors:true});"));
test("question 46862: preserves adjacent source contract",()=>has(3,"return assemblies.assembliesContainingMember(project(),ref,{includeAncestors:true});\nfunction parentAssemblyForEntry(entry){"));
test("question 46863: preserves adjacent source contract",()=>has(3,"function parentAssemblyForEntry(entry){\nconst direct=containingAssembliesForEntry(entry).filter(parent=>{"));
test("question 46864: preserves adjacent source contract",()=>has(3,"const direct=containingAssembliesForEntry(entry).filter(parent=>{\nconst ref=refFromEntry(entry);"));
test("question 46865: preserves adjacent source contract",()=>has(3,"const ref=refFromEntry(entry);\nreturn (parent.members??[]).some(member=>assemblies.assemblyMemberKey(member.ref)===assemblies.assemblyMemberKey(ref));"));
test("question 46866: preserves adjacent source contract",()=>has(3,"return (parent.members??[]).some(member=>assemblies.assemblyMemberKey(member.ref)===assemblies.assemblyMemberKey(ref));\nreturn direct[0]??null;"));
test("question 46867: preserves adjacent source contract",()=>has(3,"return direct[0]??null;\nfunction activeEditAssembly(){return editPath.length?assemblyById(editPath[editPath.length-1]):null;}"));
test("question 46868: preserves adjacent source contract",()=>has(3,"function activeEditAssembly(){return editPath.length?assemblyById(editPath[editPath.length-1]):null;}\nfunction editing(){return !!activeEditAssembly();}"));
test("question 46869: preserves adjacent source contract",()=>has(3,"function editing(){return !!activeEditAssembly();}\nfunction breadcrumb(){"));
test("question 46870: preserves adjacent source contract",()=>has(3,"function breadcrumb(){\nreturn [\"Project\",...editPath.map(id=>assemblyById(id)?.name??id)].join(\" > \");"));
test("question 46871: preserves adjacent source contract",()=>has(3,"return [\"Project\",...editPath.map(id=>assemblyById(id)?.name??id)].join(\" > \");\nfunction topAssemblyForEntry(entry){"));
test("question 46872: preserves adjacent source contract",()=>has(3,"function topAssemblyForEntry(entry){\nconst list=containingAssembliesForEntry(entry);"));
test("question 46873: preserves adjacent source contract",()=>has(3,"const list=containingAssembliesForEntry(entry);\nreturn list.length?list[list.length-1]:null;"));
test("question 46874: preserves adjacent source contract",()=>has(3,"return list.length?list[list.length-1]:null;\nfunction directMemberEntry(active,entry){"));
test("question 46875: preserves adjacent source contract",()=>has(3,"function directMemberEntry(active,entry){\nif(!active||!entry)return null;"));
test("question 46876: preserves adjacent source contract",()=>has(3,"if(!active||!entry)return null;\nif(entry.kind===\"project-assembly\"&&String(entry.assemblyId)===String(active.id))return entry;"));
test("question 46877: preserves adjacent source contract",()=>has(3,"if(entry.kind===\"project-assembly\"&&String(entry.assemblyId)===String(active.id))return entry;\nconst ref=refFromEntry(entry);"));
test("question 46878: preserves adjacent source contract",()=>has(3,"const ref=refFromEntry(entry);\nif(!ref||ref.kind===\"source-ref\")return null;"));
test("question 46879: preserves adjacent source contract",()=>has(3,"if(!ref||ref.kind===\"source-ref\")return null;\nconst key=assemblies.assemblyMemberKey(ref);"));
test("question 46880: preserves adjacent source contract",()=>has(3,"const key=assemblies.assemblyMemberKey(ref);\nfor(const member of active.members??[]){"));
test("question 46881: preserves adjacent source contract",()=>has(3,"for(const member of active.members??[]){\nif(assemblies.assemblyMemberKey(member.ref)===key)return entry;"));
test("question 46882: preserves adjacent source contract",()=>has(3,"if(assemblies.assemblyMemberKey(member.ref)===key)return entry;\nif(member.ref.kind!==\"assembly\")continue;"));
test("question 46883: preserves adjacent source contract",()=>has(3,"if(member.ref.kind!==\"assembly\")continue;\nif(ref.kind===\"assembly\"&&String(ref.id)===String(member.ref.id))return {kind:\"project-assembly\",assemblyId:String(member.ref.id)};"));
test("question 46884: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"assembly\"&&String(ref.id)===String(member.ref.id))return {kind:\"project-assembly\",assemblyId:String(member.ref.id)};\nconst nested=assemblies.assembliesContainingMember(project(),ref,{includeAncestors:true});"));
test("question 46885: preserves adjacent source contract",()=>has(3,"const nested=assemblies.assembliesContainingMember(project(),ref,{includeAncestors:true});\nif(nested.some(item=>String(item.id)===String(member.ref.id))){"));
test("question 46886: preserves adjacent source contract",()=>has(3,"if(nested.some(item=>String(item.id)===String(member.ref.id))){\nreturn {kind:\"project-assembly\",assemblyId:String(member.ref.id)};"));
test("question 46887: preserves adjacent source contract",()=>has(3,"return {kind:\"project-assembly\",assemblyId:String(member.ref.id)};\nreturn null;"));
test("question 46888: preserves adjacent source contract",()=>has(3,"return null;\nfunction entryKey(entry,fallback=\"\"){"));
test("question 46889: preserves adjacent source contract",()=>has(3,"function entryKey(entry,fallback=\"\"){\nif(entry?.kind===\"project-assembly\")return \"project-assembly:\"+encodeURIComponent(entry.assemblyId);"));
test("question 46890: preserves adjacent source contract",()=>has(3,"if(entry?.kind===\"project-assembly\")return \"project-assembly:\"+encodeURIComponent(entry.assemblyId);\nif(entry?.kind===\"tube\")return \"tube:\"+encodeURIComponent(entry.tubeId);"));
test("question 46891: preserves adjacent source contract",()=>has(3,"if(entry?.kind===\"tube\")return \"tube:\"+encodeURIComponent(entry.tubeId);\nif(entry?.kind===\"mesh-instance\")return \"mesh:\"+encodeURIComponent(entry.instanceId);"));
test("question 46892: preserves adjacent source contract",()=>has(3,"if(entry?.kind===\"mesh-instance\")return \"mesh:\"+encodeURIComponent(entry.instanceId);\nreturn fallback;"));
test("question 46893: preserves adjacent source contract",()=>has(3,"return fallback;\nfunction resolveInteraction(entry,originalKey=\"\"){"));
test("question 46894: preserves adjacent source contract",()=>has(3,"function resolveInteraction(entry,originalKey=\"\"){\nif(!entry)return {handled:false,key:originalKey,entry};"));
test("question 46895: preserves adjacent source contract",()=>has(3,"if(!entry)return {handled:false,key:originalKey,entry};\nconst active=activeEditAssembly();"));
test("question 46896: preserves adjacent source contract",()=>has(3,"const active=activeEditAssembly();\nif(!active){"));
test("question 46897: preserves adjacent source contract",()=>has(3,"if(!active){\nconst top=entry.kind===\"project-assembly\"?assemblyById(entry.assemblyId):topAssemblyForEntry(entry);"));
test("question 46898: preserves adjacent source contract",()=>has(3,"const top=entry.kind===\"project-assembly\"?assemblyById(entry.assemblyId):topAssemblyForEntry(entry);\nif(top)return {handled:true,key:\"project-assembly:\"+encodeURIComponent(top.id),entry:{kind:\"project-assembly\",assemblyId:String(top.id)}};"));
test("question 46899: preserves adjacent source contract",()=>has(3,"if(top)return {handled:true,key:\"project-assembly:\"+encodeURIComponent(top.id),entry:{kind:\"project-assembly\",assemblyId:String(top.id)}};\nreturn {handled:false,key:originalKey,entry};"));
test("question 46900: preserves adjacent source contract",()=>has(3,"return {handled:false,key:originalKey,entry};\nconst direct=directMemberEntry(active,entry);"));
test("question 46901: preserves adjacent source contract",()=>has(3,"const direct=directMemberEntry(active,entry);\nif(!direct)return {handled:true,blocked:true,key:null,entry:null};"));
test("question 46902: preserves adjacent source contract",()=>has(3,"if(!direct)return {handled:true,blocked:true,key:null,entry:null};\nreturn {handled:true,key:entryKey(direct,originalKey),entry:direct};"));
test("question 46903: preserves adjacent source contract",()=>has(3,"return {handled:true,key:entryKey(direct,originalKey),entry:direct};\nfunction assemblyForEditEntry(entry){"));
test("question 46904: preserves adjacent source contract",()=>has(3,"function assemblyForEditEntry(entry){\nif(!entry)return null;"));
test("question 46905: preserves adjacent source contract",()=>has(3,"if(!entry)return null;\nif(entry.kind===\"project-assembly\")return assemblyById(entry.assemblyId);"));
test("question 46906: preserves adjacent source contract",()=>has(3,"if(entry.kind===\"project-assembly\")return assemblyById(entry.assemblyId);\nconst active=activeEditAssembly();"));
test("question 46907: preserves adjacent source contract",()=>has(3,"const active=activeEditAssembly();\nif(active){"));
test("question 46908: preserves adjacent source contract",()=>has(3,"if(active){\nconst direct=directMemberEntry(active,entry);"));
test("question 46909: preserves adjacent source contract",()=>has(3,"const direct=directMemberEntry(active,entry);\nreturn direct?.kind===\"project-assembly\"?assemblyById(direct.assemblyId):null;"));
test("question 46910: preserves adjacent source contract",()=>has(3,"return direct?.kind===\"project-assembly\"?assemblyById(direct.assemblyId):null;\nreturn topAssemblyForEntry(entry);"));
test("question 46911: preserves adjacent source contract",()=>has(3,"return topAssemblyForEntry(entry);\nfunction enterEdit(assemblyId){"));
test("question 46912: preserves adjacent source contract",()=>has(3,"function enterEdit(assemblyId){\nconst target=assemblyById(assemblyId);if(!target)return false;"));
test("question 46913: preserves adjacent source contract",()=>has(3,"const target=assemblyById(assemblyId);if(!target)return false;\nconst active=activeEditAssembly();"));
test("question 46914: preserves adjacent source contract",()=>has(3,"if(active){\nconst allowed=(active.members??[]).some(member=>member.ref.kind===\"assembly\"&&String(member.ref.id)===String(target.id));"));
test("question 46915: preserves adjacent source contract",()=>has(3,"const allowed=(active.members??[]).some(member=>member.ref.kind===\"assembly\"&&String(member.ref.id)===String(target.id));\nif(!allowed){toast(\"Вложенная Assembly не принадлежит текущему уровню\");return false;}"));
test("question 46916: preserves adjacent source contract",()=>has(3,"if(!allowed){toast(\"Вложенная Assembly не принадлежит текущему уровню\");return false;}\neditPath.push(String(target.id));"));
test("question 46917: preserves adjacent source contract",()=>has(3,"editPath.push(String(target.id));\nconst parents=assemblies.assembliesContainingMember(project(),{kind:\"assembly\",id:target.id},{includeAncestors:true});"));
test("question 46918: preserves adjacent source contract",()=>has(3,"const parents=assemblies.assembliesContainingMember(project(),{kind:\"assembly\",id:target.id},{includeAncestors:true});\nconst chain=[...parents].reverse().map(item=>String(item.id));"));
test("question 46919: preserves adjacent source contract",()=>has(3,"const chain=[...parents].reverse().map(item=>String(item.id));\nchain.push(String(target.id));"));
test("question 46920: preserves adjacent source contract",()=>has(3,"chain.push(String(target.id));\neditPath.length=0;"));
test("question 46921: preserves adjacent source contract",()=>has(3,"editPath.length=0;\nfor(let index=0;index<chain.length;index++){"));
test("question 46922: preserves adjacent source contract",()=>has(3,"for(let index=0;index<chain.length;index++){\nconst id=chain[index],current=assemblyById(id);if(!current)continue;"));
test("question 46923: preserves adjacent source contract",()=>has(3,"const id=chain[index],current=assemblyById(id);if(!current)continue;\nif(index>0){"));
test("question 46924: preserves adjacent source contract",()=>has(3,"if(index>0){\nconst parent=assemblyById(chain[index-1]);"));
test("question 46925: preserves adjacent source contract",()=>has(3,"const parent=assemblyById(chain[index-1]);\nconst direct=(parent?.members??[]).some(member=>member.ref.kind===\"assembly\"&&String(member.ref.id)===id);"));
test("question 46926: preserves adjacent source contract",()=>has(3,"const direct=(parent?.members??[]).some(member=>member.ref.kind===\"assembly\"&&String(member.ref.id)===id);\nif(!direct)continue;"));
test("question 46927: preserves adjacent source contract",()=>has(3,"if(!direct)continue;\neditPath.push(id);"));
test("question 46928: preserves adjacent source contract",()=>has(3,"editPath.push(id);\nctx()?.clearSelection?.();"));
test("question 46929: preserves adjacent source contract",()=>has(3,"ctx()?.clearSelection?.();\napplyEditContext();renderTree();renderPanel();renderBreadcrumb();"));
test("question 46930: preserves adjacent source contract",()=>has(3,"applyEditContext();renderTree();renderPanel();renderBreadcrumb();\ntry{window.dispatchEvent(new CustomEvent(\"tubebender-assembly-edit-change\",{detail:{path:[...editPath],breadcrumb:breadcrumb()}}));}catch{}"));
test("question 46931: preserves adjacent source contract",()=>has(3,"try{window.dispatchEvent(new CustomEvent(\"tubebender-assembly-edit-change\",{detail:{path:[...editPath],breadcrumb:breadcrumb()}}));}catch{}\nreturn editPath.at(-1)===String(target.id);"));
test("question 46932: preserves adjacent source contract",()=>has(3,"return editPath.at(-1)===String(target.id);\nfunction exitEdit(){"));
test("question 46933: preserves adjacent source contract",()=>has(3,"function exitEdit(){\nif(!editPath.length)return false;"));
test("question 46934: preserves adjacent source contract",()=>has(3,"if(!editPath.length)return false;\neditPath.pop();ctx()?.clearSelection?.();"));
test("question 46935: preserves adjacent source contract",()=>has(3,"editPath.pop();ctx()?.clearSelection?.();\napplyEditContext();renderTree();renderPanel();renderBreadcrumb();"));
test("question 46936: preserves adjacent source contract",()=>has(3,"try{window.dispatchEvent(new CustomEvent(\"tubebender-assembly-edit-change\",{detail:{path:[...editPath],breadcrumb:breadcrumb()}}));}catch{}\nreturn true;"));
test("question 46937: preserves adjacent source contract",()=>has(3,"return true;\nfunction exitAllEdit(){"));
test("question 46938: preserves adjacent source contract",()=>has(3,"function exitAllEdit(){\nif(!editPath.length)return false;"));
test("question 46939: preserves adjacent source contract",()=>has(3,"if(!editPath.length)return false;\neditPath.length=0;ctx()?.clearSelection?.();"));
test("question 46940: preserves adjacent source contract",()=>has(3,"editPath.length=0;ctx()?.clearSelection?.();\napplyEditContext();renderTree();renderPanel();renderBreadcrumb();"));
test("question 46941: preserves adjacent source contract",()=>has(3,"applyEditContext();renderTree();renderPanel();renderBreadcrumb();\ntry{window.dispatchEvent(new CustomEvent(\"tubebender-assembly-edit-change\",{detail:{path:[],breadcrumb:breadcrumb()}}));}catch{}"));
test("question 46942: preserves adjacent source contract",()=>has(3,"try{window.dispatchEvent(new CustomEvent(\"tubebender-assembly-edit-change\",{detail:{path:[],breadcrumb:breadcrumb()}}));}catch{}\nreturn true;"));
test("question 46943: preserves adjacent source contract",()=>has(3,"return true;\nfunction objectForRef(ref){"));
test("question 46944: preserves adjacent source contract",()=>has(3,"function objectForRef(ref){\nif(ref.kind===\"tube\")return tubeById(ref.id);"));
test("question 46945: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"tube\")return tubeById(ref.id);\nif(ref.kind===\"mesh-instance\")return meshById(ref.id);"));
test("question 46946: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"mesh-instance\")return meshById(ref.id);\nif(ref.kind===\"construction\")return (project()?.construction_geometry??[]).find(x=>String(x?.id)===String(ref.id))??null;"));
test("question 46947: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"construction\")return (project()?.construction_geometry??[]).find(x=>String(x?.id)===String(ref.id))??null;\nif(ref.kind===\"dimension\")return (project()?.engineering_dimensions??[]).find(x=>String(x?.id)===String(ref.id))??null;"));
test("question 46948: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"dimension\")return (project()?.engineering_dimensions??[]).find(x=>String(x?.id)===String(ref.id))??null;\nif(ref.kind===\"assembly\")return assemblyById(ref.id);"));
test("question 46949: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"assembly\")return assemblyById(ref.id);\nreturn null;"));
test("question 46950: preserves adjacent source contract",()=>has(3,"return null;\nfunction refForObjectId(objectId){"));
test("question 46951: preserves adjacent source contract",()=>has(3,"function refForObjectId(objectId){\nconst id=String(objectId??\"\");"));
test("question 46952: preserves adjacent source contract",()=>has(3,"const id=String(objectId??\"\");\nif(!id)return null;"));
test("question 46953: preserves adjacent source contract",()=>has(3,"if(!id)return null;\nif(tubeById(id))return {kind:\"tube\",id};"));
test("question 46954: preserves adjacent source contract",()=>has(3,"if(tubeById(id))return {kind:\"tube\",id};\nif(meshById(id))return {kind:\"mesh-instance\",id};"));
test("question 46955: preserves adjacent source contract",()=>has(3,"if(meshById(id))return {kind:\"mesh-instance\",id};\nif((project()?.construction_geometry??[]).some(item=>String(item?.id)===id))return {kind:\"construction\",id};"));
test("question 46956: preserves adjacent source contract",()=>has(3,"if((project()?.construction_geometry??[]).some(item=>String(item?.id)===id))return {kind:\"construction\",id};\nif((project()?.engineering_dimensions??[]).some(item=>String(item?.id)===id))return {kind:\"dimension\",id};"));
test("question 46957: preserves adjacent source contract",()=>has(3,"if((project()?.engineering_dimensions??[]).some(item=>String(item?.id)===id))return {kind:\"dimension\",id};\nif(assemblyById(id))return {kind:\"assembly\",id};"));
test("question 46958: preserves adjacent source contract",()=>has(3,"if(assemblyById(id))return {kind:\"assembly\",id};\nreturn null;"));
test("question 46959: preserves adjacent source contract",()=>has(3,"return null;\nfunction contextForRef(ref,worldPoint=null){"));
test("question 46960: preserves adjacent source contract",()=>has(3,"function contextForRef(ref,worldPoint=null){\nif(!ref)return assemblies.crossAssemblyMetadata([]).contexts?.[0]??{"));
test("question 46961: preserves adjacent source contract",()=>has(3,"if(!ref)return assemblies.crossAssemblyMetadata([]).contexts?.[0]??{\nspace:\"project\",assembly_id:null,assembly_path:[],local_point_mm:worldPoint?clone(worldPoint):null,world_point_mm:worldPoint?clone(worldPoint):null"));
test("question 46962: preserves adjacent source contract",()=>has(3,"space:\"project\",assembly_id:null,assembly_path:[],local_point_mm:worldPoint?clone(worldPoint):null,world_point_mm:worldPoint?clone(worldPoint):null\nreturn assemblies.assemblyContextForMember(project(),ref,{world_point:worldPoint});"));
test("question 46963: preserves adjacent source contract",()=>has(3,"return assemblies.assemblyContextForMember(project(),ref,{world_point:worldPoint});\nfunction contextForObjectId(objectId,worldPoint=null){"));
test("question 46964: preserves adjacent source contract",()=>has(3,"function contextForObjectId(objectId,worldPoint=null){\nconst ref=refForObjectId(objectId);"));
test("question 46965: preserves adjacent source contract",()=>has(3,"const ref=refForObjectId(objectId);\nif(ref)return contextForRef(ref,worldPoint);"));
test("question 46966: preserves adjacent source contract",()=>has(3,"if(ref)return contextForRef(ref,worldPoint);\nconst point=worldPoint&&[worldPoint.x,worldPoint.y,worldPoint.z].every(Number.isFinite)?clone(worldPoint):null;"));
test("question 46967: preserves adjacent source contract",()=>has(3,"const point=worldPoint&&[worldPoint.x,worldPoint.y,worldPoint.z].every(Number.isFinite)?clone(worldPoint):null;\nreturn {space:\"project\",assembly_id:null,assembly_path:[],local_point_mm:point,world_point_mm:point};"));
test("question 46968: preserves adjacent source contract",()=>has(3,"return {space:\"project\",assembly_id:null,assembly_path:[],local_point_mm:point,world_point_mm:point};\nfunction crossAssemblyForContexts(contexts){return assemblies.crossAssemblyMetadata(contexts);}"));
test("question 46969: preserves adjacent source contract",()=>has(3,"function crossAssemblyForContexts(contexts){return assemblies.crossAssemblyMetadata(contexts);}\nfunction decorateAssociativeReferences(references=[]){"));
test("question 46970: preserves adjacent source contract",()=>has(3,"function decorateAssociativeReferences(references=[]){\nconst refs=(references??[]).map(ref=>{"));
test("question 46971: preserves adjacent source contract",()=>has(3,"const refs=(references??[]).map(ref=>{\nconst point=ref?.point??ref?.world_point_mm??null;"));
test("question 46972: preserves adjacent source contract",()=>has(3,"const point=ref?.point??ref?.world_point_mm??null;\nconst context=ref?.assembly_context??contextForObjectId(ref?.object_id,point);"));
test("question 46973: preserves adjacent source contract",()=>has(3,"const context=ref?.assembly_context??contextForObjectId(ref?.object_id,point);\nreturn {...clone(ref),assembly_context:clone(context)};"));
test("question 46974: preserves adjacent source contract",()=>has(3,"return {...clone(ref),assembly_context:clone(context)};\nconst relation=assemblies.crossAssemblyMetadata(refs.map(ref=>ref.assembly_context));"));
test("question 46975: preserves adjacent source contract",()=>has(3,"const relation=assemblies.crossAssemblyMetadata(refs.map(ref=>ref.assembly_context));\nreturn {references:refs,cross_assembly:relation};"));
test("question 46976: preserves adjacent source contract",()=>has(3,"return {references:refs,cross_assembly:relation};\nfunction registerCrossAssemblyLink({id=null,type=\"Associative\",references=[],payload={}}={}){"));
test("question 46977: preserves adjacent source contract",()=>has(3,"function registerCrossAssemblyLink({id=null,type=\"Associative\",references=[],payload={}}={}){\nconst p=project();if(!p)throw new Error(\"No active project\");"));
test("question 46978: preserves adjacent source contract",()=>has(3,"const p=project();if(!p)throw new Error(\"No active project\");\nconst decorated=decorateAssociativeReferences(references);"));
test("question 46979: preserves adjacent source contract",()=>has(3,"const decorated=decorateAssociativeReferences(references);\nconst link={"));
test("question 46980: preserves adjacent source contract",()=>has(3,"const link={\nid:String(id??(\"cross-link-\"+(globalThis.crypto?.randomUUID?.()??Date.now().toString(36)))),"));
test("question 46981: preserves adjacent source contract",()=>has(3,"id:String(id??(\"cross-link-\"+(globalThis.crypto?.randomUUID?.()??Date.now().toString(36)))),\ntype:String(type),"));
test("question 46982: preserves adjacent source contract",()=>has(3,"type:String(type),\nreferences:decorated.references,"));
test("question 46983: preserves adjacent source contract",()=>has(3,"references:decorated.references,\ncross_assembly:decorated.cross_assembly,"));
test("question 46984: preserves adjacent source contract",()=>has(3,"cross_assembly:decorated.cross_assembly,\npayload:clone(payload),"));
test("question 46985: preserves adjacent source contract",()=>has(3,"payload:clone(payload),\nstatus:\"Valid\""));
test("question 46986: preserves adjacent source contract",()=>has(3,"status:\"Valid\"\nconst mutate=()=>{"));
test("question 46987: preserves adjacent source contract",()=>has(3,"const mutate=()=>{\nif(!Array.isArray(p.cross_assembly_links))p.cross_assembly_links=[];"));
test("question 46988: preserves adjacent source contract",()=>has(3,"if(!Array.isArray(p.cross_assembly_links))p.cross_assembly_links=[];\nconst index=p.cross_assembly_links.findIndex(item=>String(item?.id)===String(link.id));"));
test("question 46989: preserves adjacent source contract",()=>has(3,"const index=p.cross_assembly_links.findIndex(item=>String(item?.id)===String(link.id));\nif(index>=0)p.cross_assembly_links[index]=clone(link);else p.cross_assembly_links.push(clone(link));"));
test("question 46990: preserves adjacent source contract",()=>has(3,"if(index>=0)p.cross_assembly_links[index]=clone(link);else p.cross_assembly_links.push(clone(link));\nreturn true;"));
test("question 46991: preserves adjacent source contract",()=>has(3,"return true;\nconst ok=eng()?.modelCommand?eng().modelCommand(\"Сохранить межсборочную связь\",mutate):mutate();"));
test("question 46992: preserves adjacent source contract",()=>has(3,"const ok=eng()?.modelCommand?eng().modelCommand(\"Сохранить межсборочную связь\",mutate):mutate();\nif(ok===false)return false;"));
test("question 46993: preserves adjacent source contract",()=>has(3,"if(ok===false)return false;\ntry{eng()?.save?.();}catch{}"));
test("question 46994: preserves adjacent source contract",()=>has(3,"try{eng()?.save?.();}catch{}\nreturn clone(link);"));
test("question 46995: preserves adjacent source contract",()=>has(3,"return clone(link);\nfunction decorateConstructionGeometry(object,references=[]){"));
test("question 46996: preserves adjacent source contract",()=>has(3,"function decorateConstructionGeometry(object,references=[]){\nif(!object||typeof object!==\"object\")throw new TypeError(\"Construction object is required\");"));
test("question 46997: preserves adjacent source contract",()=>has(3,"if(!object||typeof object!==\"object\")throw new TypeError(\"Construction object is required\");\nconst decorated=decorateAssociativeReferences(references);"));
test("question 46998: preserves adjacent source contract",()=>has(3,"const decorated=decorateAssociativeReferences(references);\nobject.associative_references=decorated.references.map(clone);"));
test("question 46999: preserves adjacent source contract",()=>has(3,"object.associative_references=decorated.references.map(clone);\nobject.cross_assembly=clone(decorated.cross_assembly);"));
test("question 47000: preserves adjacent source contract",()=>has(3,"object.cross_assembly=clone(decorated.cross_assembly);\nreturn object;"));
test("question 47001: preserves adjacent source contract",()=>has(3,"return object;\nfunction q78ReferenceWorldPoint(ref){"));
test("question 47002: preserves adjacent source contract",()=>has(3,"function q78ReferenceWorldPoint(ref){\nconst context=ref?.assembly_context??null;"));
test("question 47003: preserves adjacent source contract",()=>has(3,"const context=ref?.assembly_context??null;\nif(context?.assembly_id&&context?.local_point_mm){"));
test("question 47004: preserves adjacent source contract",()=>has(3,"if(context?.assembly_id&&context?.local_point_mm){\nconst a=assemblyById(context.assembly_id);"));
test("question 47005: preserves adjacent source contract",()=>has(3,"const a=assemblyById(context.assembly_id);\nif(a)return assemblies.localToWorldPoint(a.frame,context.local_point_mm);"));
test("question 47006: preserves adjacent source contract",()=>has(3,"if(a)return assemblies.localToWorldPoint(a.frame,context.local_point_mm);\nconst objectId=String(ref?.object_id??\"\");"));
test("question 47007: preserves adjacent source contract",()=>has(3,"const objectId=String(ref?.object_id??\"\");\nconst tube=tubeById(objectId);"));
test("question 47008: preserves adjacent source contract",()=>has(3,"const tube=tubeById(objectId);\nif(tube){"));
test("question 47009: preserves adjacent source contract",()=>has(3,"if(tube){\nconst sub=String(ref?.subentity_id??\"\");"));
test("question 47010: preserves adjacent source contract",()=>has(3,"const sub=String(ref?.subentity_id??\"\");\nif(sub===\"P1\")return clone(tube?.engineering?.ports?.P1?.position??tube.origin??null);"));
test("question 47011: preserves adjacent source contract",()=>has(3,"if(sub===\"P1\")return clone(tube?.engineering?.ports?.P1?.position??tube.origin??null);\nif(sub===\"P2\")return clone(tube?.engineering?.ports?.P2?.position??null);"));
test("question 47012: preserves adjacent source contract",()=>has(3,"if(sub===\"P2\")return clone(tube?.engineering?.ports?.P2?.position??null);\nif(tube.origin)return clone(tube.origin);"));
test("question 47013: preserves adjacent source contract",()=>has(3,"if(tube.origin)return clone(tube.origin);\nconst mesh=meshById(objectId);"));
test("question 47014: preserves adjacent source contract",()=>has(3,"const mesh=meshById(objectId);\nif(mesh?.transform?.position_mm)return clone(mesh.transform.position_mm);"));
test("question 47015: preserves adjacent source contract",()=>has(3,"if(mesh?.transform?.position_mm)return clone(mesh.transform.position_mm);\nconst world=context?.world_point_mm??ref?.world_point_mm??ref?.point??null;"));
test("question 47016: preserves adjacent source contract",()=>has(3,"const world=context?.world_point_mm??ref?.world_point_mm??ref?.point??null;\nreturn world&&[world.x,world.y,world.z].every(Number.isFinite)?clone(world):null;"));
test("question 47017: preserves adjacent source contract",()=>has(3,"return world&&[world.x,world.y,world.z].every(Number.isFinite)?clone(world):null;\nfunction q78Distance(a,b){"));
test("question 47018: preserves adjacent source contract",()=>has(3,"function q78Distance(a,b){\nreturn Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z);"));
test("question 47019: preserves adjacent source contract",()=>has(3,"return Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z);\nfunction q78Angle(a,b,c){"));
test("question 47020: preserves adjacent source contract",()=>has(3,"function q78Angle(a,b,c){\nconst u={x:a.x-b.x,y:a.y-b.y,z:a.z-b.z},v={x:c.x-b.x,y:c.y-b.y,z:c.z-b.z};"));
test("question 47021: preserves adjacent source contract",()=>has(3,"const u={x:a.x-b.x,y:a.y-b.y,z:a.z-b.z},v={x:c.x-b.x,y:c.y-b.y,z:c.z-b.z};\nconst lu=Math.hypot(u.x,u.y,u.z),lv=Math.hypot(v.x,v.y,v.z);"));
test("question 47022: preserves adjacent source contract",()=>has(3,"const lu=Math.hypot(u.x,u.y,u.z),lv=Math.hypot(v.x,v.y,v.z);\nif(!(lu>1e-12&&lv>1e-12))return null;"));
test("question 47023: preserves adjacent source contract",()=>has(3,"if(!(lu>1e-12&&lv>1e-12))return null;\nconst cos=Math.max(-1,Math.min(1,(u.x*v.x+u.y*v.y+u.z*v.z)/(lu*lv)));"));
test("question 47024: preserves adjacent source contract",()=>has(3,"const cos=Math.max(-1,Math.min(1,(u.x*v.x+u.y*v.y+u.z*v.z)/(lu*lv)));\nreturn Math.acos(cos)*180/Math.PI;"));
test("question 47025: preserves adjacent source contract",()=>has(3,"return Math.acos(cos)*180/Math.PI;\nfunction q78Measure(kind,references=[]){"));
test("question 47026: preserves adjacent source contract",()=>has(3,"function q78Measure(kind,references=[]){\nconst points=references.map(q78ReferenceWorldPoint);"));
test("question 47027: preserves adjacent source contract",()=>has(3,"const points=references.map(q78ReferenceWorldPoint);\nconst text=String(kind??\"\").toLowerCase();"));
test("question 47028: preserves adjacent source contract",()=>has(3,"const text=String(kind??\"\").toLowerCase();\nif(points.length>=2&&points[0]&&points[1]&&(text.includes(\"distance\")||text.includes(\"length\")||text.includes(\"coincident\")||text.includes(\"point-point\"))){"));
test("question 47029: preserves adjacent source contract",()=>has(3,"if(points.length>=2&&points[0]&&points[1]&&(text.includes(\"distance\")||text.includes(\"length\")||text.includes(\"coincident\")||text.includes(\"point-point\"))){\nreturn q78Distance(points[0],points[1]);"));
test("question 47030: preserves adjacent source contract",()=>has(3,"return q78Distance(points[0],points[1]);\nif(points.length>=3&&points[0]&&points[1]&&points[2]&&text.includes(\"angle\")){"));
test("question 47031: preserves adjacent source contract",()=>has(3,"if(points.length>=3&&points[0]&&points[1]&&points[2]&&text.includes(\"angle\")){\nreturn q78Angle(points[0],points[1],points[2]);"));
test("question 47032: preserves adjacent source contract",()=>has(3,"return q78Angle(points[0],points[1],points[2]);\nreturn null;"));
test("question 47033: preserves adjacent source contract",()=>has(3,"return null;\nfunction q78UpdateReferenceContexts(references=[]){"));
test("question 47034: preserves adjacent source contract",()=>has(3,"function q78UpdateReferenceContexts(references=[]){\nfor(const ref of references??[]){"));
test("question 47035: preserves adjacent source contract",()=>has(3,"for(const ref of references??[]){\nconst point=q78ReferenceWorldPoint(ref);"));
test("question 47036: preserves adjacent source contract",()=>has(3,"const point=q78ReferenceWorldPoint(ref);\nif(point&&ref?.assembly_context){"));
test("question 47037: preserves adjacent source contract",()=>has(3,"if(point&&ref?.assembly_context){\nref.assembly_context.world_point_mm=clone(point);"));
test("question 47038: preserves adjacent source contract",()=>has(3,"ref.assembly_context.world_point_mm=clone(point);\nif(point&&Object.prototype.hasOwnProperty.call(ref??{},\"world_point_mm\"))ref.world_point_mm=clone(point);"));
test("question 47039: preserves adjacent source contract",()=>has(3,"if(point&&Object.prototype.hasOwnProperty.call(ref??{},\"world_point_mm\"))ref.world_point_mm=clone(point);\nif(point&&Object.prototype.hasOwnProperty.call(ref??{},\"point\"))ref.point=clone(point);"));
test("question 47040: preserves adjacent source contract",()=>has(3,"if(point&&Object.prototype.hasOwnProperty.call(ref??{},\"point\"))ref.point=clone(point);\nfunction q78RelationAssemblyIds(item){"));
test("question 47041: preserves adjacent source contract",()=>has(3,"function q78RelationAssemblyIds(item){\nconst ids=item?.cross_assembly?.assembly_ids??item?.cross_assembly?.contexts?.map(x=>x?.assembly_id)??[];"));
test("question 47042: preserves adjacent source contract",()=>has(3,"const ids=item?.cross_assembly?.assembly_ids??item?.cross_assembly?.contexts?.map(x=>x?.assembly_id)??[];\nreturn new Set((ids??[]).map(String).filter(Boolean));"));
test("question 47043: preserves adjacent source contract",()=>has(3,"return new Set((ids??[]).map(String).filter(Boolean));\nfunction q78MovedAssemblyIds(rootIds=[]){"));
test("question 47044: preserves adjacent source contract",()=>has(3,"function q78MovedAssemblyIds(rootIds=[]){\nconst ids=new Set();"));
test("question 47045: preserves adjacent source contract",()=>has(3,"const ids=new Set();\nfor(const raw of rootIds){"));
test("question 47046: preserves adjacent source contract",()=>has(3,"for(const raw of rootIds){\nconst id=String(raw);ids.add(id);"));
test("question 47047: preserves adjacent source contract",()=>has(3,"const id=String(raw);ids.add(id);\nfor(const child of assemblies.assemblyDescendantIds(project(),id)??[])ids.add(String(child));"));
test("question 47048: preserves adjacent source contract",()=>has(3,"for(const child of assemblies.assemblyDescendantIds(project(),id)??[])ids.add(String(child));\nreturn ids;"));
test("question 47049: preserves adjacent source contract",()=>has(3,"return ids;\nfunction q78Relevant(item,movedIds){"));
test("question 47050: preserves adjacent source contract",()=>has(3,"function q78Relevant(item,movedIds){\nconst relation=q78RelationAssemblyIds(item);"));
test("question 47051: preserves adjacent source contract",()=>has(3,"const relation=q78RelationAssemblyIds(item);\nif(!relation.size)return false;"));
test("question 47052: preserves adjacent source contract",()=>has(3,"if(!relation.size)return false;\nlet touches=false,outside=false;"));
test("question 47053: preserves adjacent source contract",()=>has(3,"let touches=false,outside=false;\nfor(const id of relation){if(movedIds.has(id))touches=true;else outside=true;}"));
test("question 47054: preserves adjacent source contract",()=>has(3,"for(const id of relation){if(movedIds.has(id))touches=true;else outside=true;}\nreturn touches&&outside;"));
test("question 47055: preserves adjacent source contract",()=>has(3,"return touches&&outside;\nfunction q78ConstraintSpec(item){"));
test("question 47056: preserves adjacent source contract",()=>has(3,"function q78ConstraintSpec(item){\nconst payload=item?.payload??{};"));
test("question 47057: preserves adjacent source contract",()=>has(3,"const payload=item?.payload??{};\nconst type=String(item?.type??item?.kind??payload?.type??payload?.kind??payload?.constraint_kind??\"\");"));
test("question 47058: preserves adjacent source contract",()=>has(3,"const type=String(item?.type??item?.kind??payload?.type??payload?.kind??payload?.constraint_kind??\"\");\nconst lower=type.toLowerCase();"));
test("question 47059: preserves adjacent source contract",()=>has(3,"const lower=type.toLowerCase();\nconst driving=item?.mode===\"Driving\"||payload?.mode===\"Driving\"||payload?.driving===true||lower.includes(\"constraint\")||lower.includes(\"coincident\")||lower.includes(\"driving\");"));
test("question 47060: preserves adjacent source contract",()=>has(3,"const driving=item?.mode===\"Driving\"||payload?.mode===\"Driving\"||payload?.driving===true||lower.includes(\"constraint\")||lower.includes(\"coincident\")||lower.includes(\"driving\");\nconst targetRaw=item?.target_value??payload?.target_value??payload?.target_value_mm??payload?.expected_distance_mm??payload?.distance_mm;"));
test("question 47061: preserves adjacent source contract",()=>has(3,"const targetRaw=item?.target_value??payload?.target_value??payload?.target_value_mm??payload?.expected_distance_mm??payload?.distance_mm;\nconst target=lower.includes(\"coincident\")?0:Number(targetRaw);"));
test("question 47062: preserves adjacent source contract",()=>has(3,"const target=lower.includes(\"coincident\")?0:Number(targetRaw);\nconst angle=lower.includes(\"angle\");"));
test("question 47063: preserves adjacent source contract",()=>has(3,"const angle=lower.includes(\"angle\");\nconst toleranceRaw=angle?(payload?.tolerance_deg??item?.tolerance_deg):(payload?.tolerance_mm??item?.tolerance_mm);"));
test("question 47064: preserves adjacent source contract",()=>has(3,"const toleranceRaw=angle?(payload?.tolerance_deg??item?.tolerance_deg):(payload?.tolerance_mm??item?.tolerance_mm);\nconst tolerance=Number.isFinite(Number(toleranceRaw))?Math.max(0,Number(toleranceRaw)):(angle?1e-6:1e-6);"));
test("question 47065: preserves adjacent source contract",()=>has(3,"const tolerance=Number.isFinite(Number(toleranceRaw))?Math.max(0,Number(toleranceRaw)):(angle?1e-6:1e-6);\nreturn {type,driving,target:Number.isFinite(target)?target:null,tolerance};"));
test("question 47066: preserves adjacent source contract",()=>has(3,"return {type,driving,target:Number.isFinite(target)?target:null,tolerance};\nfunction q78ValidateAfterAssemblyTransform(rootIds=[]){"));
test("question 47067: preserves adjacent source contract",()=>has(3,"function q78ValidateAfterAssemblyTransform(rootIds=[]){\nconst p=project(),movedIds=q78MovedAssemblyIds(rootIds),conflicts=[],updated=[];"));
test("question 47068: preserves adjacent source contract",()=>has(3,"const p=project(),movedIds=q78MovedAssemblyIds(rootIds),conflicts=[],updated=[];\nfor(const dim of p?.engineering_dimensions??[]){"));
test("question 47069: preserves adjacent source contract",()=>has(3,"for(const dim of p?.engineering_dimensions??[]){\nif(!q78Relevant(dim,movedIds))continue;"));
test("question 47070: preserves adjacent source contract",()=>has(3,"if(!q78Relevant(dim,movedIds))continue;\nq78UpdateReferenceContexts(dim.references);"));
test("question 47071: preserves adjacent source contract",()=>has(3,"q78UpdateReferenceContexts(dim.references);\nconst value=q78Measure(dim.kind,dim.references);"));
test("question 47072: preserves adjacent source contract",()=>has(3,"const value=q78Measure(dim.kind,dim.references);\nif(value!=null&&Number.isFinite(value)){"));
test("question 47073: preserves adjacent source contract",()=>has(3,"if(value!=null&&Number.isFinite(value)){\ndim.value=value;"));
test("question 47074: preserves adjacent source contract",()=>has(3,"dim.value=value;\nif(dim.mode===\"Driving\"){"));
test("question 47075: preserves adjacent source contract",()=>has(3,"if(dim.mode===\"Driving\"){\nconst target=Number(dim.target_value??dim.value);"));
test("question 47076: preserves adjacent source contract",()=>has(3,"const target=Number(dim.target_value??dim.value);\nconst tolerance=/angle/i.test(String(dim.kind))?1e-6:1e-6;"));
test("question 47077: preserves adjacent source contract",()=>has(3,"const tolerance=/angle/i.test(String(dim.kind))?1e-6:1e-6;\nif(!Number.isFinite(target)||Math.abs(value-target)>tolerance){"));
test("question 47078: preserves adjacent source contract",()=>has(3,"if(!Number.isFinite(target)||Math.abs(value-target)>tolerance){\ndim.status=\"Conflict\";conflicts.push({kind:\"Dimension\",id:dim.id,value,target,tolerance});"));
test("question 47079: preserves adjacent source contract",()=>has(3,"dim.status=\"Conflict\";conflicts.push({kind:\"Dimension\",id:dim.id,value,target,tolerance});\n}else dim.status=\"Valid\";"));
test("question 47080: preserves adjacent source contract",()=>has(3,"}else dim.status=\"Valid\";\n}else dim.status=\"Valid\";"));
test("question 47081: preserves adjacent source contract",()=>has(3,"}else dim.status=\"Valid\";\nupdated.push({kind:\"Dimension\",id:dim.id,value});"));
test("question 47082: preserves adjacent source contract",()=>has(3,"updated.push({kind:\"Dimension\",id:dim.id,value});\n}else if(dim.mode===\"Driving\"){"));
test("question 47083: preserves adjacent source contract",()=>has(3,"}else if(dim.mode===\"Driving\"){\ndim.status=\"Conflict\";"));
test("question 47084: preserves adjacent source contract",()=>has(3,"dim.status=\"Conflict\";\nconflicts.push({kind:\"Dimension\",id:dim.id,reason:\"Driving cross-Assembly dimension cannot be resolved\"});"));
test("question 47085: preserves adjacent source contract",()=>has(3,"conflicts.push({kind:\"Dimension\",id:dim.id,reason:\"Driving cross-Assembly dimension cannot be resolved\"});\nfor(const link of p?.cross_assembly_links??[]){"));
test("question 47086: preserves adjacent source contract",()=>has(3,"for(const link of p?.cross_assembly_links??[]){\nif(!q78Relevant(link,movedIds))continue;"));
test("question 47087: preserves adjacent source contract",()=>has(3,"if(!q78Relevant(link,movedIds))continue;\nq78UpdateReferenceContexts(link.references);"));
test("question 47088: preserves adjacent source contract",()=>has(3,"q78UpdateReferenceContexts(link.references);\nconst spec=q78ConstraintSpec(link);"));
test("question 47089: preserves adjacent source contract",()=>has(3,"const spec=q78ConstraintSpec(link);\nconst value=q78Measure(spec.type,link.references);"));
test("question 47090: preserves adjacent source contract",()=>has(3,"const value=q78Measure(spec.type,link.references);\nif(spec.driving){"));
test("question 47091: preserves adjacent source contract",()=>has(3,"if(spec.driving){\nif(value==null||!Number.isFinite(value)||spec.target==null){"));
test("question 47092: preserves adjacent source contract",()=>has(3,"if(value==null||!Number.isFinite(value)||spec.target==null){\nlink.status=\"Conflict\";"));
test("question 47093: preserves adjacent source contract",()=>has(3,"link.status=\"Conflict\";\nconflicts.push({kind:\"CrossAssemblyLink\",id:link.id,reason:\"Cross-Assembly constraint cannot be resolved fail-closed\"});"));
test("question 47094: preserves adjacent source contract",()=>has(3,"conflicts.push({kind:\"CrossAssemblyLink\",id:link.id,reason:\"Cross-Assembly constraint cannot be resolved fail-closed\"});\n}else if(Math.abs(value-spec.target)>spec.tolerance){"));
test("question 47095: preserves adjacent source contract",()=>has(3,"}else if(Math.abs(value-spec.target)>spec.tolerance){\nlink.status=\"Conflict\";"));
test("question 47096: preserves adjacent source contract",()=>has(3,"link.status=\"Conflict\";\nconflicts.push({kind:\"CrossAssemblyLink\",id:link.id,value,target:spec.target,tolerance:spec.tolerance});"));
test("question 47097: preserves adjacent source contract",()=>has(3,"conflicts.push({kind:\"CrossAssemblyLink\",id:link.id,value,target:spec.target,tolerance:spec.tolerance});\nlink.status=\"Valid\";link.value=value;"));
test("question 47098: preserves adjacent source contract",()=>has(3,"link.status=\"Valid\";link.value=value;\nlink.status=\"Valid\";"));
test("question 47099: preserves adjacent source contract",()=>has(3,"link.status=\"Valid\";\nif(value!=null&&Number.isFinite(value))link.value=value;"));
test("question 47100: preserves adjacent source contract",()=>has(3,"if(value!=null&&Number.isFinite(value))link.value=value;\nupdated.push({kind:\"CrossAssemblyLink\",id:link.id,value:value??null});"));
test("question 47101: preserves adjacent source contract",()=>has(3,"updated.push({kind:\"CrossAssemblyLink\",id:link.id,value:value??null});\nreturn {ok:conflicts.length===0,conflicts,updated,moved_assembly_ids:[...movedIds]};"));
test("question 47102: preserves adjacent source contract",()=>has(3,"return {ok:conflicts.length===0,conflicts,updated,moved_assembly_ids:[...movedIds]};\nfunction q78RestoreProject(snapshot){"));
test("question 47103: preserves adjacent source contract",()=>has(3,"function q78RestoreProject(snapshot){\nconst p=project();if(!p||!snapshot)return false;"));
test("question 47104: preserves adjacent source contract",()=>has(3,"const p=project();if(!p||!snapshot)return false;\nfor(const key of Object.keys(p))delete p[key];"));
test("question 47105: preserves adjacent source contract",()=>has(3,"for(const key of Object.keys(p))delete p[key];\nObject.assign(p,clone(snapshot));"));
test("question 47106: preserves adjacent source contract",()=>has(3,"Object.assign(p,clone(snapshot));\ntry{eng()?.reloadActiveTube?.();}catch{}"));
test("question 47107: preserves adjacent source contract",()=>has(3,"try{eng()?.reloadActiveTube?.();}catch{}\nreturn true;"));
test("question 47108: preserves adjacent source contract",()=>has(3,"return true;\nfunction q78GuardedAssemblyTransform(label,rootIds,mutate){"));
test("question 47109: preserves adjacent source contract",()=>has(3,"function q78GuardedAssemblyTransform(label,rootIds,mutate){\nconst p=project(),snapshot=clone(p);"));
test("question 47110: preserves adjacent source contract",()=>has(3,"const p=project(),snapshot=clone(p);\nreturn command(label,()=>{"));
test("question 47111: preserves adjacent source contract",()=>has(3,"return command(label,()=>{\nconst result=mutate();"));
test("question 47112: preserves adjacent source contract",()=>has(3,"const result=mutate();\nif(result===false){q78RestoreProject(snapshot);return false;}"));
test("question 47113: preserves adjacent source contract",()=>has(3,"if(result===false){q78RestoreProject(snapshot);return false;}\nconst validation=q78ValidateAfterAssemblyTransform(rootIds);"));
test("question 47114: preserves adjacent source contract",()=>has(3,"const validation=q78ValidateAfterAssemblyTransform(rootIds);\nif(!validation.ok){"));
test("question 47115: preserves adjacent source contract",()=>has(3,"if(!validation.ok){\nq78RestoreProject(snapshot);"));
test("question 47116: preserves adjacent source contract",()=>has(3,"q78RestoreProject(snapshot);\ntoast(\"Перемещение Assembly отменено: конфликт межсборочных constraints\");"));
test("question 47117: preserves adjacent source contract",()=>has(3,"toast(\"Перемещение Assembly отменено: конфликт межсборочных constraints\");\nreturn false;"));
test("question 47118: preserves adjacent source contract",()=>has(3,"return false;\np.last_cross_assembly_validation={"));
test("question 47119: preserves adjacent source contract",()=>has(3,"p.last_cross_assembly_validation={\nstatus:\"Valid\","));
test("question 47120: preserves adjacent source contract",()=>has(3,"status:\"Valid\",\noperation:String(label),"));
test("question 47121: preserves adjacent source contract",()=>has(3,"operation:String(label),\nmoved_assembly_ids:validation.moved_assembly_ids,"));
test("question 47122: preserves adjacent source contract",()=>has(3,"moved_assembly_ids:validation.moved_assembly_ids,\nupdated:validation.updated,"));
test("question 47123: preserves adjacent source contract",()=>has(3,"updated:validation.updated,\nchecked_at:new Date().toISOString()"));
test("question 47124: preserves adjacent source contract",()=>has(3,"checked_at:new Date().toISOString()\nreturn result;"));
test("question 47125: preserves adjacent source contract",()=>has(3,"return result;\nfunction tubeDirection(tube){"));
test("question 47126: preserves adjacent source contract",()=>has(3,"function tubeDirection(tube){\nif(tube?.startVector&&[tube.startVector.x,tube.startVector.y,tube.startVector.z].every(Number.isFinite))return clone(tube.startVector);"));
test("question 47127: preserves adjacent source contract",()=>has(3,"if(tube?.startVector&&[tube.startVector.x,tube.startVector.y,tube.startVector.z].every(Number.isFinite))return clone(tube.startVector);\nif(tube?.startAxis===\"Y\")return {x:0,y:1,z:0};"));
test("question 47128: preserves adjacent source contract",()=>has(3,"if(tube?.startAxis===\"Y\")return {x:0,y:1,z:0};\nif(tube?.startAxis===\"Z\")return {x:0,y:0,z:1};"));
test("question 47129: preserves adjacent source contract",()=>has(3,"if(tube?.startAxis===\"Z\")return {x:0,y:0,z:1};\nreturn {x:1,y:0,z:0};"));
test("question 47130: preserves adjacent source contract",()=>has(3,"return {x:1,y:0,z:0};\nfunction memberPose(ref){"));
test("question 47131: preserves adjacent source contract",()=>has(3,"function memberPose(ref){\nif(ref.kind===\"tube\"){"));
test("question 47132: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"tube\"){\nconst tube=tubeById(ref.id);if(!tube)return null;"));
test("question 47133: preserves adjacent source contract",()=>has(3,"const tube=tubeById(ref.id);if(!tube)return null;\nreturn {position_mm:clone(tube.origin??{x:0,y:0,z:0}),rotation_quaternion:null,direction:tubeDirection(tube)};"));
test("question 47134: preserves adjacent source contract",()=>has(3,"return {position_mm:clone(tube.origin??{x:0,y:0,z:0}),rotation_quaternion:null,direction:tubeDirection(tube)};\nif(ref.kind===\"mesh-instance\"){"));
test("question 47135: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"mesh-instance\"){\nconst mesh=meshById(ref.id);if(!mesh)return null;"));
test("question 47136: preserves adjacent source contract",()=>has(3,"const mesh=meshById(ref.id);if(!mesh)return null;\nreturn {"));
test("question 47137: preserves adjacent source contract",()=>has(3,"return {\nposition_mm:clone(mesh.transform?.position_mm??{x:0,y:0,z:0}),"));
test("question 47138: preserves adjacent source contract",()=>has(3,"position_mm:clone(mesh.transform?.position_mm??{x:0,y:0,z:0}),\nrotation_quaternion:clone(mesh.transform?.rotation_quaternion??{x:0,y:0,z:0,w:1}),"));
test("question 47139: preserves adjacent source contract",()=>has(3,"rotation_quaternion:clone(mesh.transform?.rotation_quaternion??{x:0,y:0,z:0,w:1}),\ndirection:null"));
test("question 47140: preserves adjacent source contract",()=>has(3,"direction:null\nif(ref.kind===\"construction\"){"));
test("question 47141: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"construction\"){\nconst item=objectForRef(ref);if(!item)return null;"));
test("question 47142: preserves adjacent source contract",()=>has(3,"const item=objectForRef(ref);if(!item)return null;\nreturn {position_mm:clone(item.position_mm??item.origin??null),rotation_quaternion:clone(item.rotation_quaternion??null),direction:clone(item.direction??null)};"));
test("question 47143: preserves adjacent source contract",()=>has(3,"return {position_mm:clone(item.position_mm??item.origin??null),rotation_quaternion:clone(item.rotation_quaternion??null),direction:clone(item.direction??null)};\nif(ref.kind===\"dimension\"){"));
test("question 47144: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"dimension\"){\nconst dim=objectForRef(ref);if(!dim)return null;"));
test("question 47145: preserves adjacent source contract",()=>has(3,"const dim=objectForRef(ref);if(!dim)return null;\nreturn {position_mm:clone(dim.text_position??null),rotation_quaternion:null,direction:null};"));
test("question 47146: preserves adjacent source contract",()=>has(3,"return {position_mm:clone(dim.text_position??null),rotation_quaternion:null,direction:null};\nif(ref.kind===\"assembly\"){"));
test("question 47147: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"assembly\"){\nconst child=assemblyById(ref.id);if(!child)return null;"));
test("question 47148: preserves adjacent source contract",()=>has(3,"const child=assemblyById(ref.id);if(!child)return null;\nreturn {position_mm:clone(child.frame?.origin_mm),rotation_quaternion:clone(child.frame?.rotation_quaternion),direction:null};"));
test("question 47149: preserves adjacent source contract",()=>has(3,"return {position_mm:clone(child.frame?.origin_mm),rotation_quaternion:clone(child.frame?.rotation_quaternion),direction:null};\nreturn null;"));
test("question 47150: preserves adjacent source contract",()=>has(3,"return null;\nfunction localFromPose(frame,pose){"));
test("question 47151: preserves adjacent source contract",()=>has(3,"function localFromPose(frame,pose){\nreturn {"));
test("question 47152: preserves adjacent source contract",()=>has(3,"return {\nposition_mm:pose?.position_mm==null?null:assemblies.worldToLocalPoint(frame,pose.position_mm),"));
test("question 47153: preserves adjacent source contract",()=>has(3,"position_mm:pose?.position_mm==null?null:assemblies.worldToLocalPoint(frame,pose.position_mm),\nrotation_quaternion:pose?.rotation_quaternion==null?null:assemblies.worldToLocalQuaternion(frame,pose.rotation_quaternion),"));
test("question 47154: preserves adjacent source contract",()=>has(3,"rotation_quaternion:pose?.rotation_quaternion==null?null:assemblies.worldToLocalQuaternion(frame,pose.rotation_quaternion),\ndirection:pose?.direction==null?null:assemblies.rotateVectorByQuaternion(pose.direction,assemblies.conjugateQuaternion(frame.rotation_quaternion))"));
test("question 47155: preserves adjacent source contract",()=>has(3,"direction:pose?.direction==null?null:assemblies.rotateVectorByQuaternion(pose.direction,assemblies.conjugateQuaternion(frame.rotation_quaternion))\nfunction syncAssemblyLocals(assemblyId,visited=new Set()){"));
test("question 47156: preserves adjacent source contract",()=>has(3,"function syncAssemblyLocals(assemblyId,visited=new Set()){\nconst id=String(assemblyId);if(visited.has(id))return;"));
test("question 47157: preserves adjacent source contract",()=>has(3,"const id=String(assemblyId);if(visited.has(id))return;\nvisited.add(id);"));
test("question 47158: preserves adjacent source contract",()=>has(3,"visited.add(id);\nconst assembly=assemblyById(id);if(!assembly)return;"));
test("question 47159: preserves adjacent source contract",()=>has(3,"const assembly=assemblyById(id);if(!assembly)return;\nfor(const member of [...(assembly.members??[])]){"));
test("question 47160: preserves adjacent source contract",()=>has(3,"for(const member of [...(assembly.members??[])]){\nif(member.ref.kind===\"assembly\")syncAssemblyLocals(member.ref.id,visited);"));
test("question 47161: preserves adjacent source contract",()=>has(3,"if(member.ref.kind===\"assembly\")syncAssemblyLocals(member.ref.id,visited);\nconst pose=memberPose(member.ref);"));
test("question 47162: preserves adjacent source contract",()=>has(3,"const pose=memberPose(member.ref);\nif(!pose)continue;"));
test("question 47163: preserves adjacent source contract",()=>has(3,"if(!pose)continue;\nassemblies.setAssemblyMemberLocal(project(),assembly.id,member.ref,localFromPose(assembly.frame,pose));"));
test("question 47164: preserves adjacent source contract",()=>has(3,"assemblies.setAssemblyMemberLocal(project(),assembly.id,member.ref,localFromPose(assembly.frame,pose));\nif(member.ref.kind===\"tube\")syncTubePortConstraints(member.ref.id);"));
test("question 47165: preserves adjacent source contract",()=>has(3,"if(member.ref.kind===\"tube\")syncTubePortConstraints(member.ref.id);\nfunction selectionRefs(){"));
test("question 47166: preserves adjacent source contract",()=>has(3,"function selectionRefs(){\nconst refs=new Map();"));
test("question 47167: preserves adjacent source contract",()=>has(3,"const refs=new Map();\nfor(const entry of entries()){"));
test("question 47168: preserves adjacent source contract",()=>has(3,"for(const entry of entries()){\nconst ref=refFromEntry(entry);if(!ref)continue;"));
test("question 47169: preserves adjacent source contract",()=>has(3,"const ref=refFromEntry(entry);if(!ref)continue;\nif(ref.kind===\"source-ref\")throw new Error(\"Source / Reference нельзя включить напрямую: сначала создайте Editable Mesh Instance\");"));
test("question 47170: preserves adjacent source contract",()=>has(3,"if(ref.kind===\"source-ref\")throw new Error(\"Source / Reference нельзя включить напрямую: сначала создайте Editable Mesh Instance\");\nrefs.set(assemblies.assemblyMemberKey(ref),ref);"));
test("question 47171: preserves adjacent source contract",()=>has(3,"refs.set(assemblies.assemblyMemberKey(ref),ref);\nreturn [...refs.values()];"));
test("question 47172: preserves adjacent source contract",()=>has(3,"return [...refs.values()];\nfunction assertSingleParent(ref,targetAssemblyId=null){"));
test("question 47173: preserves adjacent source contract",()=>has(3,"function assertSingleParent(ref,targetAssemblyId=null){\nconst direct=directAssembliesForRef(ref).filter(item=>String(item.id)!==String(targetAssemblyId??\"\"));"));
