import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const files=["src/ui/object-selection-context-ui.js","src/ui/editing-ui.js","src/import/dwfx/reference-scene-ui.js","src/ui/assemblies-runtime.js","src/ui/equipment-library-ui.js"];
const normalized=files.map(rel=>fs.readFileSync(path.join(root,rel),"utf8").split(/\r?\n/).map(s=>s.trim()).filter(s=>s.length>=8&&!s.startsWith("//")&&s!=="{"&&s!=="}"&&s!=="};").join("\n"));
const has=(fileIndex,pair)=>assert.ok(normalized[fileIndex].includes(pair));
test("question 46124: preserves adjacent source contract",()=>has(2,"'<button class=\"tb-tree-icon\" data-ref-scene-toggle=\"'+escape(scene.id)+'\" title=\"Свернуть/развернуть файл\">'+\n(sceneCollapsed?'▸':'▾')+"));
test("question 46125: preserves adjacent source contract",()=>has(2,"(sceneCollapsed?'▸':'▾')+\n'</button>'+"));
test("question 46126: preserves adjacent source contract",()=>has(2,"'</button>'+\n'<span class=\"tb-tree-label\">📦 '+escape(sceneLabel)+' <small>· DWFx · Source readonly</small></span>'+"));
test("question 46127: preserves adjacent source contract",()=>has(2,"'<span class=\"tb-tree-label\">📦 '+escape(sceneLabel)+' <small>· DWFx · Source readonly</small></span>'+\n'<button class=\"tb-tree-eye\" data-ref-scene-eye=\"'+escape(scene.id)+'\" title=\"Видимость Source\">'+"));
test("question 46128: preserves adjacent source contract",()=>has(2,"'<button class=\"tb-tree-eye\" data-ref-scene-eye=\"'+escape(scene.id)+'\" title=\"Видимость Source\">'+\n(scene.visible===false?'○':'◉')+"));
test("question 46129: preserves adjacent source contract",()=>has(2,"(scene.visible===false?'○':'◉')+\n'</button></div>'"));
test("question 46130: preserves adjacent source contract",()=>has(2,"'</button></div>'\nif(sceneCollapsed)continue;"));
test("question 46131: preserves adjacent source contract",()=>has(2,"if(sceneCollapsed)continue;\nconst append=(node,depth)=>{"));
test("question 46132: preserves adjacent source contract",()=>has(2,"const append=(node,depth)=>{\nif(q&&!matchNode(node,q))return;"));
test("question 46133: preserves adjacent source contract",()=>has(2,"if(q&&!matchNode(node,q))return;\nconst hasChildren=(node.children??[]).length>0;"));
test("question 46134: preserves adjacent source contract",()=>has(2,"const hasChildren=(node.children??[]).length>0;\nconst collapsed=q?false:collapsedScenes.has(String(node.id));"));
test("question 46135: preserves adjacent source contract",()=>has(2,"const collapsed=q?false:collapsedScenes.has(String(node.id));\nconst isHidden=hidden.has(String(node.id));"));
test("question 46136: preserves adjacent source contract",()=>has(2,"const isHidden=hidden.has(String(node.id));\nconst isTransparent=transparent.has(String(node.id));"));
test("question 46137: preserves adjacent source contract",()=>has(2,"const isTransparent=transparent.has(String(node.id));\nconst status=String(node.geometry_status??\"\");"));
test("question 46138: preserves adjacent source contract",()=>has(2,"const status=String(node.geometry_status??\"\");\nconst editable=!!node.editable_part_number;"));
test("question 46139: preserves adjacent source contract",()=>has(2,"const editable=!!node.editable_part_number;\nconst linked=linkedTubeForSource(project,scene.id,node.id);"));
test("question 46140: preserves adjacent source contract",()=>has(2,"const linked=linkedTubeForSource(project,scene.id,node.id);\nconst selectable=!editable;"));
test("question 46141: preserves adjacent source contract",()=>has(2,"const selectable=!editable;\nconst checked=selectable&&bulkSelected.has(selectionKey(scene.id,node.id));"));
test("question 46142: preserves adjacent source contract",()=>has(2,"const checked=selectable&&bulkSelected.has(selectionKey(scene.id,node.id));\nconst icon=hasChildren"));
test("question 46143: preserves adjacent source contract",()=>has(2,"const icon=hasChildren\n? (collapsed?'▸':'▾')"));
test("question 46144: preserves adjacent source contract",()=>has(2,"? (collapsed?'▸':'▾')\n: editable"));
test("question 46145: preserves adjacent source contract",()=>has(2,": editable\n: status===\"unresolved\"||status===\"partial\""));
test("question 46146: preserves adjacent source contract",()=>has(2,": status===\"unresolved\"||status===\"partial\"\n: status===\"metadata_only\""));
test("question 46147: preserves adjacent source contract",()=>has(2,": status===\"metadata_only\"\nconst pad=Math.min(260,66+depth*18);"));
test("question 46148: preserves adjacent source contract",()=>has(2,"const pad=Math.min(260,66+depth*18);\nconst cls="));
test("question 46149: preserves adjacent source contract",()=>has(2,"const cls=\nselected?.sceneId===String(scene.id)&&"));
test("question 46150: preserves adjacent source contract",()=>has(2,"selected?.sceneId===String(scene.id)&&\nselected?.nodeId===String(node.id)"));
test("question 46151: preserves adjacent source contract",()=>has(2,"selected?.nodeId===String(node.id)\n? \" active\""));
test("question 46152: preserves adjacent source contract",()=>has(2,"? \" active\"\nrows.push("));
test("question 46153: preserves adjacent source contract",()=>has(2,"rows.push(\n'<div class=\"tb-tree-node clickable tb-ref-node'+cls+'\" '+"));
test("question 46154: preserves adjacent source contract",()=>has(2,"'<div class=\"tb-tree-node clickable tb-ref-node'+cls+'\" '+\n'style=\"padding-left:'+pad+'px\" '+"));
test("question 46155: preserves adjacent source contract",()=>has(2,"'style=\"padding-left:'+pad+'px\" '+\n'data-ref-scene=\"'+escape(scene.id)+'\" data-ref-node=\"'+escape(node.id)+'\" '+"));
test("question 46156: preserves adjacent source contract",()=>has(2,"'data-ref-scene=\"'+escape(scene.id)+'\" data-ref-node=\"'+escape(node.id)+'\" '+\n(node.editable_part_number?'data-ref-editable-part=\"'+escape(node.editable_part_number)+'\" ':'')+"));
test("question 46157: preserves adjacent source contract",()=>has(2,"(node.editable_part_number?'data-ref-editable-part=\"'+escape(node.editable_part_number)+'\" ':'')+\n(selectable"));
test("question 46158: preserves adjacent source contract",()=>has(2,"(selectable\n? '<input type=\"checkbox\" data-ref-select=\"'+escape(node.id)+'\" '+(checked?'checked ':'')+'title=\"Выбрать Source компонент/группу\">'"));
test("question 46159: preserves adjacent source contract",()=>has(2,"? '<input type=\"checkbox\" data-ref-select=\"'+escape(node.id)+'\" '+(checked?'checked ':'')+'title=\"Выбрать Source компонент/группу\">'\n: '<span style=\"width:13px;display:inline-block\"></span>')+"));
test("question 46160: preserves adjacent source contract",()=>has(2,": '<span style=\"width:13px;display:inline-block\"></span>')+\n'<button class=\"tb-tree-icon\" '+(hasChildren?'data-ref-toggle=\"'+escape(node.id)+'\"':'disabled')+'>'+"));
test("question 46161: preserves adjacent source contract",()=>has(2,"'<button class=\"tb-tree-icon\" '+(hasChildren?'data-ref-toggle=\"'+escape(node.id)+'\"':'disabled')+'>'+\nicon+'</button>'+"));
test("question 46162: preserves adjacent source contract",()=>has(2,"icon+'</button>'+\n'<span class=\"tb-tree-label\">'+escape(node.label??node.id)+"));
test("question 46163: preserves adjacent source contract",()=>has(2,"'<span class=\"tb-tree-label\">'+escape(node.label??node.id)+\n(editable"));
test("question 46164: preserves adjacent source contract",()=>has(2,"(editable\n? ' <small>· Source'+(linked?' ↔ Editable':' · recognized')+'</small>'"));
test("question 46165: preserves adjacent source contract",()=>has(2,"? ' <small>· Source'+(linked?' ↔ Editable':' · recognized')+'</small>'\n: status===\"metadata_only\""));
test("question 46166: preserves adjacent source contract",()=>has(2,": status===\"metadata_only\"\n? ' <small>· Source · без геометрии</small>'"));
test("question 46167: preserves adjacent source contract",()=>has(2,"? ' <small>· Source · без геометрии</small>'\n: ' <small>· Source · только чтение'+(isTransparent?' · прозрачно':'')+'</small>')+"));
test("question 46168: preserves adjacent source contract",()=>has(2,": ' <small>· Source · только чтение'+(isTransparent?' · прозрачно':'')+'</small>')+\n'</span>'+"));
test("question 46169: preserves adjacent source contract",()=>has(2,"'</span>'+\n'<button class=\"tb-tree-eye\" data-ref-eye=\"'+escape(node.id)+'\" title=\"Видимость Source\">'+"));
test("question 46170: preserves adjacent source contract",()=>has(2,"'<button class=\"tb-tree-eye\" data-ref-eye=\"'+escape(node.id)+'\" title=\"Видимость Source\">'+\n(isHidden?'○':'◉')+"));
test("question 46171: preserves adjacent source contract",()=>has(2,"(isHidden?'○':'◉')+\n'</button></div>'"));
test("question 46172: preserves adjacent source contract",()=>has(2,"'</button></div>'\nif(hasChildren&&!collapsed){"));
test("question 46173: preserves adjacent source contract",()=>has(2,"if(hasChildren&&!collapsed){\nfor(const child of node.children??[])append(child,depth+1);"));
test("question 46174: preserves adjacent source contract",()=>has(2,"for(const child of node.children??[])append(child,depth+1);\nfor(const root of scene.tree??[])append(root,0);"));
test("question 46175: preserves adjacent source contract",()=>has(2,"for(const root of scene.tree??[])append(root,0);\nconst editableMatches=editableTubes.filter((tube)=>{"));
test("question 46176: preserves adjacent source contract",()=>has(2,"const editableMatches=editableTubes.filter((tube)=>{\nif(!q)return true;"));
test("question 46177: preserves adjacent source contract",()=>has(2,"if(!q)return true;\nconst link=sourceLink(tube);"));
test("question 46178: preserves adjacent source contract",()=>has(2,"const link=sourceLink(tube);\nreturn ["));
test("question 46179: preserves adjacent source contract",()=>has(2,"return [\ntube?.name,tube?.partNumber,tube?.part_number,"));
test("question 46180: preserves adjacent source contract",()=>has(2,"tube?.name,tube?.partNumber,tube?.part_number,\nlink?.source_label,link?.part_number,link?.source_file"));
test("question 46181: preserves adjacent source contract",()=>has(2,"link?.source_label,link?.part_number,link?.source_file\n].filter(Boolean).some((value)=>String(value).toLowerCase().includes(q));"));
test("question 46182: preserves adjacent source contract",()=>has(2,"].filter(Boolean).some((value)=>String(value).toLowerCase().includes(q));\nrows.push("));
test("question 46183: preserves adjacent source contract",()=>has(2,"rows.push(\n'<div class=\"tb-tree-node level2 tb-ref-editable-root\" style=\"padding-left:30px\" data-ref-editable-root=\"1\">'+"));
test("question 46184: preserves adjacent source contract",()=>has(2,"'<div class=\"tb-tree-node level2 tb-ref-editable-root\" style=\"padding-left:30px\" data-ref-editable-root=\"1\">'+\n'<button class=\"tb-tree-icon\" data-ref-editable-toggle=\"1\" title=\"Свернуть/развернуть Editable geometry\">'+"));
test("question 46185: preserves adjacent source contract",()=>has(2,"'<button class=\"tb-tree-icon\" data-ref-editable-toggle=\"1\" title=\"Свернуть/развернуть Editable geometry\">'+\n(editableCollapsed?'▸':'▾')+"));
test("question 46186: preserves adjacent source contract",()=>has(2,"(editableCollapsed?'▸':'▾')+\n'</button>'+"));
test("question 46187: preserves adjacent source contract",()=>has(2,"'</button>'+\n'<span class=\"tb-tree-label\">✎ Editable geometry <small>· '+(editableTubes.length+editableMeshes.length)+'</small></span>'+"));
test("question 46188: preserves adjacent source contract",()=>has(2,"'<span class=\"tb-tree-label\">✎ Editable geometry <small>· '+(editableTubes.length+editableMeshes.length)+'</small></span>'+\n'</div>'"));
test("question 46189: preserves adjacent source contract",()=>has(2,"'</div>'\nif(!editableCollapsed){"));
test("question 46190: preserves adjacent source contract",()=>has(2,"if(!editableCollapsed){\nfor(const tube of editableMatches){"));
test("question 46191: preserves adjacent source contract",()=>has(2,"for(const tube of editableMatches){\nconst link=sourceLink(tube);"));
test("question 46192: preserves adjacent source contract",()=>has(2,"const link=sourceLink(tube);\nconst linked=!!link&&link.detached!==true&&!!sourceNodeForTube(project,tube);"));
test("question 46193: preserves adjacent source contract",()=>has(2,"const linked=!!link&&link.detached!==true&&!!sourceNodeForTube(project,tube);\nconst display=String(link?.display??\"hidden\");"));
test("question 46194: preserves adjacent source contract",()=>has(2,"const display=String(link?.display??\"hidden\");\nrows.push("));
test("question 46195: preserves adjacent source contract",()=>has(2,"rows.push(\n'<div class=\"tb-tree-node clickable tb-import-editable\" style=\"padding-left:50px\" '+"));
test("question 46196: preserves adjacent source contract",()=>has(2,"'<div class=\"tb-tree-node clickable tb-import-editable\" style=\"padding-left:50px\" '+\n'data-tree-tube=\"'+escape(tube.id)+'\" data-import-editable-tube=\"'+escape(tube.id)+'\">'+"));
test("question 46197: preserves adjacent source contract",()=>has(2,"'data-tree-tube=\"'+escape(tube.id)+'\" data-import-editable-tube=\"'+escape(tube.id)+'\">'+\n'<span style=\"width:13px;display:inline-block\"></span>'+"));
test("question 46198: preserves adjacent source contract",()=>has(2,"'<span style=\"width:13px;display:inline-block\"></span>'+\n'<span class=\"tb-tree-icon\">'+(linked?'🔗':'⛓̸')+'</span>'+"));
test("question 46199: preserves adjacent source contract",()=>has(2,"'<span class=\"tb-tree-icon\">'+(linked?'🔗':'⛓̸')+'</span>'+\n'<span class=\"tb-tree-label\">'+escape(tube.name??tube.partNumber??tube.id)+"));
test("question 46200: preserves adjacent source contract",()=>has(2,"'<span class=\"tb-tree-label\">'+escape(tube.name??tube.partNumber??tube.id)+\n' <small>· Editable'+(linked?' · source '+escape(link.part_number??\"\"):' · link broken')+"));
test("question 46201: preserves adjacent source contract",()=>has(2,"' <small>· Editable'+(linked?' · source '+escape(link.part_number??\"\"):' · link broken')+\n(linked&&display!==\"hidden\"?' · Source '+escape(display):'')+"));
test("question 46202: preserves adjacent source contract",()=>has(2,"(linked&&display!==\"hidden\"?' · Source '+escape(display):'')+\n'</small></span></div>'"));
test("question 46203: preserves adjacent source contract",()=>has(2,"'</small></span></div>'\nconst meshMatches=editableMeshes.filter((instance)=>{"));
test("question 46204: preserves adjacent source contract",()=>has(2,"const meshMatches=editableMeshes.filter((instance)=>{\nif(!q)return true;"));
test("question 46205: preserves adjacent source contract",()=>has(2,"if(!q)return true;\nreturn ["));
test("question 46206: preserves adjacent source contract",()=>has(2,"return [\ninstance?.name,instance?.source?.label,instance?.source?.source_file"));
test("question 46207: preserves adjacent source contract",()=>has(2,"instance?.name,instance?.source?.label,instance?.source?.source_file\n].filter(Boolean).some((value)=>String(value).toLowerCase().includes(q));"));
test("question 46208: preserves adjacent source contract",()=>has(2,"].filter(Boolean).some((value)=>String(value).toLowerCase().includes(q));\nfor(const instance of meshMatches){"));
test("question 46209: preserves adjacent source contract",()=>has(2,"for(const instance of meshMatches){\nconst linked=instance.link_status!==\"detached\";"));
test("question 46210: preserves adjacent source contract",()=>has(2,"const linked=instance.link_status!==\"detached\";\nconst p=instance.transform?.position_mm??{x:0,y:0,z:0};"));
test("question 46211: preserves adjacent source contract",()=>has(2,"const p=instance.transform?.position_mm??{x:0,y:0,z:0};\nrows.push("));
test("question 46212: preserves adjacent source contract",()=>has(2,"rows.push(\n'<div class=\"tb-tree-node clickable tb-import-mesh-instance\" style=\"padding-left:50px\" '+"));
test("question 46213: preserves adjacent source contract",()=>has(2,"'<div class=\"tb-tree-node clickable tb-import-mesh-instance\" style=\"padding-left:50px\" '+\n'data-import-mesh-instance=\"'+escape(instance.id)+'\">'+"));
test("question 46214: preserves adjacent source contract",()=>has(2,"'data-import-mesh-instance=\"'+escape(instance.id)+'\">'+\n'<span style=\"width:13px;display:inline-block\"></span>'+"));
test("question 46215: preserves adjacent source contract",()=>has(2,"'<span style=\"width:13px;display:inline-block\"></span>'+\n'<span class=\"tb-tree-icon\">'+(linked?'◇':'◆')+'</span>'+"));
test("question 46216: preserves adjacent source contract",()=>has(2,"'<span class=\"tb-tree-icon\">'+(linked?'◇':'◆')+'</span>'+\n'<span class=\"tb-tree-label\">'+escape(instance.name??instance.id)+"));
test("question 46217: preserves adjacent source contract",()=>has(2,"'<span class=\"tb-tree-label\">'+escape(instance.name??instance.id)+\n' <small>· Mesh Instance · '+(linked?'shared Source':'detached')+"));
test("question 46218: preserves adjacent source contract",()=>has(2,"' <small>· Mesh Instance · '+(linked?'shared Source':'detached')+\n' · Δ '+escape(Number(p.x||0).toFixed(1))+','+escape(Number(p.y||0).toFixed(1))+','+escape(Number(p.z||0).toFixed(1))+"));
test("question 46219: preserves adjacent source contract",()=>has(2,"' · Δ '+escape(Number(p.x||0).toFixed(1))+','+escape(Number(p.y||0).toFixed(1))+','+escape(Number(p.z||0).toFixed(1))+\n'</small></span></div>'"));
test("question 46220: preserves adjacent source contract",()=>has(2,"'</small></span></div>'\nreturn rows;"));
test("question 46221: preserves adjacent source contract",()=>has(2,"return rows;\nfunction findScene(project,id){"));
test("question 46222: preserves adjacent source contract",()=>has(2,"function findScene(project,id){\nreturn (project?.referenceScenes??[]).find("));
test("question 46223: preserves adjacent source contract",()=>has(2,"return (project?.referenceScenes??[]).find(\n(scene)=>String(scene?.id)===String(id)"));
test("question 46224: preserves adjacent source contract",()=>has(2,"(scene)=>String(scene?.id)===String(id)\n)??null;"));
test("question 46225: preserves adjacent source contract",()=>has(2,")??null;\nfunction findNode(tree,id){"));
test("question 46226: preserves adjacent source contract",()=>has(2,"function findNode(tree,id){\nconst target=String(id);"));
test("question 46227: preserves adjacent source contract",()=>has(2,"const target=String(id);\nconst stack=[...(tree??[])];"));
test("question 46228: preserves adjacent source contract",()=>has(2,"const stack=[...(tree??[])];\nwhile(stack.length){"));
test("question 46229: preserves adjacent source contract",()=>has(2,"const node=stack.shift();\nif(String(node?.id)===target)return node;"));
test("question 46230: preserves adjacent source contract",()=>has(2,"if(String(node?.id)===target)return node;\nstack.unshift(...(node?.children??[]));"));
test("question 46231: preserves adjacent source contract",()=>has(2,"stack.unshift(...(node?.children??[]));\nreturn null;"));
test("question 46232: preserves adjacent source contract",()=>has(2,"return null;\nfunction ancestorsFor(tree,targetId){"));
test("question 46233: preserves adjacent source contract",()=>has(2,"function ancestorsFor(tree,targetId){\nconst target=String(targetId);"));
test("question 46234: preserves adjacent source contract",()=>has(2,"const target=String(targetId);\nconst path=[];"));
test("question 46235: preserves adjacent source contract",()=>has(2,"const path=[];\nconst walk=(nodes)=>{"));
test("question 46236: preserves adjacent source contract",()=>has(2,"const walk=(nodes)=>{\nfor(const node of nodes??[]){"));
test("question 46237: preserves adjacent source contract",()=>has(2,"for(const node of nodes??[]){\npath.push(String(node.id));"));
test("question 46238: preserves adjacent source contract",()=>has(2,"path.push(String(node.id));\nif(String(node.id)===target)return true;"));
test("question 46239: preserves adjacent source contract",()=>has(2,"if(String(node.id)===target)return true;\nif(walk(node.children))return true;"));
test("question 46240: preserves adjacent source contract",()=>has(2,"if(walk(node.children))return true;\npath.pop();"));
test("question 46241: preserves adjacent source contract",()=>has(2,"path.pop();\nreturn false;"));
test("question 46242: preserves adjacent source contract",()=>has(2,"return false;\nwalk(tree??[]);"));
test("question 46243: preserves adjacent source contract",()=>has(2,"walk(tree??[]);\nreturn path;"));
test("question 46244: preserves adjacent source contract",()=>has(2,"return path;\nfunction toggleSceneSelection(scene,checked){"));
test("question 46245: preserves adjacent source contract",()=>has(2,"function toggleSceneSelection(scene,checked){\nfor(const node of collectSelectableNodes(scene?.tree??[])){"));
test("question 46246: preserves adjacent source contract",()=>has(2,"for(const node of collectSelectableNodes(scene?.tree??[])){\nconst key=selectionKey(scene.id,node.id);"));
test("question 46247: preserves adjacent source contract",()=>has(2,"const key=selectionKey(scene.id,node.id);\nif(checked)bulkSelected.add(key);else bulkSelected.delete(key);"));
test("question 46248: preserves adjacent source contract",()=>has(2,"if(checked)bulkSelected.add(key);else bulkSelected.delete(key);\nfunction toggleNodeSelection(scene,node,checked){"));
test("question 46249: preserves adjacent source contract",()=>has(2,"function toggleNodeSelection(scene,node,checked){\nfor(const item of collectSelectableSubtree(node)){"));
test("question 46250: preserves adjacent source contract",()=>has(2,"for(const item of collectSelectableSubtree(node)){\nconst key=selectionKey(scene.id,item.id);"));
test("question 46251: preserves adjacent source contract",()=>has(2,"const key=selectionKey(scene.id,item.id);\nif(checked)bulkSelected.add(key);else bulkSelected.delete(key);"));
test("question 46252: preserves adjacent source contract",()=>has(2,"if(checked)bulkSelected.add(key);else bulkSelected.delete(key);\nfunction applyBulkVisibility(project,visible){"));
test("question 46253: preserves adjacent source contract",()=>has(2,"function applyBulkVisibility(project,visible){\nfor(const {scene,node} of selectedEntries(project)){"));
test("question 46254: preserves adjacent source contract",()=>has(2,"for(const {scene,node} of selectedEntries(project)){\nconst hidden=hiddenSet(scene);"));
test("question 46255: preserves adjacent source contract",()=>has(2,"const hidden=hiddenSet(scene);\nif(visible){"));
test("question 46256: preserves adjacent source contract",()=>has(2,"if(visible){\nhidden.delete(String(node.id));"));
test("question 46257: preserves adjacent source contract",()=>has(2,"hidden.delete(String(node.id));\nfor(const ancestorId of ancestorsFor(scene.tree,node.id))hidden.delete(String(ancestorId));"));
test("question 46258: preserves adjacent source contract",()=>has(2,"for(const ancestorId of ancestorsFor(scene.tree,node.id))hidden.delete(String(ancestorId));\nhidden.add(String(node.id));"));
test("question 46259: preserves adjacent source contract",()=>has(2,"hidden.add(String(node.id));\nscene.hiddenNodeIds=[...hidden];"));
test("question 46260: preserves adjacent source contract",()=>has(2,"scene.hiddenNodeIds=[...hidden];\nfunction isolateSelection(project){"));
test("question 46261: preserves adjacent source contract",()=>has(2,"function isolateSelection(project){\nconst selectedTop=selectedTopLevelEntries(project);"));
test("question 46262: preserves adjacent source contract",()=>has(2,"const selectedTop=selectedTopLevelEntries(project);\nconst selectedByScene=new Map();"));
test("question 46263: preserves adjacent source contract",()=>has(2,"const selectedByScene=new Map();\nfor(const {scene,node} of selectedTop){"));
test("question 46264: preserves adjacent source contract",()=>has(2,"for(const {scene,node} of selectedTop){\nconst key=String(scene.id);"));
test("question 46265: preserves adjacent source contract",()=>has(2,"const key=String(scene.id);\nconst list=selectedByScene.get(key)??[];"));
test("question 46266: preserves adjacent source contract",()=>has(2,"const list=selectedByScene.get(key)??[];\nlist.push(node);"));
test("question 46267: preserves adjacent source contract",()=>has(2,"list.push(node);\nselectedByScene.set(key,list);"));
test("question 46268: preserves adjacent source contract",()=>has(2,"selectedByScene.set(key,list);\nfor(const scene of project?.referenceScenes??[]){"));
test("question 46269: preserves adjacent source contract",()=>has(2,"for(const scene of project?.referenceScenes??[]){\nconst chosen=selectedByScene.get(String(scene.id))??[];"));
test("question 46270: preserves adjacent source contract",()=>has(2,"const chosen=selectedByScene.get(String(scene.id))??[];\nif(!chosen.length){"));
test("question 46271: preserves adjacent source contract",()=>has(2,"if(!chosen.length){\nscene.visible=false;"));
test("question 46272: preserves adjacent source contract",()=>has(2,"scene.visible=false;\ncontinue;"));
test("question 46273: preserves adjacent source contract",()=>has(2,"continue;\nscene.visible=true;"));
test("question 46274: preserves adjacent source contract",()=>has(2,"scene.visible=true;\nconst keep=new Set();"));
test("question 46275: preserves adjacent source contract",()=>has(2,"const keep=new Set();\nfor(const selectedNode of chosen){"));
test("question 46276: preserves adjacent source contract",()=>has(2,"for(const selectedNode of chosen){\nfor(const id of ancestorsFor(scene.tree,selectedNode.id))keep.add(String(id));"));
test("question 46277: preserves adjacent source contract",()=>has(2,"for(const id of ancestorsFor(scene.tree,selectedNode.id))keep.add(String(id));\nfor(const item of collectSelectableSubtree(selectedNode))keep.add(String(item.id));"));
test("question 46278: preserves adjacent source contract",()=>has(2,"for(const item of collectSelectableSubtree(selectedNode))keep.add(String(item.id));\nconst stack=[...(selectedNode.children??[])];"));
test("question 46279: preserves adjacent source contract",()=>has(2,"const stack=[...(selectedNode.children??[])];\nwhile(stack.length){"));
test("question 46280: preserves adjacent source contract",()=>has(2,"while(stack.length){\nconst child=stack.shift();"));
test("question 46281: preserves adjacent source contract",()=>has(2,"const child=stack.shift();\nkeep.add(String(child.id));"));
test("question 46282: preserves adjacent source contract",()=>has(2,"keep.add(String(child.id));\nstack.unshift(...(child.children??[]));"));
test("question 46283: preserves adjacent source contract",()=>has(2,"stack.unshift(...(child.children??[]));\nconst hidden=new Set();"));
test("question 46284: preserves adjacent source contract",()=>has(2,"const hidden=new Set();\nconst stack=[...(scene.tree??[])];"));
test("question 46285: preserves adjacent source contract",()=>has(2,"const stack=[...(scene.tree??[])];\nwhile(stack.length){"));
test("question 46286: preserves adjacent source contract",()=>has(2,"const node=stack.shift();\nif(!keep.has(String(node.id)))hidden.add(String(node.id));"));
test("question 46287: preserves adjacent source contract",()=>has(2,"if(!keep.has(String(node.id)))hidden.add(String(node.id));\nstack.unshift(...(node.children??[]));"));
test("question 46288: preserves adjacent source contract",()=>has(2,"stack.unshift(...(node.children??[]));\nscene.hiddenNodeIds=[...hidden];"));
test("question 46289: preserves adjacent source contract",()=>has(2,"scene.hiddenNodeIds=[...hidden];\nreturn selectedTop.length;"));
test("question 46290: preserves adjacent source contract",()=>has(2,"return selectedTop.length;\nfunction showAll(project){"));
test("question 46291: preserves adjacent source contract",()=>has(2,"function showAll(project){\nlet changed=0;"));
test("question 46292: preserves adjacent source contract",()=>has(2,"let changed=0;\nfor(const scene of project?.referenceScenes??[]){"));
test("question 46293: preserves adjacent source contract",()=>has(2,"for(const scene of project?.referenceScenes??[]){\nif(scene?.visible===false)changed+=1;"));
test("question 46294: preserves adjacent source contract",()=>has(2,"if(scene?.visible===false)changed+=1;\nif(Array.isArray(scene?.hiddenNodeIds)&&scene.hiddenNodeIds.length)changed+=scene.hiddenNodeIds.length;"));
test("question 46295: preserves adjacent source contract",()=>has(2,"if(Array.isArray(scene?.hiddenNodeIds)&&scene.hiddenNodeIds.length)changed+=scene.hiddenNodeIds.length;\nscene.visible=true;"));
test("question 46296: preserves adjacent source contract",()=>has(2,"scene.visible=true;\nscene.hiddenNodeIds=[];"));
test("question 46297: preserves adjacent source contract",()=>has(2,"scene.hiddenNodeIds=[];\nreturn changed;"));
test("question 46298: preserves adjacent source contract",()=>has(2,"return changed;\nfunction applyBulkTransparency(project){"));
test("question 46299: preserves adjacent source contract",()=>has(2,"function applyBulkTransparency(project){\nconst entries=selectedEntries(project);"));
test("question 46300: preserves adjacent source contract",()=>has(2,"const entries=selectedEntries(project);\nif(!entries.length)return;"));
test("question 46301: preserves adjacent source contract",()=>has(2,"if(!entries.length)return;\nconst allTransparent=entries.every(({scene,node})=>"));
test("question 46302: preserves adjacent source contract",()=>has(2,"const allTransparent=entries.every(({scene,node})=>\ntransparentSet(scene).has(String(node.id))"));
test("question 46303: preserves adjacent source contract",()=>has(2,"transparentSet(scene).has(String(node.id))\nconst byScene=new Map();"));
test("question 46304: preserves adjacent source contract",()=>has(2,"const byScene=new Map();\nfor(const {scene,node} of entries){"));
test("question 46305: preserves adjacent source contract",()=>has(2,"for(const {scene,node} of entries){\nconst key=String(scene.id);"));
test("question 46306: preserves adjacent source contract",()=>has(2,"const key=String(scene.id);\nconst set=byScene.get(key)??transparentSet(scene);"));
test("question 46307: preserves adjacent source contract",()=>has(2,"const set=byScene.get(key)??transparentSet(scene);\nif(allTransparent)set.delete(String(node.id));"));
test("question 46308: preserves adjacent source contract",()=>has(2,"if(allTransparent)set.delete(String(node.id));\nelse set.add(String(node.id));"));
test("question 46309: preserves adjacent source contract",()=>has(2,"else set.add(String(node.id));\nbyScene.set(key,set);"));
test("question 46310: preserves adjacent source contract",()=>has(2,"byScene.set(key,set);\nfor(const scene of project.referenceScenes??[]){"));
test("question 46311: preserves adjacent source contract",()=>has(2,"for(const scene of project.referenceScenes??[]){\nconst set=byScene.get(String(scene.id));"));
test("question 46312: preserves adjacent source contract",()=>has(2,"const set=byScene.get(String(scene.id));\nif(set)scene.transparentNodeIds=[...set];"));
test("question 46313: preserves adjacent source contract",()=>has(2,"if(set)scene.transparentNodeIds=[...set];\nfunction subtreeHasEditable(node){"));
test("question 46314: preserves adjacent source contract",()=>has(2,"function subtreeHasEditable(node){\nif(node?.editable_part_number)return true;"));
test("question 46315: preserves adjacent source contract",()=>has(2,"if(node?.editable_part_number)return true;\nreturn (node?.children??[]).some(subtreeHasEditable);"));
test("question 46316: preserves adjacent source contract",()=>has(2,"return (node?.children??[]).some(subtreeHasEditable);\nfunction deleteSelectedFromTree(scene,nodes){"));
test("question 46317: preserves adjacent source contract",()=>has(2,"function deleteSelectedFromTree(scene,nodes){\nconst removeIds=new Set("));
test("question 46318: preserves adjacent source contract",()=>has(2,"const removeIds=new Set(\nselectedEntries({referenceScenes:[scene]}).map(({node})=>String(node.id))"));
test("question 46319: preserves adjacent source contract",()=>has(2,"selectedEntries({referenceScenes:[scene]}).map(({node})=>String(node.id))\nconst prune=(node)=>{"));
test("question 46320: preserves adjacent source contract",()=>has(2,"const prune=(node)=>{\nconst selectedForDelete=removeIds.has(String(node.id))&&selectableNode(node);"));
test("question 46321: preserves adjacent source contract",()=>has(2,"const selectedForDelete=removeIds.has(String(node.id))&&selectableNode(node);\nif(selectedForDelete&&!subtreeHasEditable(node))return null;"));
test("question 46322: preserves adjacent source contract",()=>has(2,"if(selectedForDelete&&!subtreeHasEditable(node))return null;\nconst children=(node.children??[]).map(prune).filter(Boolean);"));
test("question 46323: preserves adjacent source contract",()=>has(2,"const children=(node.children??[]).map(prune).filter(Boolean);\nif(selectedForDelete){"));
test("question 46324: preserves adjacent source contract",()=>has(2,"if(selectedForDelete){\nreturn {"));
test("question 46325: preserves adjacent source contract",()=>has(2,"return {\n...node,"));
test("question 46326: preserves adjacent source contract",()=>has(2,"...node,\ngeometry_instances:[],"));
test("question 46327: preserves adjacent source contract",()=>has(2,"geometry_instances:[],\ngeometry_status:children.length?\"group\":\"metadata_only\","));
test("question 46328: preserves adjacent source contract",()=>has(2,"geometry_status:children.length?\"group\":\"metadata_only\",\nchildren"));
test("question 46329: preserves adjacent source contract",()=>has(2,"children\nreturn {...node,children};"));
test("question 46330: preserves adjacent source contract",()=>has(2,"return {...node,children};\nreturn (nodes??[]).map(prune).filter(Boolean);"));
test("question 46331: preserves adjacent source contract",()=>has(2,"return (nodes??[]).map(prune).filter(Boolean);\nfunction previewDeleteFrame(project){"));
test("question 46332: preserves adjacent source contract",()=>has(2,"function previewDeleteFrame(project){\nconst selectedNow=selectedEntries(project);"));
test("question 46333: preserves adjacent source contract",()=>has(2,"const selectedNow=selectedEntries(project);\nif(!selectedNow.length){"));
test("question 46334: preserves adjacent source contract",()=>has(2,"if(!selectedNow.length){\nreturn Object.freeze({"));
test("question 46335: preserves adjacent source contract",()=>has(2,"return Object.freeze({\nstatus:\"no_selection\","));
test("question 46336: preserves adjacent source contract",()=>has(2,"status:\"no_selection\",\nframe:null,"));
test("question 46337: preserves adjacent source contract",()=>has(2,"frame:null,\nselected_count:0"));
test("question 46338: preserves adjacent source contract",()=>has(2,"selected_count:0\nconst affected=new Set(selectedNow.map(({scene})=>String(scene.id)));"));
test("question 46339: preserves adjacent source contract",()=>has(2,"const affected=new Set(selectedNow.map(({scene})=>String(scene.id)));\nconst scenes=[];"));
test("question 46340: preserves adjacent source contract",()=>has(2,"const scenes=[];\nfor(const source of project?.referenceScenes??[]){"));
test("question 46341: preserves adjacent source contract",()=>has(2,"for(const source of project?.referenceScenes??[]){\nconst scene=JSON.parse(JSON.stringify(source));"));
test("question 46342: preserves adjacent source contract",()=>has(2,"const scene=JSON.parse(JSON.stringify(source));\nif(affected.has(String(scene.id))){"));
test("question 46343: preserves adjacent source contract",()=>has(2,"if(affected.has(String(scene.id))){\nscene.tree=deleteSelectedFromTree(scene,scene.tree);"));
test("question 46344: preserves adjacent source contract",()=>has(2,"scene.tree=deleteSelectedFromTree(scene,scene.tree);\nif(Array.isArray(scene.tree)&&scene.tree.length)scenes.push(scene);"));
test("question 46345: preserves adjacent source contract",()=>has(2,"if(Array.isArray(scene.tree)&&scene.tree.length)scenes.push(scene);\nconst bounds=currentReferenceProjectBounds({referenceScenes:scenes});"));
test("question 46346: preserves adjacent source contract",()=>has(2,"const bounds=currentReferenceProjectBounds({referenceScenes:scenes});\nconst frame=automaticFrameFromCurrentBounds(bounds);"));
test("question 46347: preserves adjacent source contract",()=>has(2,"const frame=automaticFrameFromCurrentBounds(bounds);\nreturn Object.freeze({"));
test("question 46348: preserves adjacent source contract",()=>has(2,"return Object.freeze({\nstatus:frame.status,"));
test("question 46349: preserves adjacent source contract",()=>has(2,"status:frame.status,\nframe:frame.status===\"exact\"?frame:null,"));
test("question 46350: preserves adjacent source contract",()=>has(2,"frame:frame.status===\"exact\"?frame:null,\nselected_count:selectedNow.length,"));
test("question 46351: preserves adjacent source contract",()=>has(2,"selected_count:selectedNow.length,\nreason:frame.status===\"exact\"?null:frame.reason??bounds.reason??null"));
test("question 46352: preserves adjacent source contract",()=>has(2,"reason:frame.status===\"exact\"?null:frame.reason??bounds.reason??null\nfunction applyBulkDelete(project){"));
test("question 46353: preserves adjacent source contract",()=>has(2,"function applyBulkDelete(project){\nconst affected=new Set("));
test("question 46354: preserves adjacent source contract",()=>has(2,"const affected=new Set(\nselectedEntries(project).map(({scene})=>String(scene.id))"));
test("question 46355: preserves adjacent source contract",()=>has(2,"selectedEntries(project).map(({scene})=>String(scene.id))\nfor(const scene of project.referenceScenes??[]){"));
test("question 46356: preserves adjacent source contract",()=>has(2,"for(const scene of project.referenceScenes??[]){\nif(!affected.has(String(scene.id)))continue;"));
test("question 46357: preserves adjacent source contract",()=>has(2,"if(!affected.has(String(scene.id)))continue;\nscene.tree=deleteSelectedFromTree(scene,scene.tree);"));
test("question 46358: preserves adjacent source contract",()=>has(2,"scene.tree=deleteSelectedFromTree(scene,scene.tree);\nconst kept=[];"));
test("question 46359: preserves adjacent source contract",()=>has(2,"const kept=[];\nfor(const scene of project.referenceScenes??[]){"));
test("question 46360: preserves adjacent source contract",()=>has(2,"for(const scene of project.referenceScenes??[]){\nif(Array.isArray(scene.tree)&&scene.tree.length>0){"));
test("question 46361: preserves adjacent source contract",()=>has(2,"if(Array.isArray(scene.tree)&&scene.tree.length>0){\nkept.push(scene);"));
test("question 46362: preserves adjacent source contract",()=>has(2,"kept.push(scene);\ncontinue;"));
test("question 46363: preserves adjacent source contract",()=>has(2,"continue;\nconst runtimeId=runtimeKey(scene);"));
test("question 46364: preserves adjacent source contract",()=>has(2,"const runtimeId=runtimeKey(scene);\nruntimes.delete(runtimeId);"));
test("question 46365: preserves adjacent source contract",()=>has(2,"runtimes.delete(runtimeId);\nfor(const key of [...templates.keys()]){"));
test("question 46366: preserves adjacent source contract",()=>has(2,"for(const key of [...templates.keys()]){\nif(key.startsWith(runtimeId+\"|\"))templates.delete(key);"));
test("question 46367: preserves adjacent source contract",()=>has(2,"if(key.startsWith(runtimeId+\"|\"))templates.delete(key);\nproject.referenceScenes=kept;"));
test("question 46368: preserves adjacent source contract",()=>has(2,"project.referenceScenes=kept;\nbulkSelected.clear();"));
test("question 46369: preserves adjacent source contract",()=>has(2,"bulkSelected.clear();\nfunction selectScene(project,sceneId,checked=true){"));
test("question 46370: preserves adjacent source contract",()=>has(2,"function selectScene(project,sceneId,checked=true){\nconst scene=findScene(project,sceneId);"));
test("question 46371: preserves adjacent source contract",()=>has(2,"const scene=findScene(project,sceneId);\nif(!scene)return 0;"));
test("question 46372: preserves adjacent source contract",()=>has(2,"if(!scene)return 0;\ntoggleSceneSelection(scene,checked);"));
test("question 46373: preserves adjacent source contract",()=>has(2,"toggleSceneSelection(scene,checked);\nreturn selectedCount(project);"));
test("question 46374: preserves adjacent source contract",()=>has(2,"return selectedCount(project);\nfunction selectNode(project,sceneId,nodeId,checked=true){"));
test("question 46375: preserves adjacent source contract",()=>has(2,"function selectNode(project,sceneId,nodeId,checked=true){\nconst scene=findScene(project,sceneId);"));
test("question 46376: preserves adjacent source contract",()=>has(2,"const node=findNode(scene?.tree,nodeId);\nif(!scene||!node||!selectableNode(node))return selectedCount(project);"));
test("question 46377: preserves adjacent source contract",()=>has(2,"if(!scene||!node||!selectableNode(node))return selectedCount(project);\ntoggleNodeSelection(scene,node,checked);"));
test("question 46378: preserves adjacent source contract",()=>has(2,"toggleNodeSelection(scene,node,checked);\nreturn selectedCount(project);"));
test("question 46379: preserves adjacent source contract",()=>has(2,"return selectedCount(project);\nfunction clearSelection(){"));
test("question 46380: preserves adjacent source contract",()=>has(2,"function clearSelection(){\nbulkSelected.clear();"));
test("question 46381: preserves adjacent source contract",()=>has(2,"bulkSelected.clear();\nrangeAnchorKey=null;"));
test("question 46382: preserves adjacent source contract",()=>has(2,"rangeAnchorKey=null;\nselected=null;"));
test("question 46383: preserves adjacent source contract",()=>has(2,"selected=null;\nreturn 0;"));
test("question 46384: preserves adjacent source contract",()=>has(2,"return 0;\nfunction sceneNodeFromKey(project,key){"));
test("question 46385: preserves adjacent source contract",()=>has(2,"function sceneNodeFromKey(project,key){\nconst text=String(key??\"\");"));
test("question 46386: preserves adjacent source contract",()=>has(2,"const text=String(key??\"\");\nconst split=text.indexOf(\"|\");"));
test("question 46387: preserves adjacent source contract",()=>has(2,"const split=text.indexOf(\"|\");\nif(split<0)return null;"));
test("question 46388: preserves adjacent source contract",()=>has(2,"if(split<0)return null;\nconst sceneId=text.slice(0,split);"));
test("question 46389: preserves adjacent source contract",()=>has(2,"const sceneId=text.slice(0,split);\nconst nodeId=text.slice(split+1);"));
test("question 46390: preserves adjacent source contract",()=>has(2,"const nodeId=text.slice(split+1);\nconst scene=findScene(project,sceneId);"));
test("question 46391: preserves adjacent source contract",()=>has(2,"const node=findNode(scene?.tree,nodeId);\nreturn scene&&node?{scene,node}:null;"));
test("question 46392: preserves adjacent source contract",()=>has(2,"return scene&&node?{scene,node}:null;\nfunction visibleSelectionKeys(host){"));
test("question 46393: preserves adjacent source contract",()=>has(2,"function visibleSelectionKeys(host){\nreturn [...host.querySelectorAll(\"[data-ref-node]\")]"));
test("question 46394: preserves adjacent source contract",()=>has(2,"return [...host.querySelectorAll(\"[data-ref-node]\")]\n.filter((row)=>!row.dataset.refEditablePart)"));
test("question 46395: preserves adjacent source contract",()=>has(2,".filter((row)=>!row.dataset.refEditablePart)\n.map((row)=>selectionKey(row.dataset.refScene,row.dataset.refNode));"));
test("question 46396: preserves adjacent source contract",()=>has(2,".map((row)=>selectionKey(row.dataset.refScene,row.dataset.refNode));\nfunction applyModifierSelection("));
test("question 46397: preserves adjacent source contract",()=>has(2,"function applyModifierSelection(\nproject,"));
test("question 46398: preserves adjacent source contract",()=>has(2,"project,\norderedKeys,"));
test("question 46399: preserves adjacent source contract",()=>has(2,"orderedKeys,\ntargetKey,"));
test("question 46400: preserves adjacent source contract",()=>has(2,"targetKey,\n{ctrlKey=false,metaKey=false,shiftKey=false}={}"));
test("question 46401: preserves adjacent source contract",()=>has(2,"{ctrlKey=false,metaKey=false,shiftKey=false}={}\nconst additive=!!(ctrlKey||metaKey);"));
test("question 46402: preserves adjacent source contract",()=>has(2,"const additive=!!(ctrlKey||metaKey);\nconst target=sceneNodeFromKey(project,targetKey);"));
test("question 46403: preserves adjacent source contract",()=>has(2,"const target=sceneNodeFromKey(project,targetKey);\nif(!target||!selectableNode(target.node))return selectedCount(project);"));
test("question 46404: preserves adjacent source contract",()=>has(2,"if(!target||!selectableNode(target.node))return selectedCount(project);\nif(shiftKey){"));
test("question 46405: preserves adjacent source contract",()=>has(2,"if(shiftKey){\nconst keys=Array.isArray(orderedKeys)?orderedKeys.map(String):[];"));
test("question 46406: preserves adjacent source contract",()=>has(2,"const keys=Array.isArray(orderedKeys)?orderedKeys.map(String):[];\nconst targetIndex=keys.indexOf(String(targetKey));"));
test("question 46407: preserves adjacent source contract",()=>has(2,"const targetIndex=keys.indexOf(String(targetKey));\nlet anchorIndex=keys.indexOf(String(rangeAnchorKey??\"\"));"));
test("question 46408: preserves adjacent source contract",()=>has(2,"let anchorIndex=keys.indexOf(String(rangeAnchorKey??\"\"));\nif(targetIndex<0)return selectedCount(project);"));
test("question 46409: preserves adjacent source contract",()=>has(2,"if(targetIndex<0)return selectedCount(project);\nif(anchorIndex<0){"));
test("question 46410: preserves adjacent source contract",()=>has(2,"if(anchorIndex<0){\nanchorIndex=targetIndex;"));
test("question 46411: preserves adjacent source contract",()=>has(2,"anchorIndex=targetIndex;\nrangeAnchorKey=String(targetKey);"));
test("question 46412: preserves adjacent source contract",()=>has(2,"rangeAnchorKey=String(targetKey);\nif(!additive)bulkSelected.clear();"));
test("question 46413: preserves adjacent source contract",()=>has(2,"if(!additive)bulkSelected.clear();\nconst from=Math.min(anchorIndex,targetIndex);"));
test("question 46414: preserves adjacent source contract",()=>has(2,"const from=Math.min(anchorIndex,targetIndex);\nconst to=Math.max(anchorIndex,targetIndex);"));
test("question 46415: preserves adjacent source contract",()=>has(2,"const to=Math.max(anchorIndex,targetIndex);\nfor(let index=from;index<=to;index+=1){"));
test("question 46416: preserves adjacent source contract",()=>has(2,"for(let index=from;index<=to;index+=1){\nconst entry=sceneNodeFromKey(project,keys[index]);"));
test("question 46417: preserves adjacent source contract",()=>has(2,"const entry=sceneNodeFromKey(project,keys[index]);\nif(entry&&selectableNode(entry.node)){"));
test("question 46418: preserves adjacent source contract",()=>has(2,"if(entry&&selectableNode(entry.node)){\ntoggleNodeSelection(entry.scene,entry.node,true);"));
test("question 46419: preserves adjacent source contract",()=>has(2,"toggleNodeSelection(entry.scene,entry.node,true);\nreturn selectedCount(project);"));
test("question 46420: preserves adjacent source contract",()=>has(2,"return selectedCount(project);\nif(additive){"));
test("question 46421: preserves adjacent source contract",()=>has(2,"if(additive){\nconst key=selectionKey(target.scene.id,target.node.id);"));
test("question 46422: preserves adjacent source contract",()=>has(2,"const key=selectionKey(target.scene.id,target.node.id);\ntoggleNodeSelection("));
test("question 46423: preserves adjacent source contract",()=>has(2,"toggleNodeSelection(\ntarget.scene,"));
test("question 46424: preserves adjacent source contract",()=>has(2,"target.scene,\ntarget.node,"));
test("question 46425: preserves adjacent source contract",()=>has(2,"target.node,\n!bulkSelected.has(key)"));
test("question 46426: preserves adjacent source contract",()=>has(2,"!bulkSelected.has(key)\nrangeAnchorKey=key;"));
test("question 46427: preserves adjacent source contract",()=>has(2,"rangeAnchorKey=key;\nreturn selectedCount(project);"));
test("question 46428: preserves adjacent source contract",()=>has(2,"return selectedCount(project);\nrangeAnchorKey=selectionKey(target.scene.id,target.node.id);"));
test("question 46429: preserves adjacent source contract",()=>has(2,"rangeAnchorKey=selectionKey(target.scene.id,target.node.id);\nreturn selectedCount(project);"));
test("question 46430: preserves adjacent source contract",()=>has(2,"return selectedCount(project);\nfunction selectedKeys(project){"));
test("question 46431: preserves adjacent source contract",()=>has(2,"function selectedKeys(project){\npruneBulkSelection(project);"));
test("question 46432: preserves adjacent source contract",()=>has(2,"pruneBulkSelection(project);\nreturn Object.freeze([...bulkSelected]);"));
test("question 46433: preserves adjacent source contract",()=>has(2,"return Object.freeze([...bulkSelected]);\nfunction replaceSelection(project,keys=[]){"));
test("question 46434: preserves adjacent source contract",()=>has(2,"function replaceSelection(project,keys=[]){\nbulkSelected.clear();"));
test("question 46435: preserves adjacent source contract",()=>has(2,"bulkSelected.clear();\nlet active=null;"));
test("question 46436: preserves adjacent source contract",()=>has(2,"let active=null;\nfor(const key of keys??[]){"));
test("question 46437: preserves adjacent source contract",()=>has(2,"for(const key of keys??[]){\nconst entry=sceneNodeFromKey(project,key);"));
test("question 46438: preserves adjacent source contract",()=>has(2,"const entry=sceneNodeFromKey(project,key);\nif(entry&&selectableNode(entry.node)){"));
test("question 46439: preserves adjacent source contract",()=>has(2,"if(entry&&selectableNode(entry.node)){\nconst normalized=selectionKey(entry.scene.id,entry.node.id);"));
test("question 46440: preserves adjacent source contract",()=>has(2,"const normalized=selectionKey(entry.scene.id,entry.node.id);\nbulkSelected.add(normalized);"));
test("question 46441: preserves adjacent source contract",()=>has(2,"bulkSelected.add(normalized);\nactive={sceneId:String(entry.scene.id),nodeId:String(entry.node.id)};"));
test("question 46442: preserves adjacent source contract",()=>has(2,"active={sceneId:String(entry.scene.id),nodeId:String(entry.node.id)};\nselected=active;"));
test("question 46443: preserves adjacent source contract",()=>has(2,"selected=active;\nrangeAnchorKey=active?selectionKey(active.sceneId,active.nodeId):null;"));
test("question 46444: preserves adjacent source contract",()=>has(2,"rangeAnchorKey=active?selectionKey(active.sceneId,active.nodeId):null;\nreturn selectedCount(project);"));
test("question 46445: preserves adjacent source contract",()=>has(2,"return selectedCount(project);\nfunction selectOnlyNode(project,sceneId,nodeId){"));
test("question 46446: preserves adjacent source contract",()=>has(2,"function selectOnlyNode(project,sceneId,nodeId){\nbulkSelected.clear();"));
test("question 46447: preserves adjacent source contract",()=>has(2,"bulkSelected.clear();\nconst scene=findScene(project,sceneId);"));
test("question 46448: preserves adjacent source contract",()=>has(2,"const node=findNode(scene?.tree,nodeId);\nif(!scene||!node||!selectableNode(node))return 0;"));
test("question 46449: preserves adjacent source contract",()=>has(2,"if(!scene||!node||!selectableNode(node))return 0;\nbulkSelected.add(selectionKey(scene.id,node.id));"));
test("question 46450: preserves adjacent source contract",()=>has(2,"bulkSelected.add(selectionKey(scene.id,node.id));\nrangeAnchorKey=selectionKey(scene.id,node.id);"));
test("question 46451: preserves adjacent source contract",()=>has(2,"rangeAnchorKey=selectionKey(scene.id,node.id);\nselected={sceneId:String(scene.id),nodeId:String(node.id)};"));
test("question 46452: preserves adjacent source contract",()=>has(2,"selected={sceneId:String(scene.id),nodeId:String(node.id)};\nreturn selectedCount(project);"));
test("question 46453: preserves adjacent source contract",()=>has(2,"return selectedCount(project);\nfunction selectedTopLevelEntries(project){"));
test("question 46454: preserves adjacent source contract",()=>has(2,"function selectedTopLevelEntries(project){\nconst entries=selectedEntries(project);"));
test("question 46455: preserves adjacent source contract",()=>has(2,"const entries=selectedEntries(project);\nconst selectedSet=new Set("));
test("question 46456: preserves adjacent source contract",()=>has(2,"const selectedSet=new Set(\nentries.map(({scene,node})=>selectionKey(scene.id,node.id))"));
test("question 46457: preserves adjacent source contract",()=>has(2,"entries.map(({scene,node})=>selectionKey(scene.id,node.id))\nreturn entries.filter(({scene,node})=>"));
test("question 46458: preserves adjacent source contract",()=>has(2,"return entries.filter(({scene,node})=>\n!ancestorsFor(scene.tree,node.id)"));
test("question 46459: preserves adjacent source contract",()=>has(2,"!ancestorsFor(scene.tree,node.id)\n.filter((ancestorId)=>String(ancestorId)!==String(node.id))"));
test("question 46460: preserves adjacent source contract",()=>has(2,".filter((ancestorId)=>String(ancestorId)!==String(node.id))\n.some((ancestorId)=>"));
test("question 46461: preserves adjacent source contract",()=>has(2,".some((ancestorId)=>\nselectedSet.has(selectionKey(scene.id,ancestorId))"));
test("question 46462: preserves adjacent source contract",()=>has(2,"selectedSet.has(selectionKey(scene.id,ancestorId))\nfunction moveSelection(project,deltaMm){"));
test("question 46463: preserves adjacent source contract",()=>has(2,"function moveSelection(project,deltaMm){\nconst delta={"));
test("question 46464: preserves adjacent source contract",()=>has(2,"const delta={\nx:Number(deltaMm?.x)||0,"));
test("question 46465: preserves adjacent source contract",()=>has(2,"x:Number(deltaMm?.x)||0,\ny:Number(deltaMm?.y)||0,"));
test("question 46466: preserves adjacent source contract",()=>has(2,"y:Number(deltaMm?.y)||0,\nz:Number(deltaMm?.z)||0"));
test("question 46467: preserves adjacent source contract",()=>has(2,"z:Number(deltaMm?.z)||0\nif(!delta.x&&!delta.y&&!delta.z)return {count:0,instance_ids:[]};"));
test("question 46468: preserves adjacent source contract",()=>has(2,"if(!delta.x&&!delta.y&&!delta.z)return {count:0,instance_ids:[]};\nconst entries=selectedTopLevelEntries(project);"));
test("question 46469: preserves adjacent source contract",()=>has(2,"const entries=selectedTopLevelEntries(project);\nconst instanceIds=[];"));
test("question 46470: preserves adjacent source contract",()=>has(2,"const instanceIds=[];\nfor(const {scene,node} of entries){"));
test("question 46471: preserves adjacent source contract",()=>has(2,"for(const {scene,node} of entries){\nconst instance=ensureEditableMeshInstance(project,scene,node);"));
test("question 46472: preserves adjacent source contract",()=>has(2,"const instance=ensureEditableMeshInstance(project,scene,node);\nmoveEditableMeshInstance(project,instance.id,delta);"));
test("question 46473: preserves adjacent source contract",()=>has(2,"moveEditableMeshInstance(project,instance.id,delta);\ninstanceIds.push(String(instance.id));"));
test("question 46474: preserves adjacent source contract",()=>has(2,"instanceIds.push(String(instance.id));\nreturn {count:instanceIds.length,instance_ids:instanceIds};"));
test("question 46475: preserves adjacent source contract",()=>has(2,"return {count:instanceIds.length,instance_ids:instanceIds};\nfunction applyBulkAction(project,action){"));
test("question 46476: preserves adjacent source contract",()=>has(2,"function applyBulkAction(project,action){\nconst command=String(action??\"\");"));
test("question 46477: preserves adjacent source contract",()=>has(2,"const command=String(action??\"\");\nif(command===\"clear\")return clearSelection();"));
test("question 46478: preserves adjacent source contract",()=>has(2,"if(command===\"clear\")return clearSelection();\nif(![\"show\",\"hide\",\"transparent\"].includes(command)){"));
test("question 46479: preserves adjacent source contract",()=>has(2,"if(![\"show\",\"hide\",\"transparent\"].includes(command)){\nthrow new RangeError(\"Immutable Source / Reference does not support bulk action: \"+command);"));
test("question 46480: preserves adjacent source contract",()=>has(2,"throw new RangeError(\"Immutable Source / Reference does not support bulk action: \"+command);\nif(!bulkSelected.size)return 0;"));
test("question 46481: preserves adjacent source contract",()=>has(2,"if(!bulkSelected.size)return 0;\nif(command===\"show\")applyBulkVisibility(project,true);"));
test("question 46482: preserves adjacent source contract",()=>has(2,"if(command===\"show\")applyBulkVisibility(project,true);\nelse if(command===\"hide\")applyBulkVisibility(project,false);"));
test("question 46483: preserves adjacent source contract",()=>has(2,"else if(command===\"hide\")applyBulkVisibility(project,false);\nelse if(command===\"transparent\")applyBulkTransparency(project);"));
test("question 46484: preserves adjacent source contract",()=>has(2,"else if(command===\"transparent\")applyBulkTransparency(project);\nreturn selectedCount(project);"));
test("question 46485: preserves adjacent source contract",()=>has(2,"return selectedCount(project);\nfunction revealNode(project,sceneId,nodeId){"));
test("question 46486: preserves adjacent source contract",()=>has(2,"function revealNode(project,sceneId,nodeId){\nconst scene=findScene(project,sceneId);"));
test("question 46487: preserves adjacent source contract",()=>has(2,"const node=findNode(scene?.tree,nodeId);\nif(!scene||!node)return false;"));
test("question 46488: preserves adjacent source contract",()=>has(2,"if(!scene||!node)return false;\nproject.referenceGeometryTreeCollapsed=false;"));
test("question 46489: preserves adjacent source contract",()=>has(2,"project.referenceGeometryTreeCollapsed=false;\nscene.treeCollapsed=false;"));
test("question 46490: preserves adjacent source contract",()=>has(2,"scene.treeCollapsed=false;\nconst collapsed=new Set("));
test("question 46491: preserves adjacent source contract",()=>has(2,"const collapsed=new Set(\nArray.isArray(scene.collapsedNodeIds)"));
test("question 46492: preserves adjacent source contract",()=>has(2,"? scene.collapsedNodeIds.map(String)\nfor(const ancestorId of ancestorsFor(scene.tree,node.id)){"));
test("question 46493: preserves adjacent source contract",()=>has(2,"for(const ancestorId of ancestorsFor(scene.tree,node.id)){\nif(String(ancestorId)!==String(node.id))collapsed.delete(String(ancestorId));"));
test("question 46494: preserves adjacent source contract",()=>has(2,"if(String(ancestorId)!==String(node.id))collapsed.delete(String(ancestorId));\nscene.collapsedNodeIds=[...collapsed];"));
test("question 46495: preserves adjacent source contract",()=>has(2,"scene.collapsedNodeIds=[...collapsed];\nselected={sceneId:String(scene.id),nodeId:String(node.id)};"));
test("question 46496: preserves adjacent source contract",()=>has(2,"selected={sceneId:String(scene.id),nodeId:String(node.id)};\nreturn true;"));
test("question 46497: preserves adjacent source contract",()=>has(2,"return true;\nfunction notifyExternalSelection(source=\"tree\"){"));
test("question 46498: preserves adjacent source contract",()=>has(2,"function notifyExternalSelection(source=\"tree\"){\nqueueMicrotask(()=>{"));
test("question 46499: preserves adjacent source contract",()=>has(2,"queueMicrotask(()=>{\nwindow.TubeBenderObjectContext?.adoptReferenceSelection?.({source});"));
test("question 46500: preserves adjacent source contract",()=>has(2,"window.TubeBenderObjectContext?.adoptReferenceSelection?.({source});\n}catch(error){"));
test("question 46501: preserves adjacent source contract",()=>has(2,"}catch(error){\nconsole.warn(\"Reference selection synchronization:\",error);"));
test("question 46502: preserves adjacent source contract",()=>has(2,"console.warn(\"Reference selection synchronization:\",error);\nfunction importedEditableTubeById(project,id){"));
test("question 46503: preserves adjacent source contract",()=>has(2,"function importedEditableTubeById(project,id){\nreturn (project?.tubes??[]).find((tube)=>"));
test("question 46504: preserves adjacent source contract",()=>has(2,"return (project?.tubes??[]).find((tube)=>\nString(tube?.id??\"\")===String(id??\"\")&&"));
test("question 46505: preserves adjacent source contract",()=>has(2,"String(tube?.id??\"\")===String(id??\"\")&&\n(tube?.currentProjectImport?.source_format===\"DWFx\"||!!sourceLink(tube))"));
test("question 46506: preserves adjacent source contract",()=>has(2,"(tube?.currentProjectImport?.source_format===\"DWFx\"||!!sourceLink(tube))\n)??null;"));
test("question 46507: preserves adjacent source contract",()=>has(2,")??null;\nfunction mutateSourceLinkDisplay(tube,display){"));
test("question 46508: preserves adjacent source contract",()=>has(2,"function mutateSourceLinkDisplay(tube,display){\nconst link=sourceLink(tube);"));
test("question 46509: preserves adjacent source contract",()=>has(2,"const link=sourceLink(tube);\nif(!link||link.detached===true)throw new Error(\"Editable object is not linked to Source\");"));
test("question 46510: preserves adjacent source contract",()=>has(2,"if(!link||link.detached===true)throw new Error(\"Editable object is not linked to Source\");\nif(![\"hidden\",\"shown\",\"compare\"].includes(display))throw new RangeError(\"Unknown Source display mode\");"));
test("question 46511: preserves adjacent source contract",()=>has(2,"if(![\"hidden\",\"shown\",\"compare\"].includes(display))throw new RangeError(\"Unknown Source display mode\");\nlink.display=display;"));
test("question 46512: preserves adjacent source contract",()=>has(2,"link.display=display;\nlink.status=\"linked\";"));
test("question 46513: preserves adjacent source contract",()=>has(2,"link.status=\"linked\";\nreturn true;"));
test("question 46514: preserves adjacent source contract",()=>has(2,"return true;\nfunction breakSourceLink(tube){"));
test("question 46515: preserves adjacent source contract",()=>has(2,"function breakSourceLink(tube){\nconst link=sourceLink(tube);"));
test("question 46516: preserves adjacent source contract",()=>has(2,"const link=sourceLink(tube);\nif(!link||link.detached===true)return false;"));
test("question 46517: preserves adjacent source contract",()=>has(2,"if(!link||link.detached===true)return false;\nlink.detached=true;"));
test("question 46518: preserves adjacent source contract",()=>has(2,"link.detached=true;\nlink.status=\"detached\";"));
test("question 46519: preserves adjacent source contract",()=>has(2,"link.status=\"detached\";\nlink.display=\"hidden\";"));
test("question 46520: preserves adjacent source contract",()=>has(2,"link.display=\"hidden\";\nreturn true;"));
test("question 46521: preserves adjacent source contract",()=>has(2,"return true;\nfunction runSourceLinkCommand(label,mutate,{modelCommand,save,renderAll,refreshProjectTree,reloadActiveTube}={}){"));
test("question 46522: preserves adjacent source contract",()=>has(2,"function runSourceLinkCommand(label,mutate,{modelCommand,save,renderAll,refreshProjectTree,reloadActiveTube}={}){\nconst ok=typeof modelCommand===\"function\"?modelCommand(label,mutate):mutate();"));
test("question 46523: preserves adjacent source contract",()=>has(2,"const ok=typeof modelCommand===\"function\"?modelCommand(label,mutate):mutate();\nif(ok===false)return false;"));
test("question 46524: preserves adjacent source contract",()=>has(2,"if(ok===false)return false;\nsave?.();"));
test("question 46525: preserves adjacent source contract",()=>has(2,"save?.();\nreloadActiveTube?.();"));
test("question 46526: preserves adjacent source contract",()=>has(2,"reloadActiveTube?.();\nrenderAll?.();"));
test("question 46527: preserves adjacent source contract",()=>has(2,"renderAll?.();\nrefreshProjectTree?.();"));
test("question 46528: preserves adjacent source contract",()=>has(2,"refreshProjectTree?.();\nreturn true;"));
test("question 46529: preserves adjacent source contract",()=>has(2,"return true;\nfunction ensureSourceLinkMenu(){"));
test("question 46530: preserves adjacent source contract",()=>has(2,"function ensureSourceLinkMenu(){\nlet menu=document.getElementById(\"tbSourceLinkMenu\");"));
test("question 46531: preserves adjacent source contract",()=>has(2,"let menu=document.getElementById(\"tbSourceLinkMenu\");\nif(menu)return menu;"));
test("question 46532: preserves adjacent source contract",()=>has(2,"if(menu)return menu;\nmenu=document.createElement(\"div\");"));
test("question 46533: preserves adjacent source contract",()=>has(2,"menu=document.createElement(\"div\");\nmenu.id=\"tbSourceLinkMenu\";"));
test("question 46534: preserves adjacent source contract",()=>has(2,"menu.id=\"tbSourceLinkMenu\";\nmenu.style.cssText=\"position:fixed;display:none;z-index:120700;min-width:230px;padding:5px;border:1px solid #42566d;border-radius:7px;background:#111c28;color:#eef5ff;box-shadow:0 10px 30px rgba(0,0,0,.45);font:12px system-ui\";"));
test("question 46535: preserves adjacent source contract",()=>has(2,"menu.style.cssText=\"position:fixed;display:none;z-index:120700;min-width:230px;padding:5px;border:1px solid #42566d;border-radius:7px;background:#111c28;color:#eef5ff;box-shadow:0 10px 30px rgba(0,0,0,.45);font:12px system-ui\";\ndocument.body.appendChild(menu);"));
test("question 46536: preserves adjacent source contract",()=>has(2,"document.body.appendChild(menu);\ndocument.addEventListener(\"pointerdown\",(event)=>{"));
test("question 46537: preserves adjacent source contract",()=>has(2,"document.addEventListener(\"pointerdown\",(event)=>{\nif(menu.style.display!==\"none\"&&!menu.contains(event.target))menu.style.display=\"none\";"));
test("question 46538: preserves adjacent source contract",()=>has(2,"if(menu.style.display!==\"none\"&&!menu.contains(event.target))menu.style.display=\"none\";\n},true);"));
test("question 46539: preserves adjacent source contract",()=>has(2,"},true);\nreturn menu;"));
test("question 46540: preserves adjacent source contract",()=>has(2,"return menu;\nfunction showSourceLinkMenu(event,project,tube,callbacks={}){"));
test("question 46541: preserves adjacent source contract",()=>has(2,"function showSourceLinkMenu(event,project,tube,callbacks={}){\nconst link=sourceLink(tube);"));
test("question 46542: preserves adjacent source contract",()=>has(2,"const link=sourceLink(tube);\nif(!link)return false;"));
test("question 46543: preserves adjacent source contract",()=>has(2,"if(!link)return false;\nconst menu=ensureSourceLinkMenu();"));
test("question 46544: preserves adjacent source contract",()=>has(2,"const menu=ensureSourceLinkMenu();\nconst linked=link.detached!==true&&!!sourceNodeForTube(project,tube);"));
test("question 46545: preserves adjacent source contract",()=>has(2,"const linked=link.detached!==true&&!!sourceNodeForTube(project,tube);\nconst button=(action,label,disabled=false)=>"));
test("question 46546: preserves adjacent source contract",()=>has(2,"const button=(action,label,disabled=false)=>\n'<button data-source-link-action=\"'+action+'\" '+(disabled?'disabled ':'')+"));
test("question 46547: preserves adjacent source contract",()=>has(2,"'<button data-source-link-action=\"'+action+'\" '+(disabled?'disabled ':'')+\n'style=\"display:block;width:100%;text-align:left;padding:6px 8px;border:0;border-radius:4px;background:transparent;color:'+"));
test("question 46548: preserves adjacent source contract",()=>has(2,"'style=\"display:block;width:100%;text-align:left;padding:6px 8px;border:0;border-radius:4px;background:transparent;color:'+\n(disabled?'#65778b':'#eef5ff')+';cursor:'+(disabled?'default':'pointer')+'\">'+label+'</button>';"));
test("question 46549: preserves adjacent source contract",()=>has(2,"(disabled?'#65778b':'#eef5ff')+';cursor:'+(disabled?'default':'pointer')+'\">'+label+'</button>';\nmenu.innerHTML="));
test("question 46550: preserves adjacent source contract",()=>has(2,"menu.innerHTML=\n'<div style=\"padding:5px 8px;color:#8fa4ba;border-bottom:1px solid #2b3a4b;margin-bottom:4px\">'+"));
test("question 46551: preserves adjacent source contract",()=>has(2,"'<div style=\"padding:5px 8px;color:#8fa4ba;border-bottom:1px solid #2b3a4b;margin-bottom:4px\">'+\nescHtml(tube.name??tube.partNumber??tube.id)+'</div>'+"));
test("question 46552: preserves adjacent source contract",()=>has(2,"escHtml(tube.name??tube.partNumber??tube.id)+'</div>'+\nbutton(\"show\",\"Показать исходник\",!linked)+"));
test("question 46553: preserves adjacent source contract",()=>has(2,"button(\"show\",\"Показать исходник\",!linked)+\nbutton(\"hide\",\"Скрыть исходник\",!linked)+"));
test("question 46554: preserves adjacent source contract",()=>has(2,"button(\"hide\",\"Скрыть исходник\",!linked)+\nbutton(\"compare\",\"Сравнить с исходником\",!linked)+"));
test("question 46555: preserves adjacent source contract",()=>has(2,"button(\"compare\",\"Сравнить с исходником\",!linked)+\nbutton(\"restore\",\"Восстановить из исходника\",!linked||!tube?.currentProjectImport?.source_geometry_snapshot)+"));
test("question 46556: preserves adjacent source contract",()=>has(2,"button(\"restore\",\"Восстановить из исходника\",!linked||!tube?.currentProjectImport?.source_geometry_snapshot)+\nbutton(\"break\",\"Разорвать связь с исходником\",!linked);"));
test("question 46557: preserves adjacent source contract",()=>has(2,"button(\"break\",\"Разорвать связь с исходником\",!linked);\nmenu.style.left=Math.min(window.innerWidth-245,Math.max(6,event.clientX))+\"px\";"));
test("question 46558: preserves adjacent source contract",()=>has(2,"menu.style.left=Math.min(window.innerWidth-245,Math.max(6,event.clientX))+\"px\";\nmenu.style.top=Math.min(window.innerHeight-190,Math.max(6,event.clientY))+\"px\";"));
test("question 46559: preserves adjacent source contract",()=>has(2,"menu.style.top=Math.min(window.innerHeight-190,Math.max(6,event.clientY))+\"px\";\nmenu.style.display=\"block\";"));
test("question 46560: preserves adjacent source contract",()=>has(2,"menu.style.display=\"block\";\nmenu.querySelectorAll(\"[data-source-link-action]\").forEach((item)=>{"));
test("question 46561: preserves adjacent source contract",()=>has(2,"menu.querySelectorAll(\"[data-source-link-action]\").forEach((item)=>{\nitem.addEventListener(\"click\",(click)=>{"));
test("question 46562: preserves adjacent source contract",()=>has(2,"item.addEventListener(\"click\",(click)=>{\nclick.stopPropagation();"));
test("question 46563: preserves adjacent source contract",()=>has(2,"click.stopPropagation();\nif(item.disabled)return;"));
test("question 46564: preserves adjacent source contract",()=>has(2,"if(item.disabled)return;\nconst action=item.dataset.sourceLinkAction;"));
test("question 46565: preserves adjacent source contract",()=>has(2,"const action=item.dataset.sourceLinkAction;\nmenu.style.display=\"none\";"));
test("question 46566: preserves adjacent source contract",()=>has(2,"menu.style.display=\"none\";\nif(action===\"show\"){"));
test("question 46567: preserves adjacent source contract",()=>has(2,"if(action===\"show\"){\nrunSourceLinkCommand(\"Показать исходник\",()=>mutateSourceLinkDisplay(tube,\"shown\"),callbacks);"));
test("question 46568: preserves adjacent source contract",()=>has(2,"runSourceLinkCommand(\"Показать исходник\",()=>mutateSourceLinkDisplay(tube,\"shown\"),callbacks);\n}else if(action===\"hide\"){"));
test("question 46569: preserves adjacent source contract",()=>has(2,"}else if(action===\"hide\"){\nrunSourceLinkCommand(\"Скрыть исходник\",()=>mutateSourceLinkDisplay(tube,\"hidden\"),callbacks);"));
test("question 46570: preserves adjacent source contract",()=>has(2,"runSourceLinkCommand(\"Скрыть исходник\",()=>mutateSourceLinkDisplay(tube,\"hidden\"),callbacks);\n}else if(action===\"compare\"){"));
test("question 46571: preserves adjacent source contract",()=>has(2,"}else if(action===\"compare\"){\nrunSourceLinkCommand(\"Сравнить с исходником\",()=>mutateSourceLinkDisplay(tube,\"compare\"),callbacks);"));
test("question 46572: preserves adjacent source contract",()=>has(2,"runSourceLinkCommand(\"Сравнить с исходником\",()=>mutateSourceLinkDisplay(tube,\"compare\"),callbacks);\n}else if(action===\"restore\"){"));
test("question 46573: preserves adjacent source contract",()=>has(2,"}else if(action===\"restore\"){\nrunSourceLinkCommand(\"Восстановить из исходника\",()=>restoreLinkedTubeGeometry(tube),callbacks);"));
test("question 46574: preserves adjacent source contract",()=>has(2,"runSourceLinkCommand(\"Восстановить из исходника\",()=>restoreLinkedTubeGeometry(tube),callbacks);\n}else if(action===\"break\"){"));
test("question 46575: preserves adjacent source contract",()=>has(2,"}else if(action===\"break\"){\nrunSourceLinkCommand(\"Разорвать связь с исходником\",()=>breakSourceLink(tube),callbacks);"));
test("question 46576: preserves adjacent source contract",()=>has(2,"runSourceLinkCommand(\"Разорвать связь с исходником\",()=>breakSourceLink(tube),callbacks);\nevent.preventDefault();event.stopPropagation();"));
test("question 46577: preserves adjacent source contract",()=>has(2,"event.preventDefault();event.stopPropagation();\nreturn true;"));
test("question 46578: preserves adjacent source contract",()=>has(2,"return true;\nfunction bindTree(host,project,{switchTube,save,renderAll,refreshProjectTree,modelCommand,reloadActiveTube}={}){"));
test("question 46579: preserves adjacent source contract",()=>has(2,"function bindTree(host,project,{switchTube,save,renderAll,refreshProjectTree,modelCommand,reloadActiveTube}={}){\nif(!host||!project)return;"));
test("question 46580: preserves adjacent source contract",()=>has(2,"if(!host||!project)return;\nhost.querySelector(\"[data-ref-root-toggle]\")?.addEventListener(\"click\",(event)=>{"));
test("question 46581: preserves adjacent source contract",()=>has(2,"host.querySelector(\"[data-ref-root-toggle]\")?.addEventListener(\"click\",(event)=>{\nevent.stopPropagation();"));
test("question 46582: preserves adjacent source contract",()=>has(2,"event.stopPropagation();\nproject.referenceGeometryTreeCollapsed=project.referenceGeometryTreeCollapsed!==true;"));
test("question 46583: preserves adjacent source contract",()=>has(2,"project.referenceGeometryTreeCollapsed=project.referenceGeometryTreeCollapsed!==true;\nsave?.();"));
test("question 46584: preserves adjacent source contract",()=>has(2,"save?.();\nrefreshProjectTree?.();"));
test("question 46585: preserves adjacent source contract",()=>has(2,"refreshProjectTree?.();\nhost.querySelector(\"[data-ref-source-toggle]\")?.addEventListener(\"click\",(event)=>{"));
test("question 46586: preserves adjacent source contract",()=>has(2,"host.querySelector(\"[data-ref-source-toggle]\")?.addEventListener(\"click\",(event)=>{\nevent.stopPropagation();"));
test("question 46587: preserves adjacent source contract",()=>has(2,"event.stopPropagation();\nproject.referenceSourceTreeCollapsed=project.referenceSourceTreeCollapsed!==true;"));
test("question 46588: preserves adjacent source contract",()=>has(2,"project.referenceSourceTreeCollapsed=project.referenceSourceTreeCollapsed!==true;\nsave?.();refreshProjectTree?.();"));
test("question 46589: preserves adjacent source contract",()=>has(2,"save?.();refreshProjectTree?.();\nhost.querySelector(\"[data-ref-editable-toggle]\")?.addEventListener(\"click\",(event)=>{"));
test("question 46590: preserves adjacent source contract",()=>has(2,"host.querySelector(\"[data-ref-editable-toggle]\")?.addEventListener(\"click\",(event)=>{\nevent.stopPropagation();"));
test("question 46591: preserves adjacent source contract",()=>has(2,"event.stopPropagation();\nproject.referenceEditableTreeCollapsed=project.referenceEditableTreeCollapsed!==true;"));
test("question 46592: preserves adjacent source contract",()=>has(2,"project.referenceEditableTreeCollapsed=project.referenceEditableTreeCollapsed!==true;\nsave?.();refreshProjectTree?.();"));
test("question 46593: preserves adjacent source contract",()=>has(2,"save?.();refreshProjectTree?.();\nconst rootSelect=host.querySelector(\"[data-ref-root-select]\");"));
test("question 46594: preserves adjacent source contract",()=>has(2,"const rootSelect=host.querySelector(\"[data-ref-root-select]\");\nif(rootSelect){"));
test("question 46595: preserves adjacent source contract",()=>has(2,"if(rootSelect){\nrootSelect.indeterminate=rootSelect.dataset.refIndeterminate===\"1\";"));
test("question 46596: preserves adjacent source contract",()=>has(2,"rootSelect.indeterminate=rootSelect.dataset.refIndeterminate===\"1\";\nrootSelect.addEventListener(\"change\",(event)=>{"));
test("question 46597: preserves adjacent source contract",()=>has(2,"rootSelect.addEventListener(\"change\",(event)=>{\nevent.stopPropagation();"));
test("question 46598: preserves adjacent source contract",()=>has(2,"event.stopPropagation();\nfor(const scene of project.referenceScenes??[])toggleSceneSelection(scene,rootSelect.checked);"));
test("question 46599: preserves adjacent source contract",()=>has(2,"for(const scene of project.referenceScenes??[])toggleSceneSelection(scene,rootSelect.checked);\nconst firstScene=(project.referenceScenes??[])[0]??null;"));
test("question 46600: preserves adjacent source contract",()=>has(2,"const firstScene=(project.referenceScenes??[])[0]??null;\nconst firstNode=firstScene?collectSelectableNodes(firstScene.tree??[])[0]??null:null;"));
test("question 46601: preserves adjacent source contract",()=>has(2,"const firstNode=firstScene?collectSelectableNodes(firstScene.tree??[])[0]??null:null;\nrangeAnchorKey=firstScene&&firstNode?selectionKey(firstScene.id,firstNode.id):null;"));
test("question 46602: preserves adjacent source contract",()=>has(2,"rangeAnchorKey=firstScene&&firstNode?selectionKey(firstScene.id,firstNode.id):null;\nselected=firstScene&&firstNode"));
test("question 46603: preserves adjacent source contract",()=>has(2,"selected=firstScene&&firstNode\n? {sceneId:String(firstScene.id),nodeId:String(firstNode.id)}"));
test("question 46604: preserves adjacent source contract",()=>has(2,"? {sceneId:String(firstScene.id),nodeId:String(firstNode.id)}\nrefreshProjectTree?.();"));
test("question 46605: preserves adjacent source contract",()=>has(2,"refreshProjectTree?.();\nnotifyExternalSelection(\"tree\");"));
test("question 46606: preserves adjacent source contract",()=>has(2,"notifyExternalSelection(\"tree\");\nhost.querySelectorAll(\"[data-ref-scene-toggle]\").forEach((button)=>{"));
test("question 46607: preserves adjacent source contract",()=>has(2,"host.querySelectorAll(\"[data-ref-scene-toggle]\").forEach((button)=>{\nbutton.addEventListener(\"click\",(event)=>{"));
test("question 46608: preserves adjacent source contract",()=>has(2,"button.addEventListener(\"click\",(event)=>{\nevent.stopPropagation();"));
test("question 46609: preserves adjacent source contract",()=>has(2,"event.stopPropagation();\nconst scene=findScene(project,button.dataset.refSceneToggle);"));
test("question 46610: preserves adjacent source contract",()=>has(2,"const scene=findScene(project,button.dataset.refSceneToggle);\nif(!scene)return;"));
test("question 46611: preserves adjacent source contract",()=>has(2,"if(!scene)return;\nscene.treeCollapsed=scene.treeCollapsed!==true;"));
test("question 46612: preserves adjacent source contract",()=>has(2,"scene.treeCollapsed=scene.treeCollapsed!==true;\nsave?.();"));
test("question 46613: preserves adjacent source contract",()=>has(2,"refreshProjectTree?.();\nhost.querySelectorAll(\"[data-ref-scene-select]\").forEach((input)=>{"));
test("question 46614: preserves adjacent source contract",()=>has(2,"host.querySelectorAll(\"[data-ref-scene-select]\").forEach((input)=>{\ninput.indeterminate=input.dataset.refIndeterminate===\"1\";"));
test("question 46615: preserves adjacent source contract",()=>has(2,"input.indeterminate=input.dataset.refIndeterminate===\"1\";\ninput.addEventListener(\"change\",(event)=>{"));
test("question 46616: preserves adjacent source contract",()=>has(2,"input.addEventListener(\"change\",(event)=>{\nevent.stopPropagation();"));
test("question 46617: preserves adjacent source contract",()=>has(2,"event.stopPropagation();\nconst scene=findScene(project,input.dataset.refSceneSelect);"));
test("question 46618: preserves adjacent source contract",()=>has(2,"const scene=findScene(project,input.dataset.refSceneSelect);\nif(!scene)return;"));
test("question 46619: preserves adjacent source contract",()=>has(2,"if(!scene)return;\ntoggleSceneSelection(scene,input.checked);"));
test("question 46620: preserves adjacent source contract",()=>has(2,"toggleSceneSelection(scene,input.checked);\nconst first=collectSelectableNodes(scene.tree??[])[0]??null;"));
test("question 46621: preserves adjacent source contract",()=>has(2,"const first=collectSelectableNodes(scene.tree??[])[0]??null;\nrangeAnchorKey=first?selectionKey(scene.id,first.id):null;"));
test("question 46622: preserves adjacent source contract",()=>has(2,"rangeAnchorKey=first?selectionKey(scene.id,first.id):null;\nselected=first?{sceneId:String(scene.id),nodeId:String(first.id)}:null;"));
test("question 46623: preserves adjacent source contract",()=>has(2,"selected=first?{sceneId:String(scene.id),nodeId:String(first.id)}:null;\nrefreshProjectTree?.();"));
test("question 46624: preserves adjacent source contract",()=>has(2,"notifyExternalSelection(\"tree\");\nhost.querySelectorAll(\"[data-ref-select]\").forEach((input)=>{"));
test("question 46625: preserves adjacent source contract",()=>has(2,"host.querySelectorAll(\"[data-ref-select]\").forEach((input)=>{\ninput.addEventListener(\"change\",(event)=>{"));
test("question 46626: preserves adjacent source contract",()=>has(2,"event.stopPropagation();\nconst row=input.closest(\"[data-ref-scene]\");"));
test("question 46627: preserves adjacent source contract",()=>has(2,"const row=input.closest(\"[data-ref-scene]\");\nconst scene=findScene(project,row?.dataset.refScene);"));
test("question 46628: preserves adjacent source contract",()=>has(2,"const scene=findScene(project,row?.dataset.refScene);\nconst node=findNode(scene?.tree,input.dataset.refSelect);"));
test("question 46629: preserves adjacent source contract",()=>has(2,"const node=findNode(scene?.tree,input.dataset.refSelect);\nif(!scene||!node)return;"));
test("question 46630: preserves adjacent source contract",()=>has(2,"if(!scene||!node)return;\ntoggleNodeSelection(scene,node,input.checked);"));
test("question 46631: preserves adjacent source contract",()=>has(2,"toggleNodeSelection(scene,node,input.checked);\nrangeAnchorKey=selectionKey(scene.id,node.id);"));
test("question 46632: preserves adjacent source contract",()=>has(2,"rangeAnchorKey=selectionKey(scene.id,node.id);\nselected=input.checked"));
test("question 46633: preserves adjacent source contract",()=>has(2,"selected=input.checked\n? {sceneId:String(scene.id),nodeId:String(node.id)}"));
test("question 46634: preserves adjacent source contract",()=>has(2,"? {sceneId:String(scene.id),nodeId:String(node.id)}\n: selected;"));
test("question 46635: preserves adjacent source contract",()=>has(2,": selected;\nrefreshProjectTree?.();"));
test("question 46636: preserves adjacent source contract",()=>has(2,"notifyExternalSelection(\"tree\");\nhost.querySelectorAll(\"[data-ref-bulk-action]\").forEach((button)=>{"));
test("question 46637: preserves adjacent source contract",()=>has(2,"host.querySelectorAll(\"[data-ref-bulk-action]\").forEach((button)=>{\nbutton.addEventListener(\"click\",(event)=>{"));
test("question 46638: preserves adjacent source contract",()=>has(2,"event.stopPropagation();\nconst action=button.dataset.refBulkAction;"));
test("question 46639: preserves adjacent source contract",()=>has(2,"const action=button.dataset.refBulkAction;\nif(action===\"clear\"){"));
test("question 46640: preserves adjacent source contract",()=>has(2,"if(action===\"clear\"){\nclearSelection();"));
test("question 46641: preserves adjacent source contract",()=>has(2,"clearSelection();\nrefreshProjectTree?.();"));
test("question 46642: preserves adjacent source contract",()=>has(2,"refreshProjectTree?.();\nif(!bulkSelected.size)return;"));
test("question 46643: preserves adjacent source contract",()=>has(2,"if(!bulkSelected.size)return;\nconst mutate=()=>applyBulkAction(project,action);"));
test("question 46644: preserves adjacent source contract",()=>has(2,"const mutate=()=>applyBulkAction(project,action);\nmutate();"));
test("question 46645: preserves adjacent source contract",()=>has(2,"mutate();\nsave?.();"));
test("question 46646: preserves adjacent source contract",()=>has(2,"save?.();\nrenderAll?.();"));
test("question 46647: preserves adjacent source contract",()=>has(2,"refreshProjectTree?.();\nhost.querySelectorAll(\"[data-ref-scene-eye]\").forEach((button)=>{"));
test("question 46648: preserves adjacent source contract",()=>has(2,"host.querySelectorAll(\"[data-ref-scene-eye]\").forEach((button)=>{\nbutton.addEventListener(\"click\",(event)=>{"));
