import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const ui=fs.readFileSync(path.join(root,"src","ui","measurements-ui.js"),"utf8");
const has=s=>assert.ok(ui.includes(s), "missing source contract: "+s);

test("question 1759: canonical review-progress signature comes from runtime",()=>has("const canonicalManagerReviewProgressSignature=managerReviewProgressRuntime.signature;"));
test("question 1760: canonical review-progress source comes from runtime",()=>has("const canonicalManagerReviewProgressSource=managerReviewProgressRuntime.source;"));
test("question 1761: legacy diagnostics model receives reason count",()=>has("reason_count:reviewReasonEntries.length,"));
test("question 1762: legacy diagnostics model validates reason coverage count",()=>has("count_consistent:reviewReasonCoverageCounts.complete+reviewReasonPendingCount===reviewReasonEntries.length,"));
test("question 1763: legacy diagnostics model validates completed and pending lists",()=>has("lists_consistent:reviewReasonCompletedNames.length===reviewReasonCoverageCounts.complete&&reviewReasonPendingNames.length===reviewReasonPendingCount,"));
test("question 1764: legacy diagnostics model carries model consistency",()=>has("model_consistent:sharedManagerReviewProgressConsistent,"));
test("question 1765: legacy diagnostics model carries domain status",()=>has("domain_status:managerReviewProgressRuntime.domain_status,"));
test("question 1766: legacy diagnostics model carries domain consistency",()=>has("domain_consistent:domainManagerReviewProgressConsistent"));
test("question 1767: standalone diagnostics runtime is computed from current items and selection",()=>has("const standaloneManagerReviewDiagnosticsRuntime=dimensionReviewProgressDiagnosticsRuntimeState(items,selectedDimensionAuditIds());"));
test("question 1768: manager diagnostics model comes from standalone runtime",()=>has("const managerReviewDiagnosticsModel=standaloneManagerReviewDiagnosticsRuntime.diagnostics;"));
test("question 1769: diagnostics errors are exposed from model",()=>has("const reviewReasonProgressErrors=managerReviewDiagnosticsModel.errors;"));
test("question 1770: diagnostics issue count is exposed from model",()=>has("const reviewReasonProgressIssueCount=managerReviewDiagnosticsModel.issue_count;"));
test("question 1771: diagnostics primary error is exposed from model",()=>has("const reviewReasonProgressError=managerReviewDiagnosticsModel.primary_error;"));
test("question 1772: diagnostics validity is exposed from model",()=>has("const reviewReasonDiagnosticsValid=managerReviewDiagnosticsModel.valid;"));
test("question 1773: diagnostics status is exposed from model",()=>has("const reviewReasonProgressStatus=managerReviewDiagnosticsModel.status;"));
test("question 1774: diagnostics consistency requires issue-count consistency",()=>has("managerReviewDiagnosticsModel.issue_count_consistent"));
test("question 1775: diagnostics consistency requires valid error codes",()=>has("&&managerReviewDiagnosticsModel.error_codes_valid;"));
test("question 1776: diagnostics signature comes from standalone runtime",()=>has("const managerReviewDiagnosticsSignature=standaloneManagerReviewDiagnosticsRuntime.signature;"));
test("question 1777: standalone diagnostics consistency compares legacy and runtime signatures",()=>has("dimensionReviewProgressDiagnosticsSignature(legacyManagerReviewDiagnosticsModel)===managerReviewDiagnosticsSignature;"));
test("question 1778: diagnostics integrity parity receives standalone runtime",()=>has("const managerReviewDiagnosticsIntegrityParity=dimensionReviewProgressDiagnosticsIntegrityParity("));
test("question 1779: diagnostics integrity parity receives standalone consistency",()=>has("standaloneManagerReviewDiagnosticsConsistent"));
test("question 1780: diagnostics integrity receives standalone runtime",()=>has("const managerReviewDiagnosticsIntegrity=dimensionReviewProgressDiagnosticsIntegrity("));
test("question 1781: diagnostics integrity receives standalone consistency",()=>has("standaloneManagerReviewDiagnosticsConsistent,"));
test("question 1782: diagnostics integrity conditionally receives parity consistency",()=>has("managerReviewDiagnosticsIntegrityParity.available?managerReviewDiagnosticsIntegrityParity.consistent:null"));
test("question 1783: diagnostics integrity signature is derived from integrity state",()=>has("dimensionReviewProgressDiagnosticsIntegritySignature(managerReviewDiagnosticsIntegrity);"));
test("question 1784: full review queue requires needs-review filter",()=>has("const fullReviewQueueActive=dimensionManagerFilter===\"needs-review\"&&dimensionManagerSort===\"audit\"&&!dimensionManagerSearch;"));
test("question 1785: active review reason is derived centrally",()=>has("const activeReviewReason=activeDimensionReviewReason();"));
test("question 1786: visible manager items use filtered manager items",()=>has("const visibleItems=filteredDimensionManagerItems(items);"));
test("question 1787: selected dimension ids are captured once for rendering",()=>has("const selectedIds=selectedDimensionAuditIds();"));
test("question 1788: selected id set is built for constant-time lookup",()=>has("const selectedIdSet=new Set(selectedIds);"));
test("question 1789: selected review-queue count requires selected id and needs-review",()=>has("selectedIdSet.has(String(dimension?.id??\"\"))&&dimensionAuditNeedsReview(dimension)"));
test("question 1790: unselected review-queue count is clamped at zero",()=>has("const unselectedReviewQueueCount=Math.max(0,auditSummary.needs_review-selectedReviewQueueCount);"));
test("question 1791: selected review-queue percent is rounded",()=>has("const selectedReviewQueuePercent=auditSummary.needs_review?Math.round(selectedReviewQueueCount/auditSummary.needs_review*100):0;"));
test("question 1792: review-queue coverage distinguishes none complete and partial",()=>has("const selectedReviewQueueCoverage=selectedReviewQueueCount===0?\"none\":selectedReviewQueueCount===auditSummary.needs_review?\"complete\":\"partial\";"));
test("question 1793: active reason ids are derived from matching audit reasons",()=>has("items.filter(dimension=>dimensionAuditReviewReasons(dimension).includes(activeReviewReason)).map(dimension=>String(dimension?.id??\"\"))"));
test("question 1794: no active reason yields empty reason-id list",()=>has(":[];"));
test("question 1795: selected reason count filters active reason ids by selection",()=>has("const selectedReviewReasonCount=activeReviewReasonIds.filter(id=>selectedIdSet.has(id)).length;"));
test("question 1796: selected reason percent is rounded",()=>has("const selectedReviewReasonPercent=activeReviewReasonIds.length?Math.round(selectedReviewReasonCount/activeReviewReasonIds.length*100):0;"));
test("question 1797: selected reason coverage distinguishes none complete and partial",()=>has("const selectedReviewReasonCoverage=selectedReviewReasonCount===0?\"none\":selectedReviewReasonCount===activeReviewReasonIds.length?\"complete\":\"partial\";"));
test("question 1798: selection-kind summary comes from dimension selection kind counts",()=>has("const selectionKindSummary=Object.entries(dimensionSelectionKindCounts())"));
test("question 1799: selection-kind summary renders kind and count",()=>has(".map(([kind,count])=>kind+\": \"+count).join(\" · \");"));
test("question 1800: visible id set is built from visible manager items",()=>has("const visibleIdSet=new Set(visibleItems.map(dimension=>String(dimension?.id??\"\")));"));
test("question 1801: selected-in-view count intersects selected ids and visible ids",()=>has("const selectedInViewCount=selectedIds.filter(id=>visibleIdSet.has(String(id))).length;"));
test("question 1802: selected-outside-view count is derived by subtraction",()=>has("const selectedOutsideViewCount=selectedIds.length-selectedInViewCount;"));
test("question 1803: selectable visible count excludes hidden dimensions",()=>has("const selectableVisibleCount=visibleItems.filter(dimension=>dimension?.visible!==false).length;"));
test("question 1804: manager rows are built from visible items",()=>has("const rows=visibleItems.map(dimension=>{"));
test("question 1805: row stale flag is based on Stale status",()=>has("const stale=String(dimension.status)===\"Stale\",visible=dimension.visible!==false;"));
test("question 1806: row selected flag uses selected id set",()=>has("const selected=selectedIdSet.has(String(dimension?.id??\"\"));"));
test("question 1807: row review context uses manager review-context state",()=>has("const reviewContext=dimensionReviewContext(dimension,managerReviewContextState);"));
test("question 1808: angle dimensions use degree units",()=>has("const unit=/angle/i.test(String(dimension.kind))?\"deg\":\"mm\";"));
test("question 1809: finite dimension values are formatted while invalid values show dash",()=>has("const valueText=Number.isFinite(Number(dimension.value))?formatted(Number(dimension.value),unit):\"—\";"));
test("question 1810: rebound count safely handles missing history",()=>has("const rebindCount=Array.isArray(dimension.rebound_history)?dimension.rebound_history.length:0;"));
test("question 1811: latest rebind comes from last rebound-history entry",()=>has("const latestRebind=rebindCount?dimension.rebound_history[rebindCount-1]:null;"));
test("question 1812: previous source ids are deduplicated",()=>has("const previousSources=latestRebind?[...new Set((latestRebind.previous_references??[]).map(ref=>String(ref?.object_id??\"\")).filter(Boolean))]:[];"));
test("question 1813: current source object ids are deduplicated",()=>has("const sourceObjects=[...new Set((dimension.references??[]).map(ref=>String(ref?.object_id??\"\")).filter(Boolean))];"));
test("question 1814: row geometry class uses audit geometry classifier",()=>has("const geometryClass=dimensionAuditGeometryClass(dimension);"));
test("question 1815: row review reasons use central audit-reason helper",()=>has("const reviewReasons=dimensionAuditReviewReasons(dimension);"));
test("question 1816: needs-review row flag derives from review-reason count",()=>has("const needsReview=reviewReasons.length>0;"));
test("question 1817: fitted stats use central fitted-audit helper",()=>has("const fittedStats=dimensionFittedAuditStats(dimension);"));
test("question 1818: fitted text includes reference count",()=>has("\"Fitted refs: \"+fittedStats.reference_count+"));
test("question 1819: fitted text includes max error in mm",()=>has("\" · max error \"+auditNumber(fittedStats.max_error_mm)+\" mm / \""));
test("question 1820: fitted text includes max angular error",()=>has("auditNumber(fittedStats.max_error_deg)+\"°\"+"));
test("question 1821: fitted text includes minimum confidence",()=>has("\" · min confidence \"+auditNumber(fittedStats.min_confidence)"));
test("question 1822: provenance includes geometry class",()=>has("\"Geometry: \"+geometryClass,"));
test("question 1823: provenance marks dimensions needing review",()=>has("needsReview?\"Audit: Needs review\":null,"));
test("question 1824: provenance includes review reasons",()=>has("reviewReasons.length?(\"Review reasons: \"+reviewReasons.join(\", \")):null,"));
test("question 1825: provenance includes stale reason when available",()=>has("stale&&dimension.stale_reason?(\"Reason: \"+String(dimension.stale_reason)):null,"));
test("question 1826: provenance includes source objects",()=>has("sourceObjects.length?(\"Source: \"+sourceObjects.join(\", \")):null,"));
test("question 1827: provenance records rebound audit count",()=>has("dimension.rebound_from_stale===true?(\"Rebound · audit \"+rebindCount):null,"));
test("question 1828: provenance bits drop empty entries before rendering",()=>has("].filter(Boolean);"));
