import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const ui=fs.readFileSync(path.join(root,"src","ui","measurements-ui.js"),"utf8");

test("question 479: Dimension audit JSON filename helper preserves suffix within hard bounds",()=>{
  const fn=ui.match(/function dimensionAuditJsonFilenameconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)(stem,generatedAt,maxLength=DIMENSION_AUDIT_FILENAME_POLICYconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\).json_default_lengthconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\))const limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\){([const limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)sconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)S]*?)const limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)n  const limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)}/)?.[1]??"";
  assert.match(fn,/const limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)|const limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)|const limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)/);
  assert.match(fn,/const suffix="-"const limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)+stampconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)+"const limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\).json"/);
  assert.match(fn,/const budget=Mathconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\).maxconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)(16,limit-suffixconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\).lengthconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\))/);
  assert.match(fn,/Stringconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)(stemconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)?const limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)?"dimension-audit"const limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\))const limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\).sliceconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)(0,budgetconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\))/);
  assert.match(fn,/return safeStemconst limit=Math\.max\(DIMENSION_AUDIT_FILENAME_POLICY\.json_min_length,Math\.min\(DIMENSION_AUDIT_FILENAME_POLICY\.json_max_length,Math\.trunc\(Number\(maxLength\)\|\|DIMENSION_AUDIT_FILENAME_POLICY\.json_default_length\)\)\)+suffix/);
});
