import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const ui=fs.readFileSync(path.join(root,"src","ui","measurements-ui.js"),"utf8");

test("question 1709: copy final-state snapshot validity is checked",()=>{assert.match(ui,/const auditDownloadHistoryCopyFinalStateSnapshotValid=dimensionAuditDownloadHistoryExportFinalStateSnapshotValid\(auditDownloadHistoryCopyFinalStateSnapshot,"copy",auditDownloadHistoryExportActionStatusSnapshot,auditDownloadHistoryExportPayloadBindingSnapshot,auditDownloadHistorySnapshot,auditDownloadHistoryExportChainSnapshot\)/);});
test("question 1710: download final-state snapshot validity is checked",()=>{assert.match(ui,/const auditDownloadHistoryDownloadFinalStateSnapshotValid=dimensionAuditDownloadHistoryExportFinalStateSnapshotValid\(auditDownloadHistoryDownloadFinalStateSnapshot,"download",auditDownloadHistoryExportActionStatusSnapshot,auditDownloadHistoryExportPayloadBindingSnapshot,auditDownloadHistorySnapshot,auditDownloadHistoryExportChainSnapshot\)/);});
test("question 1711: copy permit ready requires valid final snapshot and ready final state",()=>{assert.match(ui,/const auditDownloadHistoryCopyPermitReady=auditDownloadHistoryCopyFinalStateSnapshotValid&&auditDownloadHistoryCopyFinalState\.ready/);});
test("question 1712: download permit ready requires valid final snapshot and ready final state",()=>{assert.match(ui,/const auditDownloadHistoryDownloadPermitReady=auditDownloadHistoryDownloadFinalStateSnapshotValid&&auditDownloadHistoryDownloadFinalState\.ready/);});
test("question 1713: export ready requires valid authorization snapshot and allowed authorization",()=>{assert.match(ui,/const auditDownloadHistoryExportReady=auditDownloadHistoryExportAuthorizationSnapshotValid&&auditDownloadHistoryExportAuthorization\.allowed/);});
test("question 1714: export action ready requires valid payload binding snapshot and allowed binding",()=>{assert.match(ui,/const auditDownloadHistoryExportActionReady=auditDownloadHistoryExportPayloadBindingSnapshotValid&&auditDownloadHistoryExportPayloadBinding\.allowed/);});
test("question 1715: legacy button contract remains documented for regression coverage",()=>{assert.match(ui,/Compatibility source-contract retained for historical regression coverage/);});
test("question 1716: legacy buttons are gated by export-ready authorization",()=>{assert.match(ui,/auditDownloadHistoryLegacyButtonContract='<button data-copy-dimension-audit-download-history '\+\(auditDownloadHistoryExportReady\?'':'disabled'\)/);});
test("question 1717: legacy button contract is explicitly marked as compatibility-only",()=>{assert.match(ui,/void auditDownloadHistoryLegacyButtonContract/);});
test("question 1718: current action-ready buttons are gated by payload-binding readiness",()=>{assert.match(ui,/auditDownloadHistoryActionReadyButtonContract='<button data-copy-dimension-audit-download-history '\+\(auditDownloadHistoryExportActionReady\?'':'disabled'\)/);});
test("question 1719: current action-ready button contract is explicitly retained",()=>{assert.match(ui,/void auditDownloadHistoryActionReadyButtonContract/);});
test("question 1720: manager captures last audit-download attempt",()=>{assert.match(ui,/const lastAuditDownloadAttempt=dimensionAuditDownloadLastAttempt\(\)/);});
test("question 1721: manager computes review context state from items and selected ids",()=>{assert.match(ui,/const managerReviewContextState=dimensionReviewContextState\(items,selectedDimensionAuditIds\(\)\)/);});
test("question 1722: manager computes review context summary from the shared state",()=>{assert.match(ui,/const managerReviewContextSummary=dimensionReviewContextSummary\(items,managerReviewContextState\)/);});
test("question 1723: status summary is derived from audit summary by-status map",()=>{assert.match(ui,/const statusSummary=Object\.entries\(auditSummary\.by_status\).*join\(' · '\)/);});
test("question 1724: mode summary is derived from audit summary by-mode map",()=>{assert.match(ui,/const modeSummary=Object\.entries\(auditSummary\.by_mode\).*join\(' · '\)/);});
test("question 1725: geometry summary is derived from by-geometry-status map",()=>{assert.match(ui,/const geometrySummary=Object\.entries\(auditSummary\.by_geometry_status\).*join\(' · '\)/);});
test("question 1726: reference summary is derived from reference geometry counts",()=>{assert.match(ui,/const referenceSummary=Object\.entries\(auditSummary\.reference_geometry_counts\).*join\(' · '\)/);});
test("question 1727: review-reason counting only scans dimensions needing review",()=>{assert.match(ui,/for\(const dimension of items\.filter\(dimension=>dimensionAuditNeedsReview\(dimension\)\)\)/);});
test("question 1728: review reasons are counted by normalized string key",()=>{assert.match(ui,/const key=String\(reason\);reviewReasonCounts\[key\]=\(reviewReasonCounts\[key\]\?\?0\)\+1/);});
test("question 1729: review-reason entries are sorted lexically",()=>{assert.match(ui,/const reviewReasonEntries=Object\.entries\(reviewReasonCounts\)\.sort\(\(\[a\],\[b\]\)=>String\(a\)\.localeCompare\(String\(b\)\)\)/);});
test("question 1730: review-reason summary renders reason counts",()=>{assert.match(ui,/const reviewReasonSummary=reviewReasonEntries\.map\(\(\[reason,count\]\)=>reason\+': '\+count\)\.join\(' · '\)/);});
test("question 1731: review-reason selection uses current selected ids",()=>{assert.match(ui,/const reviewReasonSelectedIds=new Set\(selectedDimensionAuditIds\(\)\)/);});
test("question 1732: review-reason coverage initializes none partial complete counters",()=>{assert.match(ui,/const reviewReasonCoverageCounts=\{none:0,partial:0,complete:0\}/);});
test("question 1733: review-reason selected count checks both selected id and matching reason",()=>{assert.match(ui,/reviewReasonSelectedIds\.has\(String\(dimension\?\.id\?\?"\"\)\)&&dimensionAuditReviewReasons\(dimension\)\.includes\(reason\)/);});
test("question 1734: review-reason unselected count is clamped at zero",()=>{assert.match(ui,/const unselectedCount=Math\.max\(0,count-selectedCount\)/);});
test("question 1735: review-reason selected percent is rounded",()=>{assert.match(ui,/const selectedPercent=count\?Math\.round\(selectedCount\/count\*100\):0/);});
test("question 1736: review-reason coverage distinguishes none complete and partial",()=>{assert.match(ui,/const selectionCoverage=selectedCount===0\?"none":selectedCount===count\?"complete":"partial"/);});
test("question 1737: review-reason coverage counter increments selected coverage bucket",()=>{assert.match(ui,/reviewReasonCoverageCounts\[selectionCoverage\]\+\+/);});
test("question 1738: review-reason button embeds selection coverage",()=>{assert.match(ui,/data-selection-coverage="'\+selectionCoverage\+'"/);});
test("question 1739: review-reason active button disables when filter sort and search match",()=>{assert.match(ui,/dimensionManagerFilter==="needs-review"&&dimensionManagerSort==="audit"&&dimensionManagerSearch===reason\?'disabled':''/);});
test("question 1740: pending review-reason count sums partial and none coverage",()=>{assert.match(ui,/const reviewReasonPendingCount=reviewReasonCoverageCounts\.partial\+reviewReasonCoverageCounts\.none/);});
test("question 1741: pending reason names require count greater than selected count",()=>{assert.match(ui,/return count>0&&selectedCount<count/);});
test("question 1742: completed reason names require selected count equal total count",()=>{assert.match(ui,/return count>0&&selectedCount===count/);});
test("question 1743: complete percent is rounded across reason entries",()=>{assert.match(ui,/Math\.round\(reviewReasonCoverageCounts\.complete\/reviewReasonEntries\.length\*100\)/);});
test("question 1744: completion state distinguishes empty complete and pending",()=>{assert.match(ui,/const reviewReasonCompletionState=reviewReasonEntries\.length===0\?"empty":reviewReasonPendingCount===0\?"complete":"pending"/);});
test("question 1745: review-reason progress validates count coverage",()=>{assert.match(ui,/reviewReasonCoverageCounts\.complete\+reviewReasonPendingCount===reviewReasonEntries\.length/);});
test("question 1746: review-reason progress validates completed-name count",()=>{assert.match(ui,/reviewReasonCompletedNames\.length===reviewReasonCoverageCounts\.complete/);});
test("question 1747: review-reason progress validates pending-name count",()=>{assert.match(ui,/reviewReasonPendingNames\.length===reviewReasonPendingCount/);});
test("question 1748: shared manager review progress uses items and current selected ids",()=>{assert.match(ui,/const sharedManagerReviewProgress=dimensionReviewProgress\(items,selectedDimensionAuditIds\(\)\)/);});
test("question 1749: shared review progress checks reason count consistency",()=>{assert.match(ui,/sharedManagerReviewProgress\.reason_count===reviewReasonEntries\.length/);});
test("question 1750: shared review progress checks pending count consistency",()=>{assert.match(ui,/sharedManagerReviewProgress\.pending_count===reviewReasonPendingCount/);});
test("question 1751: shared review progress checks complete percent consistency",()=>{assert.match(ui,/sharedManagerReviewProgress\.complete_percent===reviewReasonCompletePercent/);});
test("question 1752: shared review progress checks completion-state consistency",()=>{assert.match(ui,/sharedManagerReviewProgress\.completion_state===reviewReasonCompletionState/);});
test("question 1753: shared review progress status maps empty valid and error states",()=>{assert.match(ui,/sharedManagerReviewProgress\.status===\(reviewReasonEntries\.length===0\?"empty":reviewReasonProgressValid\?"ok":"error"\)/);});
test("question 1754: manager review-progress runtime is computed from items and selected ids",()=>{assert.match(ui,/const managerReviewProgressRuntime=dimensionReviewProgressRuntimeState\(items,selectedDimensionAuditIds\(\)\)/);});
test("question 1755: runtime exposes domain availability",()=>{assert.match(ui,/const domainManagerReviewProgressAvailable=managerReviewProgressRuntime\.domain_available/);});
test("question 1756: runtime exposes domain compatibility",()=>{assert.match(ui,/const domainManagerReviewProgressCompatible=managerReviewProgressRuntime\.domain_compatible/);});
test("question 1757: runtime exposes domain comparability",()=>{assert.match(ui,/const domainManagerReviewProgressComparable=managerReviewProgressRuntime\.domain_comparable/);});
test("question 1758: runtime exposes domain consistency",()=>{assert.match(ui,/const domainManagerReviewProgressConsistent=managerReviewProgressRuntime\.domain_consistent/);});
