import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const ui=fs.readFileSync(path.join(root,"src","ui","measurements-ui.js"),"utf8");
const has=s=>assert.ok(ui.includes(s),"missing source contract: "+s);

test("question 1829: row markup exposes selected state",()=>has("data-dim-selected=\"'+(selected?'1':'0')+'\""));
test("question 1830: row markup exposes review-context health",()=>has("data-review-context-health=\"'+esc(reviewContext.health)+'\""));
test("question 1831: row markup exposes review-context state",()=>has("data-review-context-state=\"'+esc(reviewContext.state)+'\""));
test("question 1832: row markup exposes review action-required flag",()=>has("data-review-action-required=\"'+(reviewContext.action_required?'1':'0')+'\""));
test("question 1833: selected rows render selected marker",()=>has("(selected?'✓ Selected · ':'')"));
test("question 1834: row title prefers note over kind",()=>has("esc(dimension.note??dimension.kind)"));
test("question 1835: row title defaults missing mode to Reference",()=>has("esc(dimension.mode??\"Reference\")"));
test("question 1836: stale row title renders stale warning",()=>has("(stale?' · ⚠ Stale':' · '+esc(dimension.status??\"NeedsUpdate\"))"));
test("question 1837: non-stale row status defaults to NeedsUpdate",()=>has("esc(dimension.status??\"NeedsUpdate\")"));
test("question 1838: review health is omitted for not-required",()=>has("(reviewContext.health!==\"not-required\"?' · Review '+esc(reviewContext.health):'')"));
test("question 1839: row note renders formatted value text",()=>has("esc(valueText)+' · '"));
test("question 1840: row note renders visible-hidden state",()=>has("(visible?'Visible':'Hidden')"));
test("question 1841: row note renders dimension id",()=>has("esc(dimension.id)+'</div>'"));
test("question 1842: provenance block is conditional on provenance bits",()=>has("(provenanceBits.length?'<div class=\"tb-measure-note\""));
test("question 1843: provenance block carries dimension id",()=>has("data-dim-provenance=\"'+esc(dimension.id)+'\""));
test("question 1844: provenance block marks needs-review rows",()=>has("(needsReview?'data-dim-needs-review=\"1\"':'')"));
test("question 1845: provenance joins entries with middle dot separator",()=>has("esc(provenanceBits.join(' · '))"));
test("question 1846: row appends fitted evidence markup",()=>has("dimensionFittedEvidenceHtml(dimension)+"));
test("question 1847: row appends rebind audit markup",()=>has("dimensionRebindAuditHtml(dimension)+"));
test("question 1848: row action area is rendered",()=>has("'<div class=\"tb-measure-actions\">'+"));
test("question 1849: select button carries dimension id",()=>has("data-dim-manager-select=\"'+esc(dimension.id)+'\""));
test("question 1850: select button exposes current visibility",()=>has("data-select-visible=\"'+(visible?\"1\":\"0\")+'\""));
test("question 1851: hidden select is disabled in readonly mode",()=>has("(!visible&&locked?'disabled title=\"Проект открыт только для просмотра\"':'')"));
test("question 1852: select button switches between Select and Show & Select",()=>has("(visible?'Select':'Show & Select')"));
test("question 1853: visibility button carries dimension id",()=>has("data-dim-manager-visible=\"'+esc(dimension.id)+'\""));
test("question 1854: visibility button exposes current visibility",()=>has("data-visible=\"'+(visible?\"1\":\"0\")+'\""));
test("question 1855: visibility action is disabled in readonly mode",()=>has("(locked?'disabled title=\"Проект открыт только для просмотра\"':'')"));
test("question 1856: visibility button switches between Hide and Show",()=>has("(visible?'Hide':'Show')"));
test("question 1857: delete button carries dimension id",()=>has("data-dim-manager-delete=\"'+esc(dimension.id)+'\""));
test("question 1858: delete button is disabled in readonly mode",()=>has(">Delete</button>"));
test("question 1859: stale section-derived dimensions expose Rebind",()=>has("(stale&&isSectionDerivedDimension(dimension)?'<button data-section-rebind=\"'+esc(dimension.id)+'\""));
test("question 1860: rebind button is disabled in readonly mode",()=>has(">Rebind</button>':'')"));
test("question 1861: empty filtered rows render audit-filter empty state",()=>has("Нет размеров для выбранного audit-фильтра."));
test("question 1862: filter toolbar is marked with dimension-audit-filters",()=>has("data-dimension-audit-filters"));
test("question 1863: all filter is available",()=>has("['all','selected','unselected'"));
test("question 1864: selected filter is available",()=>has("'selected'"));
test("question 1865: unselected filter is available",()=>has("'unselected'"));
test("question 1866: needs-review filter is available",()=>has("'needs-review'"));
test("question 1867: review-action filter is available",()=>has("'review-action'"));
test("question 1868: review-ready filter is available",()=>has("'review-ready'"));
test("question 1869: review-pending filter is available",()=>has("'review-pending'"));
test("question 1870: diagnostics-error filter is available",()=>has("'review-diagnostics-error'"));
test("question 1871: stale filter is available",()=>has("'stale'"));
test("question 1872: rebound filter is available",()=>has("'rebound'"));
test("question 1873: section-derived filter is available",()=>has("'section-derived'"));
test("question 1874: exact filter is available",()=>has("'exact'"));
test("question 1875: fitted filter is available",()=>has("'fitted'"));
test("question 1876: unknown-geometry filter is available",()=>has("'unknown-geometry'"));
test("question 1877: reference filter is available",()=>has("'reference'"));
test("question 1878: driving filter is available",()=>has("'driving'"));
test("question 1879: visible filter is available",()=>has("'visible'"));
test("question 1880: hidden filter is available",()=>has("'hidden'"));
test("question 1881: active filter button is disabled",()=>has("(dimensionManagerFilter===name?'disabled':'')"));
test("question 1882: review-action label includes action-required count",()=>has("'Review action ('+managerReviewContextSummary.action_required+')'"));
test("question 1883: review-ready label includes ready count",()=>has("'Review ready ('+(managerReviewContextSummary.by_health?.ready??0)+')'"));
test("question 1884: review-pending label includes pending count",()=>has("'Review pending ('+(managerReviewContextSummary.by_health?.pending??0)+')'"));
test("question 1885: diagnostics-error label includes diagnostics-error count",()=>has("'Review diagnostics error ('+(managerReviewContextSummary.by_health?.[\"diagnostics-error\"]??0)+')'"));
test("question 1886: sort toolbar is marked with dimension-audit-sort",()=>has("data-dimension-audit-sort"));
test("question 1887: project-order sort is available",()=>has("data-dimension-sort=\"project\""));
test("question 1888: audit-priority sort is available",()=>has("data-dimension-sort=\"audit\""));
test("question 1889: review-context sort is available",()=>has("data-dimension-sort=\"review-context\""));
test("question 1890: active sort button is disabled",()=>has("(dimensionManagerSort===\"project\"?'disabled':'')"));
test("question 1891: review queue exposes selection coverage",()=>has("data-dimension-review-queue data-selection-coverage=\"'+selectedReviewQueueCoverage+'\""));
test("question 1892: empty review queue disables review-queue button",()=>has("auditSummary.needs_review===0||"));
test("question 1893: active full review queue disables review-queue button",()=>has("dimensionManagerFilter===\"needs-review\"&&dimensionManagerSort===\"audit\"&&!dimensionManagerSearch"));
test("question 1894: review queue label includes total needs-review count",()=>has("'>Review queue ('+auditSummary.needs_review"));
test("question 1895: review queue label includes selected count",()=>has("' · selected '+selectedReviewQueueCount"));
test("question 1896: review queue label includes unselected count",()=>has("' · unselected '+unselectedReviewQueueCount"));
test("question 1897: review queue label includes selected percent",()=>has("' · '+selectedReviewQueuePercent+'%"));
test("question 1898: review queue label includes coverage state",()=>has("+selectedReviewQueueCoverage+')'"));
