import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const ui=fs.readFileSync(path.join(root,"src","ui","measurements-ui.js"),"utf8");
const has=s=>assert.ok(ui.includes(s),"missing source contract: "+s);

test("question 1899: select review queue control is rendered when review items exist",()=>has("data-select-dimension-review-queue"));
test("question 1900: select review queue disables when entire queue is selected",()=>has("selectedReviewQueueCount===auditSummary.needs_review?'disabled':''"));
test("question 1901: add review queue control is rendered when review items exist",()=>has("data-add-dimension-review-queue"));
test("question 1902: remove review queue control is rendered when selected review items exist",()=>has("data-remove-dimension-review-queue"));
test("question 1903: invert review queue control is rendered when review items exist",()=>has("data-invert-dimension-review-queue"));
test("question 1904: copy review queue audit control is available",()=>has("data-copy-dimension-review-queue-audit"));
test("question 1905: download review queue audit control is available",()=>has("data-download-dimension-review-queue-audit"));
test("question 1906: active reason exposes select-reason control",()=>has("data-select-dimension-review-reason"));
test("question 1907: select reason disables when full reason queue is selected",()=>has("selectedReviewReasonCount===activeReviewReasonIds.length?'disabled':''"));
test("question 1908: active reason exposes add-reason control",()=>has("data-add-dimension-review-reason"));
test("question 1909: active reason exposes remove-reason control",()=>has("data-remove-dimension-review-reason"));
test("question 1910: remove-reason disables when no reason rows are selected",()=>has("selectedReviewReasonCount?'':'disabled'"));
test("question 1911: active reason exposes invert-reason control",()=>has("data-invert-dimension-review-reason"));
test("question 1912: active reason exposes copy reason-audit control",()=>has("data-copy-dimension-review-reason-audit"));
test("question 1913: active reason exposes download reason-audit control",()=>has("data-download-dimension-review-reason-audit"));
test("question 1914: full review queue exposes exit control",()=>has("data-dimension-review-queue-exit"));
test("question 1915: search toolbar is marked with audit-search attribute",()=>has("data-dimension-audit-search"));
test("question 1916: search input persists current manager search",()=>has('data-dimension-search value="'+esc(dimensionManagerSearch)+'"'));
test("question 1917: search input documents supported search dimensions",()=>has("Search ID, kind, source, stale reason"));
test("question 1918: search apply control is available",()=>has("data-dimension-search-apply"));
test("question 1919: search clear control is available",()=>has("data-dimension-search-clear"));
test("question 1920: search clear disables with empty search",()=>has("!dimensionManagerSearch?'disabled':''"));
test("question 1921: view reset control is available",()=>has("data-dimension-view-reset"));
test("question 1922: view reset disables in default view",()=>has('dimensionManagerFilter==="all"&&dimensionManagerSort==="project"&&!dimensionManagerSearch'));
test("question 1923: manager result title remains Saved Dimensions",()=>has('tb-measure-title">Saved Dimensions'));
test("question 1924: manager description mentions Reference and Driving dimensions",()=>has("Управление сохранёнными Reference/Driving Dimensions"));
test("question 1925: audit summary carries total count",()=>has("Total: '+auditSummary.total"));
test("question 1926: audit summary carries visible count",()=>has("' · Visible: '+auditSummary.visible"));
test("question 1927: audit summary carries hidden count",()=>has("' · Hidden: '+auditSummary.hidden"));
test("question 1928: audit summary carries selected count",()=>has("' · Selected: '+auditSummary.selected"));
test("question 1929: audit summary carries unselected count",()=>has("' · Unselected: '+auditSummary.unselected"));
test("question 1930: audit summary carries needs-review count",()=>has("' · Needs review: '+auditSummary.needs_review"));
test("question 1931: audit summary carries section-derived count",()=>has("' · Section-derived: '+auditSummary.section_derived"));
test("question 1932: audit summary carries stale count",()=>has("' · Stale: '+auditSummary.stale"));
test("question 1933: audit summary carries rebound count",()=>has("' · Rebound: '+auditSummary.rebound"));
test("question 1934: download-history note exposes snapshot source",()=>has("data-history-snapshot-source"));
test("question 1935: download-history note exposes provenance signature",()=>has("data-history-provenance-signature"));
test("question 1936: download-history note exposes provenance validity",()=>has("data-history-provenance-valid"));
test("question 1937: download-history note exposes export readiness",()=>has("data-history-export-ready"));
test("question 1938: download-history note exposes action readiness",()=>has("data-history-export-action-ready"));
test("question 1939: download-history note exposes action-status schema",()=>has("data-history-export-action-status-schema"));
test("question 1940: download-history note exposes action-status code",()=>has("data-history-export-action-status-code"));
test("question 1941: download-history note exposes action-status readiness",()=>has("data-history-export-action-status-ready"));
test("question 1942: download-history note exposes action-status validity",()=>has("data-history-export-action-status-valid"));
test("question 1943: download-history note exposes copy permit readiness",()=>has("data-history-export-copy-permit-ready"));
test("question 1944: download-history note exposes download permit readiness",()=>has("data-history-export-download-permit-ready"));
test("question 1945: copy history button is gated by copy final readiness",()=>has("auditDownloadHistoryCopyPermitReady?'':'disabled'"));
test("question 1946: download history button is gated by download final readiness",()=>has("auditDownloadHistoryDownloadPermitReady?'':'disabled'"));
test("question 1947: clear history button disables when history is empty",()=>has("data-clear-dimension-audit-download-history"));
test("question 1948: copy export events requires valid envelope snapshot and events",()=>has("auditDownloadHistoryExportEventLogEnvelopeSnapshotValid&&auditDownloadHistoryExportEventSummary.total"));
test("question 1949: download export events requires valid envelope snapshot and events",()=>has("data-download-dimension-audit-history-export-events"));
test("question 1950: clear export events control is available",()=>has("data-clear-dimension-audit-history-export-events"));
test("question 1951: last download attempt note is conditional",()=>has("(lastAuditDownloadAttempt?'<div"));
test("question 1952: last download attempt exposes status",()=>has("data-status"));
test("question 1953: last download attempt exposes code",()=>has("data-code"));
test("question 1954: last download attempt exposes signature",()=>has("data-signature"));
test("question 1955: review reason summary is conditional on needs-review count",()=>has("(auditSummary.needs_review?'<div"));
test("question 1956: review summary exposes action-required count",()=>has("data-review-context-action-required"));
test("question 1957: review summary exposes ready count",()=>has("data-review-context-ready"));
test("question 1958: review summary exposes pending count",()=>has("data-review-context-pending"));
test("question 1959: review summary exposes diagnostics-error count",()=>has("data-review-context-diagnostics-error"));
test("question 1960: review summary exposes canonical progress signature",()=>has("data-review-progress-signature"));
test("question 1961: active review reason note exposes selection coverage",()=>has("data-dimension-review-reason-active data-selection-coverage"));
test("question 1962: visible count note reports showing versus total items",()=>has("data-dimension-visible-count"));
test("question 1963: selection scope note reports in-view selection",()=>has("Selected in view: '+selectedInViewCount"));
test("question 1964: selection scope note reports outside-view selection",()=>has("' · outside view: '+selectedOutsideViewCount"));
test("question 1965: exact focus note is conditional on focus id",()=>has("data-dimension-exact-focus"));
test("question 1966: exact focus exposes clear-focus control",()=>has("data-dimension-focus-clear"));
test("question 1967: select visible audit control is available",()=>has("data-select-visible-dimension-audit"));
test("question 1968: add visible audit control is available",()=>has("data-add-visible-dimension-audit"));
test("question 1969: remove visible audit control is available",()=>has("data-remove-visible-dimension-audit"));
test("question 1970: invert visible audit control is available",()=>has("data-invert-visible-dimension-audit"));
test("question 1971: invert visible audit disables when no visible dimensions are selectable",()=>has("selectableVisibleCount===0?'disabled':''"));
test("question 1972: clear dimension selection control is available",()=>has("data-clear-dimension-selection"));
test("question 1973: clear selection disables with empty selection",()=>has("selectedIds.length===0?'disabled':''"));
test("question 1974: prune selection control is available",()=>has("data-prune-dimension-selection"));
test("question 1975: prune selection disables when nothing is outside the view",()=>has("selectedOutsideViewCount===0?'disabled':''"));
test("question 1976: show audit results control is available",()=>has("data-show-dimension-audit"));
test("question 1977: show-and-select audit results control is available",()=>has("data-show-select-dimension-audit"));
test("question 1978: hide audit results control is available",()=>has("data-hide-dimension-audit"));
test("question 1979: selected audit copy control is available",()=>has("data-copy-selected-dimension-audits"));
test("question 1980: selected audit download control is available",()=>has("data-download-selected-dimension-audits"));
test("question 1981: visible audit copy control is available",()=>has("data-copy-visible-dimension-audits"));
test("question 1982: visible audit download control is available",()=>has("data-download-visible-dimension-audits"));
test("question 1983: all audit copy control is available",()=>has("data-copy-all-dimension-audits"));
test("question 1984: all audit download control is available",()=>has("data-download-all-dimension-audits"));
test("question 1985: manager select binding reveals hidden dimension before selecting",()=>has("if(!visible)window.TubeBenderDimensionGrips?.setDimensionVisible?.(id,true);"));
test("question 1986: manager select binding selects dimension through grips API",()=>has("window.TubeBenderDimensionGrips?.selectDimension?.(id);"));
test("question 1987: manager select binding rerenders after selection",()=>has("window.TubeBenderDimensionGrips?.selectDimension?.(id);\n        render();"));
test("question 1988: visibility binding toggles dimension visibility",()=>has("setDimensionVisible?.(button.dataset.dimManagerVisible,!visible)"));
test("question 1989: delete binding deletes through grips API",()=>has("deleteDimension?.(button.dataset.dimManagerDelete)"));
test("question 1990: copy rebind-audit binding delegates dimension id",()=>has("copyDimensionRebindAudit(button.dataset.copyRebindAudit)"));
test("question 1991: download rebind-audit binding delegates dimension id",()=>has("downloadDimensionRebindAudit(button.dataset.downloadRebindAudit)"));
test("question 1992: clear dimension selection binding uses central action",()=>has('addEventListener("click",clearDimensionSelection)'));
test("question 1993: prune selection binding uses central action",()=>has('addEventListener("click",pruneDimensionSelectionToAuditView)'));
test("question 1994: show audit binding uses central action",()=>has('addEventListener("click",showDimensionAuditResults)'));
test("question 1995: show-select audit binding uses central action",()=>has('addEventListener("click",showAndSelectDimensionAuditResults)'));
test("question 1996: hide audit binding uses central action",()=>has('addEventListener("click",hideDimensionAuditResults)'));
test("question 1997: section-derived panel only includes section-derived dimensions",()=>has("const items=savedDimensions().filter(isSectionDerivedDimension);"));
test("question 1998: saving a Reference Dimension is blocked in readonly mode",()=>has('if(readonly()){toast("Проект открыт только для просмотра");return;}'));
