import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const files=["src/ui/section-view-runtime.js","src/ui/associative-array-runtime.js","src/ui/normalize-geometry-runtime.js"];
const sources=files.map(rel=>fs.readFileSync(path.join(root,rel),"utf8"));
const has=(fileIndex,snippet)=>assert.ok(sources[fileIndex].includes(snippet),"missing source contract: "+files[fileIndex]+"::"+snippet);
test("question 25299: preserves geometry runtime source contract",()=>has(0,"const SECTION_URL=\"__TB_SECTION_VIEW_MODULE_URL__\";"));
test("question 25300: preserves geometry runtime source contract",()=>has(0,"const SECTION_DERIVED_URL=\"__TB_SECTION_DERIVED_MODULE_URL__\";"));
test("question 25301: preserves geometry runtime source contract",()=>has(0,"let domain=null,derived=null,installed=false,panel=null,toggle=null,helperGroup=null,selectionOverlay=null;"));
test("question 25302: preserves geometry runtime source contract",()=>has(0,"const derivedSelectionRegistry=new Map();"));
test("question 25303: preserves geometry runtime source contract",()=>has(0,"const eng=()=>window.TubeBenderEngineering??null;"));
test("question 25304: preserves geometry runtime source contract",()=>has(0,"const project=()=>{try{return eng()?.activeProject?.()??null;}catch{return null;}};"));
test("question 25305: preserves geometry runtime source contract",()=>has(0,"const toast=m=>{try{eng()?.toast?.(String(m??\"\"));}catch{}};"));
test("question 25306: preserves geometry runtime source contract",()=>has(0,"const sceneScale=()=>typeof GEOM_SCALE===\"number\"&&Number.isFinite(GEOM_SCALE)&&Math.abs(GEOM_SCALE)>1e-12?GEOM_SCALE:1;"));
test("question 25307: preserves geometry runtime source contract",()=>has(0,"const esc=v=>String(v??\"\").replace(/[&<>\"']/g,ch=>({\"&\":\"&amp;\",\"<\":\"&lt;\",\">\":\"&gt;\",'\"':\"&quot;\",\"'\":\"&#39;\"}[ch]));"));
test("question 25308: preserves geometry runtime source contract",()=>has(0,"function command(label,mutate){"));
test("question 25309: preserves geometry runtime source contract",()=>has(0,"const fn=eng()?.modelCommand;let ok;"));
test("question 25310: preserves geometry runtime source contract",()=>has(0,"try{ok=typeof fn===\"function\"?fn(label,mutate):mutate();}catch(error){toast(error?.message??error);return false;}"));
test("question 25311: preserves geometry runtime source contract",()=>has(0,"if(ok===false)return false;"));
test("question 25312: preserves geometry runtime source contract",()=>has(0,"try{eng()?.save?.();}catch{}"));
test("question 25313: preserves geometry runtime source contract",()=>has(0,"apply();renderPanel();dispatch();return true;"));
test("question 25314: preserves geometry runtime source contract",()=>has(0,"function current(){return domain.ensureSectionViewState(project());}"));
test("question 25315: preserves geometry runtime source contract",()=>has(0,"function planeToThree(input){"));
test("question 25316: preserves geometry runtime source contract",()=>has(0,"if(typeof THREE===\"undefined\")return null;"));
test("question 25317: preserves geometry runtime source contract",()=>has(0,"let n=new THREE.Vector3(input.normal.x,input.normal.y,input.normal.z).normalize();"));
test("question 25318: preserves geometry runtime source contract",()=>has(0,"if(input.flipped)n.multiplyScalar(-1);"));
test("question 25319: preserves geometry runtime source contract",()=>has(0,"const scale=sceneScale(),p=new THREE.Vector3(input.point.x*scale,input.point.y*scale,input.point.z*scale);"));
test("question 25320: preserves geometry runtime source contract",()=>has(0,"return new THREE.Plane().setFromNormalAndCoplanarPoint(n,p);"));
test("question 25321: preserves geometry runtime source contract",()=>has(0,"function boxToPlanes(box){"));
test("question 25322: preserves geometry runtime source contract",()=>has(0,"if(typeof THREE===\"undefined\")return [];"));
test("question 25323: preserves geometry runtime source contract",()=>has(0,"const {min,max}=box,scale=sceneScale();"));
test("question 25324: preserves geometry runtime source contract",()=>has(0,"new THREE.Plane(new THREE.Vector3( 1,0,0),-min.x*scale),"));
test("question 25325: preserves geometry runtime source contract",()=>has(0,"new THREE.Plane(new THREE.Vector3(-1,0,0), max.x*scale),"));
test("question 25326: preserves geometry runtime source contract",()=>has(0,"new THREE.Plane(new THREE.Vector3(0, 1,0),-min.y*scale),"));
test("question 25327: preserves geometry runtime source contract",()=>has(0,"new THREE.Plane(new THREE.Vector3(0,-1,0), max.y*scale),"));
test("question 25328: preserves geometry runtime source contract",()=>has(0,"new THREE.Plane(new THREE.Vector3(0,0, 1),-min.z*scale),"));
test("question 25329: preserves geometry runtime source contract",()=>has(0,"new THREE.Plane(new THREE.Vector3(0,0,-1), max.z*scale)"));
test("question 25330: preserves geometry runtime source contract",()=>has(0,"function clearSelectionOverlay(){"));
test("question 25331: preserves geometry runtime source contract",()=>has(0,"if(!selectionOverlay)return;"));
test("question 25332: preserves geometry runtime source contract",()=>has(0,"try{selectionOverlay.parent?.remove(selectionOverlay);}catch{}"));
test("question 25333: preserves geometry runtime source contract",()=>has(0,"try{selectionOverlay.traverse(obj=>{obj.geometry?.dispose?.();if(Array.isArray(obj.material))obj.material.forEach(m=>m?.dispose?.());else obj.material?.dispose?.();});}catch{}"));
test("question 25334: preserves geometry runtime source contract",()=>has(0,"selectionOverlay=null;"));
test("question 25335: preserves geometry runtime source contract",()=>has(0,"function renderSelectionOverlay(entries=null){"));
test("question 25336: preserves geometry runtime source contract",()=>has(0,"clearSelectionOverlay();"));
test("question 25337: preserves geometry runtime source contract",()=>has(0,"if(typeof THREE===\"undefined\"||typeof pipeGroup===\"undefined\"||!pipeGroup)return false;"));
test("question 25338: preserves geometry runtime source contract",()=>has(0,"const selectedEntries=Array.isArray(entries)?entries:(window.TubeBenderObjectContext?.selectionEntries?.()??[]);"));
test("question 25339: preserves geometry runtime source contract",()=>has(0,"const records=selectedEntries"));
test("question 25340: preserves geometry runtime source contract",()=>has(0,".filter(entry=>entry?.kind===\"section-derived\")"));
test("question 25341: preserves geometry runtime source contract",()=>has(0,".map(entry=>derivedSelectionById(entry.derivedId))"));
test("question 25342: preserves geometry runtime source contract",()=>has(0,".filter(record=>record?.segment?.start&&record?.segment?.end);"));
test("question 25343: preserves geometry runtime source contract",()=>has(0,"if(!records.length){try{if(typeof markViewerDirty===\"function\")markViewerDirty();}catch{}return false;}"));
test("question 25344: preserves geometry runtime source contract",()=>has(0,"const scale=sceneScale(),group=new THREE.Group();group.id=\"tbSectionDerivedSelectionOverlay\";"));
test("question 25345: preserves geometry runtime source contract",()=>has(0,"group.userData={helper:true,objectSelectionHelper:true,sectionDerivedSelection:true};"));
test("question 25346: preserves geometry runtime source contract",()=>has(0,"for(const record of records){"));
test("question 25347: preserves geometry runtime source contract",()=>has(0,"const a=record.segment.start,b=record.segment.end;"));
test("question 25348: preserves geometry runtime source contract",()=>has(0,"const points=[new THREE.Vector3(a.x*scale,a.y*scale,a.z*scale),new THREE.Vector3(b.x*scale,b.y*scale,b.z*scale)];"));
test("question 25349: preserves geometry runtime source contract",()=>has(0,"const line=new THREE.Line("));
test("question 25350: preserves geometry runtime source contract",()=>has(0,"new THREE.BufferGeometry().setFromPoints(points),"));
test("question 25351: preserves geometry runtime source contract",()=>has(0,"new THREE.LineBasicMaterial({depthTest:false,depthWrite:false})"));
test("question 25352: preserves geometry runtime source contract",()=>has(0,"line.renderOrder=11940;line.userData={helper:true,objectSelectionHelper:true,sectionDerivedSelection:true,derivedId:record.id};group.add(line);"));
test("question 25353: preserves geometry runtime source contract",()=>has(0,"for(const p of points){"));
test("question 25354: preserves geometry runtime source contract",()=>has(0,"const marker=new THREE.Mesh(new THREE.SphereGeometry(Math.max(.025,2.5*scale),10,7),new THREE.MeshBasicMaterial({depthTest:false,depthWrite:false}));"));
test("question 25355: preserves geometry runtime source contract",()=>has(0,"marker.position.copy(p);marker.renderOrder=11941;marker.userData={helper:true,objectSelectionHelper:true,sectionDerivedSelection:true,derivedId:record.id};group.add(marker);"));
test("question 25356: preserves geometry runtime source contract",()=>has(0,"pipeGroup.add(group);selectionOverlay=group;"));
test("question 25357: preserves geometry runtime source contract",()=>has(0,"try{if(typeof markViewerDirty===\"function\")markViewerDirty();}catch{}"));
test("question 25358: preserves geometry runtime source contract",()=>has(0,"return true;"));
test("question 25359: preserves geometry runtime source contract",()=>has(0,"function clearHelper(){"));
test("question 25360: preserves geometry runtime source contract",()=>has(0,"if(!helperGroup)return;"));
test("question 25361: preserves geometry runtime source contract",()=>has(0,"try{helperGroup.parent?.remove(helperGroup);}catch{}"));
test("question 25362: preserves geometry runtime source contract",()=>has(0,"try{helperGroup.traverse(obj=>{obj.geometry?.dispose?.();if(Array.isArray(obj.material))obj.material.forEach(m=>m?.dispose?.());else obj.material?.dispose?.();});}catch{}"));
test("question 25363: preserves geometry runtime source contract",()=>has(0,"helperGroup=null;"));
test("question 25364: preserves geometry runtime source contract",()=>has(0,"function modelCenterAndSize(){"));
test("question 25365: preserves geometry runtime source contract",()=>has(0,"if(typeof THREE===\"undefined\"||typeof pipeGroup===\"undefined\"||!pipeGroup)return {center:new THREE.Vector3(),size:new THREE.Vector3(10,10,10)};"));
test("question 25366: preserves geometry runtime source contract",()=>has(0,"const box=new THREE.Box3().setFromObject(pipeGroup);"));
test("question 25367: preserves geometry runtime source contract",()=>has(0,"if(box.isEmpty())return {center:new THREE.Vector3(),size:new THREE.Vector3(10,10,10)};"));
test("question 25368: preserves geometry runtime source contract",()=>has(0,"return {center:box.getCenter(new THREE.Vector3()),size:box.getSize(new THREE.Vector3())};"));
test("question 25369: preserves geometry runtime source contract",()=>has(0,"function buildHelper(state){"));
test("question 25370: preserves geometry runtime source contract",()=>has(0,"clearHelper();"));
test("question 25371: preserves geometry runtime source contract",()=>has(0,"if(!state.enabled||!state.show_helper||typeof THREE===\"undefined\"||typeof scene===\"undefined\"||!scene)return;"));
test("question 25372: preserves geometry runtime source contract",()=>has(0,"helperGroup=new THREE.Group();helperGroup.userData={helper:true,sectionHelper:true};"));
test("question 25373: preserves geometry runtime source contract",()=>has(0,"if(state.mode===\"plane\"){"));
test("question 25374: preserves geometry runtime source contract",()=>has(0,"const {center,size}=modelCenterAndSize(),normal=new THREE.Vector3(state.plane.normal.x,state.plane.normal.y,state.plane.normal.z).normalize();"));
test("question 25375: preserves geometry runtime source contract",()=>has(0,"if(state.plane.flipped)normal.multiplyScalar(-1);"));
test("question 25376: preserves geometry runtime source contract",()=>has(0,"const span=Math.max(size.x,size.y,size.z,1)*1.25,scale=sceneScale();"));
test("question 25377: preserves geometry runtime source contract",()=>has(0,"const geo=new THREE.PlaneGeometry(span,span);"));
test("question 25378: preserves geometry runtime source contract",()=>has(0,"const mat=new THREE.MeshBasicMaterial({transparent:true,opacity:.12,side:THREE.DoubleSide,depthWrite:false});"));
test("question 25379: preserves geometry runtime source contract",()=>has(0,"const mesh=new THREE.Mesh(geo,mat);"));
test("question 25380: preserves geometry runtime source contract",()=>has(0,"mesh.position.set(state.plane.point.x*scale,state.plane.point.y*scale,state.plane.point.z*scale);"));
test("question 25381: preserves geometry runtime source contract",()=>has(0,"mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),normal);"));
test("question 25382: preserves geometry runtime source contract",()=>has(0,"mesh.userData={helper:true,sectionHelper:true};"));
test("question 25383: preserves geometry runtime source contract",()=>has(0,"helperGroup.add(mesh);"));
test("question 25384: preserves geometry runtime source contract",()=>has(0,"const arrow=new THREE.ArrowHelper(normal,new THREE.Vector3(state.plane.point.x*scale,state.plane.point.y*scale,state.plane.point.z*scale),Math.max(.5,span*.15));"));
test("question 25385: preserves geometry runtime source contract",()=>has(0,"arrow.userData={helper:true,sectionHelper:true};helperGroup.add(arrow);"));
test("question 25386: preserves geometry runtime source contract",()=>has(0,"}else if(state.mode===\"box\"){"));
test("question 25387: preserves geometry runtime source contract",()=>has(0,"const scale=sceneScale(),min=new THREE.Vector3(state.box.min.x*scale,state.box.min.y*scale,state.box.min.z*scale),max=new THREE.Vector3(state.box.max.x*scale,state.box.max.y*scale,state.box.max.z*scale);"));
test("question 25388: preserves geometry runtime source contract",()=>has(0,"const box=new THREE.Box3(min,max),helper=new THREE.Box3Helper(box);"));
test("question 25389: preserves geometry runtime source contract",()=>has(0,"helper.userData={helper:true,sectionHelper:true};helperGroup.add(helper);"));
test("question 25390: preserves geometry runtime source contract",()=>has(0,"scene.add(helperGroup);"));
test("question 25391: preserves geometry runtime source contract",()=>has(0,"function apply(){"));
test("question 25392: preserves geometry runtime source contract",()=>has(0,"if(!domain||typeof renderer===\"undefined\"||!renderer)return false;"));
test("question 25393: preserves geometry runtime source contract",()=>has(0,"const state=current();"));
test("question 25394: preserves geometry runtime source contract",()=>has(0,"renderer.localClippingEnabled=true;"));
test("question 25395: preserves geometry runtime source contract",()=>has(0,"renderer.clippingPlanes=!state.enabled||state.mode===\"off\""));
test("question 25396: preserves geometry runtime source contract",()=>has(0,":state.mode===\"plane\""));
test("question 25397: preserves geometry runtime source contract",()=>has(0,"?[planeToThree(state.plane)].filter(Boolean)"));
test("question 25398: preserves geometry runtime source contract",()=>has(0,":boxToPlanes(state.box);"));
test("question 25399: preserves geometry runtime source contract",()=>has(0,"buildHelper(state);"));
test("question 25400: preserves geometry runtime source contract",()=>has(0,"function setPlane(plane,options={}){return command(\"Section Plane\",()=>{domain.setSectionPlane(project(),plane,options);return true;});}"));
test("question 25401: preserves geometry runtime source contract",()=>has(0,"function setBox(box,options={}){return command(\"Section Box\",()=>{domain.setSectionBox(project(),box,options);return true;});}"));
test("question 25402: preserves geometry runtime source contract",()=>has(0,"function disable(){return command(\"Отключить Section View\",()=>{domain.disableSectionView(project());return true;});}"));
test("question 25403: preserves geometry runtime source contract",()=>has(0,"function flipPlane(){"));
test("question 25404: preserves geometry runtime source contract",()=>has(0,"const state=current();if(state.mode!==\"plane\")return false;"));
test("question 25405: preserves geometry runtime source contract",()=>has(0,"return setPlane({...state.plane,flipped:!state.plane.flipped},{enabled:true,show_helper:state.show_helper});"));
test("question 25406: preserves geometry runtime source contract",()=>has(0,"function setHelper(visible){"));
test("question 25407: preserves geometry runtime source contract",()=>has(0,"return command(\"Section helper\",()=>{"));
test("question 25408: preserves geometry runtime source contract",()=>has(0,"project().section_view={...state,show_helper:visible===true};return true;"));
test("question 25409: preserves geometry runtime source contract",()=>has(0,"function capture(){return domain.sectionViewSnapshot(project());}"));
test("question 25410: preserves geometry runtime source contract",()=>has(0,"function restore(snapshot,{recordHistory=false}={}){"));
test("question 25411: preserves geometry runtime source contract",()=>has(0,"const mutate=()=>{project().section_view={...domain.normalizeSectionView(snapshot??{})};return true;};"));
test("question 25412: preserves geometry runtime source contract",()=>has(0,"if(recordHistory)return command(\"Восстановить Section View\",mutate);"));
test("question 25413: preserves geometry runtime source contract",()=>has(0,"mutate();apply();renderPanel();renderSelectionOverlay();dispatch();return true;"));
test("question 25414: preserves geometry runtime source contract",()=>has(0,"function parseVec(text,fallback){"));
test("question 25415: preserves geometry runtime source contract",()=>has(0,"const parts=String(text??\"\").replace(/,/g,\".\").split(\";\").map(Number);"));
test("question 25416: preserves geometry runtime source contract",()=>has(0,"x:Number.isFinite(parts[0])?parts[0]:fallback.x,"));
test("question 25417: preserves geometry runtime source contract",()=>has(0,"y:Number.isFinite(parts[1])?parts[1]:fallback.y,"));
test("question 25418: preserves geometry runtime source contract",()=>has(0,"z:Number.isFinite(parts[2])?parts[2]:fallback.z"));
test("question 25419: preserves geometry runtime source contract",()=>has(0,"function screenDistance(point,event,canvas){"));
test("question 25420: preserves geometry runtime source contract",()=>has(0,"if(!point||!event||!canvas||typeof camera===\"undefined\"||!camera||typeof THREE===\"undefined\")return 0;"));
test("question 25421: preserves geometry runtime source contract",()=>has(0,"const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return 0;"));
test("question 25422: preserves geometry runtime source contract",()=>has(0,"const scale=sceneScale(),v=new THREE.Vector3(point.x*scale,point.y*scale,point.z*scale).project(camera);"));
test("question 25423: preserves geometry runtime source contract",()=>has(0,"const sx=rect.left+(v.x+1)*.5*rect.width,sy=rect.top+(1-v.y)*.5*rect.height;"));
test("question 25424: preserves geometry runtime source contract",()=>has(0,"return Math.hypot(Number(event.clientX)-sx,Number(event.clientY)-sy);"));
test("question 25425: preserves geometry runtime source contract",()=>has(0,"function sourceForObject(object){"));
test("question 25426: preserves geometry runtime source contract",()=>has(0,"let item=object,source=\"Editable\",objectId=object?.uuid??\"section-object\";"));
test("question 25427: preserves geometry runtime source contract",()=>has(0,"while(item){"));
test("question 25428: preserves geometry runtime source contract",()=>has(0,"const data=item.userData??{};"));
test("question 25429: preserves geometry runtime source contract",()=>has(0,"if(data.referenceEditableInstanceId){source=\"MeshFitted\";objectId=String(data.referenceEditableInstanceId);break;}"));
test("question 25430: preserves geometry runtime source contract",()=>has(0,"if(data.referenceNodeId&&data.referenceSceneId){source=\"SourceReference\";objectId=String(data.referenceSceneId)+\":\"+String(data.referenceNodeId);break;}"));
test("question 25431: preserves geometry runtime source contract",()=>has(0,"if(data.constructionId||data.constructionGeometryId){source=\"Construction\";objectId=String(data.constructionId??data.constructionGeometryId);}"));
test("question 25432: preserves geometry runtime source contract",()=>has(0,"if(data.tubeId){source=\"Tube\";objectId=String(data.tubeId);}"));
test("question 25433: preserves geometry runtime source contract",()=>has(0,"item=item.parent;"));
test("question 25434: preserves geometry runtime source contract",()=>has(0,"return {source,objectId};"));
test("question 25435: preserves geometry runtime source contract",()=>has(0,"function triangleFromHit(hit){"));
test("question 25436: preserves geometry runtime source contract",()=>has(0,"const geometry=hit?.object?.geometry,position=geometry?.attributes?.position,face=hit?.face;"));
test("question 25437: preserves geometry runtime source contract",()=>has(0,"if(!position||!face)return null;"));
test("question 25438: preserves geometry runtime source contract",()=>has(0,"const scale=sceneScale(),out=[];"));
test("question 25439: preserves geometry runtime source contract",()=>has(0,"for(const index of [face.a,face.b,face.c]){"));
test("question 25440: preserves geometry runtime source contract",()=>has(0,"if(!Number.isInteger(index)||index<0||index>=position.count)return null;"));
test("question 25441: preserves geometry runtime source contract",()=>has(0,"const world=new THREE.Vector3().fromBufferAttribute(position,index);"));
test("question 25442: preserves geometry runtime source contract",()=>has(0,"hit.object.localToWorld(world);"));
test("question 25443: preserves geometry runtime source contract",()=>has(0,"out.push({x:world.x/scale,y:world.y/scale,z:world.z/scale});"));
test("question 25444: preserves geometry runtime source contract",()=>has(0,"function candidate(id,type,point,event,canvas,{source,objectId,segment,face,index}={}){"));
test("question 25445: preserves geometry runtime source contract",()=>has(0,"return Object.freeze({"));
test("question 25446: preserves geometry runtime source contract",()=>has(0,"id:String(id),type:String(type),source:\"SectionDerived\","));
test("question 25447: preserves geometry runtime source contract",()=>has(0,"object_id:String(objectId??\"section\"),subentity_id:\"section:\"+String(face??\"plane\")+\":\"+String(index??0),"));
test("question 25448: preserves geometry runtime source contract",()=>has(0,"point:{x:Number(point.x),y:Number(point.y),z:Number(point.z)},"));
test("question 25449: preserves geometry runtime source contract",()=>has(0,"screen_distance_px:screenDistance(point,event,canvas),"));
test("question 25450: preserves geometry runtime source contract",()=>has(0,"visible:true,virtual:true,through:false,fitted:false,"));
test("question 25451: preserves geometry runtime source contract",()=>has(0,"geometry_status:\"SectionDerived\",fitting_error:{mm:0,deg:0},confidence:1,"));
test("question 25452: preserves geometry runtime source contract",()=>has(0,"evidence:[{kind:\"SectionDerived\",source_geometry:String(source??\"Editable\"),section_face:String(face??\"plane\")}],"));
test("question 25453: preserves geometry runtime source contract",()=>has(0,"label:\"Section-derived \"+type,"));
test("question 25454: preserves geometry runtime source contract",()=>has(0,"section_derived:true,section_mode:String(current().mode),section_face:String(face??\"plane\"),"));
test("question 25455: preserves geometry runtime source contract",()=>has(0,"source_geometry:String(source??\"Editable\"),"));
test("question 25456: preserves geometry runtime source contract",()=>has(0,"primitive:segment?{kind:\"segment\",start:{...segment[0]},end:{...segment[1]}}:null"));
test("question 25457: preserves geometry runtime source contract",()=>has(0,"function segmentScreenDistance(segment,event,canvas){"));
test("question 25458: preserves geometry runtime source contract",()=>has(0,"if(!segment||!event||!canvas||typeof camera===\"undefined\"||!camera||typeof THREE===\"undefined\")return Infinity;"));
test("question 25459: preserves geometry runtime source contract",()=>has(0,"const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return Infinity;"));
test("question 25460: preserves geometry runtime source contract",()=>has(0,"const scale=sceneScale();"));
test("question 25461: preserves geometry runtime source contract",()=>has(0,"const projectPoint=(p)=>{"));
test("question 25462: preserves geometry runtime source contract",()=>has(0,"const v=new THREE.Vector3(p.x*scale,p.y*scale,p.z*scale).project(camera);"));
test("question 25463: preserves geometry runtime source contract",()=>has(0,"return {x:rect.left+(v.x+1)*.5*rect.width,y:rect.top+(1-v.y)*.5*rect.height};"));
test("question 25464: preserves geometry runtime source contract",()=>has(0,"const a=projectPoint(segment[0]),b=projectPoint(segment[1]),px=Number(event.clientX),py=Number(event.clientY);"));
test("question 25465: preserves geometry runtime source contract",()=>has(0,"const vx=b.x-a.x,vy=b.y-a.y,den=vx*vx+vy*vy;"));
test("question 25466: preserves geometry runtime source contract",()=>has(0,"const u=den>1e-12?Math.max(0,Math.min(1,((px-a.x)*vx+(py-a.y)*vy)/den)):0;"));
test("question 25467: preserves geometry runtime source contract",()=>has(0,"return Math.hypot(px-(a.x+u*vx),py-(a.y+u*vy));"));
test("question 25468: preserves geometry runtime source contract",()=>has(0,"function rememberDerivedSelection(record){"));
test("question 25469: preserves geometry runtime source contract",()=>has(0,"if(!record?.id)return null;"));
test("question 25470: preserves geometry runtime source contract",()=>has(0,"derivedSelectionRegistry.set(String(record.id),Object.freeze(structuredClone(record)));"));
test("question 25471: preserves geometry runtime source contract",()=>has(0,"if(derivedSelectionRegistry.size>256){"));
test("question 25472: preserves geometry runtime source contract",()=>has(0,"const first=derivedSelectionRegistry.keys().next().value;"));
test("question 25473: preserves geometry runtime source contract",()=>has(0,"if(first!=null)derivedSelectionRegistry.delete(first);"));
test("question 25474: preserves geometry runtime source contract",()=>has(0,"return record;"));
test("question 25475: preserves geometry runtime source contract",()=>has(0,"function selectionRecord(id,segment,event,canvas,{source,objectId,face,index}={}){"));
test("question 25476: preserves geometry runtime source contract",()=>has(0,"const mid={x:(segment[0].x+segment[1].x)/2,y:(segment[0].y+segment[1].y)/2,z:(segment[0].z+segment[1].z)/2};"));
test("question 25477: preserves geometry runtime source contract",()=>has(0,"const record={"));
test("question 25478: preserves geometry runtime source contract",()=>has(0,"id:String(id),kind:\"section-derived\",virtual:true,readonly:true,"));
test("question 25479: preserves geometry runtime source contract",()=>has(0,"source:\"SectionDerived\",source_geometry:String(source??\"Editable\"),"));
test("question 25480: preserves geometry runtime source contract",()=>has(0,"section_mode:String(current().mode),section_face:String(face??\"plane\"),"));
test("question 25481: preserves geometry runtime source contract",()=>has(0,"segment:{start:{...segment[0]},end:{...segment[1]},midpoint:mid},"));
test("question 25482: preserves geometry runtime source contract",()=>has(0,"screen_distance_px:segmentScreenDistance(segment,event,canvas),"));
test("question 25483: preserves geometry runtime source contract",()=>has(0,"geometry_status:\"SectionDerived\","));
test("question 25484: preserves geometry runtime source contract",()=>has(0,"evidence:[{kind:\"SectionDerived\",source_geometry:String(source??\"Editable\"),section_face:String(face??\"plane\")}]"));
test("question 25485: preserves geometry runtime source contract",()=>has(0,"return rememberDerivedSelection(record);"));
test("question 25486: preserves geometry runtime source contract",()=>has(0,"function selectionCandidatesAtEvent(event,{thresholdPx=10}={}){"));
test("question 25487: preserves geometry runtime source contract",()=>has(0,"if(!state.enabled||state.mode===\"off\"||!derived||typeof THREE===\"undefined\"||typeof pipeGroup===\"undefined\"||!pipeGroup||typeof camera===\"undefined\"||!camera)return Object.freeze([]);"));
test("question 25488: preserves geometry runtime source contract",()=>has(0,"const canvas=document.getElementById(\"threeCanvas\"),rect=canvas?.getBoundingClientRect?.();"));
test("question 25489: preserves geometry runtime source contract",()=>has(0,"if(!canvas||!rect?.width||!rect?.height)return Object.freeze([]);"));
test("question 25490: preserves geometry runtime source contract",()=>has(0,"const raycaster=new THREE.Raycaster();"));
test("question 25491: preserves geometry runtime source contract",()=>has(0,"const mouse=new THREE.Vector2(((event.clientX-rect.left)/rect.width)*2-1,-((event.clientY-rect.top)/rect.height)*2+1);"));
test("question 25492: preserves geometry runtime source contract",()=>has(0,"raycaster.setFromCamera(mouse,camera);"));
test("question 25493: preserves geometry runtime source contract",()=>has(0,"const hits=raycaster.intersectObjects(pipeGroup.children,true),records=[],seen=new Set();"));
test("question 25494: preserves geometry runtime source contract",()=>has(0,"for(const hit of hits){"));
test("question 25495: preserves geometry runtime source contract",()=>has(0,"if(records.length>=24)break;"));
test("question 25496: preserves geometry runtime source contract",()=>has(0,"if(hit.object?.userData?.helper||hit.object?.userData?.hitProxy||hit.object?.visible===false)continue;"));
test("question 25497: preserves geometry runtime source contract",()=>has(0,"const triangle=triangleFromHit(hit);if(!triangle)continue;"));
test("question 25498: preserves geometry runtime source contract",()=>has(0,"const segments=derived.sectionSegmentsFromTriangles([triangle],state),src=sourceForObject(hit.object);"));
test("question 25499: preserves geometry runtime source contract",()=>has(0,"segments.forEach((item,segmentIndex)=>{"));
test("question 25500: preserves geometry runtime source contract",()=>has(0,"const id=\"section:\"+src.objectId+\":\"+String(item.face)+\":\"+String(hit.faceIndex??segmentIndex)+\":segment\";"));
test("question 25501: preserves geometry runtime source contract",()=>has(0,"if(seen.has(id))return;seen.add(id);"));
test("question 25502: preserves geometry runtime source contract",()=>has(0,"const record=selectionRecord(id,item.segment,event,canvas,{...src,face:item.face,index:segmentIndex});"));
test("question 25503: preserves geometry runtime source contract",()=>has(0,"if(record.screen_distance_px<=thresholdPx)records.push(record);"));
test("question 25504: preserves geometry runtime source contract",()=>has(0,"records.sort((a,b)=>a.screen_distance_px-b.screen_distance_px);"));
test("question 25505: preserves geometry runtime source contract",()=>has(0,"return Object.freeze(records);"));
test("question 25506: preserves geometry runtime source contract",()=>has(0,"function derivedSelectionById(id){return derivedSelectionRegistry.get(String(id??\"\"))??null;}"));
test("question 25507: preserves geometry runtime source contract",()=>has(0,"function snapCandidatesAtEvent(event){"));
test("question 25508: preserves geometry runtime source contract",()=>has(0,"const add=record=>{if(record&&!seen.has(record.id)){seen.add(record.id);records.push(record);}};"));
test("question 25509: preserves geometry runtime source contract",()=>has(0,"if(records.length>=18)break;"));
test("question 25510: preserves geometry runtime source contract",()=>has(0,"const segments=derived.sectionSegmentsFromTriangles([triangle],state);"));
test("question 25511: preserves geometry runtime source contract",()=>has(0,"const src=sourceForObject(hit.object);"));
test("question 25512: preserves geometry runtime source contract",()=>has(0,"const segment=item.segment,a=segment[0],b=segment[1],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2,z:(a.z+b.z)/2};"));
test("question 25513: preserves geometry runtime source contract",()=>has(0,"const base=\"section:\"+src.objectId+\":\"+String(item.face)+\":\"+String(hit.faceIndex??segmentIndex);"));
test("question 25514: preserves geometry runtime source contract",()=>has(0,"add(candidate(base+\":a\",\"Endpoint\",a,event,canvas,{...src,segment,face:item.face,index:segmentIndex}));"));
test("question 25515: preserves geometry runtime source contract",()=>has(0,"add(candidate(base+\":m\",\"Midpoint\",mid,event,canvas,{...src,segment,face:item.face,index:segmentIndex}));"));
test("question 25516: preserves geometry runtime source contract",()=>has(0,"add(candidate(base+\":b\",\"Endpoint\",b,event,canvas,{...src,segment,face:item.face,index:segmentIndex}));"));
test("question 25517: preserves geometry runtime source contract",()=>has(0,"add(candidate(base+\":axis\",\"LineAxis\",mid,event,canvas,{...src,segment,face:item.face,index:segmentIndex}));"));
test("question 25518: preserves geometry runtime source contract",()=>has(0,"function ensurePanel(){"));
test("question 25519: preserves geometry runtime source contract",()=>has(0,"if(panel)return panel;"));
test("question 25520: preserves geometry runtime source contract",()=>has(0,"const style=document.createElement(\"style\");style.id=\"tbSectionStyles\";style.textContent="));
test("question 25521: preserves geometry runtime source contract",()=>has(0,"'#tbSectionToggle{position:fixed;right:638px;top:54px;z-index:120374;background:#26384b;color:#eef5ff;border:1px solid #455b72;border-radius:6px;padding:6px 10px;cursor:pointer}#tbSectionPanel{position:fixed;right:14px;top:88px;width:min(430px,calc(100vw - 28px));max-height:calc(100vh - 110px);z-index:120367;display:none;flex-direction:column;background:rgba(13,22,32,.985);color:#edf4fb;border:1px solid #41566f;border-radius:9px;box-shadow:0 14px 40px rgba(0,0,0,.45);font:12px system-ui}#tbSectionPanel.open{display:flex}.tb-sec-head{display:flex;gap:6px;align-items:center;padding:8px 10px;border-bottom:1px solid #304154}.tb-sec-head .grow{flex:1}.tb-sec-body{padding:8px;overflow:auto}.tb-sec-grid{display:grid;grid-template-columns:120px 1fr;gap:7px;align-items:center}.tb-sec-grid input,.tb-sec-grid select{background:#09131c;color:#fff;border:1px solid #40536a;border-radius:4px;padding:5px}.tb-sec-actions{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.tb-sec-actions button{background:#26384b;color:#eef5ff;border:1px solid #455b72;border-radius:4px;padding:5px 7px;cursor:pointer}';"));
test("question 25522: preserves geometry runtime source contract",()=>has(0,"document.head.appendChild(style);"));
test("question 25523: preserves geometry runtime source contract",()=>has(0,"toggle=document.createElement(\"button\");toggle.id=\"tbSectionToggle\";toggle.type=\"button\";toggle.textContent=\"Section\";document.body.appendChild(toggle);"));
test("question 25524: preserves geometry runtime source contract",()=>has(0,"panel=document.createElement(\"section\");panel.id=\"tbSectionPanel\";panel.innerHTML='<div class=\"tb-sec-head\"><b>Section View</b><span class=\"grow\"></span><button data-sec-close>×</button></div><div class=\"tb-sec-body\" data-sec-body></div>';document.body.appendChild(panel);"));
test("question 25525: preserves geometry runtime source contract",()=>has(0,"toggle.onclick=()=>{panel.classList.toggle(\"open\");renderPanel();};panel.querySelector(\"[data-sec-close]\").onclick=()=>panel.classList.remove(\"open\");"));
test("question 25526: preserves geometry runtime source contract",()=>has(0,"return panel;"));
test("question 25527: preserves geometry runtime source contract",()=>has(0,"function renderPanel(){"));
test("question 25528: preserves geometry runtime source contract",()=>has(0,"if(!domain)return;const state=current(),root=ensurePanel(),body=root.querySelector(\"[data-sec-body]\");"));
test("question 25529: preserves geometry runtime source contract",()=>has(0,"body.innerHTML='<div class=\"tb-sec-grid\"><label>Mode</label><select data-sec-mode><option value=\"off\" '+(state.mode===\"off\"?\"selected\":\"\")+'>Off</option><option value=\"plane\" '+(state.mode===\"plane\"?\"selected\":\"\")+'>Section Plane</option><option value=\"box\" '+(state.mode===\"box\"?\"selected\":\"\")+'>Section Box</option></select><label>Plane point XYZ</label><input data-sec-point value=\"'+esc([state.plane.point.x,state.plane.point.y,state.plane.point.z].join(\";\"))+'\"><label>Plane normal XYZ</label><input data-sec-normal value=\"'+esc([state.plane.normal.x,state.plane.normal.y,state.plane.normal.z].join(\";\"))+'\"><label>Box min XYZ</label><input data-sec-min value=\"'+esc([state.box.min.x,state.box.min.y,state.box.min.z].join(\";\"))+'\"><label>Box max XYZ</label><input data-sec-max value=\"'+esc([state.box.max.x,state.box.max.y,state.box.max.z].join(\";\"))+'\"><label>Helper</label><input data-sec-helper type=\"checkbox\" '+(state.show_helper?\"checked\":\"\")+'></div><div class=\"tb-sec-actions\"><button data-sec-apply>Apply</button><button data-sec-flip '+(state.mode!==\"plane\"?\"disabled\":\"\")+'>Flip Plane</button><button data-sec-off>Off</button></div>';"));
test("question 25530: preserves geometry runtime source contract",()=>has(0,"body.querySelector(\"[data-sec-apply]\").onclick=()=>{"));
test("question 25531: preserves geometry runtime source contract",()=>has(0,"const mode=body.querySelector(\"[data-sec-mode]\").value,show=body.querySelector(\"[data-sec-helper]\").checked;"));
test("question 25532: preserves geometry runtime source contract",()=>has(0,"if(mode===\"plane\")setPlane({point:parseVec(body.querySelector(\"[data-sec-point]\").value,state.plane.point),normal:parseVec(body.querySelector(\"[data-sec-normal]\").value,state.plane.normal),flipped:state.plane.flipped},{enabled:true,show_helper:show});"));
test("question 25533: preserves geometry runtime source contract",()=>has(0,"else if(mode===\"box\")setBox({min:parseVec(body.querySelector(\"[data-sec-min]\").value,state.box.min),max:parseVec(body.querySelector(\"[data-sec-max]\").value,state.box.max)},{enabled:true,show_helper:show});"));
test("question 25534: preserves geometry runtime source contract",()=>has(0,"else disable();"));
test("question 25535: preserves geometry runtime source contract",()=>has(0,"body.querySelector(\"[data-sec-flip]\").onclick=flipPlane;"));
test("question 25536: preserves geometry runtime source contract",()=>has(0,"body.querySelector(\"[data-sec-off]\").onclick=disable;"));
test("question 25537: preserves geometry runtime source contract",()=>has(0,"body.querySelector(\"[data-sec-helper]\").onchange=e=>setHelper(e.target.checked);"));
test("question 25538: preserves geometry runtime source contract",()=>has(0,"function invalidateDerivedSelections(){"));
test("question 25539: preserves geometry runtime source contract",()=>has(0,"derivedSelectionRegistry.clear();clearSelectionOverlay();"));
test("question 25540: preserves geometry runtime source contract",()=>has(0,"const context=window.TubeBenderObjectContext;"));
test("question 25541: preserves geometry runtime source contract",()=>has(0,"const keys=context?.selectionKeys?.()??[];"));
test("question 25542: preserves geometry runtime source contract",()=>has(0,"const kept=keys.filter(key=>context?.parseSelectionKey?.(key)?.kind!==\"section-derived\");"));
test("question 25543: preserves geometry runtime source contract",()=>has(0,"if(kept.length!==keys.length)context?.replaceSelectionKeys?.(kept,{announce:true});"));
test("question 25544: preserves geometry runtime source contract",()=>has(0,"function dispatch(){"));
test("question 25545: preserves geometry runtime source contract",()=>has(0,"invalidateDerivedSelections();"));
test("question 25546: preserves geometry runtime source contract",()=>has(0,"try{window.dispatchEvent(new CustomEvent(\"tubebender-section-view-change\",{detail:{state:capture()}}));}catch{}"));
test("question 25547: preserves geometry runtime source contract",()=>has(0,"async function install(){"));
test("question 25548: preserves geometry runtime source contract",()=>has(0,"if(installed)return;installed=true;"));
test("question 25549: preserves geometry runtime source contract",()=>has(0,"try{[domain,derived]=await Promise.all([import(SECTION_URL),import(SECTION_DERIVED_URL)]);}catch(error){console.error(\"Section View failed\",error);return;}"));
test("question 25550: preserves geometry runtime source contract",()=>has(0,"domain.ensureSectionViewState(project());ensurePanel();renderPanel();apply();"));
test("question 25551: preserves geometry runtime source contract",()=>has(0,"window.addEventListener(\"tubebender-selection-change\",(event)=>renderSelectionOverlay(event?.detail?.entries));"));
test("question 25552: preserves geometry runtime source contract",()=>has(0,"window.addEventListener(\"tubebender-section-view-change\",()=>renderSelectionOverlay());"));
test("question 25553: preserves geometry runtime source contract",()=>has(0,"window.TubeBenderSectionView=Object.freeze({setPlane,setBox,disable,flipPlane,setHelper,capture,restore,apply,snapCandidatesAtEvent,selectionCandidatesAtEvent,derivedSelectionById,renderSelectionOverlay,openPanel:()=>{ensurePanel().classList.add(\"open\");renderPanel();},domain,derived});"));
test("question 25554: preserves geometry runtime source contract",()=>has(0,"if(document.readyState===\"loading\")document.addEventListener(\"DOMContentLoaded\",()=>install().catch(console.error),{once:true});else install().catch(console.error);"));
test("question 25555: preserves geometry runtime source contract",()=>has(1,"const TRANSFORM_URL=\"__TB_TRANSFORM_COMMANDS_MODULE_URL__\";"));
test("question 25556: preserves geometry runtime source contract",()=>has(1,"const RIGID_URL=\"__TB_RIGID_TRANSFORM_MODULE_URL__\";"));
test("question 25557: preserves geometry runtime source contract",()=>has(1,"const DYNAMIC_INPUT_URL=\"__TB_DYNAMIC_INPUT_MODULE_URL__\";"));
test("question 25558: preserves geometry runtime source contract",()=>has(1,"let transforms=null,rigid=null,dynamicInput=null,installed=false,syncing=false;"));
test("question 25559: preserves geometry runtime source contract",()=>has(1,"const api=()=>window.TubeBenderEngineering??null;"));
test("question 25560: preserves geometry runtime source contract",()=>has(1,"const project=()=>{try{return api()?.activeProject?.()??null;}catch{return null;}};"));
test("question 25561: preserves geometry runtime source contract",()=>has(1,"const clone=(v)=>v==null?v:structuredClone(v);"));
test("question 25562: preserves geometry runtime source contract",()=>has(1,"function makeId(prefix){"));
test("question 25563: preserves geometry runtime source contract",()=>has(1,"const uuid=globalThis.crypto?.randomUUID?.();"));
test("question 25564: preserves geometry runtime source contract",()=>has(1,"return uuid?prefix+\"-\"+uuid:prefix+\"-\"+Date.now().toString(36)+\"-\"+Math.random().toString(36).slice(2,9);"));
test("question 25565: preserves geometry runtime source contract",()=>has(1,"function point(v){"));
test("question 25566: preserves geometry runtime source contract",()=>has(1,"const x=Number(v?.x??0),y=Number(v?.y??0),z=Number(v?.z??0);"));
test("question 25567: preserves geometry runtime source contract",()=>has(1,"if(![x,y,z].every(Number.isFinite))throw new TypeError(\"array anchor point must be finite\");"));
test("question 25568: preserves geometry runtime source contract",()=>has(1,"return {x,y,z};"));
test("question 25569: preserves geometry runtime source contract",()=>has(1,"function sub(a,b){return {x:a.x-b.x,y:a.y-b.y,z:a.z-b.z};}"));
test("question 25570: preserves geometry runtime source contract",()=>has(1,"function add(a,b){return {x:a.x+b.x,y:a.y+b.y,z:a.z+b.z};}"));
test("question 25571: preserves geometry runtime source contract",()=>has(1,"function scale(a,s){return {x:a.x*s,y:a.y*s,z:a.z*s};}"));
test("question 25572: preserves geometry runtime source contract",()=>has(1,"function dot(a,b){return a.x*b.x+a.y*b.y+a.z*b.z;}"));
test("question 25573: preserves geometry runtime source contract",()=>has(1,"function length(a){return Math.hypot(a.x,a.y,a.z);}"));
test("question 25574: preserves geometry runtime source contract",()=>has(1,"function unit(a,name=\"vector\"){const n=length(a);if(!(n>1e-12))throw new Error(name+\" must be non-zero\");return scale(a,1/n);}"));
test("question 25575: preserves geometry runtime source contract",()=>has(1,"const FORMULA_FIELDS=Object.freeze({"));
test("question 25576: preserves geometry runtime source contract",()=>has(1,"count:\"scalar\",step:\"length\","));
test("question 25577: preserves geometry runtime source contract",()=>has(1,"count_x:\"scalar\",count_y:\"scalar\",count_z:\"scalar\","));
test("question 25578: preserves geometry runtime source contract",()=>has(1,"step_x:\"length\",step_y:\"length\",step_z:\"length\","));
test("question 25579: preserves geometry runtime source contract",()=>has(1,"total_angle_deg:\"angle\",initial_angle_deg:\"angle\",radius_mm:\"length\""));
test("question 25580: preserves geometry runtime source contract",()=>has(1,"function formulaVariables(p=project()){"));
test("question 25581: preserves geometry runtime source contract",()=>has(1,"return {...(p?.formula_variables??{}),...(p?.array_formula_variables??{})};"));
test("question 25582: preserves geometry runtime source contract",()=>has(1,"function rawParameterValue(def,name){"));
test("question 25583: preserves geometry runtime source contract",()=>has(1,"const params=def?.parameters??{};"));
test("question 25584: preserves geometry runtime source contract",()=>has(1,"if(name===\"count_x\")return params.counts?.[0];"));
test("question 25585: preserves geometry runtime source contract",()=>has(1,"if(name===\"count_y\")return params.counts?.[1];"));
test("question 25586: preserves geometry runtime source contract",()=>has(1,"if(name===\"count_z\")return params.counts?.[2];"));
test("question 25587: preserves geometry runtime source contract",()=>has(1,"if(name===\"step_x\")return params.steps?.[0];"));
test("question 25588: preserves geometry runtime source contract",()=>has(1,"if(name===\"step_y\")return params.steps?.[1];"));
test("question 25589: preserves geometry runtime source contract",()=>has(1,"if(name===\"step_z\")return params.steps?.[2];"));
test("question 25590: preserves geometry runtime source contract",()=>has(1,"return params[name];"));
test("question 25591: preserves geometry runtime source contract",()=>has(1,"function evaluateFormulaFields(def,p=project()){"));
test("question 25592: preserves geometry runtime source contract",()=>has(1,"const formulas=def?.parameter_formulas??{},base=formulaVariables(p),resolved={},visiting=new Set();"));
test("question 25593: preserves geometry runtime source contract",()=>has(1,"const resolve=(name)=>{"));
test("question 25594: preserves geometry runtime source contract",()=>has(1,"if(name in resolved)return resolved[name];"));
test("question 25595: preserves geometry runtime source contract",()=>has(1,"if(visiting.has(name))throw new Error(\"Array formula cycle: \"+[...visiting,name].join(\" -> \"));"));
test("question 25596: preserves geometry runtime source contract",()=>has(1,"if(!(name in formulas)){"));
test("question 25597: preserves geometry runtime source contract",()=>has(1,"const raw=rawParameterValue(def,name);"));
test("question 25598: preserves geometry runtime source contract",()=>has(1,"if(raw!=null&&raw!==\"\"){const n=Number(raw);if(Number.isFinite(n)){resolved[name]=n;return n;}}"));
test("question 25599: preserves geometry runtime source contract",()=>has(1,"if(name in base){const n=Number(base[name]);if(Number.isFinite(n)){resolved[name]=n;return n;}}"));
test("question 25600: preserves geometry runtime source contract",()=>has(1,"throw new Error(\"Unknown array formula variable: \"+name);"));
test("question 25601: preserves geometry runtime source contract",()=>has(1,"visiting.add(name);"));
test("question 25602: preserves geometry runtime source contract",()=>has(1,"const expression=String(formulas[name]??\"\").trim();"));
test("question 25603: preserves geometry runtime source contract",()=>has(1,"const deps=[...new Set(expression.match(/\\b[A-Za-z_]\\w*\\b/g)??[])];"));
test("question 25604: preserves geometry runtime source contract",()=>has(1,"const vars={...base,...resolved};"));
test("question 25605: preserves geometry runtime source contract",()=>has(1,"for(const dep of deps){"));
test("question 25606: preserves geometry runtime source contract",()=>has(1,"if(dep===name)throw new Error(\"Array formula cycle: \"+name+\" -> \"+name);"));
test("question 25607: preserves geometry runtime source contract",()=>has(1,"if(dep in formulas||rawParameterValue(def,dep)!=null)vars[dep]=resolve(dep);"));
test("question 25608: preserves geometry runtime source contract",()=>has(1,"const kind=FORMULA_FIELDS[name]??\"length\";"));
test("question 25609: preserves geometry runtime source contract",()=>has(1,"const value=dynamicInput.evaluateNumericInput(expression,{kind,variables:vars});"));
test("question 25610: preserves geometry runtime source contract",()=>has(1,"visiting.delete(name);resolved[name]=value;return value;"));
test("question 25611: preserves geometry runtime source contract",()=>has(1,"for(const name of Object.keys(formulas))if(name in FORMULA_FIELDS)resolve(name);"));
test("question 25612: preserves geometry runtime source contract",()=>has(1,"return resolved;"));
test("question 25613: preserves geometry runtime source contract",()=>has(1,"function evaluatedParameters(def,p=project()){"));
test("question 25614: preserves geometry runtime source contract",()=>has(1,"const params=clone(def?.parameters??{}),values=evaluateFormulaFields(def,p);"));
test("question 25615: preserves geometry runtime source contract",()=>has(1,"const value=(name,fallback)=>{"));
test("question 25616: preserves geometry runtime source contract",()=>has(1,"if(name in values)return values[name];"));
test("question 25617: preserves geometry runtime source contract",()=>has(1,"const raw=Number(rawParameterValue(def,name));"));
test("question 25618: preserves geometry runtime source contract",()=>has(1,"return Number.isFinite(raw)?raw:fallback;"));
test("question 25619: preserves geometry runtime source contract",()=>has(1,"if(def?.type===\"Linear\"){"));
test("question 25620: preserves geometry runtime source contract",()=>has(1,"params.count=Math.max(1,Math.trunc(value(\"count\",1)));"));
test("question 25621: preserves geometry runtime source contract",()=>has(1,"params.step=value(\"step\",0);"));
test("question 25622: preserves geometry runtime source contract",()=>has(1,"params.direction=point(params.direction??{x:1,y:0,z:0});"));
test("question 25623: preserves geometry runtime source contract",()=>has(1,"}else if(def?.type===\"Matrix\"){"));
test("question 25624: preserves geometry runtime source contract",()=>has(1,"params.counts=["));
test("question 25625: preserves geometry runtime source contract",()=>has(1,"Math.max(1,Math.trunc(value(\"count_x\",1))),"));
test("question 25626: preserves geometry runtime source contract",()=>has(1,"Math.max(1,Math.trunc(value(\"count_y\",1))),"));
test("question 25627: preserves geometry runtime source contract",()=>has(1,"Math.max(1,Math.trunc(value(\"count_z\",1)))"));
test("question 25628: preserves geometry runtime source contract",()=>has(1,"params.steps=[value(\"step_x\",0),value(\"step_y\",0),value(\"step_z\",0)];"));
test("question 25629: preserves geometry runtime source contract",()=>has(1,"params.directions=(params.directions??[{x:1,y:0,z:0},{x:0,y:1,z:0},{x:0,y:0,z:1}]).map(point);"));
test("question 25630: preserves geometry runtime source contract",()=>has(1,"}else if(def?.type===\"Circular\"){"));
test("question 25631: preserves geometry runtime source contract",()=>has(1,"params.total_angle_deg=value(\"total_angle_deg\",360);"));
test("question 25632: preserves geometry runtime source contract",()=>has(1,"params.initial_angle_deg=value(\"initial_angle_deg\",0);"));
test("question 25633: preserves geometry runtime source contract",()=>has(1,"const radius=value(\"radius_mm\",NaN);params.radius_mm=Number.isFinite(radius)&&radius>=0?radius:null;"));
test("question 25634: preserves geometry runtime source contract",()=>has(1,"params.center=point(params.center??{x:0,y:0,z:0});"));
test("question 25635: preserves geometry runtime source contract",()=>has(1,"params.axis=point(params.axis??{x:0,y:0,z:1});"));
test("question 25636: preserves geometry runtime source contract",()=>has(1,"params.clockwise=params.clockwise===true;"));
test("question 25637: preserves geometry runtime source contract",()=>has(1,"params.rotate_elements=params.rotate_elements!==false;"));
test("question 25638: preserves geometry runtime source contract",()=>has(1,"return params;"));
test("question 25639: preserves geometry runtime source contract",()=>has(1,"function byId(p,id){return (p?.tubes??[]).find((t)=>String(t?.id)===String(id))??null;}"));
test("question 25640: preserves geometry runtime source contract",()=>has(1,"function lockMode(object){return String(object?.lock_state?.mode??object?.lock_mode??\"Unlocked\");}"));
test("question 25641: preserves geometry runtime source contract",()=>has(1,"function assertUnlockedObject(object){"));
test("question 25642: preserves geometry runtime source contract",()=>has(1,"if(lockMode(object)===\"Object\"){"));
test("question 25643: preserves geometry runtime source contract",()=>has(1,"const error=new Error(\"Объект заблокирован\");error.code=\"OBJECT_LOCKED\";throw error;"));
test("question 25644: preserves geometry runtime source contract",()=>has(1,"function assertArrayEditable(def){assertUnlockedObject(def);}"));
test("question 25645: preserves geometry runtime source contract",()=>has(1,"function assertSourcesEditable(ids,p){"));
test("question 25646: preserves geometry runtime source contract",()=>has(1,"for(const id of ids){"));
test("question 25647: preserves geometry runtime source contract",()=>has(1,"const tube=byId(p,id);"));
test("question 25648: preserves geometry runtime source contract",()=>has(1,"if(tube)assertUnlockedObject(tube);"));
test("question 25649: preserves geometry runtime source contract",()=>has(1,"function definitions(p=project()){"));
test("question 25650: preserves geometry runtime source contract",()=>has(1,"if(!p)return [];"));
test("question 25651: preserves geometry runtime source contract",()=>has(1,"if(!Array.isArray(p.associative_arrays))p.associative_arrays=[];"));
test("question 25652: preserves geometry runtime source contract",()=>has(1,"return p.associative_arrays;"));
test("question 25653: preserves geometry runtime source contract",()=>has(1,"function sourceIds(def){return [...new Set((def?.source_tube_ids??[]).map(String).filter(Boolean))];}"));
test("question 25654: preserves geometry runtime source contract",()=>has(1,"function dispatchArrayChange(arrayId,reason){"));
test("question 25655: preserves geometry runtime source contract",()=>has(1,"try{window.dispatchEvent(new CustomEvent(\"tubebender-array-change\",{detail:{array_id:String(arrayId??\"\"),reason:String(reason??\"change\")}}));}catch{}"));
test("question 25656: preserves geometry runtime source contract",()=>has(1,"function memberKey(arrayId,sourceId,index){return String(arrayId)+\"|\"+String(sourceId)+\"|\"+String(index);}"));
test("question 25657: preserves geometry runtime source contract",()=>has(1,"function existingMemberMap(p,arrayId){"));
test("question 25658: preserves geometry runtime source contract",()=>has(1,"const map=new Map();"));
test("question 25659: preserves geometry runtime source contract",()=>has(1,"for(const tube of p?.tubes??[]){"));
test("question 25660: preserves geometry runtime source contract",()=>has(1,"const m=tube?.array_member;"));
test("question 25661: preserves geometry runtime source contract",()=>has(1,"if(String(m?.array_id??\"\")!==String(arrayId))continue;"));
test("question 25662: preserves geometry runtime source contract",()=>has(1,"map.set(memberKey(arrayId,m.source_tube_id,m.member_index),tube);"));
test("question 25663: preserves geometry runtime source contract",()=>has(1,"function detachDerivedLinks(tube){"));
test("question 25664: preserves geometry runtime source contract",()=>has(1,"const copy=clone(tube);"));
test("question 25665: preserves geometry runtime source contract",()=>has(1,"delete copy.array_member;"));
test("question 25666: preserves geometry runtime source contract",()=>has(1,"delete copy.sourceGeometryId;"));
test("question 25667: preserves geometry runtime source contract",()=>has(1,"delete copy.editableGeometryId;"));
test("question 25668: preserves geometry runtime source contract",()=>has(1,"delete copy.source_geometry_id;"));
test("question 25669: preserves geometry runtime source contract",()=>has(1,"delete copy.editable_geometry_id;"));
test("question 25670: preserves geometry runtime source contract",()=>has(1,"if(copy.engineering?.ports){"));
test("question 25671: preserves geometry runtime source contract",()=>has(1,"for(const port of Object.values(copy.engineering.ports)){"));
test("question 25672: preserves geometry runtime source contract",()=>has(1,"if(port&&typeof port===\"object\"){"));
test("question 25673: preserves geometry runtime source contract",()=>has(1,"port.externalRefId=\"\";"));
test("question 25674: preserves geometry runtime source contract",()=>has(1,"port.ownerObjectId=\"\";"));
test("question 25675: preserves geometry runtime source contract",()=>has(1,"if(copy.importEvidence?.spatialPlacement){"));
test("question 25676: preserves geometry runtime source contract",()=>has(1,"copy.importEvidence.spatialPlacement.user_origin_override=true;"));
test("question 25677: preserves geometry runtime source contract",()=>has(1,"copy.importEvidence.spatialPlacement.array_derived=true;"));
test("question 25678: preserves geometry runtime source contract",()=>has(1,"return copy;"));
test("question 25679: preserves geometry runtime source contract",()=>has(1,"function transformForLinearOrMatrix(source,matrix){"));
test("question 25680: preserves geometry runtime source contract",()=>has(1,"const origin=point(source.origin);"));
test("question 25681: preserves geometry runtime source contract",()=>has(1,"const next=transforms.transformPoint(matrix,origin);"));
test("question 25682: preserves geometry runtime source contract",()=>has(1,"return rigid.translateLegacyTubeRigid(source,sub(next,origin));"));
test("question 25683: preserves geometry runtime source contract",()=>has(1,"function circularAngle(def,index,p=project()){"));
test("question 25684: preserves geometry runtime source contract",()=>has(1,"const params=evaluatedParameters(def,p),count=params.count,total=params.total_angle_deg,initial=params.initial_angle_deg??0;"));
test("question 25685: preserves geometry runtime source contract",()=>has(1,"if(!(count>=1)||!Number.isFinite(total))throw new Error(\"Invalid circular array parameters\");"));
test("question 25686: preserves geometry runtime source contract",()=>has(1,"if(index===0)return 0;"));
test("question 25687: preserves geometry runtime source contract",()=>has(1,"const full=Math.abs(Math.abs(total)-360)<1e-9;"));
test("question 25688: preserves geometry runtime source contract",()=>has(1,"const step=count<=1?0:total/(full?count:count-1);"));
test("question 25689: preserves geometry runtime source contract",()=>has(1,"const sign=params.clockwise?-1:1;"));
test("question 25690: preserves geometry runtime source contract",()=>has(1,"return sign*(initial+step*index);"));
test("question 25691: preserves geometry runtime source contract",()=>has(1,"function circularRadiusAdjustedSource(def,source,p=project()){"));
test("question 25692: preserves geometry runtime source contract",()=>has(1,"const params=evaluatedParameters(def,p),radius=params.radius_mm;"));
test("question 25693: preserves geometry runtime source contract",()=>has(1,"if(radius==null)return source;"));
test("question 25694: preserves geometry runtime source contract",()=>has(1,"const center=point(params.center),axis=unit(point(params.axis),\"array axis\"),origin=point(source.origin);"));
test("question 25695: preserves geometry runtime source contract",()=>has(1,"const relative=sub(origin,center),axial=scale(axis,dot(relative,axis)),radial=sub(relative,axial);"));
test("question 25696: preserves geometry runtime source contract",()=>has(1,"let radialUnit;"));
test("question 25697: preserves geometry runtime source contract",()=>has(1,"if(length(radial)>1e-9)radialUnit=unit(radial,\"array radius direction\");"));
test("question 25698: preserves geometry runtime source contract",()=>has(1,"const helper=Math.abs(axis.x)<.9?{x:1,y:0,z:0}:{x:0,y:1,z:0};"));
test("question 25699: preserves geometry runtime source contract",()=>has(1,"radialUnit=unit({x:axis.y*helper.z-axis.z*helper.y,y:axis.z*helper.x-axis.x*helper.z,z:axis.x*helper.y-axis.y*helper.x},\"array radius direction\");"));
test("question 25700: preserves geometry runtime source contract",()=>has(1,"const target=add(center,add(axial,scale(radialUnit,radius)));"));
test("question 25701: preserves geometry runtime source contract",()=>has(1,"const moved=rigid.translateLegacyTubeRigid(source,sub(target,origin));"));
test("question 25702: preserves geometry runtime source contract",()=>has(1,"if(moved?.status!==\"exact\"||!moved.tube)throw new Error(moved?.reason??\"Array radius adjustment failed\");"));
test("question 25703: preserves geometry runtime source contract",()=>has(1,"return moved.tube;"));
test("question 25704: preserves geometry runtime source contract",()=>has(1,"function transformedSource(def,source,index,p=project()){"));
test("question 25705: preserves geometry runtime source contract",()=>has(1,"if(index===0)return {status:\"exact\",tube:clone(source)};"));
test("question 25706: preserves geometry runtime source contract",()=>has(1,"const params=evaluatedParameters(def,p);"));
test("question 25707: preserves geometry runtime source contract",()=>has(1,"if(def.type===\"Linear\"){"));
test("question 25708: preserves geometry runtime source contract",()=>has(1,"const matrices=transforms.linearArrayTransforms(params);"));
test("question 25709: preserves geometry runtime source contract",()=>has(1,"return transformForLinearOrMatrix(source,matrices[index]);"));
test("question 25710: preserves geometry runtime source contract",()=>has(1,"if(def.type===\"Matrix\"){"));
test("question 25711: preserves geometry runtime source contract",()=>has(1,"const matrices=transforms.matrixArrayTransforms(params);"));
test("question 25712: preserves geometry runtime source contract",()=>has(1,"if(def.type===\"Circular\"){"));
test("question 25713: preserves geometry runtime source contract",()=>has(1,"const center=point(params.center??{x:0,y:0,z:0});"));
test("question 25714: preserves geometry runtime source contract",()=>has(1,"const axis=point(params.axis??{x:0,y:0,z:1});"));
test("question 25715: preserves geometry runtime source contract",()=>has(1,"const angle=circularAngle(def,index,p),base=circularRadiusAdjustedSource(def,source,p);"));
test("question 25716: preserves geometry runtime source contract",()=>has(1,"if(params.rotate_elements===false){"));
test("question 25717: preserves geometry runtime source contract",()=>has(1,"const rotation=transforms.rotationMatrix({axis,center,angle_deg:angle});"));
test("question 25718: preserves geometry runtime source contract",()=>has(1,"const origin=point(base.origin);"));
test("question 25719: preserves geometry runtime source contract",()=>has(1,"const next=transforms.transformPoint(rotation,origin);"));
test("question 25720: preserves geometry runtime source contract",()=>has(1,"return rigid.translateLegacyTubeRigid(base,sub(next,origin));"));
test("question 25721: preserves geometry runtime source contract",()=>has(1,"return rigid.rotateLegacyTubeRigid(base,{axis,center,angle_deg:angle});"));
test("question 25722: preserves geometry runtime source contract",()=>has(1,"throw new Error(\"Unsupported associative array type\");"));
test("question 25723: preserves geometry runtime source contract",()=>has(1,"function memberCount(def,p=project()){"));
test("question 25724: preserves geometry runtime source contract",()=>has(1,"if(def.type===\"Linear\"||def.type===\"Circular\")return Math.trunc(Number(params.count)||0);"));
test("question 25725: preserves geometry runtime source contract",()=>has(1,"const counts=params.counts??[];"));
test("question 25726: preserves geometry runtime source contract",()=>has(1,"if(!Array.isArray(counts)||counts.length!==3)return 0;"));
test("question 25727: preserves geometry runtime source contract",()=>has(1,"return counts.map(Number).reduce((a,b)=>a*Math.trunc(b),1);"));
test("question 25728: preserves geometry runtime source contract",()=>has(1,"function createDefinition(input={}){"));
test("question 25729: preserves geometry runtime source contract",()=>has(1,"const type=String(input.type??\"\");"));
test("question 25730: preserves geometry runtime source contract",()=>has(1,"if(![\"Linear\",\"Matrix\",\"Circular\"].includes(type))throw new Error(\"Array type must be Linear, Matrix or Circular\");"));
test("question 25731: preserves geometry runtime source contract",()=>has(1,"const ids=[...new Set((input.source_tube_ids??[]).map(String).filter(Boolean))];"));
test("question 25732: preserves geometry runtime source contract",()=>has(1,"if(!ids.length)throw new Error(\"Associative Array requires at least one source tube\");"));
test("question 25733: preserves geometry runtime source contract",()=>has(1,"id:String(input.id??makeId(\"array\")),"));
test("question 25734: preserves geometry runtime source contract",()=>has(1,"name:String(input.name??(type+\" Array\")),"));
test("question 25735: preserves geometry runtime source contract",()=>has(1,"source_tube_ids:ids,"));
test("question 25736: preserves geometry runtime source contract",()=>has(1,"parameters:clone(input.parameters??{}),"));
test("question 25737: preserves geometry runtime source contract",()=>has(1,"parameter_formulas:clone(input.parameter_formulas??{}),"));
test("question 25738: preserves geometry runtime source contract",()=>has(1,"suppressed_members:[...new Set((input.suppressed_members??[]).map((x)=>Math.trunc(Number(x))).filter((x)=>Number.isInteger(x)&&x>0))].sort((a,b)=>a-b),"));
test("question 25739: preserves geometry runtime source contract",()=>has(1,"member_ids:clone(input.member_ids??{}),"));
test("question 25740: preserves geometry runtime source contract",()=>has(1,"associative:true,"));
test("question 25741: preserves geometry runtime source contract",()=>has(1,"status:\"NeedsSync\""));
test("question 25742: preserves geometry runtime source contract",()=>has(1,"const count=memberCount(def);"));
test("question 25743: preserves geometry runtime source contract",()=>has(1,"if(count<1)throw new Error(\"Array member count must be >= 1\");"));
test("question 25744: preserves geometry runtime source contract",()=>has(1,"return Object.freeze(def);"));
test("question 25745: preserves geometry runtime source contract",()=>has(1,"function synchronize(p=project()){"));
test("question 25746: preserves geometry runtime source contract",()=>has(1,"if(!p||!transforms||!rigid||syncing)return {ok:true,changed:false};"));
test("question 25747: preserves geometry runtime source contract",()=>has(1,"syncing=true;"));
test("question 25748: preserves geometry runtime source contract",()=>has(1,"const defs=definitions(p);"));
test("question 25749: preserves geometry runtime source contract",()=>has(1,"let changed=false;"));
test("question 25750: preserves geometry runtime source contract",()=>has(1,"const keepDerived=new Set();"));
test("question 25751: preserves geometry runtime source contract",()=>has(1,"for(const def of defs){"));
test("question 25752: preserves geometry runtime source contract",()=>has(1,"const sources=sourceIds(def).map((id)=>byId(p,id));"));
test("question 25753: preserves geometry runtime source contract",()=>has(1,"const missing=sourceIds(def).filter((id)=>!byId(p,id));"));
test("question 25754: preserves geometry runtime source contract",()=>has(1,"if(missing.length){"));
test("question 25755: preserves geometry runtime source contract",()=>has(1,"def.status=\"LostSource\";"));
test("question 25756: preserves geometry runtime source contract",()=>has(1,"def.missing_source_ids=missing;"));
test("question 25757: preserves geometry runtime source contract",()=>has(1,"for(const tube of p.tubes??[]){"));
test("question 25758: preserves geometry runtime source contract",()=>has(1,"if(String(tube?.array_member?.array_id??\"\")===String(def.id)){"));
test("question 25759: preserves geometry runtime source contract",()=>has(1,"tube.array_member={...tube.array_member,status:\"LostSource\"};"));
test("question 25760: preserves geometry runtime source contract",()=>has(1,"keepDerived.add(String(tube.id));"));
test("question 25761: preserves geometry runtime source contract",()=>has(1,"const existing=existingMemberMap(p,def.id);"));
test("question 25762: preserves geometry runtime source contract",()=>has(1,"const suppressed=new Set(def.suppressed_members??[]);"));
test("question 25763: preserves geometry runtime source contract",()=>has(1,"if(count<1){def.status=\"Error\";continue;}"));
test("question 25764: preserves geometry runtime source contract",()=>has(1,"for(const source of sources){"));
test("question 25765: preserves geometry runtime source contract",()=>has(1,"for(let index=1;index<count;index++){"));
test("question 25766: preserves geometry runtime source contract",()=>has(1,"if(suppressed.has(index))continue;"));
test("question 25767: preserves geometry runtime source contract",()=>has(1,"const key=memberKey(def.id,source.id,index);"));
test("question 25768: preserves geometry runtime source contract",()=>has(1,"try{result=transformedSource(def,source,index);}"));
test("question 25769: preserves geometry runtime source contract",()=>has(1,"catch(error){def.status=\"Error\";def.error=String(error?.message??error);continue;}"));
test("question 25770: preserves geometry runtime source contract",()=>has(1,"if(result?.status!==\"exact\"||!result.tube){"));
test("question 25771: preserves geometry runtime source contract",()=>has(1,"def.status=\"Error\";def.error=result?.reason??\"Array transform failed\";continue;"));
test("question 25772: preserves geometry runtime source contract",()=>has(1,"const previous=existing.get(key);"));
test("question 25773: preserves geometry runtime source contract",()=>has(1,"const member=detachDerivedLinks(result.tube);"));
test("question 25774: preserves geometry runtime source contract",()=>has(1,"const stableKey=String(source.id)+\":\"+String(index);"));
test("question 25775: preserves geometry runtime source contract",()=>has(1,"const stableId=def.member_ids?.[stableKey]??previous?.id??makeId(\"array-member\");"));
test("question 25776: preserves geometry runtime source contract",()=>has(1,"if(!def.member_ids||typeof def.member_ids!==\"object\")def.member_ids={};"));
test("question 25777: preserves geometry runtime source contract",()=>has(1,"def.member_ids[stableKey]=stableId;"));
test("question 25778: preserves geometry runtime source contract",()=>has(1,"member.id=stableId;"));
test("question 25779: preserves geometry runtime source contract",()=>has(1,"member.name=(source.name??source.id)+\" [\"+def.name+\" \"+(index+1)+\"]\";"));
test("question 25780: preserves geometry runtime source contract",()=>has(1,"member.array_member={"));
test("question 25781: preserves geometry runtime source contract",()=>has(1,"array_id:def.id,"));
test("question 25782: preserves geometry runtime source contract",()=>has(1,"source_tube_id:String(source.id),"));
test("question 25783: preserves geometry runtime source contract",()=>has(1,"member_index:index,"));
test("question 25784: preserves geometry runtime source contract",()=>has(1,"status:\"Valid\","));
test("question 25785: preserves geometry runtime source contract",()=>has(1,"derived_readonly:true"));
test("question 25786: preserves geometry runtime source contract",()=>has(1,"member.uiHiddenIn3D=previous?.uiHiddenIn3D===true;"));
test("question 25787: preserves geometry runtime source contract",()=>has(1,"member.uiTransparentIn3D=false;"));
test("question 25788: preserves geometry runtime source contract",()=>has(1,"keepDerived.add(String(member.id));"));
test("question 25789: preserves geometry runtime source contract",()=>has(1,"if(previous){"));
test("question 25790: preserves geometry runtime source contract",()=>has(1,"const before=JSON.stringify(previous);"));
test("question 25791: preserves geometry runtime source contract",()=>has(1,"for(const k of Object.keys(previous))delete previous[k];"));
test("question 25792: preserves geometry runtime source contract",()=>has(1,"Object.assign(previous,member);"));
test("question 25793: preserves geometry runtime source contract",()=>has(1,"if(JSON.stringify(previous)!==before)changed=true;"));
test("question 25794: preserves geometry runtime source contract",()=>has(1,"p.tubes.push(member);"));
test("question 25795: preserves geometry runtime source contract",()=>has(1,"changed=true;"));
test("question 25796: preserves geometry runtime source contract",()=>has(1,"if(def.status!==\"Error\"){"));
test("question 25797: preserves geometry runtime source contract",()=>has(1,"def.status=\"Valid\";"));
test("question 25798: preserves geometry runtime source contract",()=>has(1,"delete def.error;"));
test("question 25799: preserves geometry runtime source contract",()=>has(1,"delete def.missing_source_ids;"));
test("question 25800: preserves geometry runtime source contract",()=>has(1,"const filtered=(p.tubes??[]).filter((tube)=>{"));
test("question 25801: preserves geometry runtime source contract",()=>has(1,"if(!tube?.array_member)return true;"));
test("question 25802: preserves geometry runtime source contract",()=>has(1,"const arrayExists=defs.some((d)=>String(d.id)===String(tube.array_member.array_id));"));
test("question 25803: preserves geometry runtime source contract",()=>has(1,"if(!arrayExists)return false;"));
test("question 25804: preserves geometry runtime source contract",()=>has(1,"return keepDerived.has(String(tube.id));"));
test("question 25805: preserves geometry runtime source contract",()=>has(1,"if(filtered.length!==(p.tubes??[]).length){p.tubes=filtered;changed=true;}"));
test("question 25806: preserves geometry runtime source contract",()=>has(1,"return {ok:true,changed};"));
test("question 25807: preserves geometry runtime source contract",()=>has(1,"}finally{syncing=false;}"));
test("question 25808: preserves geometry runtime source contract",()=>has(1,"function addArray(input,p=project()){"));
test("question 25809: preserves geometry runtime source contract",()=>has(1,"if(!p)throw new Error(\"No active project\");"));
test("question 25810: preserves geometry runtime source contract",()=>has(1,"assertSourcesEditable(input?.source_tube_ids??[],p);"));
test("question 25811: preserves geometry runtime source contract",()=>has(1,"const def=createDefinition(input);"));
test("question 25812: preserves geometry runtime source contract",()=>has(1,"definitions(p).push(clone(def));"));
test("question 25813: preserves geometry runtime source contract",()=>has(1,"synchronize(p);"));
test("question 25814: preserves geometry runtime source contract",()=>has(1,"dispatchArrayChange(def.id,\"create\");"));
test("question 25815: preserves geometry runtime source contract",()=>has(1,"function definitionById(arrayId,p=project()){"));
test("question 25816: preserves geometry runtime source contract",()=>has(1,"return definitions(p).find(def=>String(def?.id)===String(arrayId))??null;"));
test("question 25817: preserves geometry runtime source contract",()=>has(1,"function updateParameters(arrayId,patch={},options={},p=project()){"));
test("question 25818: preserves geometry runtime source contract",()=>has(1,"const def=definitionById(arrayId,p);if(!def)throw new Error(\"Associative Array not found\");"));
test("question 25819: preserves geometry runtime source contract",()=>has(1,"assertArrayEditable(def);"));
test("question 25820: preserves geometry runtime source contract",()=>has(1,"def.parameters={...(def.parameters??{}),...clone(patch)};"));
test("question 25821: preserves geometry runtime source contract",()=>has(1,"if(patch.counts)def.parameters.counts=[...patch.counts];"));
test("question 25822: preserves geometry runtime source contract",()=>has(1,"if(patch.steps)def.parameters.steps=[...patch.steps];"));
test("question 25823: preserves geometry runtime source contract",()=>has(1,"if(patch.directions)def.parameters.directions=clone(patch.directions);"));
