import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const files=["src/domain/constraints/constraint-dof-analysis.mjs","src/domain/editing/dynamic-input.mjs","src/domain/manufacturing/bending-simulation-collision.mjs","src/import/dwfx/current-project-ui.js","src/ui/transform-stack-runtime.js","src/recognition/legacy-row-kinematics.mjs","src/recognition/tube-local-frame.mjs","src/import/dwfx/transform-provenance.mjs"];
const sources=files.map(rel=>fs.readFileSync(path.join(root,rel),"utf8"));
const has=(fileIndex,snippet)=>assert.ok(sources[fileIndex].includes(snippet),"missing source contract: "+files[fileIndex]+"::"+snippet);
test("question 31499: preserves source contract",()=>has(0,"const freeze=(v)=>{"));
test("question 31500: preserves source contract",()=>has(0,"if(Array.isArray(v))return Object.freeze(v.map(freeze));"));
test("question 31501: preserves source contract",()=>has(0,"if(v&&typeof v===\"object\"&&!Object.isFrozen(v)){for(const k of Object.keys(v))v[k]=freeze(v[k]);return Object.freeze(v);}"));
test("question 31502: preserves source contract",()=>has(0,"const clone=(v)=>v==null?v:structuredClone(v);"));
test("question 31503: preserves source contract",()=>has(0,"const RIGID_AXES=Object.freeze([\"Tx\",\"Ty\",\"Tz\",\"Rx\",\"Ry\",\"Rz\"]);"));
test("question 31504: preserves source contract",()=>has(0,"function objectIds(constraint){"));
test("question 31505: preserves source contract",()=>has(0,"return [...new Set((constraint?.references??[]).map(ref=>String(ref?.object_id??\"\")).filter(Boolean))];"));
test("question 31506: preserves source contract",()=>has(0,"function refKey(ref){return String(ref?.object_id??\"\")+\"|\"+String(ref?.subentity_id??\"\");}"));
test("question 31507: preserves source contract",()=>has(0,"function variable(objectId,axis){return String(objectId)+\":\"+String(axis);}"));
test("question 31508: preserves source contract",()=>has(0,"function scalarVariable(ref){return \"scalar:\"+refKey(ref);}"));
test("question 31509: preserves source contract",()=>has(0,"function row(entries={},meta={}){"));
test("question 31510: preserves source contract",()=>has(0,"return {entries:{...entries},meta:{...meta}};"));
test("question 31511: preserves source contract",()=>has(0,"function relative(a,b,axis,meta){"));
test("question 31512: preserves source contract",()=>has(0,"return row({[variable(a,axis)]:1,[variable(b,axis)]:-1},meta);"));
test("question 31513: preserves source contract",()=>has(0,"function fixed(a,axis,meta){return row({[variable(a,axis)]:1},meta);}"));
test("question 31514: preserves source contract",()=>has(0,"function relationRows(constraint){"));
test("question 31515: preserves source contract",()=>has(0,"const refs=constraint?.references??[],ids=objectIds(constraint),type=String(constraint?.type??\"\"),meta={constraint_id:String(constraint?.id??\"\"),type};"));
test("question 31516: preserves source contract",()=>has(0,"const a=ids[0],b=ids[1]??ids[0],out=[];"));
test("question 31517: preserves source contract",()=>has(0,"if(!a)return out;"));
test("question 31518: preserves source contract",()=>has(0,"const rel=(axis)=>out.push(relative(a,b,axis,meta));"));
test("question 31519: preserves source contract",()=>has(0,"const fix=(axis)=>out.push(fixed(a,axis,meta));"));
test("question 31520: preserves source contract",()=>has(0,"if(type===\"Coincident\"){[\"Tx\",\"Ty\",\"Tz\"].forEach(rel);}"));
test("question 31521: preserves source contract",()=>has(0,"else if(type===\"Concentric\"){[\"Tx\",\"Ty\",\"Tz\"].forEach(rel);}"));
test("question 31522: preserves source contract",()=>has(0,"else if(type===\"Collinear\"){[\"Tx\",\"Ty\",\"Rx\",\"Ry\"].forEach(rel);}"));
test("question 31523: preserves source contract",()=>has(0,"else if(type===\"Parallel\"){[\"Rx\",\"Ry\"].forEach(rel);}"));
test("question 31524: preserves source contract",()=>has(0,"else if(type===\"Perpendicular\"){rel(\"Rz\");}"));
test("question 31525: preserves source contract",()=>has(0,"else if(type===\"Tangent\"){rel(\"Tz\");}"));
test("question 31526: preserves source contract",()=>has(0,"else if(type===\"Horizontal\"||type===\"Vertical\"){[\"Rx\",\"Ry\"].forEach(fix);}"));
test("question 31527: preserves source contract",()=>has(0,"else if(type===\"FixedDirection\"){[\"Rx\",\"Ry\"].forEach(fix);}"));
test("question 31528: preserves source contract",()=>has(0,"else if(type===\"FixedPoint\"){[\"Tx\",\"Ty\",\"Tz\"].forEach(fix);}"));
test("question 31529: preserves source contract",()=>has(0,"else if(type===\"FixedGeometry\"){RIGID_AXES.forEach(fix);}"));
test("question 31530: preserves source contract",()=>has(0,"else if(type===\"Equal\"&&refs.length>=2){"));
test("question 31531: preserves source contract",()=>has(0,"out.push(row({[scalarVariable(refs[0])]:1,[scalarVariable(refs[1])]:-1},meta));"));
test("question 31532: preserves source contract",()=>has(0,"function gaussianRank(rows,variables,{epsilon=1e-10}={}){"));
test("question 31533: preserves source contract",()=>has(0,"const cols=[...variables],matrix=rows.map(r=>cols.map(c=>Number(r.entries[c]??0)));"));
test("question 31534: preserves source contract",()=>has(0,"let rank=0,col=0;const pivots=[],dependent=[];"));
test("question 31535: preserves source contract",()=>has(0,"const sourceIndexes=rows.map((_,i)=>i);"));
test("question 31536: preserves source contract",()=>has(0,"while(rank<matrix.length&&col<cols.length){"));
test("question 31537: preserves source contract",()=>has(0,"let pivot=-1,best=epsilon;"));
test("question 31538: preserves source contract",()=>has(0,"for(let r=rank;r<matrix.length;r++){"));
test("question 31539: preserves source contract",()=>has(0,"const value=Math.abs(matrix[r][col]);"));
test("question 31540: preserves source contract",()=>has(0,"if(value>best){best=value;pivot=r;}"));
test("question 31541: preserves source contract",()=>has(0,"if(pivot<0){col++;continue;}"));
test("question 31542: preserves source contract",()=>has(0,"[matrix[rank],matrix[pivot]]=[matrix[pivot],matrix[rank]];"));
test("question 31543: preserves source contract",()=>has(0,"[sourceIndexes[rank],sourceIndexes[pivot]]=[sourceIndexes[pivot],sourceIndexes[rank]];"));
test("question 31544: preserves source contract",()=>has(0,"const p=matrix[rank][col];"));
test("question 31545: preserves source contract",()=>has(0,"for(let c=col;c<cols.length;c++)matrix[rank][c]/=p;"));
test("question 31546: preserves source contract",()=>has(0,"for(let r=0;r<matrix.length;r++){"));
test("question 31547: preserves source contract",()=>has(0,"if(r===rank)continue;"));
test("question 31548: preserves source contract",()=>has(0,"const factor=matrix[r][col];if(Math.abs(factor)<=epsilon)continue;"));
test("question 31549: preserves source contract",()=>has(0,"for(let c=col;c<cols.length;c++)matrix[r][c]-=factor*matrix[rank][c];"));
test("question 31550: preserves source contract",()=>has(0,"pivots.push({row_index:sourceIndexes[rank],column:cols[col]});"));
test("question 31551: preserves source contract",()=>has(0,"rank++;col++;"));
test("question 31552: preserves source contract",()=>has(0,"const pivotRows=new Set(pivots.map(p=>p.row_index));"));
test("question 31553: preserves source contract",()=>has(0,"for(let i=0;i<rows.length;i++)if(!pivotRows.has(i))dependent.push(i);"));
test("question 31554: preserves source contract",()=>has(0,"return {rank,pivots,dependent_rows:dependent,free_columns:cols.filter(c=>!pivots.some(p=>p.column===c))};"));
test("question 31555: preserves source contract",()=>has(0,"function classifyAxis(variableName){"));
test("question 31556: preserves source contract",()=>has(0,"const split=String(variableName).lastIndexOf(\":\");"));
test("question 31557: preserves source contract",()=>has(0,"const object_id=split>=0?String(variableName).slice(0,split):\"\";"));
test("question 31558: preserves source contract",()=>has(0,"const axis=split>=0?String(variableName).slice(split+1):String(variableName);"));
test("question 31559: preserves source contract",()=>has(0,"if(String(variableName).startsWith(\"scalar:\"))return {object_id:null,axis:\"Scalar\",variable:variableName};"));
test("question 31560: preserves source contract",()=>has(0,"return {object_id,axis,variable:variableName};"));
test("question 31561: preserves source contract",()=>has(0,"export function analyzeConstraintDoF(project,{"));
test("question 31562: preserves source contract",()=>has(0,"include_disabled=false,"));
test("question 31563: preserves source contract",()=>has(0,"object_ids=[]"));
test("question 31564: preserves source contract",()=>has(0,"const constraints=Array.isArray(project?.geometric_constraints)?project.geometric_constraints:[];"));
test("question 31565: preserves source contract",()=>has(0,"const active=constraints.filter(c=>include_disabled||c?.enabled!==false);"));
test("question 31566: preserves source contract",()=>has(0,"const invalid=active.filter(c=>[\"LostReference\",\"Error\",\"Invalid\"].includes(String(c?.status)));"));
test("question 31567: preserves source contract",()=>has(0,"const conflicts=active.filter(c=>String(c?.status)===\"Conflict\");"));
test("question 31568: preserves source contract",()=>has(0,"const refs=active.flatMap(c=>c?.references??[]);"));
test("question 31569: preserves source contract",()=>has(0,"const scopedIds=(object_ids??[]).map(String).filter(Boolean);"));
test("question 31570: preserves source contract",()=>has(0,"const ids=[...new Set([...refs.map(r=>String(r?.object_id??\"\")).filter(Boolean),...scopedIds])];"));
test("question 31571: preserves source contract",()=>has(0,"const variableSet=new Set();"));
test("question 31572: preserves source contract",()=>has(0,"for(const id of ids)for(const axis of RIGID_AXES)variableSet.add(variable(id,axis));"));
test("question 31573: preserves source contract",()=>has(0,"for(const c of active)if(c?.type===\"Equal\")for(const ref of c.references??[])variableSet.add(scalarVariable(ref));"));
test("question 31574: preserves source contract",()=>has(0,"const rows=[];"));
test("question 31575: preserves source contract",()=>has(0,"for(const c of active){"));
test("question 31576: preserves source contract",()=>has(0,"if([\"LostReference\",\"Error\",\"Invalid\",\"Disabled\"].includes(String(c?.status)))continue;"));
test("question 31577: preserves source contract",()=>has(0,"rows.push(...relationRows(c));"));
test("question 31578: preserves source contract",()=>has(0,"const linear=gaussianRank(rows,variableSet);"));
test("question 31579: preserves source contract",()=>has(0,"const dependentConstraints=[...new Set(linear.dependent_rows.map(index=>rows[index]?.meta?.constraint_id).filter(Boolean))];"));
test("question 31580: preserves source contract",()=>has(0,"const total=variableSet.size,free=Math.max(0,total-linear.rank);"));
test("question 31581: preserves source contract",()=>has(0,"if(invalid.length)status=\"Invalid\";"));
test("question 31582: preserves source contract",()=>has(0,"else if(conflicts.length||dependentConstraints.length)status=\"Over-constrained\";"));
test("question 31583: preserves source contract",()=>has(0,"else if(total===0||free>0)status=\"Under-constrained\";"));
test("question 31584: preserves source contract",()=>has(0,"else status=\"Fully constrained\";"));
test("question 31585: preserves source contract",()=>has(0,"const freeVariables=linear.free_columns.map(classifyAxis);"));
test("question 31586: preserves source contract",()=>has(0,"const byObject={};"));
test("question 31587: preserves source contract",()=>has(0,"for(const id of ids)byObject[id]={object_id:id,free_translation:[],free_rotation:[],free_scalar:[],free_variables:[]};"));
test("question 31588: preserves source contract",()=>has(0,"for(const item of freeVariables){"));
test("question 31589: preserves source contract",()=>has(0,"if(item.object_id&&byObject[item.object_id]){"));
test("question 31590: preserves source contract",()=>has(0,"byObject[item.object_id].free_variables.push(item.axis);"));
test("question 31591: preserves source contract",()=>has(0,"if(item.axis.startsWith(\"T\"))byObject[item.object_id].free_translation.push(item.axis);"));
test("question 31592: preserves source contract",()=>has(0,"else if(item.axis.startsWith(\"R\"))byObject[item.object_id].free_rotation.push(item.axis);"));
test("question 31593: preserves source contract",()=>has(0,"for(const item of freeVariables.filter(v=>v.axis===\"Scalar\")){"));
test("question 31594: preserves source contract",()=>has(0,"const key=String(item.variable).slice(\"scalar:\".length),objectId=key.split(\"|\")[0];"));
test("question 31595: preserves source contract",()=>has(0,"if(byObject[objectId])byObject[objectId].free_scalar.push(key);"));
test("question 31596: preserves source contract",()=>has(0,"const reasons=[];"));
test("question 31597: preserves source contract",()=>has(0,"if(invalid.length)reasons.push(\"Есть потерянные или невычислимые ссылки Constraints.\");"));
test("question 31598: preserves source contract",()=>has(0,"if(conflicts.length)reasons.push(\"Есть конфликтующие Driving Constraints.\");"));
test("question 31599: preserves source contract",()=>has(0,"if(dependentConstraints.length)reasons.push(\"Есть избыточные зависимые Constraints.\");"));
test("question 31600: preserves source contract",()=>has(0,"if(status===\"Under-constrained\"&&free>0)reasons.push(\"Остались свободные степени перемещения, вращения или параметров.\");"));
test("question 31601: preserves source contract",()=>has(0,"if(status===\"Fully constrained\")reasons.push(\"Все структурные степени свободы ограничены независимыми Constraints.\");"));
test("question 31602: preserves source contract",()=>has(0,"return freeze({"));
test("question 31603: preserves source contract",()=>has(0,"total_dof:total,"));
test("question 31604: preserves source contract",()=>has(0,"constrained_dof:linear.rank,"));
test("question 31605: preserves source contract",()=>has(0,"remaining_dof:free,"));
test("question 31606: preserves source contract",()=>has(0,"variables:Object.freeze([...variableSet]),"));
test("question 31607: preserves source contract",()=>has(0,"free_variables:freeVariables,"));
test("question 31608: preserves source contract",()=>has(0,"objects:Object.freeze(Object.values(byObject).map(freeze)),"));
test("question 31609: preserves source contract",()=>has(0,"invalid_constraint_ids:Object.freeze(invalid.map(c=>String(c.id))),"));
test("question 31610: preserves source contract",()=>has(0,"conflict_constraint_ids:Object.freeze(conflicts.map(c=>String(c.id))),"));
test("question 31611: preserves source contract",()=>has(0,"redundant_constraint_ids:Object.freeze(dependentConstraints),"));
test("question 31612: preserves source contract",()=>has(0,"reasons:Object.freeze(reasons),"));
test("question 31613: preserves source contract",()=>has(0,"equation_count:rows.length,"));
test("question 31614: preserves source contract",()=>has(0,"structural_rank:linear.rank"));
test("question 31615: preserves source contract",()=>has(0,"export function dofLabel(axis){"));
test("question 31616: preserves source contract",()=>has(0,"Tx:\"Move X\",Ty:\"Move Y\",Tz:\"Move Z\","));
test("question 31617: preserves source contract",()=>has(0,"Rx:\"Rotate X\",Ry:\"Rotate Y\",Rz:\"Rotate Z\","));
test("question 31618: preserves source contract",()=>has(0,"Scalar:\"Parameter\""));
test("question 31619: preserves source contract",()=>has(0,"})[String(axis)]??String(axis);"));
test("question 31620: preserves source contract",()=>has(1,"function freeze(value){"));
test("question 31621: preserves source contract",()=>has(1,"if(Array.isArray(value))return Object.freeze(value.map(freeze));"));
test("question 31622: preserves source contract",()=>has(1,"if(value&&typeof value===\"object\"&&!Object.isFrozen(value)){for(const key of Object.keys(value))value[key]=freeze(value[key]);return Object.freeze(value);}"));
test("question 31623: preserves source contract",()=>has(1,"return value;"));
test("question 31624: preserves source contract",()=>has(1,"const LENGTH_UNITS=Object.freeze({mm:1,cm:10,m:1000,in:25.4,inch:25.4});"));
test("question 31625: preserves source contract",()=>has(1,"const ANGLE_UNITS=Object.freeze({deg:1,\"°\":1,rad:180/Math.PI});"));
test("question 31626: preserves source contract",()=>has(1,"export const DECIMAL_SEPARATOR_PREFERENCES=Object.freeze([\"auto\",\".\",\",\"]);"));
test("question 31627: preserves source contract",()=>has(1,"export function normalizeDecimalSeparatorPreference(value=\"auto\"){"));
test("question 31628: preserves source contract",()=>has(1,"const preference=String(value??\"auto\").trim();"));
test("question 31629: preserves source contract",()=>has(1,"if(!DECIMAL_SEPARATOR_PREFERENCES.includes(preference))throw new RangeError(\"decimal_separator must be auto, . or ,\");"));
test("question 31630: preserves source contract",()=>has(1,"return preference;"));
test("question 31631: preserves source contract",()=>has(1,"export function detectNumericDecimalSeparator(input){"));
test("question 31632: preserves source contract",()=>has(1,"const text=String(input??\"\").trim();"));
test("question 31633: preserves source contract",()=>has(1,"const comma=/(?:^|[^\\d])[-+]?\\d+,\\d+(?:$|[^\\d])/.test(text);"));
test("question 31634: preserves source contract",()=>has(1,"const dot=/(?:^|[^\\d])[-+]?\\d+\\.\\d+(?:$|[^\\d])/.test(text);"));
test("question 31635: preserves source contract",()=>has(1,"if(comma&&!dot)return \",\";"));
test("question 31636: preserves source contract",()=>has(1,"if(dot&&!comma)return \".\";"));
test("question 31637: preserves source contract",()=>has(1,"if(comma&&dot)return \"mixed\";"));
test("question 31638: preserves source contract",()=>has(1,"return null;"));
test("question 31639: preserves source contract",()=>has(1,"export function resolveDecimalSeparator(preference=\"auto\",{locale=null,input=null}={}){"));
test("question 31640: preserves source contract",()=>has(1,"const normalized=normalizeDecimalSeparatorPreference(preference);"));
test("question 31641: preserves source contract",()=>has(1,"if(normalized!==\"auto\")return normalized;"));
test("question 31642: preserves source contract",()=>has(1,"const detected=input==null?null:detectNumericDecimalSeparator(input);"));
test("question 31643: preserves source contract",()=>has(1,"if(detected===\".\"||detected===\",\")return detected;"));
test("question 31644: preserves source contract",()=>has(1,"const formatted=new Intl.NumberFormat(String(locale),{useGrouping:false,maximumFractionDigits:1}).format(1.1);"));
test("question 31645: preserves source contract",()=>has(1,"if(formatted.includes(\",\"))return \",\";"));
test("question 31646: preserves source contract",()=>has(1,"export function formatNumericInput(value,{decimal_separator=\"auto\",locale=null,maximumFractionDigits=6}={}){"));
test("question 31647: preserves source contract",()=>has(1,"const n=Number(value);"));
test("question 31648: preserves source contract",()=>has(1,"if(!Number.isFinite(n))throw new TypeError(\"value must be finite\");"));
test("question 31649: preserves source contract",()=>has(1,"const digits=Math.max(0,Math.min(12,Math.trunc(Number(maximumFractionDigits))));"));
test("question 31650: preserves source contract",()=>has(1,"let text=n.toFixed(digits);"));
test("question 31651: preserves source contract",()=>has(1,"if(text.includes(\".\"))text=text.replace(/0+$/,\"\").replace(/\\.$/,\"\");"));
test("question 31652: preserves source contract",()=>has(1,"return resolveDecimalSeparator(decimal_separator,{locale})===\",\"?text.replace(\".\",\",\"):text;"));
test("question 31653: preserves source contract",()=>has(1,"function normalizeDecimal(text){return String(text??\"\").trim().replace(/(\\d),(\\d)/g,\"$1.$2\");}"));
test("question 31654: preserves source contract",()=>has(1,"function replaceUnits(expr,kind){"));
test("question 31655: preserves source contract",()=>has(1,"if(kind===\"scalar\")return expr;"));
test("question 31656: preserves source contract",()=>has(1,"const units=kind===\"angle\"?ANGLE_UNITS:LENGTH_UNITS;"));
test("question 31657: preserves source contract",()=>has(1,"return expr.replace(/(\\d+(?:\\.\\d+)?)(?:\\s*)(mm|cm|inch|in|m|deg|rad|°)/gi,(_m,num,unit)=>{"));
test("question 31658: preserves source contract",()=>has(1,"const key=String(unit).toLowerCase(),factor=units[key]??units[unit];"));
test("question 31659: preserves source contract",()=>has(1,"if(factor==null)return _m;"));
test("question 31660: preserves source contract",()=>has(1,"return \"(\"+num+\"*\"+factor+\")\";"));
test("question 31661: preserves source contract",()=>has(1,"function safeArithmetic(expr,variables={}){"));
test("question 31662: preserves source contract",()=>has(1,"let text=String(expr);"));
test("question 31663: preserves source contract",()=>has(1,"text=text.replace(/\\b[A-Za-z_]\\w*\\b/g,(name)=>{if(!(name in variables))throw new Error(\"Unknown variable: \"+name);const n=Number(variables[name]);if(!Number.isFinite(n))throw new Error(\"Variable is not finite: \"+name);return \"(\"+n+\")\";});"));
test("question 31664: preserves source contract",()=>has(1,"if(!/^[0-9eE+*/().\\s-]+$/.test(text))throw new Error(\"Unsupported expression\");"));
test("question 31665: preserves source contract",()=>has(1,"const value=Function('\"use strict\";return ('+text+')')();"));
test("question 31666: preserves source contract",()=>has(1,"if(!Number.isFinite(value))throw new Error(\"Expression result is not finite\");"));
test("question 31667: preserves source contract",()=>has(1,"export function evaluateNumericInput(input,{kind=\"length\",variables={}}={}){let expr=normalizeDecimal(input);if(!expr)throw new Error(\"Value is required\");expr=replaceUnits(expr,kind);return safeArithmetic(expr,variables);}"));
test("question 31668: preserves source contract",()=>has(1,"export function evaluateAssociativeFormulas(formulas={},baseVariables={}){"));
test("question 31669: preserves source contract",()=>has(1,"const source={...formulas},resolved={...baseVariables},visiting=new Set(),visited=new Set();"));
test("question 31670: preserves source contract",()=>has(1,"function resolve(name){"));
test("question 31671: preserves source contract",()=>has(1,"if(name in resolved&&!(name in source))return Number(resolved[name]);"));
test("question 31672: preserves source contract",()=>has(1,"if(visited.has(name))return Number(resolved[name]);"));
test("question 31673: preserves source contract",()=>has(1,"if(visiting.has(name))throw new Error(\"Formula cycle detected: \"+[...visiting,name].join(\" -> \"));"));
test("question 31674: preserves source contract",()=>has(1,"if(!(name in source))throw new Error(\"Unknown variable: \"+name);"));
test("question 31675: preserves source contract",()=>has(1,"visiting.add(name);"));
test("question 31676: preserves source contract",()=>has(1,"const expression=normalizeDecimal(source[name]);"));
test("question 31677: preserves source contract",()=>has(1,"const deps=[...new Set(expression.match(/\\b[A-Za-z_]\\w*\\b/g)??[])];"));
test("question 31678: preserves source contract",()=>has(1,"const vars={...resolved};for(const dep of deps)vars[dep]=resolve(dep);"));
test("question 31679: preserves source contract",()=>has(1,"const value=evaluateNumericInput(expression,{kind:\"length\",variables:vars});"));
test("question 31680: preserves source contract",()=>has(1,"visiting.delete(name);visited.add(name);resolved[name]=value;return value;"));
test("question 31681: preserves source contract",()=>has(1,"for(const name of Object.keys(source))resolve(name);"));
test("question 31682: preserves source contract",()=>has(1,"return freeze(resolved);"));
test("question 31683: preserves source contract",()=>has(1,"function splitCoordinates(text,{decimal_separator=\"auto\"}={}){"));
test("question 31684: preserves source contract",()=>has(1,"const raw=String(text??\"\").trim(),preference=normalizeDecimalSeparatorPreference(decimal_separator);"));
test("question 31685: preserves source contract",()=>has(1,"if(raw.includes(\";\"))return raw.split(\";\").map((x)=>x.trim());"));
test("question 31686: preserves source contract",()=>has(1,"if(preference===\",\")throw new Error(\"With decimal comma, separate X/Y/Z coordinates using semicolons\");"));
test("question 31687: preserves source contract",()=>has(1,"return raw.split(/\\s*,\\s*/).map((x)=>x.trim());"));
test("question 31688: preserves source contract",()=>has(1,"export function parseCoordinateInput(input,{origin={x:0,y:0,z:0},variables={},decimal_separator=\"auto\"}={}){"));
test("question 31689: preserves source contract",()=>has(1,"let text=String(input??\"\").trim(),relative=false;if(text.startsWith(\"@\")){relative=true;text=text.slice(1).trim();}"));
test("question 31690: preserves source contract",()=>has(1,"if(text.includes(\"<\")){"));
test("question 31691: preserves source contract",()=>has(1,"const parts=text.split(\"<\").map((x)=>x.trim());if(parts.length<2||parts.length>3)throw new Error(\"Polar input must be distance<azimuth or distance<azimuth<elevation\");"));
test("question 31692: preserves source contract",()=>has(1,"const distance=evaluateNumericInput(parts[0],{kind:\"length\",variables});"));
test("question 31693: preserves source contract",()=>has(1,"const az=evaluateNumericInput(parts[1],{kind:\"angle\",variables})*Math.PI/180;"));
test("question 31694: preserves source contract",()=>has(1,"const el=parts.length===3?evaluateNumericInput(parts[2],{kind:\"angle\",variables})*Math.PI/180:0;"));
test("question 31695: preserves source contract",()=>has(1,"const delta={x:distance*Math.cos(el)*Math.cos(az),y:distance*Math.cos(el)*Math.sin(az),z:distance*Math.sin(el)};"));
test("question 31696: preserves source contract",()=>has(1,"return freeze({mode:relative?\"relative-polar\":\"absolute-polar\",point:relative?{x:Number(origin.x||0)+delta.x,y:Number(origin.y||0)+delta.y,z:Number(origin.z||0)+delta.z}:delta,delta});"));
test("question 31697: preserves source contract",()=>has(1,"const parts=splitCoordinates(text,{decimal_separator});if(parts.length<2||parts.length>3)throw new Error(\"Coordinate input requires X,Y or X,Y,Z\");"));
test("question 31698: preserves source contract",()=>has(1,"const values=parts.map((part)=>evaluateNumericInput(part,{kind:\"length\",variables}));"));
test("question 31699: preserves source contract",()=>has(1,"const raw={x:values[0],y:values[1],z:values[2]??0};"));
test("question 31700: preserves source contract",()=>has(1,"const point=relative?{x:Number(origin.x||0)+raw.x,y:Number(origin.y||0)+raw.y,z:Number(origin.z||0)+raw.z}:raw;"));
test("question 31701: preserves source contract",()=>has(1,"return freeze({mode:relative?\"relative\":\"absolute\",point,delta:relative?raw:null});"));
test("question 31702: preserves source contract",()=>has(1,"export function applyOrthoTracking(delta,{enabled=false,axis=null}={}){const d={x:Number(delta?.x)||0,y:Number(delta?.y)||0,z:Number(delta?.z)||0};if(!enabled)return freeze(d);const axes=[\"x\",\"y\",\"z\"];const chosen=axis&&axes.includes(String(axis).toLowerCase())?String(axis).toLowerCase():axes.sort((a,b)=>Math.abs(d[b])-Math.abs(d[a]))[0];return freeze({x:chosen===\"x\"?d.x:0,y:chosen===\"y\"?d.y:0,z:chosen===\"z\"?d.z:0});}"));
test("question 31703: preserves source contract",()=>has(1,"export function applyPolarTracking(delta,{enabled=false,increment_deg=15}={}){const d={x:Number(delta?.x)||0,y:Number(delta?.y)||0,z:Number(delta?.z)||0};if(!enabled)return freeze(d);const inc=Number(increment_deg);if(!(inc>0))throw new RangeError(\"Polar increment must be > 0\");const r=Math.hypot(d.x,d.y),angle=Math.atan2(d.y,d.x)*180/Math.PI;const snapped=Math.round(angle/inc)*inc*Math.PI/180;return freeze({x:r*Math.cos(snapped),y:r*Math.sin(snapped),z:d.z});}"));
test("question 31704: preserves source contract",()=>has(1,"export function dynamicInputPreview(input,options={}){try{return freeze({status:\"Valid\",...parseCoordinateInput(input,options)});}catch(error){return freeze({status:\"Invalid\",error:String(error?.message??error),point:null});}}"));
test("question 31705: preserves source contract",()=>has(2,"function freeze(value){"));
test("question 31706: preserves source contract",()=>has(2,"if(Array.isArray(value))return Object.freeze(value.map(freeze));"));
test("question 31707: preserves source contract",()=>has(2,"if(value&&typeof value===\"object\"&&!Object.isFrozen(value)){"));
test("question 31708: preserves source contract",()=>has(2,"for(const key of Object.keys(value))value[key]=freeze(value[key]);"));
test("question 31709: preserves source contract",()=>has(2,"return Object.freeze(value);"));
test("question 31710: preserves source contract",()=>has(2,"return value;"));
test("question 31711: preserves source contract",()=>has(2,"function finite(value,defaultValue=null){"));
test("question 31712: preserves source contract",()=>has(2,"if(value===null||value===undefined||value===\"\")return defaultValue;"));
test("question 31713: preserves source contract",()=>has(2,"const n=Number(value);return Number.isFinite(n)?n:defaultValue;"));
test("question 31714: preserves source contract",()=>has(2,"function bendKey(step,index){"));
test("question 31715: preserves source contract",()=>has(2,"return String(step?.elementId??step?.bend_id??step?.bend??index+1);"));
test("question 31716: preserves source contract",()=>has(2,"const STATUS_RANK=Object.freeze({"));
test("question 31717: preserves source contract",()=>has(2,"NotChecked:0,"));
test("question 31718: preserves source contract",()=>has(2,"Collision:3,"));
test("question 31719: preserves source contract",()=>has(2,"Impossible:4"));
test("question 31720: preserves source contract",()=>has(2,"export const SimulationCollisionStatus=Object.freeze({"));
test("question 31721: preserves source contract",()=>has(2,"NOT_CHECKED:\"NotChecked\","));
test("question 31722: preserves source contract",()=>has(2,"WARNING:\"Warning\","));
test("question 31723: preserves source contract",()=>has(2,"COLLISION:\"Collision\","));
test("question 31724: preserves source contract",()=>has(2,"IMPOSSIBLE:\"Impossible\""));
test("question 31725: preserves source contract",()=>has(2,"export const SimulationCollisionMode=Object.freeze({"));
test("question 31726: preserves source contract",()=>has(2,"MONITOR:\"Monitor\","));
test("question 31727: preserves source contract",()=>has(2,"STOP:\"Stop\","));
test("question 31728: preserves source contract",()=>has(2,"VALIDATION_LOCK:\"ValidationLock\""));
test("question 31729: preserves source contract",()=>has(2,"export function normalizeCollisionObservation(input={}){"));
test("question 31730: preserves source contract",()=>has(2,"const kind=String(input.kind??\"machine\");"));
test("question 31731: preserves source contract",()=>has(2,"if(![\"machine\",\"tooling\",\"self\",\"fixture\",\"other\"].includes(kind)){"));
test("question 31732: preserves source contract",()=>has(2,"throw new RangeError(`unsupported collision observation kind: ${kind}`);"));
test("question 31733: preserves source contract",()=>has(2,"const clearance=finite(input.clearance_mm,null);"));
test("question 31734: preserves source contract",()=>has(2,"return freeze({"));
test("question 31735: preserves source contract",()=>has(2,"bend_id:String(input.bend_id??input.element_id??input.bend??\"\"),"));
test("question 31736: preserves source contract",()=>has(2,"checked:input.checked!==false,"));
test("question 31737: preserves source contract",()=>has(2,"collision:input.collision===true,"));
test("question 31738: preserves source contract",()=>has(2,"impossible:input.impossible===true,"));
test("question 31739: preserves source contract",()=>has(2,"contact:input.contact===true,"));
test("question 31740: preserves source contract",()=>has(2,"clearance_mm:clearance,"));
test("question 31741: preserves source contract",()=>has(2,"message:input.message==null?null:String(input.message),"));
test("question 31742: preserves source contract",()=>has(2,"source:input.source==null?\"simulation\":String(input.source)"));
test("question 31743: preserves source contract",()=>has(2,"function worstStatus(statuses){"));
test("question 31744: preserves source contract",()=>has(2,"let best=SimulationCollisionStatus.NOT_CHECKED;"));
test("question 31745: preserves source contract",()=>has(2,"for(const status of statuses){"));
test("question 31746: preserves source contract",()=>has(2,"if((STATUS_RANK[status]??-1)>(STATUS_RANK[best]??-1))best=status;"));
test("question 31747: preserves source contract",()=>has(2,"return best;"));
test("question 31748: preserves source contract",()=>has(2,"export function classifyBendSimulationStep(step,observations=[],{"));
test("question 31749: preserves source contract",()=>has(2,"warning_clearance_mm=5,"));
test("question 31750: preserves source contract",()=>has(2,"contact_tolerance_mm=0.1,"));
test("question 31751: preserves source contract",()=>has(2,"contact_rule=\"warn\""));
test("question 31752: preserves source contract",()=>has(2,"if(![\"allow\",\"warn\",\"forbid\"].includes(contact_rule)){"));
test("question 31753: preserves source contract",()=>has(2,"throw new RangeError(\"contact_rule must be allow, warn or forbid\");"));
test("question 31754: preserves source contract",()=>has(2,"const obs=(observations??[]).map(normalizeCollisionObservation);"));
test("question 31755: preserves source contract",()=>has(2,"const checked=obs.filter((x)=>x.checked);"));
test("question 31756: preserves source contract",()=>has(2,"const errors=[],warnings=[];"));
test("question 31757: preserves source contract",()=>has(2,"let minClearance=null;"));
test("question 31758: preserves source contract",()=>has(2,"for(const item of checked){"));
test("question 31759: preserves source contract",()=>has(2,"if(Number.isFinite(item.clearance_mm)){"));
test("question 31760: preserves source contract",()=>has(2,"minClearance=minClearance===null?item.clearance_mm:Math.min(minClearance,item.clearance_mm);"));
test("question 31761: preserves source contract",()=>has(2,"if(item.impossible){"));
test("question 31762: preserves source contract",()=>has(2,"errors.push(item.message||`${item.kind}: operation is impossible`);"));
test("question 31763: preserves source contract",()=>has(2,"if(item.collision){"));
test("question 31764: preserves source contract",()=>has(2,"errors.push(item.message||`${item.kind}: collision`);"));
test("question 31765: preserves source contract",()=>has(2,"const contact=item.contact===true||"));
test("question 31766: preserves source contract",()=>has(2,"(Number.isFinite(item.clearance_mm)&&Math.abs(item.clearance_mm)<=contact_tolerance_mm);"));
test("question 31767: preserves source contract",()=>has(2,"if(contact){"));
test("question 31768: preserves source contract",()=>has(2,"if(contact_rule===\"forbid\"){"));
test("question 31769: preserves source contract",()=>has(2,"errors.push(item.message||`${item.kind}: contact is forbidden`);"));
test("question 31770: preserves source contract",()=>has(2,"}else if(contact_rule===\"warn\"){"));
test("question 31771: preserves source contract",()=>has(2,"warnings.push(item.message||`${item.kind}: contact`);"));
test("question 31772: preserves source contract",()=>has(2,"}else if(Number.isFinite(item.clearance_mm)&&item.clearance_mm<warning_clearance_mm){"));
test("question 31773: preserves source contract",()=>has(2,"warnings.push(item.message||`${item.kind}: clearance ${item.clearance_mm} mm below warning threshold ${warning_clearance_mm} mm`);"));
test("question 31774: preserves source contract",()=>has(2,"if(checked.some((x)=>x.impossible))status=SimulationCollisionStatus.IMPOSSIBLE;"));
test("question 31775: preserves source contract",()=>has(2,"else if(checked.some((x)=>x.collision)||errors.length)status=SimulationCollisionStatus.COLLISION;"));
test("question 31776: preserves source contract",()=>has(2,"else if(warnings.length)status=SimulationCollisionStatus.WARNING;"));
test("question 31777: preserves source contract",()=>has(2,"else if(checked.length)status=SimulationCollisionStatus.OK;"));
test("question 31778: preserves source contract",()=>has(2,"else status=SimulationCollisionStatus.NOT_CHECKED;"));
test("question 31779: preserves source contract",()=>has(2,"bend_id:String(step?.id??step?.elementId??step?.bend_id??step?.bend??\"\"),"));
test("question 31780: preserves source contract",()=>has(2,"bend:Number.isFinite(Number(step?.bend))?Number(step.bend):null,"));
test("question 31781: preserves source contract",()=>has(2,"checked:checked.length>0,"));
test("question 31782: preserves source contract",()=>has(2,"min_clearance_mm:minClearance,"));
test("question 31783: preserves source contract",()=>has(2,"observations:checked,"));
test("question 31784: preserves source contract",()=>has(2,"errors:[...new Set(errors)],"));
test("question 31785: preserves source contract",()=>has(2,"warnings:[...new Set(warnings)]"));
test("question 31786: preserves source contract",()=>has(2,"export function analyzeBendingSimulation(steps=[],observations=[],options={}){"));
test("question 31787: preserves source contract",()=>has(2,"if(!Array.isArray(steps))throw new TypeError(\"steps must be an array\");"));
test("question 31788: preserves source contract",()=>has(2,"if(!Array.isArray(observations))throw new TypeError(\"observations must be an array\");"));
test("question 31789: preserves source contract",()=>has(2,"const normalizedObs=observations.map(normalizeCollisionObservation);"));
test("question 31790: preserves source contract",()=>has(2,"const perBend=steps.map((step,index)=>{"));
test("question 31791: preserves source contract",()=>has(2,"const key=bendKey(step,index);"));
test("question 31792: preserves source contract",()=>has(2,"const related=normalizedObs.filter((item)=>item.bend_id===key||(!item.bend_id&&Number(item.bend)===Number(step?.bend)));"));
test("question 31793: preserves source contract",()=>has(2,"return classifyBendSimulationStep({...step,id:key},related,options);"));
test("question 31794: preserves source contract",()=>has(2,"const status=worstStatus(perBend.map((x)=>x.status));"));
test("question 31795: preserves source contract",()=>has(2,"const checkedCount=perBend.filter((x)=>x.checked).length;"));
test("question 31796: preserves source contract",()=>has(2,"const collisionCount=perBend.filter((x)=>x.status===SimulationCollisionStatus.COLLISION).length;"));
test("question 31797: preserves source contract",()=>has(2,"const impossibleCount=perBend.filter((x)=>x.status===SimulationCollisionStatus.IMPOSSIBLE).length;"));
test("question 31798: preserves source contract",()=>has(2,"const warningCount=perBend.filter((x)=>x.status===SimulationCollisionStatus.WARNING).length;"));
test("question 31799: preserves source contract",()=>has(2,"const minClearance=perBend.reduce((min,item)=>{"));
test("question 31800: preserves source contract",()=>has(2,"if(!Number.isFinite(item.min_clearance_mm))return min;"));
test("question 31801: preserves source contract",()=>has(2,"return min===null?item.min_clearance_mm:Math.min(min,item.min_clearance_mm);"));
test("question 31802: preserves source contract",()=>has(2,"fully_checked:steps.length>0&&checkedCount===steps.length,"));
test("question 31803: preserves source contract",()=>has(2,"bend_count:steps.length,"));
test("question 31804: preserves source contract",()=>has(2,"checked_bend_count:checkedCount,"));
test("question 31805: preserves source contract",()=>has(2,"warning_count:warningCount,"));
test("question 31806: preserves source contract",()=>has(2,"collision_count:collisionCount,"));
test("question 31807: preserves source contract",()=>has(2,"impossible_count:impossibleCount,"));
test("question 31808: preserves source contract",()=>has(2,"per_bend:perBend"));
test("question 31809: preserves source contract",()=>has(2,"export function simulationModeDecision(report,mode=SimulationCollisionMode.MONITOR){"));
test("question 31810: preserves source contract",()=>has(2,"if(!Object.values(SimulationCollisionMode).includes(mode)){"));
test("question 31811: preserves source contract",()=>has(2,"throw new RangeError(`unsupported simulation collision mode: ${mode}`);"));
test("question 31812: preserves source contract",()=>has(2,"const status=report?.status??SimulationCollisionStatus.NOT_CHECKED;"));
test("question 31813: preserves source contract",()=>has(2,"const hasHard=status===SimulationCollisionStatus.COLLISION||status===SimulationCollisionStatus.IMPOSSIBLE;"));
test("question 31814: preserves source contract",()=>has(2,"const unchecked=report?.fully_checked!==true;"));
test("question 31815: preserves source contract",()=>has(2,"if(mode===SimulationCollisionMode.MONITOR){"));
test("question 31816: preserves source contract",()=>has(2,"can_continue:true,"));
test("question 31817: preserves source contract",()=>has(2,"release_blocked:false,"));
test("question 31818: preserves source contract",()=>has(2,"reason:hasHard?\"Collision recorded; Monitor mode does not stop playback\":unchecked?\"Collision check incomplete\":null"));
test("question 31819: preserves source contract",()=>has(2,"if(mode===SimulationCollisionMode.STOP){"));
test("question 31820: preserves source contract",()=>has(2,"can_continue:!hasHard,"));
test("question 31821: preserves source contract",()=>has(2,"reason:hasHard?\"Playback stopped by collision mode\":null"));
test("question 31822: preserves source contract",()=>has(2,"release_blocked:hasHard||unchecked,"));
test("question 31823: preserves source contract",()=>has(2,"reason:hasHard?\"Validation Lock: collision/impossible bend\":unchecked?\"Validation Lock: collision check incomplete\":null"));
test("question 31824: preserves source contract",()=>has(2,"export function annotateSimulationSteps(steps=[],report){"));
test("question 31825: preserves source contract",()=>has(2,"const byId=new Map((report?.per_bend??[]).map((item)=>[String(item.bend_id),item]));"));
test("question 31826: preserves source contract",()=>has(2,"return freeze(steps.map((step,index)=>{"));
test("question 31827: preserves source contract",()=>has(2,"const id=bendKey(step,index),result=byId.get(id)??null;"));
test("question 31828: preserves source contract",()=>has(2,"simulation_collision_status:result?.status??SimulationCollisionStatus.NOT_CHECKED,"));
test("question 31829: preserves source contract",()=>has(2,"simulation_clearance_mm:result?.min_clearance_mm??null,"));
test("question 31830: preserves source contract",()=>has(2,"simulation_collision_checked:result?.checked===true"));
test("question 31831: preserves source contract",()=>has(3,"function currentImportButton(){"));
test("question 31832: preserves source contract",()=>has(3,"return document.getElementById(\"poImportCurrentBtn\");"));
test("question 31833: preserves source contract",()=>has(3,"function ensureCurrentImportButton(){"));
test("question 31834: preserves source contract",()=>has(3,"let button=currentImportButton();"));
test("question 31835: preserves source contract",()=>has(3,"if(button)return button;"));
test("question 31836: preserves source contract",()=>has(3,"const open=document.getElementById(\"poOpenBtn\");"));
test("question 31837: preserves source contract",()=>has(3,"const host=open?.parentElement;"));
test("question 31838: preserves source contract",()=>has(3,"if(!open||!host)return null;"));
test("question 31839: preserves source contract",()=>has(3,"button=document.createElement(\"button\");"));
test("question 31840: preserves source contract",()=>has(3,"button.className=\"po-secondary\";"));
test("question 31841: preserves source contract",()=>has(3,"button.id=\"poImportCurrentBtn\";"));
test("question 31842: preserves source contract",()=>has(3,"button.type=\"button\";"));
test("question 31843: preserves source contract",()=>has(3,"button.hidden=true;"));
test("question 31844: preserves source contract",()=>has(3,"button.disabled=true;"));
test("question 31845: preserves source contract",()=>has(3,"button.textContent=\"Импортировать геометрию в текущий проект\";"));
test("question 31846: preserves source contract",()=>has(3,"button.title=\"Добавить выбранные распознанные DWFx-трубы в активный текущий проект\";"));
test("question 31847: preserves source contract",()=>has(3,"button.addEventListener(\"click\",importSelectedDwfxTubesIntoCurrentProject);"));
test("question 31848: preserves source contract",()=>has(3,"host.insertBefore(button,open);"));
test("question 31849: preserves source contract",()=>has(3,"return button;"));
test("question 31850: preserves source contract",()=>has(3,"function selectedTubeCount(){"));
test("question 31851: preserves source contract",()=>has(3,"return Number(poSelectionCount()?.tubes)||0;"));
test("question 31852: preserves source contract",()=>has(3,"function updateCurrentImportButton(){"));
test("question 31853: preserves source contract",()=>has(3,"const button=ensureCurrentImportButton();"));
test("question 31854: preserves source contract",()=>has(3,"if(!button)return;"));
test("question 31855: preserves source contract",()=>has(3,"let pkg=null;"));
test("question 31856: preserves source contract",()=>has(3,"let readOnly=false;"));
test("question 31857: preserves source contract",()=>has(3,"try{pkg=PO.current;}catch{}"));
test("question 31858: preserves source contract",()=>has(3,"try{readOnly=poReadOnly();}catch{}"));
test("question 31859: preserves source contract",()=>has(3,"const count=selectedTubeCount();"));
test("question 31860: preserves source contract",()=>has(3,"const ready="));
test("question 31861: preserves source contract",()=>has(3,"pkg?.rawDwfxImport?.status===\"dwfx_project_candidate\" &&"));
test("question 31862: preserves source contract",()=>has(3,"Array.isArray(pkg?.projects) &&"));
test("question 31863: preserves source contract",()=>has(3,"pkg.projects.length>0;"));
test("question 31864: preserves source contract",()=>has(3,"const nextHidden=!ready;"));
test("question 31865: preserves source contract",()=>has(3,"const nextDisabled=!ready||count<1||readOnly;"));
test("question 31866: preserves source contract",()=>has(3,"const nextText=ready"));
test("question 31867: preserves source contract",()=>has(3,"? \"Импортировать в текущий проект (\"+count+\")\""));
test("question 31868: preserves source contract",()=>has(3,": \"Импортировать геометрию в текущий проект\";"));
test("question 31869: preserves source contract",()=>has(3,"if(button.hidden!==nextHidden)button.hidden=nextHidden;"));
test("question 31870: preserves source contract",()=>has(3,"if(button.disabled!==nextDisabled)button.disabled=nextDisabled;"));
test("question 31871: preserves source contract",()=>has(3,"if(button.textContent!==nextText)button.textContent=nextText;"));
test("question 31872: preserves source contract",()=>has(3,"async function importSelectedDwfxTubesIntoCurrentProject(){"));
test("question 31873: preserves source contract",()=>has(3,"if(!pkg?.rawDwfxImport||pkg.rawDwfxImport.status!==\"dwfx_project_candidate\"){"));
test("question 31874: preserves source contract",()=>has(3,"ptToast(\"Сначала распознайте DWFx-файл\");"));
test("question 31875: preserves source contract",()=>has(3,"return false;"));
test("question 31876: preserves source contract",()=>has(3,"if(poReadOnly()){"));
test("question 31877: preserves source contract",()=>has(3,"ptToast(\"Текущий проект открыт только для просмотра\");"));
test("question 31878: preserves source contract",()=>has(3,"const chosen=poSelectedMaterialized();"));
test("question 31879: preserves source contract",()=>has(3,"if(!chosen.length){"));
test("question 31880: preserves source contract",()=>has(3,"ptToast(\"Не выбраны распознанные трубы\");"));
test("question 31881: preserves source contract",()=>has(3,"const bridge=window.TubeBenderDwfxImport;"));
test("question 31882: preserves source contract",()=>has(3,"if(!bridge||typeof bridge.mergeDwfxTubesIntoCurrentProject!==\"function\"){"));
test("question 31883: preserves source contract",()=>has(3,"ptToast(\"Модуль импорта в текущий проект недоступен\");"));
test("question 31884: preserves source contract",()=>has(3,"poSetBusy(true,\"Создание резервной копии перед импортом DWFx…\");"));
test("question 31885: preserves source contract",()=>has(3,"await poStoreRecovery(\"backup\",\"Перед импортом распознанной DWFx-геометрии\");"));
test("question 31886: preserves source contract",()=>has(3,"let historyToken=null;"));
test("question 31887: preserves source contract",()=>has(3,"PO.suppressDirty=true;"));
test("question 31888: preserves source contract",()=>has(3,"syncActiveTubeFromState();"));
test("question 31889: preserves source contract",()=>has(3,"const current=activeProject();"));
test("question 31890: preserves source contract",()=>has(3,"if(!current)throw new Error(\"Активный проект не найден\");"));
test("question 31891: preserves source contract",()=>has(3,"const merged=await bridge.mergeDwfxTubesIntoCurrentProject({"));
test("question 31892: preserves source contract",()=>has(3,"project:current,"));
test("question 31893: preserves source contract",()=>has(3,"imported_projects:chosen,"));
test("question 31894: preserves source contract",()=>has(3,"conflict:document.getElementById(\"poConflict\")?.value||\"copy\","));
test("question 31895: preserves source contract",()=>has(3,"make_id:uid,"));
test("question 31896: preserves source contract",()=>has(3,"source_file:pkg.rawDwfxImport.source_file||pkg.meta?.name||\"\","));
test("question 31897: preserves source contract",()=>has(3,"diameter_catalog:"));
test("question 31898: preserves source contract",()=>has(3,"typeof pipeDb!==\"undefined\"&&Array.isArray(pipeDb)"));
test("question 31899: preserves source contract",()=>has(3,"diameter_rounding_tolerance_mm:0.35,"));
test("question 31900: preserves source contract",()=>has(3,"linear_rounding_increment_mm:1"));
test("question 31901: preserves source contract",()=>has(3,"if(merged.status!==\"merged\"||merged.imported_count<1){"));
test("question 31902: preserves source contract",()=>has(3,"ptToast(\"Новые трубы не добавлены\");"));
test("question 31903: preserves source contract",()=>has(3,"historyToken=tbHistoryBegin(\"Импортировать DWFx геометрию\");"));
test("question 31904: preserves source contract",()=>has(3,"if(!historyToken){"));
test("question 31905: preserves source contract",()=>has(3,"throw new Error(\"Завершите текущее редактирование перед импортом\");"));
test("question 31906: preserves source contract",()=>has(3,"const projectIndex=(state.projects||[]).findIndex("));
test("question 31907: preserves source contract",()=>has(3,"(project)=>String(project?.id)===String(current.id)"));
test("question 31908: preserves source contract",()=>has(3,"if(projectIndex<0){"));
test("question 31909: preserves source contract",()=>has(3,"throw new Error(\"Активный проект исчез во время импорта\");"));
test("question 31910: preserves source contract",()=>has(3,"state.projects[projectIndex]=merged.project;"));
test("question 31911: preserves source contract",()=>has(3,"state.activeProjectId=merged.project.id;"));
test("question 31912: preserves source contract",()=>has(3,"state.activeTubeId="));
test("question 31913: preserves source contract",()=>has(3,"merged.imported_tube_ids.at(-1)||"));
test("question 31914: preserves source contract",()=>has(3,"merged.project.tubes.at(-1)?.id||"));
test("question 31915: preserves source contract",()=>has(3,"state.activeTubeId;"));
test("question 31916: preserves source contract",()=>has(3,"state.workspaceDirty=true;"));
test("question 31917: preserves source contract",()=>has(3,"syncProjectToLegacy();"));
test("question 31918: preserves source contract",()=>has(3,"loadActiveTubeToState();"));
test("question 31919: preserves source contract",()=>has(3,"projectCollisionCache.clear();"));
test("question 31920: preserves source contract",()=>has(3,"tbHistoryCommit(historyToken);"));
test("question 31921: preserves source contract",()=>has(3,"historyToken=null;"));
test("question 31922: preserves source contract",()=>has(3,"renderPipeSelect();"));
test("question 31923: preserves source contract",()=>has(3,"renderPipeTable();"));
test("question 31924: preserves source contract",()=>has(3,"renderAll();"));
test("question 31925: preserves source contract",()=>has(3,"poApplyReadOnlyUi();"));
test("question 31926: preserves source contract",()=>has(3,"await poRememberOpened(pkg,pkg.rawText||JSON.stringify(pkg.rawData));"));
test("question 31927: preserves source contract",()=>has(3,"const dialog=document.getElementById(\"projectOpenDialog\");"));
test("question 31928: preserves source contract",()=>has(3,"if(dialog?.open)dialog.close();"));
test("question 31929: preserves source contract",()=>has(3,"const skipped=merged.skipped_count"));
test("question 31930: preserves source contract",()=>has(3,"?\" · пропущено \"+merged.skipped_count"));
test("question 31931: preserves source contract",()=>has(3,"const reference=merged.imported_reference_scene_count"));
test("question 31932: preserves source contract",()=>has(3,"?\" · reference-сцен: \"+merged.imported_reference_scene_count"));
test("question 31933: preserves source contract",()=>has(3,"ptToast(\"Импортировано труб: \"+merged.imported_count+reference+skipped);"));
test("question 31934: preserves source contract",()=>has(3,"return true;"));
test("question 31935: preserves source contract",()=>has(3,"}catch(error){"));
test("question 31936: preserves source contract",()=>has(3,"if(historyToken){"));
test("question 31937: preserves source contract",()=>has(3,"const before=historyToken.before;"));
test("question 31938: preserves source contract",()=>has(3,"tbHistoryCancel(historyToken);"));
test("question 31939: preserves source contract",()=>has(3,"tbHistoryRestore(before);"));
test("question 31940: preserves source contract",()=>has(3,"console.error(error);"));
test("question 31941: preserves source contract",()=>has(3,"ptToast(\"Не удалось импортировать DWFx-геометрию: \"+error.message);"));
test("question 31942: preserves source contract",()=>has(3,"PO.suppressDirty=false;"));
test("question 31943: preserves source contract",()=>has(3,"poSetBusy(false,\"Готово\");"));
test("question 31944: preserves source contract",()=>has(3,"updateCurrentImportButton();"));
test("question 31945: preserves source contract",()=>has(3,"function install(){"));
test("question 31946: preserves source contract",()=>has(3,"if(!button||!dialog)return;"));
test("question 31947: preserves source contract",()=>has(3,"dialog.addEventListener(\"change\",()=>queueMicrotask(updateCurrentImportButton),true);"));
test("question 31948: preserves source contract",()=>has(3,"dialog.addEventListener(\"click\",()=>queueMicrotask(updateCurrentImportButton),true);"));
test("question 31949: preserves source contract",()=>has(3,"let updateQueued=false;"));
test("question 31950: preserves source contract",()=>has(3,"const scheduleUpdate=()=>{"));
test("question 31951: preserves source contract",()=>has(3,"if(updateQueued)return;"));
test("question 31952: preserves source contract",()=>has(3,"updateQueued=true;"));
test("question 31953: preserves source contract",()=>has(3,"queueMicrotask(()=>{"));
test("question 31954: preserves source contract",()=>has(3,"updateQueued=false;"));
test("question 31955: preserves source contract",()=>has(3,"const observer=new MutationObserver((records)=>{"));
test("question 31956: preserves source contract",()=>has(3,"if(records.every((record)=>record.target===button||button.contains(record.target)))return;"));
test("question 31957: preserves source contract",()=>has(3,"scheduleUpdate();"));
test("question 31958: preserves source contract",()=>has(3,"observer.observe(dialog,{subtree:true,childList:true});"));
test("question 31959: preserves source contract",()=>has(3,"if(document.readyState===\"loading\"){"));
test("question 31960: preserves source contract",()=>has(3,"window.addEventListener(\"DOMContentLoaded\",install,{once:true});"));
test("question 31961: preserves source contract",()=>has(3,"window.TubeBenderDwfxCurrentProjectUi=Object.freeze({"));
test("question 31962: preserves source contract",()=>has(3,"update:updateCurrentImportButton,"));
test("question 31963: preserves source contract",()=>has(3,"importSelected:importSelectedDwfxTubesIntoCurrentProject"));
test("question 31964: preserves source contract",()=>has(4,"const STACK_URL=\"__TB_TRANSFORM_STACK_MODULE_URL__\";"));
test("question 31965: preserves source contract",()=>has(4,"let stackDomain=null,installed=false,syncing=false;"));
test("question 31966: preserves source contract",()=>has(4,"const api=()=>window.TubeBenderEngineering??null;"));
test("question 31967: preserves source contract",()=>has(4,"const project=()=>{try{return api()?.activeProject?.()??null;}catch{return null;}};"));
test("question 31968: preserves source contract",()=>has(4,"const clone=(v)=>v==null?v:structuredClone(v);"));
test("question 31969: preserves source contract",()=>has(4,"const byId=(p,id)=>(p?.tubes??[]).find((t)=>String(t?.id)===String(id))??null;"));
test("question 31970: preserves source contract",()=>has(4,"function definitions(p=project()){"));
test("question 31971: preserves source contract",()=>has(4,"if(!p)return [];"));
test("question 31972: preserves source contract",()=>has(4,"if(!Array.isArray(p.associative_transform_stacks))p.associative_transform_stacks=[];"));
test("question 31973: preserves source contract",()=>has(4,"return p.associative_transform_stacks;"));
test("question 31974: preserves source contract",()=>has(4,"function definitionById(id,p=project()){"));
test("question 31975: preserves source contract",()=>has(4,"return definitions(p).find((d)=>String(d?.id)===String(id))??null;"));
test("question 31976: preserves source contract",()=>has(4,"function definitionForTube(tubeId,p=project()){"));
test("question 31977: preserves source contract",()=>has(4,"return definitions(p).find((d)=>String(d?.object_id)===String(tubeId))??null;"));
test("question 31978: preserves source contract",()=>has(4,"function replaceTube(target,next){"));
test("question 31979: preserves source contract",()=>has(4,"const visibility={"));
test("question 31980: preserves source contract",()=>has(4,"uiHiddenIn3D:target?.uiHiddenIn3D===true,"));
test("question 31981: preserves source contract",()=>has(4,"uiTransparentIn3D:target?.uiTransparentIn3D===true"));
test("question 31982: preserves source contract",()=>has(4,"const id=target?.id,name=target?.name;"));
test("question 31983: preserves source contract",()=>has(4,"for(const key of Object.keys(target))delete target[key];"));
test("question 31984: preserves source contract",()=>has(4,"Object.assign(target,clone(next));"));
test("question 31985: preserves source contract",()=>has(4,"if(id!=null)target.id=id;"));
test("question 31986: preserves source contract",()=>has(4,"if(name!=null)target.name=name;"));
test("question 31987: preserves source contract",()=>has(4,"target.uiHiddenIn3D=visibility.uiHiddenIn3D;"));
test("question 31988: preserves source contract",()=>has(4,"target.uiTransparentIn3D=visibility.uiTransparentIn3D;"));
test("question 31989: preserves source contract",()=>has(4,"target.transform_stack_member={stack_id:String(target.transform_stack?.id??\"\"),derived_readonly:true,status:\"Valid\"};"));
test("question 31990: preserves source contract",()=>has(4,"function createForTube(tubeId,p=project()){"));
test("question 31991: preserves source contract",()=>has(4,"if(!p)throw new Error(\"No active project\");"));
test("question 31992: preserves source contract",()=>has(4,"const tube=byId(p,tubeId);"));
test("question 31993: preserves source contract",()=>has(4,"if(!tube)throw new Error(\"Tube not found\");"));
test("question 31994: preserves source contract",()=>has(4,"if(definitionForTube(tubeId,p))throw new Error(\"Tube already has an associative transform stack\");"));
test("question 31995: preserves source contract",()=>has(4,"const stack=stackDomain.createTubeTransformStack(tube);"));
test("question 31996: preserves source contract",()=>has(4,"const def=clone(stack);"));
test("question 31997: preserves source contract",()=>has(4,"definitions(p).push(def);"));
test("question 31998: preserves source contract",()=>has(4,"synchronize(p);"));
test("question 31999: preserves source contract",()=>has(4,"return clone(def);"));
test("question 32000: preserves source contract",()=>has(4,"function mutateStack(stackId,mutator,p=project()){"));
test("question 32001: preserves source contract",()=>has(4,"const defs=definitions(p);"));
test("question 32002: preserves source contract",()=>has(4,"const index=defs.findIndex((d)=>String(d?.id)===String(stackId));"));
test("question 32003: preserves source contract",()=>has(4,"if(index<0)throw new Error(\"Transform stack not found\");"));
test("question 32004: preserves source contract",()=>has(4,"const next=mutator(clone(defs[index]));"));
test("question 32005: preserves source contract",()=>has(4,"defs[index]=clone(next);"));
test("question 32006: preserves source contract",()=>has(4,"return clone(defs[index]);"));
test("question 32007: preserves source contract",()=>has(4,"function appendMove(stackId,delta,p=project()){"));
test("question 32008: preserves source contract",()=>has(4,"return mutateStack(stackId,(stack)=>stackDomain.appendTransformOperation(stack,stackDomain.createMoveOperation(delta)),p);"));
test("question 32009: preserves source contract",()=>has(4,"function appendRotate(stackId,input,p=project()){"));
test("question 32010: preserves source contract",()=>has(4,"return mutateStack(stackId,(stack)=>stackDomain.appendTransformOperation(stack,stackDomain.createRotateOperation(input)),p);"));
test("question 32011: preserves source contract",()=>has(4,"function appendMirror(stackId,input,p=project()){"));
test("question 32012: preserves source contract",()=>has(4,"return mutateStack(stackId,(stack)=>stackDomain.appendTransformOperation(stack,stackDomain.createMirrorOperation(input)),p);"));
test("question 32013: preserves source contract",()=>has(4,"function removeOperation(stackId,operationId,p=project()){"));
test("question 32014: preserves source contract",()=>has(4,"return mutateStack(stackId,(stack)=>stackDomain.removeTransformOperation(stack,operationId),p);"));
test("question 32015: preserves source contract",()=>has(4,"function reorderOperation(stackId,fromIndex,toIndex,p=project()){"));
test("question 32016: preserves source contract",()=>has(4,"return mutateStack(stackId,(stack)=>stackDomain.reorderTubeTransformOperation(stack,fromIndex,toIndex),p);"));
test("question 32017: preserves source contract",()=>has(4,"function setOperationEnabled(stackId,operationId,enabled,p=project()){"));
test("question 32018: preserves source contract",()=>has(4,"return mutateStack(stackId,(stack)=>stackDomain.setTransformOperationEnabled(stack,operationId,enabled),p);"));
test("question 32019: preserves source contract",()=>has(4,"function bake(stackId,p=project()){"));
test("question 32020: preserves source contract",()=>has(4,"const def=defs[index];"));
test("question 32021: preserves source contract",()=>has(4,"const tube=byId(p,def.object_id);"));
test("question 32022: preserves source contract",()=>has(4,"if(!tube)throw new Error(\"Transform stack source tube not found\");"));
test("question 32023: preserves source contract",()=>has(4,"const result=stackDomain.bakeTubeTransformStack(def);"));
test("question 32024: preserves source contract",()=>has(4,"if(result.status!==\"exact\"||!result.tube)throw new Error(result.reason||\"Transform stack bake failed\");"));
test("question 32025: preserves source contract",()=>has(4,"const baked=clone(result.tube);"));
test("question 32026: preserves source contract",()=>has(4,"baked.id=tube.id;"));
test("question 32027: preserves source contract",()=>has(4,"baked.name=tube.name;"));
test("question 32028: preserves source contract",()=>has(4,"delete baked.transform_stack_member;"));
test("question 32029: preserves source contract",()=>has(4,"replaceTube(tube,baked);"));
test("question 32030: preserves source contract",()=>has(4,"delete tube.transform_stack_member;"));
test("question 32031: preserves source contract",()=>has(4,"defs.splice(index,1);"));
test("question 32032: preserves source contract",()=>has(4,"return clone(result);"));
test("question 32033: preserves source contract",()=>has(4,"function deleteStack(stackId,{restoreBase=true}={},p=project()){"));
test("question 32034: preserves source contract",()=>has(4,"if(index<0)return false;"));
test("question 32035: preserves source contract",()=>has(4,"const def=defs[index],tube=byId(p,def.object_id);"));
test("question 32036: preserves source contract",()=>has(4,"if(tube&&restoreBase!==false){"));
test("question 32037: preserves source contract",()=>has(4,"const base=clone(def.base_tube);"));
test("question 32038: preserves source contract",()=>has(4,"base.id=tube.id;base.name=tube.name;"));
test("question 32039: preserves source contract",()=>has(4,"replaceTube(tube,base);"));
test("question 32040: preserves source contract",()=>has(4,"delete tube.transform_stack;"));
test("question 32041: preserves source contract",()=>has(4,"delete tube.transform_stack_state;"));
test("question 32042: preserves source contract",()=>has(4,"delete tube.transform_stack_fingerprint;"));
test("question 32043: preserves source contract",()=>has(4,"return true;"));
test("question 32044: preserves source contract",()=>has(4,"function synchronize(p=project()){"));
test("question 32045: preserves source contract",()=>has(4,"if(!p||!stackDomain||syncing)return {ok:true,changed:false};"));
test("question 32046: preserves source contract",()=>has(4,"syncing=true;"));
test("question 32047: preserves source contract",()=>has(4,"let changed=false;"));
test("question 32048: preserves source contract",()=>has(4,"for(const def of definitions(p)){"));
test("question 32049: preserves source contract",()=>has(4,"if(!tube){def.state=\"LostSource\";continue;}"));
test("question 32050: preserves source contract",()=>has(4,"const result=stackDomain.applyTubeTransformStack(def);"));
test("question 32051: preserves source contract",()=>has(4,"if(result.status!==\"exact\"||!result.tube){"));
test("question 32052: preserves source contract",()=>has(4,"def.state=\"Error\";"));
test("question 32053: preserves source contract",()=>has(4,"def.error=String(result.reason??\"Transform stack evaluation failed\");"));
test("question 32054: preserves source contract",()=>has(4,"const next=clone(result.tube);"));
test("question 32055: preserves source contract",()=>has(4,"next.id=tube.id;next.name=tube.name;"));
test("question 32056: preserves source contract",()=>has(4,"const before=JSON.stringify(tube);"));
test("question 32057: preserves source contract",()=>has(4,"replaceTube(tube,next);"));
test("question 32058: preserves source contract",()=>has(4,"if(JSON.stringify(tube)!==before)changed=true;"));
test("question 32059: preserves source contract",()=>has(4,"def.state=\"Valid\";"));
test("question 32060: preserves source contract",()=>has(4,"delete def.error;"));
test("question 32061: preserves source contract",()=>has(4,"return {ok:true,changed};"));
test("question 32062: preserves source contract",()=>has(4,"}finally{syncing=false;}"));
test("question 32063: preserves source contract",()=>has(4,"function summary(stackId,p=project()){"));
test("question 32064: preserves source contract",()=>has(4,"const def=definitionById(stackId,p);"));
test("question 32065: preserves source contract",()=>has(4,"return def?stackDomain.summarizeTransformStack(def):null;"));
test("question 32066: preserves source contract",()=>has(4,"function isStackTube(tube){return tube?.transform_stack_member?.derived_readonly===true;}"));
test("question 32067: preserves source contract",()=>has(4,"async function install(){"));
test("question 32068: preserves source contract",()=>has(4,"if(installed)return;installed=true;"));
test("question 32069: preserves source contract",()=>has(4,"stackDomain=await import(STACK_URL);"));
test("question 32070: preserves source contract",()=>has(4,"try{synchronize();}catch(error){console.warn(\"Associative Transform Stack sync:\",error);}"));
test("question 32071: preserves source contract",()=>has(4,"if(typeof renderAll===\"function\"&&!renderAll._tbTransformStacks){"));
test("question 32072: preserves source contract",()=>has(4,"const original=renderAll;"));
test("question 32073: preserves source contract",()=>has(4,"renderAll=function(...args){"));
test("question 32074: preserves source contract",()=>has(4,"return original.apply(this,args);"));
test("question 32075: preserves source contract",()=>has(4,"renderAll._tbTransformStacks=true;"));
test("question 32076: preserves source contract",()=>has(4,"window.TubeBenderTransformStacks=Object.freeze({"));
test("question 32077: preserves source contract",()=>has(4,"definitions:()=>definitions(),"));
test("question 32078: preserves source contract",()=>has(4,"definitionById:(id)=>definitionById(id),"));
test("question 32079: preserves source contract",()=>has(4,"definitionForTube:(id)=>definitionForTube(id),"));
test("question 32080: preserves source contract",()=>has(4,"createForTube,appendMove,appendRotate,appendMirror,removeOperation,reorderOperation,"));
test("question 32081: preserves source contract",()=>has(4,"setOperationEnabled,bake,deleteStack,synchronize,summary,isStackTube"));
test("question 32082: preserves source contract",()=>has(4,"if(document.readyState===\"loading\")document.addEventListener(\"DOMContentLoaded\",()=>install().catch(console.error),{once:true});"));
test("question 32083: preserves source contract",()=>has(4,"else install().catch(console.error);"));
test("question 32084: preserves source contract",()=>has(5,"function point3(value,label=\"vector\"){"));
test("question 32085: preserves source contract",()=>has(5,"if(!Array.isArray(value)||value.length!==3){"));
test("question 32086: preserves source contract",()=>has(5,"throw new TypeError(label+\" must be a 3D vector\");"));
test("question 32087: preserves source contract",()=>has(5,"const out=value.map(Number);"));
test("question 32088: preserves source contract",()=>has(5,"if(!out.every(Number.isFinite)){"));
test("question 32089: preserves source contract",()=>has(5,"throw new RangeError(label+\" contains non-finite values\");"));
test("question 32090: preserves source contract",()=>has(5,"const add=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];"));
test("question 32091: preserves source contract",()=>has(5,"const sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];"));
test("question 32092: preserves source contract",()=>has(5,"const mul=(a,s)=>[a[0]*s,a[1]*s,a[2]*s];"));
test("question 32093: preserves source contract",()=>has(5,"const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];"));
test("question 32094: preserves source contract",()=>has(5,"const cross=(a,b)=>["));
test("question 32095: preserves source contract",()=>has(5,"a[1]*b[2]-a[2]*b[1],"));
test("question 32096: preserves source contract",()=>has(5,"a[2]*b[0]-a[0]*b[2],"));
test("question 32097: preserves source contract",()=>has(5,"a[0]*b[1]-a[1]*b[0]"));
test("question 32098: preserves source contract",()=>has(5,"const len=(a)=>Math.hypot(a[0],a[1],a[2]);"));
test("question 32099: preserves source contract",()=>has(5,"const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));"));
test("question 32100: preserves source contract",()=>has(5,"function unit(value,label=\"vector\"){"));
test("question 32101: preserves source contract",()=>has(5,"const v=point3(value,label);"));
test("question 32102: preserves source contract",()=>has(5,"const l=len(v);"));
test("question 32103: preserves source contract",()=>has(5,"if(!(l>1e-15)) throw new RangeError(label+\" is degenerate\");"));
test("question 32104: preserves source contract",()=>has(5,"return mul(v,1/l);"));
test("question 32105: preserves source contract",()=>has(5,"function rotateAround(vector,axis,angleRad){"));
test("question 32106: preserves source contract",()=>has(5,"const v=point3(vector,\"rotation vector\");"));
test("question 32107: preserves source contract",()=>has(5,"const n=unit(axis,\"rotation axis\");"));
test("question 32108: preserves source contract",()=>has(5,"const c=Math.cos(angleRad),s=Math.sin(angleRad);"));
test("question 32109: preserves source contract",()=>has(5,"add(mul(v,c),mul(cross(n,v),s)),"));
test("question 32110: preserves source contract",()=>has(5,"mul(n,dot(n,v)*(1-c))"));
test("question 32111: preserves source contract",()=>has(5,"export const LEGACY_PLANE_NORMALS=Object.freeze({"));
test("question 32112: preserves source contract",()=>has(5,"XY:Object.freeze([0,0,1]),"));
test("question 32113: preserves source contract",()=>has(5,"YZ:Object.freeze([1,0,0]),"));
test("question 32114: preserves source contract",()=>has(5,"XZ:Object.freeze([0,-1,0])"));
test("question 32115: preserves source contract",()=>has(5,"export function legacyPlaneNormal(plane){"));
test("question 32116: preserves source contract",()=>has(5,"const value=LEGACY_PLANE_NORMALS[String(plane??\"\").toUpperCase()];"));
test("question 32117: preserves source contract",()=>has(5,"return value?Object.freeze([...value]):null;"));
test("question 32118: preserves source contract",()=>has(5,"export function effectiveLegacyBendAxis(tangent,plane=\"XY\",rotationDeg=0){"));
test("question 32119: preserves source contract",()=>has(5,"const t=unit(tangent,\"incoming tangent\");"));
test("question 32120: preserves source contract",()=>has(5,"const raw=legacyPlaneNormal(plane);"));
test("question 32121: preserves source contract",()=>has(5,"if(!raw) throw new RangeError(\"unsupported legacy bend plane \"+String(plane));"));
test("question 32122: preserves source contract",()=>has(5,"let base=sub(raw,mul(t,dot(raw,t)));"));
test("question 32123: preserves source contract",()=>has(5,"if(len(base)<1e-8){"));
test("question 32124: preserves source contract",()=>has(5,"const helper=Math.abs(t[2])<0.88?[0,0,1]:[0,1,0];"));
test("question 32125: preserves source contract",()=>has(5,"base=cross(helper,t);"));
test("question 32126: preserves source contract",()=>has(5,"base=unit(base,\"projected legacy bend axis\");"));
test("question 32127: preserves source contract",()=>has(5,"const angle=Number(rotationDeg)*Math.PI/180;"));
test("question 32128: preserves source contract",()=>has(5,"if(!Number.isFinite(angle)) throw new RangeError(\"rotationDeg must be finite\");"));
test("question 32129: preserves source contract",()=>has(5,"return Object.freeze(unit(rotateAround(base,t,angle),\"rotated legacy bend axis\"));"));
test("question 32130: preserves source contract",()=>has(5,"export function signedAngleAroundAxisDeg(from,to,axis){"));
test("question 32131: preserves source contract",()=>has(5,"const a=unit(from,\"from axis\");"));
test("question 32132: preserves source contract",()=>has(5,"const b=unit(to,\"to axis\");"));
test("question 32133: preserves source contract",()=>has(5,"const sine=dot(n,cross(a,b));"));
test("question 32134: preserves source contract",()=>has(5,"const cosine=clamp(dot(a,b),-1,1);"));
test("question 32135: preserves source contract",()=>has(5,"let angle=Math.atan2(sine,cosine)*180/Math.PI;"));
test("question 32136: preserves source contract",()=>has(5,"if(Math.abs(angle)<1e-12) angle=0;"));
test("question 32137: preserves source contract",()=>has(5,"return angle;"));
test("question 32138: preserves source contract",()=>has(5,"function angleBetweenDeg(a,b){"));
test("question 32139: preserves source contract",()=>has(5,"return Math.acos(clamp(dot(unit(a),unit(b)),-1,1))*180/Math.PI;"));
test("question 32140: preserves source contract",()=>has(5,"function normalizeSignedDeg(value){"));
test("question 32141: preserves source contract",()=>has(5,"let x=Number(value);"));
test("question 32142: preserves source contract",()=>has(5,"if(!Number.isFinite(x)) throw new RangeError(\"angle must be finite\");"));
test("question 32143: preserves source contract",()=>has(5,"x=((x+180)%360+360)%360-180;"));
test("question 32144: preserves source contract",()=>has(5,"if(x<=-180+1e-10) x=180;"));
test("question 32145: preserves source contract",()=>has(5,"if(Math.abs(x)<1e-12) x=0;"));
test("question 32146: preserves source contract",()=>has(5,"* Pure-JS equivalent of VC207R7 bendSettingsForTransition()."));
test("question 32147: preserves source contract",()=>has(5,"* The sign of signedAngleHintDeg is preserved; plane+rotation encode the"));
test("question 32148: preserves source contract",()=>has(5,"* effective bend axis. targetPlaneNormal is used to disambiguate 180-degree"));
test("question 32149: preserves source contract",()=>has(5,"* transitions and to cross-check canonical bend orientation."));
test("question 32150: preserves source contract",()=>has(5,"export function solveLegacyBendSettings({"));
test("question 32151: preserves source contract",()=>has(5,"signedAngleHintDeg,"));
test("question 32152: preserves source contract",()=>has(5,"targetPlaneNormal=null,"));
test("question 32153: preserves source contract",()=>has(5,"preferredPlane=null,"));
test("question 32154: preserves source contract",()=>has(5,"directionToleranceDeg=0.02,"));
test("question 32155: preserves source contract",()=>has(5,"planeNormalToleranceDeg=0.05"));
test("question 32156: preserves source contract",()=>has(5,"const inDir=unit(incoming,\"incoming\");"));
test("question 32157: preserves source contract",()=>has(5,"const outDir=unit(target,\"target\");"));
test("question 32158: preserves source contract",()=>has(5,"const dotDirections=clamp(dot(inDir,outDir),-1,1);"));
test("question 32159: preserves source contract",()=>has(5,"const magnitude=Math.acos(dotDirections)*180/Math.PI;"));
test("question 32160: preserves source contract",()=>has(5,"if(magnitude<0.05||magnitude>180.000001){"));
test("question 32161: preserves source contract",()=>has(5,"return Object.freeze({"));
test("question 32162: preserves source contract",()=>has(5,"status:\"unresolved\","));
test("question 32163: preserves source contract",()=>has(5,"reason:\"transition angle is outside the supported bend range\""));
test("question 32164: preserves source contract",()=>has(5,"const hint=Number(signedAngleHintDeg);"));
test("question 32165: preserves source contract",()=>has(5,"if(!Number.isFinite(hint)||Math.abs(hint)<0.05){"));
test("question 32166: preserves source contract",()=>has(5,"reason:\"signed canonical bend angle is missing\""));
test("question 32167: preserves source contract",()=>has(5,"const sign=Math.sign(hint)||1;"));
test("question 32168: preserves source contract",()=>has(5,"if(Math.abs(Math.abs(hint)-magnitude)>directionToleranceDeg){"));
test("question 32169: preserves source contract",()=>has(5,"status:\"blocked\","));
test("question 32170: preserves source contract",()=>has(5,"reason:\"canonical bend angle disagrees with adjacent straight directions\","));
test("question 32171: preserves source contract",()=>has(5,"transition_angle_deg:magnitude,"));
test("question 32172: preserves source contract",()=>has(5,"canonical_angle_deg:hint"));
test("question 32173: preserves source contract",()=>has(5,"let usedAxis=cross(inDir,outDir);"));
test("question 32174: preserves source contract",()=>has(5,"if(len(usedAxis)<1e-10){"));
test("question 32175: preserves source contract",()=>has(5,"if(dotDirections>0){"));
test("question 32176: preserves source contract",()=>has(5,"reason:\"parallel straight directions do not define a bend axis\""));
test("question 32177: preserves source contract",()=>has(5,"if(targetPlaneNormal==null){"));
test("question 32178: preserves source contract",()=>has(5,"reason:\"180-degree transition requires canonical bend-plane normal\""));
test("question 32179: preserves source contract",()=>has(5,"usedAxis=mul(unit(targetPlaneNormal,\"targetPlaneNormal\"),sign);"));
test("question 32180: preserves source contract",()=>has(5,"usedAxis=unit(usedAxis,\"transition bend axis\");"));
test("question 32181: preserves source contract",()=>has(5,"if(targetPlaneNormal!=null){"));
test("question 32182: preserves source contract",()=>has(5,"const canonicalActual=mul(unit(targetPlaneNormal,\"targetPlaneNormal\"),sign);"));
test("question 32183: preserves source contract",()=>has(5,"const normalError=angleBetweenDeg(usedAxis,canonicalActual);"));
test("question 32184: preserves source contract",()=>has(5,"if(normalError>planeNormalToleranceDeg){"));
test("question 32185: preserves source contract",()=>has(5,"reason:\"canonical bend-plane orientation disagrees with line transition\","));
test("question 32186: preserves source contract",()=>has(5,"plane_normal_error_deg:normalError"));
test("question 32187: preserves source contract",()=>has(5,"const desiredEffective=mul(usedAxis,sign);"));
test("question 32188: preserves source contract",()=>has(5,"const planes=[\"XY\",\"YZ\",\"XZ\"];"));
test("question 32189: preserves source contract",()=>has(5,"let best=null;"));
test("question 32190: preserves source contract",()=>has(5,"for(const plane of planes){"));
test("question 32191: preserves source contract",()=>has(5,"const base=effectiveLegacyBendAxis(inDir,plane,0);"));
test("question 32192: preserves source contract",()=>has(5,"const rotation=normalizeSignedDeg("));
test("question 32193: preserves source contract",()=>has(5,"signedAngleAroundAxisDeg(base,desiredEffective,inDir)"));
test("question 32194: preserves source contract",()=>has(5,"const rebuilt=effectiveLegacyBendAxis(inDir,plane,rotation);"));
test("question 32195: preserves source contract",()=>has(5,"const error=angleBetweenDeg(rebuilt,desiredEffective);"));
test("question 32196: preserves source contract",()=>has(5,"const score="));
test("question 32197: preserves source contract",()=>has(5,"Math.abs(rotation)*1e-5+"));
test("question 32198: preserves source contract",()=>has(5,"(plane===preferredPlane?-1e-6:0);"));
test("question 32199: preserves source contract",()=>has(5,"if(!best||score<best.score){"));
test("question 32200: preserves source contract",()=>has(5,"best={plane,rotation,error,score};"));
test("question 32201: preserves source contract",()=>has(5,"if(!best||best.error>0.01){"));
test("question 32202: preserves source contract",()=>has(5,"reason:\"legacy plane/rotation encoding could not reproduce bend axis\""));
test("question 32203: preserves source contract",()=>has(5,"status:\"exact\","));
test("question 32204: preserves source contract",()=>has(5,"angle:Number((magnitude*sign).toFixed(6)),"));
test("question 32205: preserves source contract",()=>has(5,"plane:best.plane,"));
test("question 32206: preserves source contract",()=>has(5,"rotation:Number(best.rotation.toFixed(6)),"));
test("question 32207: preserves source contract",()=>has(5,"axis_error_deg:best.error,"));
test("question 32208: preserves source contract",()=>has(5,"transition_angle_deg:magnitude"));
test("question 32209: preserves source contract",()=>has(5,"export function replayLegacyDirection(incoming,{angle,plane,rotation}){"));
test("question 32210: preserves source contract",()=>has(5,"const dir=unit(incoming,\"incoming\");"));
test("question 32211: preserves source contract",()=>has(5,"const signed=Number(angle);"));
test("question 32212: preserves source contract",()=>has(5,"if(!Number.isFinite(signed)||Math.abs(signed)<1e-12){"));
test("question 32213: preserves source contract",()=>has(5,"throw new RangeError(\"legacy bend angle must be finite and non-zero\");"));
test("question 32214: preserves source contract",()=>has(5,"const effective=effectiveLegacyBendAxis(dir,plane,rotation);"));
test("question 32215: preserves source contract",()=>has(5,"const actualAxis=mul(effective,Math.sign(signed)||1);"));
test("question 32216: preserves source contract",()=>has(5,"return Object.freeze(unit("));
test("question 32217: preserves source contract",()=>has(5,"rotateAround(dir,actualAxis,Math.abs(signed)*Math.PI/180),"));
test("question 32218: preserves source contract",()=>has(5,"\"legacy outgoing direction\""));
test("question 32219: preserves source contract",()=>has(5,"export function angleBetweenVectorsDeg(a,b){"));
test("question 32220: preserves source contract",()=>has(5,"return angleBetweenDeg(a,b);"));
test("question 32221: preserves source contract",()=>has(6,"function point3(value,label){"));
test("question 32222: preserves source contract",()=>has(6,"if(!Array.isArray(value)||value.length!==3){"));
test("question 32223: preserves source contract",()=>has(6,"throw new TypeError(label+\" must be a 3D vector\");"));
test("question 32224: preserves source contract",()=>has(6,"const out=value.map(Number);"));
test("question 32225: preserves source contract",()=>has(6,"if(!out.every(Number.isFinite)){"));
test("question 32226: preserves source contract",()=>has(6,"throw new RangeError(label+\" contains non-finite values\");"));
test("question 32227: preserves source contract",()=>has(6,"const sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];"));
test("question 32228: preserves source contract",()=>has(6,"const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];"));
test("question 32229: preserves source contract",()=>has(6,"const cross=(a,b)=>["));
test("question 32230: preserves source contract",()=>has(6,"a[1]*b[2]-a[2]*b[1],"));
test("question 32231: preserves source contract",()=>has(6,"a[2]*b[0]-a[0]*b[2],"));
test("question 32232: preserves source contract",()=>has(6,"a[0]*b[1]-a[1]*b[0]"));
test("question 32233: preserves source contract",()=>has(6,"const len=(a)=>Math.hypot(a[0],a[1],a[2]);"));
test("question 32234: preserves source contract",()=>has(6,"const mul=(a,s)=>[a[0]*s,a[1]*s,a[2]*s];"));
test("question 32235: preserves source contract",()=>has(6,"function unit(value,label){"));
test("question 32236: preserves source contract",()=>has(6,"const v=point3(value,label);"));
test("question 32237: preserves source contract",()=>has(6,"const l=len(v);"));
test("question 32238: preserves source contract",()=>has(6,"if(!(l>0)) throw new RangeError(label+\" is degenerate\");"));
test("question 32239: preserves source contract",()=>has(6,"return mul(v,1/l);"));
test("question 32240: preserves source contract",()=>has(6,"function unwrap(value,label){"));
test("question 32241: preserves source contract",()=>has(6,"if(!value||typeof value!==\"object\"||!(\"value\" in value)){"));
test("question 32242: preserves source contract",()=>has(6,"throw new TypeError(label+\" confidence value is required\");"));
test("question 32243: preserves source contract",()=>has(6,"return value.value;"));
test("question 32244: preserves source contract",()=>has(6,"function primitiveList(canonical){"));
test("question 32245: preserves source contract",()=>has(6,"if(!canonical||canonical.schema_version!==\"1.0.0\"){"));
test("question 32246: preserves source contract",()=>has(6,"throw new TypeError(\"CanonicalTubeGeometry 1.0.0 is required\");"));
test("question 32247: preserves source contract",()=>has(6,"if(!Array.isArray(canonical.primitives)||canonical.primitives.length<1){"));
test("question 32248: preserves source contract",()=>has(6,"throw new RangeError(\"canonical primitives are required\");"));
test("question 32249: preserves source contract",()=>has(6,"return canonical.primitives;"));
test("question 32250: preserves source contract",()=>has(6,"function firstLineAndBend(canonical){"));
test("question 32251: preserves source contract",()=>has(6,"const primitives=primitiveList(canonical);"));
test("question 32252: preserves source contract",()=>has(6,"const firstLine=primitives.find((p)=>p?.type===\"LINE\");"));
test("question 32253: preserves source contract",()=>has(6,"const firstBend=primitives.find((p)=>p?.type===\"BEND\");"));
test("question 32254: preserves source contract",()=>has(6,"if(!firstLine) throw new RangeError(\"tube-local frame requires at least one LINE\");"));
test("question 32255: preserves source contract",()=>has(6,"if(!firstBend){"));
test("question 32256: preserves source contract",()=>has(6,"return {primitives,firstLine,firstBend:null};"));
test("question 32257: preserves source contract",()=>has(6,"return {primitives,firstLine,firstBend};"));
test("question 32258: preserves source contract",()=>has(6,"function localComponents(vector,basis){"));
test("question 32259: preserves source contract",()=>has(6,"dot(vector,basis.x),"));
test("question 32260: preserves source contract",()=>has(6,"dot(vector,basis.y),"));
test("question 32261: preserves source contract",()=>has(6,"dot(vector,basis.z)"));
test("question 32262: preserves source contract",()=>has(6,"* Build a rigid tube-local frame from canonical intrinsic geometry."));
test("question 32263: preserves source contract",()=>has(6,"* origin = first LINE start"));
test("question 32264: preserves source contract",()=>has(6,"* +X     = first LINE direction"));
test("question 32265: preserves source contract",()=>has(6,"* +Z     = oriented first BEND plane normal"));
test("question 32266: preserves source contract",()=>has(6,"* +Y     = Z x X"));
test("question 32267: preserves source contract",()=>has(6,"* No scaling or reflection is introduced. If the first bend plane is not"));
test("question 32268: preserves source contract",()=>has(6,"* orthogonal to the first-line tangent within tolerance, mapping is blocked."));
test("question 32269: preserves source contract",()=>has(6,"export function deriveTubeLocalFrame("));
test("question 32270: preserves source contract",()=>has(6,"{orthogonality_tolerance=1e-6}={}"));
test("question 32271: preserves source contract",()=>has(6,"const {firstLine,firstBend}=firstLineAndBend(canonical);"));
test("question 32272: preserves source contract",()=>has(6,"return Object.freeze({"));
test("question 32273: preserves source contract",()=>has(6,"status:\"unresolved\","));
test("question 32274: preserves source contract",()=>has(6,"canonical_ready:false,"));
test("question 32275: preserves source contract",()=>has(6,"production_ready:false,"));
test("question 32276: preserves source contract",()=>has(6,"reason:\"A straight-only tube does not define a unique bend plane for legacy editable-row mapping.\""));
test("question 32277: preserves source contract",()=>has(6,"const origin=point3(unwrap(firstLine.start,\"first LINE start\"),\"first LINE start\");"));
test("question 32278: preserves source contract",()=>has(6,"const x=unit(unwrap(firstLine.direction,\"first LINE direction\"),\"first LINE direction\");"));
test("question 32279: preserves source contract",()=>has(6,"const rawNormal=unit("));
test("question 32280: preserves source contract",()=>has(6,"unwrap(firstBend.bend_plane_normal,\"first BEND plane normal\"),"));
test("question 32281: preserves source contract",()=>has(6,"\"first BEND plane normal\""));
test("question 32282: preserves source contract",()=>has(6,"const angle=Number(unwrap(firstBend.angle,\"first BEND angle\"));"));
test("question 32283: preserves source contract",()=>has(6,"if(!Number.isFinite(angle)||angle===0){"));
test("question 32284: preserves source contract",()=>has(6,"throw new RangeError(\"first BEND angle must be finite and non-zero\");"));
test("question 32285: preserves source contract",()=>has(6,"const z=mul(rawNormal,Math.sign(angle)||1);"));
test("question 32286: preserves source contract",()=>has(6,"const xzDot=Math.abs(dot(x,z));"));
test("question 32287: preserves source contract",()=>has(6,"if(xzDot>orthogonality_tolerance){"));
test("question 32288: preserves source contract",()=>has(6,"status:\"blocked\","));
test("question 32289: preserves source contract",()=>has(6,"reason:\"First LINE direction is not orthogonal to the oriented first-bend plane normal.\","));
test("question 32290: preserves source contract",()=>has(6,"orthogonality_error:xzDot,"));
test("question 32291: preserves source contract",()=>has(6,"tolerance:orthogonality_tolerance"));
test("question 32292: preserves source contract",()=>has(6,"const y=unit(cross(z,x),\"tube-local +Y\");"));
test("question 32293: preserves source contract",()=>has(6,"const correctedZ=unit(cross(x,y),\"tube-local +Z\");"));
test("question 32294: preserves source contract",()=>has(6,"const determinant=dot(x,cross(y,correctedZ));"));
test("question 32295: preserves source contract",()=>has(6,"status:\"exact\","));
test("question 32296: preserves source contract",()=>has(6,"canonical_ready:true,"));
test("question 32297: preserves source contract",()=>has(6,"frame_id:\"tube-local\","));
test("question 32298: preserves source contract",()=>has(6,"handedness:\"right\","));
test("question 32299: preserves source contract",()=>has(6,"origin:Object.freeze(origin),"));
test("question 32300: preserves source contract",()=>has(6,"axes:Object.freeze({"));
test("question 32301: preserves source contract",()=>has(6,"x:Object.freeze(x),"));
test("question 32302: preserves source contract",()=>has(6,"y:Object.freeze(y),"));
test("question 32303: preserves source contract",()=>has(6,"z:Object.freeze(correctedZ)"));
test("question 32304: preserves source contract",()=>has(6,"source_handedness:canonical.coordinate_frame?.handedness??null,"));
test("question 32305: preserves source contract",()=>has(6,"first_line_element_id:firstLine.element_id??null,"));
test("question 32306: preserves source contract",()=>has(6,"first_bend_element_id:firstBend.element_id??null,"));
test("question 32307: preserves source contract",()=>has(6,"legacy_start_axis:\"X\","));
test("question 32308: preserves source contract",()=>has(6,"legacy_first_bend_plane:\"XY\","));
test("question 32309: preserves source contract",()=>has(6,"determinant,"));
test("question 32310: preserves source contract",()=>has(6,"rigid_rebase:true,"));
test("question 32311: preserves source contract",()=>has(6,"reflection_applied:false,"));
test("question 32312: preserves source contract",()=>has(6,"scale_applied:false,"));
test("question 32313: preserves source contract",()=>has(6,"reason:\"Tube-local frame is derived from intrinsic geometry by translation and proper rotation only.\""));
test("question 32314: preserves source contract",()=>has(6,"export function transformPointToTubeLocal(point,frame){"));
test("question 32315: preserves source contract",()=>has(6,"if(!frame||frame.status!==\"exact\"){"));
test("question 32316: preserves source contract",()=>has(6,"throw new RangeError(\"exact tube-local frame is required\");"));
test("question 32317: preserves source contract",()=>has(6,"const p=point3(point,\"point\");"));
test("question 32318: preserves source contract",()=>has(6,"const relative=sub(p,frame.origin);"));
test("question 32319: preserves source contract",()=>has(6,"return Object.freeze(localComponents(relative,frame.axes));"));
test("question 32320: preserves source contract",()=>has(6,"export function transformVectorToTubeLocal(vector,frame){"));
test("question 32321: preserves source contract",()=>has(6,"const v=point3(vector,\"vector\");"));
test("question 32322: preserves source contract",()=>has(6,"return Object.freeze(localComponents(v,frame.axes));"));
test("question 32323: preserves source contract",()=>has(6,"* Rebase a CanonicalTubeGeometry into the derived tube-local frame while"));
test("question 32324: preserves source contract",()=>has(6,"* preserving confidence/provenance wrappers."));
test("question 32325: preserves source contract",()=>has(6,"export function rebaseCanonicalToTubeLocal(canonical,frame=deriveTubeLocalFrame(canonical)){"));
test("question 32326: preserves source contract",()=>has(6,"if(frame.status!==\"exact\"){"));
test("question 32327: preserves source contract",()=>has(6,"canonical_geometry:null,"));
test("question 32328: preserves source contract",()=>has(6,"production_ready:false"));
test("question 32329: preserves source contract",()=>has(6,"const mapValue=(wrapped,mapper)=>Object.freeze({"));
test("question 32330: preserves source contract",()=>has(6,"value:wrapped.value==null?null:mapper(wrapped.value)"));
test("question 32331: preserves source contract",()=>has(6,"const primitives=canonical.primitives.map((primitive)=>{"));
test("question 32332: preserves source contract",()=>has(6,"if(primitive.type===\"LINE\"){"));
test("question 32333: preserves source contract",()=>has(6,"...primitive,"));
test("question 32334: preserves source contract",()=>has(6,"start:mapValue(primitive.start,(v)=>transformPointToTubeLocal(v,frame)),"));
test("question 32335: preserves source contract",()=>has(6,"end:mapValue(primitive.end,(v)=>transformPointToTubeLocal(v,frame)),"));
test("question 32336: preserves source contract",()=>has(6,"direction:mapValue(primitive.direction,(v)=>transformVectorToTubeLocal(v,frame))"));
test("question 32337: preserves source contract",()=>has(6,"if(primitive.type===\"BEND\"){"));
test("question 32338: preserves source contract",()=>has(6,"tangent_in:mapValue(primitive.tangent_in,(v)=>transformPointToTubeLocal(v,frame)),"));
test("question 32339: preserves source contract",()=>has(6,"tangent_out:mapValue(primitive.tangent_out,(v)=>transformPointToTubeLocal(v,frame)),"));
test("question 32340: preserves source contract",()=>has(6,"center:mapValue(primitive.center,(v)=>transformPointToTubeLocal(v,frame)),"));
test("question 32341: preserves source contract",()=>has(6,"bend_plane_normal:mapValue("));
test("question 32342: preserves source contract",()=>has(6,"primitive.bend_plane_normal,"));
test("question 32343: preserves source contract",()=>has(6,"(v)=>transformVectorToTubeLocal(v,frame)"));
test("question 32344: preserves source contract",()=>has(6,"throw new RangeError(\"unsupported canonical primitive type \"+String(primitive.type));"));
test("question 32345: preserves source contract",()=>has(6,"status:\"rebased\","));
test("question 32346: preserves source contract",()=>has(6,"canonical_geometry:Object.freeze({"));
test("question 32347: preserves source contract",()=>has(6,"...canonical,"));
test("question 32348: preserves source contract",()=>has(6,"coordinate_frame:Object.freeze({"));
