import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const files=["src/recognition/tube-mesh-centerline.mjs","src/import/dwfx/edgebreaker-connectivity.mjs","src/import/dwfx/editable-spatial-placement.mjs"];
const sources=files.map(rel=>fs.readFileSync(path.join(root,rel),"utf8"));
const has=(fileIndex,snippet)=>assert.ok(sources[fileIndex].includes(snippet),"missing source contract: "+files[fileIndex]+"::"+snippet);
test("question 25824: preserves recognition import source contract",()=>has(0,"function finitePoint(point, label) {"));
test("question 25825: preserves recognition import source contract",()=>has(0,"if (!Array.isArray(point) || point.length !== 3) {"));
test("question 25826: preserves recognition import source contract",()=>has(0,"throw new TypeError(`${label} must be a 3D point`);"));
test("question 25827: preserves recognition import source contract",()=>has(0,"const out = point.map(Number);"));
test("question 25828: preserves recognition import source contract",()=>has(0,"if (!out.every(Number.isFinite)) {"));
test("question 25829: preserves recognition import source contract",()=>has(0,"throw new RangeError(`${label} contains non-finite coordinates`);"));
test("question 25830: preserves recognition import source contract",()=>has(0,"function distance(a, b) {"));
test("question 25831: preserves recognition import source contract",()=>has(0,"return Math.hypot(a[0]-b[0], a[1]-b[1], a[2]-b[2]);"));
test("question 25832: preserves recognition import source contract",()=>has(0,"const sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];"));
test("question 25833: preserves recognition import source contract",()=>has(0,"const add=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];"));
test("question 25834: preserves recognition import source contract",()=>has(0,"const mul=(a,s)=>[a[0]*s,a[1]*s,a[2]*s];"));
test("question 25835: preserves recognition import source contract",()=>has(0,"const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];"));
test("question 25836: preserves recognition import source contract",()=>has(0,"const cross=(a,b)=>["));
test("question 25837: preserves recognition import source contract",()=>has(0,"a[1]*b[2]-a[2]*b[1],"));
test("question 25838: preserves recognition import source contract",()=>has(0,"a[2]*b[0]-a[0]*b[2],"));
test("question 25839: preserves recognition import source contract",()=>has(0,"a[0]*b[1]-a[1]*b[0]"));
test("question 25840: preserves recognition import source contract",()=>has(0,"const vectorLength=(a)=>Math.hypot(a[0],a[1],a[2]);"));
test("question 25841: preserves recognition import source contract",()=>has(0,"function unit(a){"));
test("question 25842: preserves recognition import source contract",()=>has(0,"const length=vectorLength(a);"));
test("question 25843: preserves recognition import source contract",()=>has(0,"return length>0 ? mul(a,1/length) : null;"));
test("question 25844: preserves recognition import source contract",()=>has(0,"function clamp(value,min,max){"));
test("question 25845: preserves recognition import source contract",()=>has(0,"return Math.max(min,Math.min(max,value));"));
test("question 25846: preserves recognition import source contract",()=>has(0,"function angleDeg(a,b){"));
test("question 25847: preserves recognition import source contract",()=>has(0,"const left=unit(a),right=unit(b);"));
test("question 25848: preserves recognition import source contract",()=>has(0,"if(!left||!right) return Infinity;"));
test("question 25849: preserves recognition import source contract",()=>has(0,"return Math.acos(clamp(dot(left,right),-1,1))*180/Math.PI;"));
test("question 25850: preserves recognition import source contract",()=>has(0,"function meanPoint(points) {"));
test("question 25851: preserves recognition import source contract",()=>has(0,"const sum=[0,0,0];"));
test("question 25852: preserves recognition import source contract",()=>has(0,"for(const p of points){"));
test("question 25853: preserves recognition import source contract",()=>has(0,"sum[0]+=p[0]; sum[1]+=p[1]; sum[2]+=p[2];"));
test("question 25854: preserves recognition import source contract",()=>has(0,"return sum.map((value)=>value/points.length);"));
test("question 25855: preserves recognition import source contract",()=>has(0,"function mean(values) {"));
test("question 25856: preserves recognition import source contract",()=>has(0,"return values.reduce((sum,value)=>sum+value,0)/values.length;"));
test("question 25857: preserves recognition import source contract",()=>has(0,"function stddev(values, average=mean(values)) {"));
test("question 25858: preserves recognition import source contract",()=>has(0,"return Math.sqrt("));
test("question 25859: preserves recognition import source contract",()=>has(0,"values.reduce((sum,value)=>sum+(value-average)**2,0)/values.length"));
test("question 25860: preserves recognition import source contract",()=>has(0,"function edgeKey(a,b) {"));
test("question 25861: preserves recognition import source contract",()=>has(0,"return a<b ? `${a}:${b}` : `${b}:${a}`;"));
test("question 25862: preserves recognition import source contract",()=>has(0,"function normalizeMesh(vertices, faces) {"));
test("question 25863: preserves recognition import source contract",()=>has(0,"if (!Array.isArray(vertices) || vertices.length < 3) {"));
test("question 25864: preserves recognition import source contract",()=>has(0,"throw new RangeError(\"mesh vertices are required\");"));
test("question 25865: preserves recognition import source contract",()=>has(0,"if (!Array.isArray(faces) || faces.length < 1) {"));
test("question 25866: preserves recognition import source contract",()=>has(0,"throw new RangeError(\"mesh triangle faces are required\");"));
test("question 25867: preserves recognition import source contract",()=>has(0,"const points=vertices.map((point,index)=>finitePoint(point,`vertex ${index}`));"));
test("question 25868: preserves recognition import source contract",()=>has(0,"const triangles=faces.map((face,index)=>{"));
test("question 25869: preserves recognition import source contract",()=>has(0,"if (!Array.isArray(face) || face.length !== 3) {"));
test("question 25870: preserves recognition import source contract",()=>has(0,"throw new TypeError(`face ${index} must contain three indices`);"));
test("question 25871: preserves recognition import source contract",()=>has(0,"const tri=face.map(Number);"));
test("question 25872: preserves recognition import source contract",()=>has(0,"if (!tri.every((value)=>Number.isInteger(value) && value>=0 && value<points.length)) {"));
test("question 25873: preserves recognition import source contract",()=>has(0,"throw new RangeError(`face ${index} contains an invalid vertex index`);"));
test("question 25874: preserves recognition import source contract",()=>has(0,"if (new Set(tri).size !== 3) {"));
test("question 25875: preserves recognition import source contract",()=>has(0,"throw new RangeError(`face ${index} is degenerate`);"));
test("question 25876: preserves recognition import source contract",()=>has(0,"return {points,triangles};"));
test("question 25877: preserves recognition import source contract",()=>has(0,"function meshComponents(vertexCount, faces) {"));
test("question 25878: preserves recognition import source contract",()=>has(0,"const adjacency=Array.from({length:vertexCount},()=>new Set());"));
test("question 25879: preserves recognition import source contract",()=>has(0,"for(const [a,b,c] of faces){"));
test("question 25880: preserves recognition import source contract",()=>has(0,"for(const [u,v] of [[a,b],[b,c],[c,a]]){"));
test("question 25881: preserves recognition import source contract",()=>has(0,"adjacency[u].add(v);"));
test("question 25882: preserves recognition import source contract",()=>has(0,"adjacency[v].add(u);"));
test("question 25883: preserves recognition import source contract",()=>has(0,"const seen=new Set();"));
test("question 25884: preserves recognition import source contract",()=>has(0,"const components=[];"));
test("question 25885: preserves recognition import source contract",()=>has(0,"for(let seed=0;seed<vertexCount;seed+=1){"));
test("question 25886: preserves recognition import source contract",()=>has(0,"if(seen.has(seed) || adjacency[seed].size===0) continue;"));
test("question 25887: preserves recognition import source contract",()=>has(0,"const stack=[seed];"));
test("question 25888: preserves recognition import source contract",()=>has(0,"const vertices=[];"));
test("question 25889: preserves recognition import source contract",()=>has(0,"seen.add(seed);"));
test("question 25890: preserves recognition import source contract",()=>has(0,"while(stack.length){"));
test("question 25891: preserves recognition import source contract",()=>has(0,"const current=stack.pop();"));
test("question 25892: preserves recognition import source contract",()=>has(0,"vertices.push(current);"));
test("question 25893: preserves recognition import source contract",()=>has(0,"for(const next of adjacency[current]){"));
test("question 25894: preserves recognition import source contract",()=>has(0,"if(!seen.has(next)){"));
test("question 25895: preserves recognition import source contract",()=>has(0,"seen.add(next);"));
test("question 25896: preserves recognition import source contract",()=>has(0,"stack.push(next);"));
test("question 25897: preserves recognition import source contract",()=>has(0,"const set=new Set(vertices);"));
test("question 25898: preserves recognition import source contract",()=>has(0,"const componentFaces=faces.filter((face)=>set.has(face[0]));"));
test("question 25899: preserves recognition import source contract",()=>has(0,"const edgeCounts=new Map();"));
test("question 25900: preserves recognition import source contract",()=>has(0,"for(const [a,b,c] of componentFaces){"));
test("question 25901: preserves recognition import source contract",()=>has(0,"const key=edgeKey(u,v);"));
test("question 25902: preserves recognition import source contract",()=>has(0,"edgeCounts.set(key,(edgeCounts.get(key)??0)+1);"));
test("question 25903: preserves recognition import source contract",()=>has(0,"components.push({"));
test("question 25904: preserves recognition import source contract",()=>has(0,"vertices:vertices.sort((a,b)=>a-b),"));
test("question 25905: preserves recognition import source contract",()=>has(0,"faces:componentFaces,"));
test("question 25906: preserves recognition import source contract",()=>has(0,"boundary_edge_count:[...edgeCounts.values()].filter((count)=>count===1).length"));
test("question 25907: preserves recognition import source contract",()=>has(0,"return components;"));
test("question 25908: preserves recognition import source contract",()=>has(0,"function consecutive(indices) {"));
test("question 25909: preserves recognition import source contract",()=>has(0,"for(let i=1;i<indices.length;i+=1){"));
test("question 25910: preserves recognition import source contract",()=>has(0,"if(indices[i]!==indices[i-1]+1) return false;"));
test("question 25911: preserves recognition import source contract",()=>has(0,"return true;"));
test("question 25912: preserves recognition import source contract",()=>has(0,"function ringNormal(ring,center) {"));
test("question 25913: preserves recognition import source contract",()=>has(0,"let normal=[0,0,0];"));
test("question 25914: preserves recognition import source contract",()=>has(0,"for(let i=0;i<ring.length;i+=1){"));
test("question 25915: preserves recognition import source contract",()=>has(0,"const current=sub(ring[i],center);"));
test("question 25916: preserves recognition import source contract",()=>has(0,"const next=sub(ring[(i+1)%ring.length],center);"));
test("question 25917: preserves recognition import source contract",()=>has(0,"normal=add(normal,cross(current,next));"));
test("question 25918: preserves recognition import source contract",()=>has(0,"return unit(normal);"));
test("question 25919: preserves recognition import source contract",()=>has(0,"function orientRingNormals(centers,normals) {"));
test("question 25920: preserves recognition import source contract",()=>has(0,"return normals.map((normal,index)=>{"));
test("question 25921: preserves recognition import source contract",()=>has(0,"if(!normal) return null;"));
test("question 25922: preserves recognition import source contract",()=>has(0,"const reference=index===0"));
test("question 25923: preserves recognition import source contract",()=>has(0,"? sub(centers[1],centers[0])"));
test("question 25924: preserves recognition import source contract",()=>has(0,": index===centers.length-1"));
test("question 25925: preserves recognition import source contract",()=>has(0,"? sub(centers.at(-1),centers.at(-2))"));
test("question 25926: preserves recognition import source contract",()=>has(0,": sub(centers[index+1],centers[index-1]);"));
test("question 25927: preserves recognition import source contract",()=>has(0,"return dot(normal,reference)<0 ? mul(normal,-1) : normal;"));
test("question 25928: preserves recognition import source contract",()=>has(0,"function sideSurfaceCandidate(component, points) {"));
test("question 25929: preserves recognition import source contract",()=>has(0,"const boundary=component.boundary_edge_count;"));
test("question 25930: preserves recognition import source contract",()=>has(0,"if (boundary < 6 || boundary % 2 !== 0) return null;"));
test("question 25931: preserves recognition import source contract",()=>has(0,"const circumferenceCount=boundary/2;"));
test("question 25932: preserves recognition import source contract",()=>has(0,"if (component.vertices.length % circumferenceCount !== 0) return null;"));
test("question 25933: preserves recognition import source contract",()=>has(0,"const axialCount=component.vertices.length/circumferenceCount;"));
test("question 25934: preserves recognition import source contract",()=>has(0,"if (axialCount < 2) return null;"));
test("question 25935: preserves recognition import source contract",()=>has(0,"if (component.faces.length !== 2*circumferenceCount*(axialCount-1)) return null;"));
test("question 25936: preserves recognition import source contract",()=>has(0,"if (!consecutive(component.vertices)) return null;"));
test("question 25937: preserves recognition import source contract",()=>has(0,"const rings=[];"));
test("question 25938: preserves recognition import source contract",()=>has(0,"const centers=[];"));
test("question 25939: preserves recognition import source contract",()=>has(0,"const ringRadii=[];"));
test("question 25940: preserves recognition import source contract",()=>has(0,"const rawNormals=[];"));
test("question 25941: preserves recognition import source contract",()=>has(0,"const ringPlaneErrors=[];"));
test("question 25942: preserves recognition import source contract",()=>has(0,"for(let ringIndex=0;ringIndex<axialCount;ringIndex+=1){"));
test("question 25943: preserves recognition import source contract",()=>has(0,"const ids=component.vertices.slice("));
test("question 25944: preserves recognition import source contract",()=>has(0,"ringIndex*circumferenceCount,"));
test("question 25945: preserves recognition import source contract",()=>has(0,"(ringIndex+1)*circumferenceCount"));
test("question 25946: preserves recognition import source contract",()=>has(0,"const ring=ids.map((id)=>points[id]);"));
test("question 25947: preserves recognition import source contract",()=>has(0,"const center=meanPoint(ring);"));
test("question 25948: preserves recognition import source contract",()=>has(0,"const radii=ring.map((point)=>distance(point,center));"));
test("question 25949: preserves recognition import source contract",()=>has(0,"const normal=ringNormal(ring,center);"));
test("question 25950: preserves recognition import source contract",()=>has(0,"const planeError=Math.max("));
test("question 25951: preserves recognition import source contract",()=>has(0,"...ring.map((point)=>Math.abs(dot(sub(point,center),normal)))"));
test("question 25952: preserves recognition import source contract",()=>has(0,"rings.push(ids);"));
test("question 25953: preserves recognition import source contract",()=>has(0,"centers.push(center);"));
test("question 25954: preserves recognition import source contract",()=>has(0,"ringRadii.push(radii);"));
test("question 25955: preserves recognition import source contract",()=>has(0,"rawNormals.push(normal);"));
test("question 25956: preserves recognition import source contract",()=>has(0,"ringPlaneErrors.push(planeError);"));
test("question 25957: preserves recognition import source contract",()=>has(0,"const ringNormals=orientRingNormals(centers,rawNormals);"));
test("question 25958: preserves recognition import source contract",()=>has(0,"if(ringNormals.some((normal)=>!normal)) return null;"));
test("question 25959: preserves recognition import source contract",()=>has(0,"const allRadii=ringRadii.flat();"));
test("question 25960: preserves recognition import source contract",()=>has(0,"const radiusMean=mean(allRadii);"));
test("question 25961: preserves recognition import source contract",()=>has(0,"const radiusStddev=stddev(allRadii,radiusMean);"));
test("question 25962: preserves recognition import source contract",()=>has(0,"vertex_count:component.vertices.length,"));
test("question 25963: preserves recognition import source contract",()=>has(0,"face_count:component.faces.length,"));
test("question 25964: preserves recognition import source contract",()=>has(0,"boundary_edge_count:boundary,"));
test("question 25965: preserves recognition import source contract",()=>has(0,"circumference_count:circumferenceCount,"));
test("question 25966: preserves recognition import source contract",()=>has(0,"axial_count:axialCount,"));
test("question 25967: preserves recognition import source contract",()=>has(0,"vertex_index_start:component.vertices[0],"));
test("question 25968: preserves recognition import source contract",()=>has(0,"vertex_index_end:component.vertices.at(-1),"));
test("question 25969: preserves recognition import source contract",()=>has(0,"ring_normals:ringNormals,"));
test("question 25970: preserves recognition import source contract",()=>has(0,"radius_source_units:radiusMean,"));
test("question 25971: preserves recognition import source contract",()=>has(0,"radius_stddev_source_units:radiusStddev,"));
test("question 25972: preserves recognition import source contract",()=>has(0,"max_ring_plane_error_source_units:Math.max(...ringPlaneErrors)"));
test("question 25973: preserves recognition import source contract",()=>has(0,"function alignCenterlines(a,b) {"));
test("question 25974: preserves recognition import source contract",()=>has(0,"if(a.length!==b.length) {"));
test("question 25975: preserves recognition import source contract",()=>has(0,"return {status:\"mismatch\",centers:null,max_error:Infinity,reversed:false};"));
test("question 25976: preserves recognition import source contract",()=>has(0,"const maxError=(left,right)=>Math.max("));
test("question 25977: preserves recognition import source contract",()=>has(0,"...left.map((point,index)=>distance(point,right[index]))"));
test("question 25978: preserves recognition import source contract",()=>has(0,"const same=maxError(a,b);"));
test("question 25979: preserves recognition import source contract",()=>has(0,"const reversedB=[...b].reverse();"));
test("question 25980: preserves recognition import source contract",()=>has(0,"const reversed=maxError(a,reversedB);"));
test("question 25981: preserves recognition import source contract",()=>has(0,"const useReversed=reversed<same;"));
test("question 25982: preserves recognition import source contract",()=>has(0,"const selected=useReversed?reversedB:b;"));
test("question 25983: preserves recognition import source contract",()=>has(0,"status:\"aligned\","));
test("question 25984: preserves recognition import source contract",()=>has(0,"centers:a.map((point,index)=>meanPoint([point,selected[index]])),"));
test("question 25985: preserves recognition import source contract",()=>has(0,"max_error:Math.min(same,reversed),"));
test("question 25986: preserves recognition import source contract",()=>has(0,"reversed:useReversed"));
test("question 25987: preserves recognition import source contract",()=>has(0,"function positive(value,label) {"));
test("question 25988: preserves recognition import source contract",()=>has(0,"const number=Number(value);"));
test("question 25989: preserves recognition import source contract",()=>has(0,"if(!Number.isFinite(number) || number<=0) {"));
test("question 25990: preserves recognition import source contract",()=>has(0,"throw new RangeError(`${label} must be positive`);"));
test("question 25991: preserves recognition import source contract",()=>has(0,"return number;"));
test("question 25992: preserves recognition import source contract",()=>has(0,"function polylineLength(points) {"));
test("question 25993: preserves recognition import source contract",()=>has(0,"let total=0;"));
test("question 25994: preserves recognition import source contract",()=>has(0,"for(let i=1;i<points.length;i+=1) total+=distance(points[i-1],points[i]);"));
test("question 25995: preserves recognition import source contract",()=>has(0,"return total;"));
test("question 25996: preserves recognition import source contract",()=>has(0,"* Derive centerline samples from an Inventor-style hollow tube shell."));
test("question 25997: preserves recognition import source contract",()=>has(0,"* Acceptance is deliberately strict:"));
test("question 25998: preserves recognition import source contract",()=>has(0,"* - exactly two side-surface grid components must be present;"));
test("question 25999: preserves recognition import source contract",()=>has(0,"* - each grid must be ring-major and topologically exact;"));
test("question 26000: preserves recognition import source contract",()=>has(0,"* - both side surfaces must produce the same axial centers;"));
test("question 26001: preserves recognition import source contract",()=>has(0,"* - outer/inner radii must agree with exact metadata dimensions."));
test("question 26002: preserves recognition import source contract",()=>has(0,"* The result remains derived evidence. Primitive LINE/BEND recognition is a"));
test("question 26003: preserves recognition import source contract",()=>has(0,"* separate stage and production readiness is always false here."));
test("question 26004: preserves recognition import source contract",()=>has(0,"export function deriveTubeMeshCenterline({"));
test("question 26005: preserves recognition import source contract",()=>has(0,"outer_diameter_mm,"));
test("question 26006: preserves recognition import source contract",()=>has(0,"wall_thickness_mm,"));
test("question 26007: preserves recognition import source contract",()=>has(0,"scale_mm_per_source_unit = null,"));
test("question 26008: preserves recognition import source contract",()=>has(0,"center_match_tolerance_mm = 0.02,"));
test("question 26009: preserves recognition import source contract",()=>has(0,"radius_tolerance_mm = 0.02,"));
test("question 26010: preserves recognition import source contract",()=>has(0,"max_ring_radius_stddev_mm = 0.01,"));
test("question 26011: preserves recognition import source contract",()=>has(0,"max_ring_plane_error_mm = 0.01,"));
test("question 26012: preserves recognition import source contract",()=>has(0,"surface_tangent_tolerance_deg = 0.1,"));
test("question 26013: preserves recognition import source contract",()=>has(0,"dimension_validation = \"metadata\""));
test("question 26014: preserves recognition import source contract",()=>has(0,"if(![\"metadata\",\"geometry\"].includes(dimension_validation)){"));
test("question 26015: preserves recognition import source contract",()=>has(0,"throw new RangeError(\"dimension_validation must be metadata or geometry\");"));
test("question 26016: preserves recognition import source contract",()=>has(0,"const {points,triangles}=normalizeMesh(vertices,faces);"));
test("question 26017: preserves recognition import source contract",()=>has(0,"const components=meshComponents(points.length,triangles);"));
test("question 26018: preserves recognition import source contract",()=>has(0,"const sideCandidates=components"));
test("question 26019: preserves recognition import source contract",()=>has(0,".map((component)=>sideSurfaceCandidate(component,points))"));
test("question 26020: preserves recognition import source contract",()=>has(0,".filter(Boolean);"));
test("question 26021: preserves recognition import source contract",()=>has(0,"const outerDiameter=positive(outer_diameter_mm,\"outer_diameter_mm\");"));
test("question 26022: preserves recognition import source contract",()=>has(0,"const wall=positive(wall_thickness_mm,\"wall_thickness_mm\");"));
test("question 26023: preserves recognition import source contract",()=>has(0,"if(wall*2>=outerDiameter) {"));
test("question 26024: preserves recognition import source contract",()=>has(0,"throw new RangeError(\"wall_thickness_mm is incompatible with outer_diameter_mm\");"));
test("question 26025: preserves recognition import source contract",()=>has(0,"const explicitScale=scale_mm_per_source_unit==null"));
test("question 26026: preserves recognition import source contract",()=>has(0,": positive(scale_mm_per_source_unit,\"scale_mm_per_source_unit\");"));
test("question 26027: preserves recognition import source contract",()=>has(0,"const pairEvaluations=[];"));
test("question 26028: preserves recognition import source contract",()=>has(0,"for(let i=0;i<sideCandidates.length;i+=1){"));
test("question 26029: preserves recognition import source contract",()=>has(0,"for(let j=i+1;j<sideCandidates.length;j+=1){"));
test("question 26030: preserves recognition import source contract",()=>has(0,"const left=sideCandidates[i];"));
test("question 26031: preserves recognition import source contract",()=>has(0,"const right=sideCandidates[j];"));
test("question 26032: preserves recognition import source contract",()=>has(0,"const pairBlockers=[];"));
test("question 26033: preserves recognition import source contract",()=>has(0,"if(left.axial_count!==right.axial_count){"));
test("question 26034: preserves recognition import source contract",()=>has(0,"pairBlockers.push(\"axial ring counts differ\");"));
test("question 26035: preserves recognition import source contract",()=>has(0,"const sorted=[left,right].sort("));
test("question 26036: preserves recognition import source contract",()=>has(0,"(a,b)=>a.radius_source_units-b.radius_source_units"));
test("question 26037: preserves recognition import source contract",()=>has(0,"const inner=sorted[0];"));
test("question 26038: preserves recognition import source contract",()=>has(0,"const outer=sorted[1];"));
test("question 26039: preserves recognition import source contract",()=>has(0,"const aligned=left.axial_count===right.axial_count"));
test("question 26040: preserves recognition import source contract",()=>has(0,"? alignCenterlines(outer.centers,inner.centers)"));
test("question 26041: preserves recognition import source contract",()=>has(0,": {status:\"mismatch\",centers:null,max_error:Infinity,reversed:false};"));
test("question 26042: preserves recognition import source contract",()=>has(0,"const scale=explicitScale??("));
test("question 26043: preserves recognition import source contract",()=>has(0,"outer.radius_source_units>0"));
test("question 26044: preserves recognition import source contract",()=>has(0,"? outerDiameter/(2*outer.radius_source_units)"));
test("question 26045: preserves recognition import source contract",()=>has(0,"const scaleMethod=explicitScale==null"));
test("question 26046: preserves recognition import source contract",()=>has(0,"? \"derived_from_outer_diameter\""));
test("question 26047: preserves recognition import source contract",()=>has(0,": \"explicit\";"));
test("question 26048: preserves recognition import source contract",()=>has(0,"const observedOuterRadiusMm=outer.radius_source_units*scale;"));
test("question 26049: preserves recognition import source contract",()=>has(0,"const observedInnerRadiusMm=inner.radius_source_units*scale;"));
test("question 26050: preserves recognition import source contract",()=>has(0,"const expectedOuterRadiusMm=outerDiameter/2;"));
test("question 26051: preserves recognition import source contract",()=>has(0,"const expectedInnerRadiusMm=expectedOuterRadiusMm-wall;"));
test("question 26052: preserves recognition import source contract",()=>has(0,"const outerError=Math.abs(observedOuterRadiusMm-expectedOuterRadiusMm);"));
test("question 26053: preserves recognition import source contract",()=>has(0,"const innerError=Math.abs(observedInnerRadiusMm-expectedInnerRadiusMm);"));
test("question 26054: preserves recognition import source contract",()=>has(0,"const centerMismatchMm=aligned.max_error*scale;"));
test("question 26055: preserves recognition import source contract",()=>has(0,"const maxRadiusStddevMm=Math.max("));
test("question 26056: preserves recognition import source contract",()=>has(0,"inner.radius_stddev_source_units,"));
test("question 26057: preserves recognition import source contract",()=>has(0,"outer.radius_stddev_source_units"));
test("question 26058: preserves recognition import source contract",()=>has(0,"const maxRingPlaneErrorMm=Math.max("));
test("question 26059: preserves recognition import source contract",()=>has(0,"inner.max_ring_plane_error_source_units,"));
test("question 26060: preserves recognition import source contract",()=>has(0,"outer.max_ring_plane_error_source_units"));
test("question 26061: preserves recognition import source contract",()=>has(0,"const outerNormals=outer.ring_normals;"));
test("question 26062: preserves recognition import source contract",()=>has(0,"const innerNormals=aligned.reversed"));
test("question 26063: preserves recognition import source contract",()=>has(0,"? [...inner.ring_normals].reverse().map((normal)=>mul(normal,-1))"));
test("question 26064: preserves recognition import source contract",()=>has(0,": inner.ring_normals;"));
test("question 26065: preserves recognition import source contract",()=>has(0,"const tangentMismatchDeg=aligned.status===\"aligned\""));
test("question 26066: preserves recognition import source contract",()=>has(0,"...outerNormals.map("));
test("question 26067: preserves recognition import source contract",()=>has(0,"(normal,index)=>angleDeg(normal,innerNormals[index])"));
test("question 26068: preserves recognition import source contract",()=>has(0,"if(aligned.status!==\"aligned\"){"));
test("question 26069: preserves recognition import source contract",()=>has(0,"pairBlockers.push(\"centerline samples cannot be aligned\");"));
test("question 26070: preserves recognition import source contract",()=>has(0,"if(!Number.isFinite(scale) || scale<=0){"));
test("question 26071: preserves recognition import source contract",()=>has(0,"pairBlockers.push(\"unit scale cannot be resolved\");"));
test("question 26072: preserves recognition import source contract",()=>has(0,"if(dimension_validation===\"metadata\"){"));
test("question 26073: preserves recognition import source contract",()=>has(0,"if(outerError>radius_tolerance_mm) {"));
test("question 26074: preserves recognition import source contract",()=>has(0,"pairBlockers.push(`outer radius mismatch ${outerError} mm exceeds tolerance`);"));
test("question 26075: preserves recognition import source contract",()=>has(0,"if(innerError>radius_tolerance_mm) {"));
test("question 26076: preserves recognition import source contract",()=>has(0,"pairBlockers.push(`inner radius mismatch ${innerError} mm exceeds tolerance`);"));
test("question 26077: preserves recognition import source contract",()=>has(0,"if(centerMismatchMm>center_match_tolerance_mm) {"));
test("question 26078: preserves recognition import source contract",()=>has(0,"pairBlockers.push(`side-surface center mismatch ${centerMismatchMm} mm exceeds tolerance`);"));
test("question 26079: preserves recognition import source contract",()=>has(0,"if(maxRadiusStddevMm>max_ring_radius_stddev_mm) {"));
test("question 26080: preserves recognition import source contract",()=>has(0,"pairBlockers.push(`ring radius scatter ${maxRadiusStddevMm} mm exceeds tolerance`);"));
test("question 26081: preserves recognition import source contract",()=>has(0,"if(maxRingPlaneErrorMm>max_ring_plane_error_mm) {"));
test("question 26082: preserves recognition import source contract",()=>has(0,"pairBlockers.push(`ring plane error ${maxRingPlaneErrorMm} mm exceeds tolerance`);"));
test("question 26083: preserves recognition import source contract",()=>has(0,"if(tangentMismatchDeg>surface_tangent_tolerance_deg) {"));
test("question 26084: preserves recognition import source contract",()=>has(0,"pairBlockers.push(`inner/outer tangent mismatch ${tangentMismatchDeg} deg exceeds tolerance`);"));
test("question 26085: preserves recognition import source contract",()=>has(0,"pairEvaluations.push(Object.freeze({"));
test("question 26086: preserves recognition import source contract",()=>has(0,"candidate_indices:Object.freeze([i,j]),"));
test("question 26087: preserves recognition import source contract",()=>has(0,"accepted:pairBlockers.length===0,"));
test("question 26088: preserves recognition import source contract",()=>has(0,"blockers:Object.freeze(pairBlockers),"));
test("question 26089: preserves recognition import source contract",()=>has(0,"scaleMethod,"));
test("question 26090: preserves recognition import source contract",()=>has(0,"observedOuterRadiusMm,"));
test("question 26091: preserves recognition import source contract",()=>has(0,"observedInnerRadiusMm,"));
test("question 26092: preserves recognition import source contract",()=>has(0,"expectedOuterRadiusMm,"));
test("question 26093: preserves recognition import source contract",()=>has(0,"expectedInnerRadiusMm,"));
test("question 26094: preserves recognition import source contract",()=>has(0,"centerMismatchMm,"));
test("question 26095: preserves recognition import source contract",()=>has(0,"maxRadiusStddevMm,"));
test("question 26096: preserves recognition import source contract",()=>has(0,"maxRingPlaneErrorMm,"));
test("question 26097: preserves recognition import source contract",()=>has(0,"tangentMismatchDeg,"));
test("question 26098: preserves recognition import source contract",()=>has(0,"dimension_validation,"));
test("question 26099: preserves recognition import source contract",()=>has(0,"outerNormals,"));
test("question 26100: preserves recognition import source contract",()=>has(0,"innerNormals"));
test("question 26101: preserves recognition import source contract",()=>has(0,"const acceptedPairs=pairEvaluations.filter((pair)=>pair.accepted);"));
test("question 26102: preserves recognition import source contract",()=>has(0,"if(acceptedPairs.length!==1){"));
test("question 26103: preserves recognition import source contract",()=>has(0,"if(acceptedPairs.length===0 && pairEvaluations.length===1){"));
test("question 26104: preserves recognition import source contract",()=>has(0,"const pair=pairEvaluations[0];"));
test("question 26105: preserves recognition import source contract",()=>has(0,"return Object.freeze({"));
test("question 26106: preserves recognition import source contract",()=>has(0,"status:\"unresolved\","));
test("question 26107: preserves recognition import source contract",()=>has(0,"blocker:pair.blockers.join(\"; \"),"));
test("question 26108: preserves recognition import source contract",()=>has(0,"diagnostics:Object.freeze({"));
test("question 26109: preserves recognition import source contract",()=>has(0,"scale_mm_per_source_unit:pair.scale,"));
test("question 26110: preserves recognition import source contract",()=>has(0,"scale_method:pair.scaleMethod,"));
test("question 26111: preserves recognition import source contract",()=>has(0,"observed_outer_radius_mm:pair.observedOuterRadiusMm,"));
test("question 26112: preserves recognition import source contract",()=>has(0,"observed_inner_radius_mm:pair.observedInnerRadiusMm,"));
test("question 26113: preserves recognition import source contract",()=>has(0,"expected_outer_radius_mm:pair.expectedOuterRadiusMm,"));
test("question 26114: preserves recognition import source contract",()=>has(0,"expected_inner_radius_mm:pair.expectedInnerRadiusMm,"));
test("question 26115: preserves recognition import source contract",()=>has(0,"center_mismatch_mm:pair.centerMismatchMm,"));
test("question 26116: preserves recognition import source contract",()=>has(0,"max_ring_radius_stddev_mm:pair.maxRadiusStddevMm,"));
test("question 26117: preserves recognition import source contract",()=>has(0,"max_ring_plane_error_mm:pair.maxRingPlaneErrorMm,"));
test("question 26118: preserves recognition import source contract",()=>has(0,"max_surface_tangent_mismatch_deg:pair.tangentMismatchDeg,"));
test("question 26119: preserves recognition import source contract",()=>has(0,"ring_grid_candidate_count:sideCandidates.length,"));
test("question 26120: preserves recognition import source contract",()=>has(0,"evaluated_pair_count:1,"));
test("question 26121: preserves recognition import source contract",()=>has(0,"accepted_pair_count:0"));
test("question 26122: preserves recognition import source contract",()=>has(0,"production_ready:false,"));
test("question 26123: preserves recognition import source contract",()=>has(0,"canonical_ready:false"));
test("question 26124: preserves recognition import source contract",()=>has(0,"blocker:acceptedPairs.length===0"));
test("question 26125: preserves recognition import source contract",()=>has(0,"? `no unique inner/outer side-surface pair matches tube metadata among ${sideCandidates.length} ring-grid candidates`"));
test("question 26126: preserves recognition import source contract",()=>has(0,": `multiple inner/outer side-surface pairs match tube metadata (${acceptedPairs.length})`,"));
test("question 26127: preserves recognition import source contract",()=>has(0,"evaluated_pair_count:pairEvaluations.length,"));
test("question 26128: preserves recognition import source contract",()=>has(0,"accepted_pair_count:acceptedPairs.length,"));
test("question 26129: preserves recognition import source contract",()=>has(0,"pair_failures:Object.freeze(pairEvaluations"));
test("question 26130: preserves recognition import source contract",()=>has(0,".filter((pair)=>!pair.accepted)"));
test("question 26131: preserves recognition import source contract",()=>has(0,".map((pair)=>Object.freeze({"));
test("question 26132: preserves recognition import source contract",()=>has(0,"candidate_indices:pair.candidate_indices,"));
test("question 26133: preserves recognition import source contract",()=>has(0,"blockers:pair.blockers"));
test("question 26134: preserves recognition import source contract",()=>has(0,"const selected=acceptedPairs[0];"));
test("question 26135: preserves recognition import source contract",()=>has(0,"const derivedOuterDiameterMm=observedOuterRadiusMm*2;"));
test("question 26136: preserves recognition import source contract",()=>has(0,"const derivedWallThicknessMm=observedOuterRadiusMm-observedInnerRadiusMm;"));
test("question 26137: preserves recognition import source contract",()=>has(0,"const centerlineMm=Object.freeze("));
test("question 26138: preserves recognition import source contract",()=>has(0,"aligned.centers.map((point)=>Object.freeze(point.map((value)=>value*scale)))"));
test("question 26139: preserves recognition import source contract",()=>has(0,"const centerlineTangents=Object.freeze("));
test("question 26140: preserves recognition import source contract",()=>has(0,"outerNormals.map((normal,index)=>{"));
test("question 26141: preserves recognition import source contract",()=>has(0,"const combined=unit(add(normal,innerNormals[index]));"));
test("question 26142: preserves recognition import source contract",()=>has(0,"if(!combined) {"));
test("question 26143: preserves recognition import source contract",()=>has(0,"throw new RangeError(`tube centerline tangent ${index} is degenerate`);"));
test("question 26144: preserves recognition import source contract",()=>has(0,"return Object.freeze(combined);"));
test("question 26145: preserves recognition import source contract",()=>has(0,"status:\"centerline_candidate\","));
test("question 26146: preserves recognition import source contract",()=>has(0,"canonical_ready:false,"));
test("question 26147: preserves recognition import source contract",()=>has(0,"source_truth_category:\"derived\","));
test("question 26148: preserves recognition import source contract",()=>has(0,"scale_mm_per_source_unit:scale,"));
test("question 26149: preserves recognition import source contract",()=>has(0,"scale_method:scaleMethod,"));
test("question 26150: preserves recognition import source contract",()=>has(0,"side_surfaces:Object.freeze([inner,outer].map((surface)=>Object.freeze({"));
test("question 26151: preserves recognition import source contract",()=>has(0,"vertex_count:surface.vertex_count,"));
test("question 26152: preserves recognition import source contract",()=>has(0,"face_count:surface.face_count,"));
test("question 26153: preserves recognition import source contract",()=>has(0,"circumference_count:surface.circumference_count,"));
test("question 26154: preserves recognition import source contract",()=>has(0,"axial_count:surface.axial_count,"));
test("question 26155: preserves recognition import source contract",()=>has(0,"vertex_index_start:surface.vertex_index_start,"));
test("question 26156: preserves recognition import source contract",()=>has(0,"vertex_index_end:surface.vertex_index_end,"));
test("question 26157: preserves recognition import source contract",()=>has(0,"radius_source_units:surface.radius_source_units,"));
test("question 26158: preserves recognition import source contract",()=>has(0,"radius_stddev_source_units:surface.radius_stddev_source_units,"));
test("question 26159: preserves recognition import source contract",()=>has(0,"max_ring_plane_error_source_units:surface.max_ring_plane_error_source_units"));
test("question 26160: preserves recognition import source contract",()=>has(0,"observed_outer_radius_mm:observedOuterRadiusMm,"));
test("question 26161: preserves recognition import source contract",()=>has(0,"observed_inner_radius_mm:observedInnerRadiusMm,"));
test("question 26162: preserves recognition import source contract",()=>has(0,"derived_outer_diameter_mm:derivedOuterDiameterMm,"));
test("question 26163: preserves recognition import source contract",()=>has(0,"derived_wall_thickness_mm:derivedWallThicknessMm,"));
test("question 26164: preserves recognition import source contract",()=>has(0,"metadata_outer_diameter_mm:outerDiameter,"));
test("question 26165: preserves recognition import source contract",()=>has(0,"metadata_wall_thickness_mm:wall,"));
test("question 26166: preserves recognition import source contract",()=>has(0,"metadata_dimension_match:"));
test("question 26167: preserves recognition import source contract",()=>has(0,"Math.abs(derivedOuterDiameterMm-outerDiameter)<=radius_tolerance_mm*2 &&"));
test("question 26168: preserves recognition import source contract",()=>has(0,"Math.abs(derivedWallThicknessMm-wall)<=radius_tolerance_mm,"));
test("question 26169: preserves recognition import source contract",()=>has(0,"center_mismatch_mm:centerMismatchMm,"));
test("question 26170: preserves recognition import source contract",()=>has(0,"max_ring_radius_stddev_mm:maxRadiusStddevMm,"));
test("question 26171: preserves recognition import source contract",()=>has(0,"max_ring_plane_error_mm:maxRingPlaneErrorMm,"));
test("question 26172: preserves recognition import source contract",()=>has(0,"max_surface_tangent_mismatch_deg:tangentMismatchDeg,"));
test("question 26173: preserves recognition import source contract",()=>has(0,"centerline_points_mm:centerlineMm,"));
test("question 26174: preserves recognition import source contract",()=>has(0,"centerline_tangents:centerlineTangents,"));
test("question 26175: preserves recognition import source contract",()=>has(0,"centerline_sample_count:centerlineMm.length,"));
test("question 26176: preserves recognition import source contract",()=>has(0,"chordal_polyline_length_mm:polylineLength(centerlineMm)"));
test("question 26177: preserves recognition import source contract",()=>has(1,"function asBytes(input) {"));
test("question 26178: preserves recognition import source contract",()=>has(1,"if (input instanceof Uint8Array) return input;"));
test("question 26179: preserves recognition import source contract",()=>has(1,"if (input instanceof ArrayBuffer) return new Uint8Array(input);"));
test("question 26180: preserves recognition import source contract",()=>has(1,"if (ArrayBuffer.isView(input)) {"));
test("question 26181: preserves recognition import source contract",()=>has(1,"return new Uint8Array(input.buffer, input.byteOffset, input.byteLength);"));
test("question 26182: preserves recognition import source contract",()=>has(1,"throw new TypeError(\"EdgeBreaker input must be an ArrayBuffer or Uint8Array\");"));
test("question 26183: preserves recognition import source contract",()=>has(1,"function readI32LE(bytes, offset) {"));
test("question 26184: preserves recognition import source contract",()=>has(1,"if (offset + 4 > bytes.length) throw new RangeError(\"truncated EdgeBreaker int32\");"));
test("question 26185: preserves recognition import source contract",()=>has(1,"return new DataView(bytes.buffer, bytes.byteOffset + offset, 4).getInt32(0, true);"));
test("question 26186: preserves recognition import source contract",()=>has(1,"function readU32LE(bytes, offset) {"));
test("question 26187: preserves recognition import source contract",()=>has(1,"if (offset + 4 > bytes.length) throw new RangeError(\"truncated EdgeBreaker uint32\");"));
test("question 26188: preserves recognition import source contract",()=>has(1,"return new DataView(bytes.buffer, bytes.byteOffset + offset, 4).getUint32(0, true);"));
test("question 26189: preserves recognition import source contract",()=>has(1,"const CASE_C = 0;"));
test("question 26190: preserves recognition import source contract",()=>has(1,"const CASE_L = 1;"));
test("question 26191: preserves recognition import source contract",()=>has(1,"const CASE_E = 2;"));
test("question 26192: preserves recognition import source contract",()=>has(1,"const CASE_R = 3;"));
test("question 26193: preserves recognition import source contract",()=>has(1,"const CASE_S = 4;"));
test("question 26194: preserves recognition import source contract",()=>has(1,"const CASE_M = 5;"));
test("question 26195: preserves recognition import source contract",()=>has(1,"const CASE_M2 = 6;"));
test("question 26196: preserves recognition import source contract",()=>has(1,"const MTABLE_HAS_LENGTHS = 0x01;"));
test("question 26197: preserves recognition import source contract",()=>has(1,"const MTABLE_HAS_M2STACKOFFSETS = 0x02;"));
test("question 26198: preserves recognition import source contract",()=>has(1,"const MTABLE_HAS_M2GATEOFFSETS = 0x04;"));
test("question 26199: preserves recognition import source contract",()=>has(1,"const MTABLE_HAS_DUMMIES = 0x08;"));
test("question 26200: preserves recognition import source contract",()=>has(1,"const MTABLE_HAS_PATCHES = 0x10;"));
test("question 26201: preserves recognition import source contract",()=>has(1,"const MTABLE_HAS_BOUNDING = 0x20;"));
test("question 26202: preserves recognition import source contract",()=>has(1,"const MTABLE_HAS_QUANTIZATION = 0x40;"));
test("question 26203: preserves recognition import source contract",()=>has(1,"const MTABLE_HAS_QUANTIZATION_NORMALS = 0x80;"));
test("question 26204: preserves recognition import source contract",()=>has(1,"function align4(value) {"));
test("question 26205: preserves recognition import source contract",()=>has(1,"return value + ((4 - (value % 4)) % 4);"));
test("question 26206: preserves recognition import source contract",()=>has(1,"function parseMTable(bytes) {"));
test("question 26207: preserves recognition import source contract",()=>has(1,"let cursor = 0;"));
test("question 26208: preserves recognition import source contract",()=>has(1,"const flags = readU32LE(bytes, cursor);"));
test("question 26209: preserves recognition import source contract",()=>has(1,"cursor += 4;"));
test("question 26210: preserves recognition import source contract",()=>has(1,"let lengthsCount = 0;"));
test("question 26211: preserves recognition import source contract",()=>has(1,"let m2Count = 0;"));
test("question 26212: preserves recognition import source contract",()=>has(1,"let dummiesCount = 0;"));
test("question 26213: preserves recognition import source contract",()=>has(1,"let patchesCount = 0;"));
test("question 26214: preserves recognition import source contract",()=>has(1,"if (flags & MTABLE_HAS_LENGTHS) {"));
test("question 26215: preserves recognition import source contract",()=>has(1,"lengthsCount = readU32LE(bytes, cursor);"));
test("question 26216: preserves recognition import source contract",()=>has(1,"if (flags & MTABLE_HAS_M2STACKOFFSETS) {"));
test("question 26217: preserves recognition import source contract",()=>has(1,"if ((flags & MTABLE_HAS_M2GATEOFFSETS) === 0) {"));
test("question 26218: preserves recognition import source contract",()=>has(1,"throw new RangeError(\"EdgeBreaker MTable has stack offsets without gate offsets\");"));
test("question 26219: preserves recognition import source contract",()=>has(1,"m2Count = readU32LE(bytes, cursor);"));
test("question 26220: preserves recognition import source contract",()=>has(1,"if (flags & MTABLE_HAS_DUMMIES) {"));
test("question 26221: preserves recognition import source contract",()=>has(1,"dummiesCount = readU32LE(bytes, cursor);"));
test("question 26222: preserves recognition import source contract",()=>has(1,"if (flags & MTABLE_HAS_PATCHES) {"));
test("question 26223: preserves recognition import source contract",()=>has(1,"patchesCount = readU32LE(bytes, cursor);"));
test("question 26224: preserves recognition import source contract",()=>has(1,"if ((patchesCount & 1) !== 0) {"));
test("question 26225: preserves recognition import source contract",()=>has(1,"throw new RangeError(\"EdgeBreaker patch table length must be even\");"));
test("question 26226: preserves recognition import source contract",()=>has(1,"const readIntArray = (count, label) => {"));
test("question 26227: preserves recognition import source contract",()=>has(1,"if (count > 10_000_000) throw new RangeError(`EdgeBreaker ${label} count is unreasonable`);"));
test("question 26228: preserves recognition import source contract",()=>has(1,"const result = new Array(count);"));
test("question 26229: preserves recognition import source contract",()=>has(1,"for (let i = 0; i < count; i += 1) {"));
test("question 26230: preserves recognition import source contract",()=>has(1,"result[i] = readI32LE(bytes, cursor);"));
test("question 26231: preserves recognition import source contract",()=>has(1,"return result;"));
test("question 26232: preserves recognition import source contract",()=>has(1,"const lengths = readIntArray(lengthsCount, \"length\");"));
test("question 26233: preserves recognition import source contract",()=>has(1,"const m2StackOffsets = readIntArray(m2Count, \"m2 stack offset\");"));
test("question 26234: preserves recognition import source contract",()=>has(1,"const m2GateOffsets = readIntArray(m2Count, \"m2 gate offset\");"));
test("question 26235: preserves recognition import source contract",()=>has(1,"const dummyDeltas = readIntArray(dummiesCount, \"dummy\");"));
test("question 26236: preserves recognition import source contract",()=>has(1,"const dummies = [];"));
test("question 26237: preserves recognition import source contract",()=>has(1,"let previousDummy = 0;"));
test("question 26238: preserves recognition import source contract",()=>has(1,"for (const delta of dummyDeltas) {"));
test("question 26239: preserves recognition import source contract",()=>has(1,"if (delta < 0) throw new RangeError(\"EdgeBreaker dummy delta must be non-negative\");"));
test("question 26240: preserves recognition import source contract",()=>has(1,"previousDummy += delta;"));
test("question 26241: preserves recognition import source contract",()=>has(1,"dummies.push(previousDummy);"));
test("question 26242: preserves recognition import source contract",()=>has(1,"const patchRaw = readIntArray(patchesCount, \"patch\");"));
test("question 26243: preserves recognition import source contract",()=>has(1,"const patches = [];"));
test("question 26244: preserves recognition import source contract",()=>has(1,"let previousPatch = 0;"));
test("question 26245: preserves recognition import source contract",()=>has(1,"for (let i = 0; i < patchRaw.length; i += 2) {"));
test("question 26246: preserves recognition import source contract",()=>has(1,"previousPatch += patchRaw[i];"));
test("question 26247: preserves recognition import source contract",()=>has(1,"patches.push(Object.freeze([previousPatch, patchRaw[i + 1]]));"));
test("question 26248: preserves recognition import source contract",()=>has(1,"let bounding = null;"));
test("question 26249: preserves recognition import source contract",()=>has(1,"if (flags & MTABLE_HAS_BOUNDING) {"));
test("question 26250: preserves recognition import source contract",()=>has(1,"if (cursor + 24 > bytes.length) throw new RangeError(\"truncated EdgeBreaker MTable bounding\");"));
test("question 26251: preserves recognition import source contract",()=>has(1,"bounding = Object.freeze(Array.from({ length: 6 }, (_, i) =>"));
test("question 26252: preserves recognition import source contract",()=>has(1,"new DataView(bytes.buffer, bytes.byteOffset + cursor + i * 4, 4).getFloat32(0, true)"));
test("question 26253: preserves recognition import source contract",()=>has(1,"cursor += 24;"));
test("question 26254: preserves recognition import source contract",()=>has(1,"let quantization = null;"));
test("question 26255: preserves recognition import source contract",()=>has(1,"if (flags & MTABLE_HAS_QUANTIZATION) {"));
test("question 26256: preserves recognition import source contract",()=>has(1,"quantization = Object.freeze(["));
test("question 26257: preserves recognition import source contract",()=>has(1,"readI32LE(bytes, cursor),"));
test("question 26258: preserves recognition import source contract",()=>has(1,"readI32LE(bytes, cursor + 4),"));
test("question 26259: preserves recognition import source contract",()=>has(1,"readI32LE(bytes, cursor + 8)"));
test("question 26260: preserves recognition import source contract",()=>has(1,"cursor += 12;"));
test("question 26261: preserves recognition import source contract",()=>has(1,"let normalQuantization = null;"));
test("question 26262: preserves recognition import source contract",()=>has(1,"if (flags & MTABLE_HAS_QUANTIZATION_NORMALS) {"));
test("question 26263: preserves recognition import source contract",()=>has(1,"normalQuantization = Object.freeze(["));
test("question 26264: preserves recognition import source contract",()=>has(1,"if (cursor !== bytes.length) {"));
test("question 26265: preserves recognition import source contract",()=>has(1,"throw new RangeError("));
test("question 26266: preserves recognition import source contract",()=>has(1,"`EdgeBreaker MTable length mismatch: decoded ${cursor} of ${bytes.length} bytes`"));
test("question 26267: preserves recognition import source contract",()=>has(1,"return Object.freeze({"));
test("question 26268: preserves recognition import source contract",()=>has(1,"lengths: Object.freeze(lengths),"));
test("question 26269: preserves recognition import source contract",()=>has(1,"m2_stack_offsets: Object.freeze(m2StackOffsets),"));
test("question 26270: preserves recognition import source contract",()=>has(1,"m2_gate_offsets: Object.freeze(m2GateOffsets),"));
test("question 26271: preserves recognition import source contract",()=>has(1,"dummies: Object.freeze(dummies),"));
test("question 26272: preserves recognition import source contract",()=>has(1,"patches: Object.freeze(patches),"));
test("question 26273: preserves recognition import source contract",()=>has(1,"quantization,"));
test("question 26274: preserves recognition import source contract",()=>has(1,"normal_quantization: normalQuantization"));
test("question 26275: preserves recognition import source contract",()=>has(1,"function preprocessComponent(ops, startOffset) {"));
test("question 26276: preserves recognition import source contract",()=>has(1,"let edgeCount = 0;"));
test("question 26277: preserves recognition import source contract",()=>has(1,"let splitCount = 0;"));
test("question 26278: preserves recognition import source contract",()=>has(1,"const edgeStack = [];"));
test("question 26279: preserves recognition import source contract",()=>has(1,"const splitStack = [];"));
test("question 26280: preserves recognition import source contract",()=>has(1,"const splitOffsets = [];"));
test("question 26281: preserves recognition import source contract",()=>has(1,"let cursor = startOffset;"));
test("question 26282: preserves recognition import source contract",()=>has(1,"while (cursor < ops.length) {"));
test("question 26283: preserves recognition import source contract",()=>has(1,"const op = ops[cursor++];"));
test("question 26284: preserves recognition import source contract",()=>has(1,"switch (op) {"));
test("question 26285: preserves recognition import source contract",()=>has(1,"case CASE_C:"));
test("question 26286: preserves recognition import source contract",()=>has(1,"edgeCount -= 1;"));
test("question 26287: preserves recognition import source contract",()=>has(1,"case CASE_L:"));
test("question 26288: preserves recognition import source contract",()=>has(1,"case CASE_R:"));
test("question 26289: preserves recognition import source contract",()=>has(1,"edgeCount += 1;"));
test("question 26290: preserves recognition import source contract",()=>has(1,"case CASE_E:"));
test("question 26291: preserves recognition import source contract",()=>has(1,"edgeCount += 3;"));
test("question 26292: preserves recognition import source contract",()=>has(1,"if (edgeStack.length > 0) {"));
test("question 26293: preserves recognition import source contract",()=>has(1,"const splitIndex = splitStack.pop();"));
test("question 26294: preserves recognition import source contract",()=>has(1,"const savedEdgeCount = edgeStack.pop();"));
test("question 26295: preserves recognition import source contract",()=>has(1,"splitOffsets[splitIndex] = edgeCount - 2 - savedEdgeCount;"));
test("question 26296: preserves recognition import source contract",()=>has(1,"if (edgeCount <= 0) {"));
test("question 26297: preserves recognition import source contract",()=>has(1,"throw new RangeError(\"EdgeBreaker component has invalid initial boundary\");"));
test("question 26298: preserves recognition import source contract",()=>has(1,"edge_count: edgeCount,"));
test("question 26299: preserves recognition import source contract",()=>has(1,"split_offsets: Object.freeze(splitOffsets),"));
test("question 26300: preserves recognition import source contract",()=>has(1,"end_offset: cursor"));
test("question 26301: preserves recognition import source contract",()=>has(1,"case CASE_S:"));
test("question 26302: preserves recognition import source contract",()=>has(1,"splitStack.push(splitCount++);"));
test("question 26303: preserves recognition import source contract",()=>has(1,"edgeStack.push(edgeCount);"));
test("question 26304: preserves recognition import source contract",()=>has(1,"case CASE_M:"));
test("question 26305: preserves recognition import source contract",()=>has(1,"case CASE_M2:"));
test("question 26306: preserves recognition import source contract",()=>has(1,"`EdgeBreaker merge opcode ${op} is not decoded by the conservative connectivity path`"));
test("question 26307: preserves recognition import source contract",()=>has(1,"throw new RangeError(`unknown EdgeBreaker topology opcode ${op}`);"));
test("question 26308: preserves recognition import source contract",()=>has(1,"throw new RangeError(\"unterminated EdgeBreaker connected component\");"));
test("question 26309: preserves recognition import source contract",()=>has(1,"function ensureSlot(array, index) {"));
test("question 26310: preserves recognition import source contract",()=>has(1,"while (array.length <= index) array.push(null);"));
test("question 26311: preserves recognition import source contract",()=>has(1,"function decodeTopologyCases(ops) {"));
test("question 26312: preserves recognition import source contract",()=>has(1,"const faces = [];"));
test("question 26313: preserves recognition import source contract",()=>has(1,"let vertexCount = 0;"));
test("question 26314: preserves recognition import source contract",()=>has(1,"const components = [];"));
test("question 26315: preserves recognition import source contract",()=>has(1,"const componentStart = cursor;"));
test("question 26316: preserves recognition import source contract",()=>has(1,"const pre = preprocessComponent(ops, cursor);"));
test("question 26317: preserves recognition import source contract",()=>has(1,"const edgeCount = pre.edge_count;"));
test("question 26318: preserves recognition import source contract",()=>has(1,"const prev = new Array(edgeCount);"));
test("question 26319: preserves recognition import source contract",()=>has(1,"const next = new Array(edgeCount);"));
test("question 26320: preserves recognition import source contract",()=>has(1,"const start = new Array(edgeCount);"));
test("question 26321: preserves recognition import source contract",()=>has(1,"for (let i = 0; i < edgeCount; i += 1) {"));
test("question 26322: preserves recognition import source contract",()=>has(1,"prev[i] = (i - 1 + edgeCount) % edgeCount;"));
test("question 26323: preserves recognition import source contract",()=>has(1,"next[i] = (i + 1) % edgeCount;"));
test("question 26324: preserves recognition import source contract",()=>has(1,"start[i] = vertexCount + i;"));
test("question 26325: preserves recognition import source contract",()=>has(1,"vertexCount += edgeCount;"));
test("question 26326: preserves recognition import source contract",()=>has(1,"let hashUsed = edgeCount;"));
test("question 26327: preserves recognition import source contract",()=>has(1,"const available = [];"));
test("question 26328: preserves recognition import source contract",()=>has(1,"const gateStack = [];"));
test("question 26329: preserves recognition import source contract",()=>has(1,"let gate = 0;"));
test("question 26330: preserves recognition import source contract",()=>has(1,"let splitIndex = 0;"));
test("question 26331: preserves recognition import source contract",()=>has(1,"let terminated = false;"));
test("question 26332: preserves recognition import source contract",()=>has(1,"while (!terminated) {"));
test("question 26333: preserves recognition import source contract",()=>has(1,"if (cursor >= ops.length) throw new RangeError(\"truncated EdgeBreaker topology stream\");"));
test("question 26334: preserves recognition import source contract",()=>has(1,"if (available.length === 0) {"));
test("question 26335: preserves recognition import source contract",()=>has(1,"available.push(hashUsed);"));
test("question 26336: preserves recognition import source contract",()=>has(1,"ensureSlot(prev, hashUsed);"));
test("question 26337: preserves recognition import source contract",()=>has(1,"ensureSlot(next, hashUsed);"));
test("question 26338: preserves recognition import source contract",()=>has(1,"ensureSlot(start, hashUsed);"));
test("question 26339: preserves recognition import source contract",()=>has(1,"hashUsed += 1;"));
test("question 26340: preserves recognition import source contract",()=>has(1,"const a = start[gate];"));
test("question 26341: preserves recognition import source contract",()=>has(1,"const b = start[next[gate]];"));
test("question 26342: preserves recognition import source contract",()=>has(1,"case CASE_C: {"));
test("question 26343: preserves recognition import source contract",()=>has(1,"c = vertexCount;"));
test("question 26344: preserves recognition import source contract",()=>has(1,"const slot = available.pop();"));
test("question 26345: preserves recognition import source contract",()=>has(1,"const before = prev[gate];"));
test("question 26346: preserves recognition import source contract",()=>has(1,"next[before] = slot;"));
test("question 26347: preserves recognition import source contract",()=>has(1,"prev[slot] = before;"));
test("question 26348: preserves recognition import source contract",()=>has(1,"next[slot] = gate;"));
